enum SkillSlugEnum {
  //^ Languages
  Python = "python",
  JavaScript = "javascript",
  TypeScript = "typescript",
  Java = "java",
  GameMakerLanguage = "game-maker-language",
  ShellScript = "shell",
  RLanguage = "r",
  Groovy = "groovy",
  ObjectOrientedProgramming = "oop",
  FunctionalProgramming = "fp",

  //^ APIs
  REST = "rest-api",
  Apollo = "apollo",
  GraphQL = "graphql-api",
  TRPC = "trpc-api",
  SocketIO = "socket-io",
  Pusher = "pusher",
  OpenAI = "open-ai",
  ReplicateAI = "replicate-ai",
  APIs = "apis",
  SDKs = "sdks",

  //^ Backend Web Development
  Firebase = "firebase",
  Supabase = "supabase",
  PocketBase = "pocketbase",
  Auth0 = "auth0",
  ClerkAuth = "clerk-auth",
  NextAuth = "next-auth",
  Stripe = "stripe",
  ExpressJS = "express-js",
  Flask = "flask",
  Django = "django",
  Spring = "spring",
  SpringBoot = "spring-boot",
  Cloudinary = "cloudinary",
  EdgeStore = "edge-store",
  Gunicorn = "gunicorn",
  Jinja = "jinja",
  WebSockets = "web-sockets",
  UserAuthentication = "user-authentication",

  //^ Full Stack Web Development
  NextJS = "next-js",
  SvelteKit = "svelte-kit",
  AngularJS = "angular-js",
  NuxtJS = "nuxt-js",

  //^ Frontend Web Development
  ReactJS = "react",
  SvelteJS = "svelte",
  VueJS = "vue-js",
  Recoil = "recoil",
  Zustand = "zustand",
  Jotai = "jotai",
  Redux = "redux",
  TailwindCSS = "tailwind-css",
  HTML = "html",
  CSS = "css",
  ChakraUI = "chakra-ui",
  HeadlessUI = "headless-ui",
  ShadcnUI = "shadcn-ui",
  RadixUI = "radix-ui",
  ReactQuery = "react-query",
  NextUI = "next-ui",
  Bootstrap = "bootstrap",
  MaterialUI = "material-ui",
  SemanticUI = "semantic-ui",
  AntDesign = "ant-design",
  StoryBooks = "story-books",
  SimpleGUI = "simple-gui",
  Axios = "axios",
  UserCentricDesign = "user-centric-design",
  StateManagement = "state-management",

  //^ Database
  Normalisation = "normalisation",
  PostgreSQL = "postgresql",
  MySQL = "mysql",
  SQLite = "sqlite",
  MongoDB = "mongodb",
  Redis = "redis",
  Convex = "convex",
  Databases = "databases",
  RelationalDatabases = "relational-databases",
  NonRelationalDatabases = "non-relational-databases",
  DatabaseManagementSystems = "database-management-systems",
  DatabaseIndexing = "indexing",

  //^ Object-Relational Mappers
  Mongoose = "moongose",
  Prisma = "prisma",
  Drizzle = "drizzle",
  SQLAlchemy = "sqlalchemy",
  TypeORM = "typeorm",
  Hibernate = "hibernate",
  ObjectRelationalMapping = "object-relational-mapping",

  //^ DevOps
  GitHubActions = "github-actions",
  GitLabCI = "gitlab-ci",
  Jenkins = "jenkins",
  TeamCity = "team-city",
  Docker = "docker",
  Podman = "podman",
  Kubernetes = "kubernetes",
  Ansible = "ansible",
  Vagrant = "vagrant",
  Terraform = "terraform",
  ContinuousIntegration = "continuous-integration",
  ContinuousDeployment = "continuous-deployment",
  ContinuousDelivery = "continuous-delivery",
  DevOps = "dev-ops",
  Containerisation = "containerisation",
  InfrastructureAsCode = "infrastructure-as-code",
  Clusterisation = "clusterisation",
  Automation = "automation",

  //^ Version Control Systems
  Git = "git",
  GitHub = "github",
  GitLab = "gitlab",
  BitBucket = "bit-bucket",
  VersionControlSystems = "version-control-systems",

  //^ Code Quality
  Black = "black",
  PyLint = "pylint",
  Zod = "zod",
  Prettier = "prettier",
  Checkstyle = "checkstyle",
  ESLint = "eslint",
  Linting = "linting",
  DesignPatterns = "design-patterns",

  //^ Testing
  Jest = "jest",
  Vitest = "vitest",
  PyTest = "pytest",
  UnitTest = "unittest",
  JUnit = "junit",
  Cypress = "cypress",
  ReactTestingLibrary = "react-testing-library",
  Testing = "testing",

  //^ Project and Dependency Management
  NPM = "npm",
  Yarn = "yarn",
  PNPM = "pnpm",
  Poetry = "poetry",
  Pip = "pip",
  PyBuilder = "pybuilder",
  Maven = "maven",
  Gradle = "gradle",
  Tox = "tox",
  NxJS = "nx-js",

  //^ Artificial Intelligence, Machine Learning, and Data Science
  ScikitLearn = "scikit-learn",
  Pandas = "pandas",
  NumPy = "numpy",
  Matplotlib = "matplotlib",
  Seaborn = "seaborn",
  Keras = "keras",
  Jupyter = "jupyter",
  MachineLearning = "machine-learning",
  DeepLearning = "deep-learning",
  ArtificialIntelligence = "artificial-intelligence",
  DataScience = "data-science",
  Hyperparameters = "hyperparameters",
  Boosting = "boosting",
  DataVisualisation = "data-visualisation",
  NeuralNetworks = "neural-networks",

  //^ Mathematics
  Probability = "probability",
  Statistics = "statistics",
  Calculus = "calculus",
  Trigonometry = "trigonometry",
  Algebra = "algebra",
  LinearAlgebra = "linear-algebra",
  Discrete = "discrete",
  Geometry = "geometry",
  Mechanics = "mechanics",
  Logics = "logics",
  Mathematics = "mathematics",

  //^ Cloud Computing
  AWS = "aws",
  AWS_K3s = "aws-k3s",
  AWS_EC2 = "aws-ec2",
  AWS_S3 = "aws-s3",
  AWS_VPC = "aws-vpc",
  AWS_Lambda = "aws-lambda",
  AWS_CloudFormation = "aws-cloudformation",
  AWS_CloudFront = "aws-cloudfront",
  AWS_ElasticBeanstalk = "aws-elastic-beanstalk",
  Azure = "azure",
  Azure_AppService = "azure-app-service",
  Azure_Monitor = "azure-monitor",
  Azure_BlobStorage = "azure-blob-storage",
  Azure_DurableFunctions = "azure-durable-functions",
  Azure_Functions = "azure-functions",
  Azure_ResourceManager = "azure-resource-manager",
  Azure_ContainerRegistry = "azure-container-registry",
  GCP = "gcp",
  GCP_AppEngine = "gcp-app-engine",
  GCP_CloudSQL = "gcp-cloud-sql",
  GCP_CloudStorage = "gcp-cloud-storage",
  GCP_CloudTasks = "gcp-cloud-tasks",
  GCP_CloudScheduler = "gcp-cloud-scheduler",
  GCP_Logging = "gcp-logging",
  CloudComputing = "cloud-computing",

  //^ Game Development
  GameMakerStudio = "game-maker-studio",
  GameDevelopment = "game-development",

  //^ Algorithms & Data Structures
  Algorithms = "algorithms",
  DataStructures = "data-structures",

  //^ Platform Development
  AndroidDevelopment = "android",
  iOSDevelopment = "ios",
  WindowsDevelopment = "windows",
  MacDevelopment = "mac",
  LinuxDevelopment = "linux",
  WebDevelopment = "web",

  //^ Others
  Symphony = "symphony",

  //^ Soft Skills
  Communication = "communication",
  ProjectManagement = "project-management",
  Teamwork = "teamwork",
  Leadership = "leadership",
  ProblemSolving = "problem-solving",
  CriticalThinking = "critical-thinking",
  Creativity = "creativity",
  Adaptability = "adaptability",
  TimeManagement = "time-management",
  RiskManagement = "risk-management",
  StakeholderManagement = "stakeholder-management",
  ScopeManagement = "scope-management",
  CostManagement = "cost-management",
  QualityManagement = "quality-management",
  ProcurementManagement = "procurement-management",
  IntegrationManagement = "integration-management",
  HumanResourceManagement = "human-resource-management",
}

export default SkillSlugEnum;
