import addNestedSkillsMaterialList from "@/actions/material/addNestedSkillsMaterialList";
import ProjectDatabaseKeys from "@/database/Projects/ProjectDatabaseKeys";
import SkillDatabaseKeys from "@/database/Skills/SkillDatabaseKeys";
import ModuleDatabaseKeys from "@/database/Modules/ModuleDatabaseKeys";
import ModuleYearGroupsEnum from "@/enums/Module/ModuleYearGroupsEnum";
import SkillCategoriesEnum from "@/enums/Skill/SkillCategoriesEnum";
import SkillTypesEnum from "@/enums/Skill/SkillTypesEnum";
import ModuleInterface from "@/database/Modules/ModuleInterface";
import skillDatabaseMap from "../Skills/SkillDatabaseMap";
import CourseDatabaseKeys from "@/database/Courses/CourseDatabaseKeys";
import CertificateDatabaseKeys from "../Certificates/CertificateDatabaseKeys";

/**
 * Hashmap of the modules I have studied at university.
 * The keys are defined in {@link ModuleDatabaseKeys}.
 * The order of the modules is the order that will be used to display them.
 */
const modulesMap: Database<ModuleInterface> = {
  //^ Royal Holloway University of London
  //* Year 1
  [ModuleDatabaseKeys.RHUL_ObjectOrientedProgramming1]: {
    name: "Object Oriented Programming 1",
    category: ModuleYearGroupsEnum.Year1,
    skills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.ObjectOrientedProgramming,
      SkillDatabaseKeys.DataStructures,
    ],
    relatedMaterials: [ProjectDatabaseKeys.JavaFundamentalsAssignments],
    learningOutcomes: [
      "Introducing basic concepts of computer programming",
      "Understanding the importance and role of data in programming",
      "Mastering control flow mechanisms such as branching and iteration",
      "Learning to write and use methods, and handling exceptions",
      "Applying learned concepts to write complex programs",
      "Organizing code using classes and packages",
      "Implementing basic data structures for efficient data management",
      "Interacting with users and environment through input/output operations, file handling, and GUI creation",
      "Preparing for in-class tests and quizzes",
      "Solving challenging problems using linked lists",
      "Preparing for final in-class test and exercise class",
    ],
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },
  [ModuleDatabaseKeys.RHUL_ObjectOrientedProgramming2]: {
    name: "Object Oriented Programming 2",
    category: ModuleYearGroupsEnum.Year1,
    skills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.ObjectOrientedProgramming,
      SkillDatabaseKeys.DataStructures,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    relatedMaterials: [
      ProjectDatabaseKeys.JavaFundamentalsAssignments,
      CertificateDatabaseKeys.UdemyJavaProgrammingMasterclass,
    ],
    learningOutcomes: [
      "Exploring enumerated types and recursion in Java",
      "Defining recursive data types and handling exceptions",
      "Understanding I/O streams and implementing stacks and queues",
      "Applying recursive data types in a practical assignment",
      "Learning about Generics and Java's Collections library",
      "Studying searching algorithms and hashtables",
      "Delving into Java's object-oriented language features",
      "Applying Java Collections and inheritance in a practical assignment",
      "Organizing and documenting code in Java",
      "Examining various sorting algorithms",
      "Investigating tree data structures and algorithms",
      "Applying knowledge of streams, inheritance, sorting, and Java in a practical assignment",
      "Understanding threads and concurrency in Java",
    ],
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },
  [ModuleDatabaseKeys.RHUL_ProgrammingLaboratory]: {
    name: "Programming Laboratory",
    category: ModuleYearGroupsEnum.Year1,
    skills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.SimpleGUI,
      SkillDatabaseKeys.ObjectOrientedProgramming,
      SkillDatabaseKeys.DataStructures,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.Leadership,
      SkillDatabaseKeys.Communication,
      SkillDatabaseKeys.ProjectManagement,
      SkillDatabaseKeys.TimeManagement,
      SkillDatabaseKeys.Creativity,
      SkillDatabaseKeys.Adaptability,
    ],
    relatedMaterials: [ProjectDatabaseKeys.OsmosGame],
    learningOutcomes: [
      "Understanding computational thinking and basic coding",
      "Translating problem-solving thoughts into precise instructions for computers",
      "Creating interactive fiction as a means of practicing coding",
      "Applying the concept of abstraction to manage complexity in programming",
      "Managing and operating on large data sets with simple data types",
      "Decomposing problems into implementable steps for effective programming",
      "Improving testing approaches for larger programs and understanding test automation",
      "Developing debugging skills to identify and resolve programming issues",
      "Working effectively in programming teams",
      "Preparing for group projects and understanding the requirements for games projects",
    ],
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },
  [ModuleDatabaseKeys.RHUL_InternetServices]: {
    name: "Internet Services",
    category: ModuleYearGroupsEnum.Year1,
    skills: [
      SkillDatabaseKeys.HTML,
      SkillDatabaseKeys.CSS,
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the organization and components of the course",
      "Engaging with self-guided non-assessed exercise sheets in lab sessions",
      "Surveying the history of the Internet and the Worldwide Web",
      "Exploring the basic concepts in networks",
      "Studying the Internet Protocol Stack and its layers",
      "Delving into applications and the transport layer",
      "Completing coursework assignment on Internet Basics and the Internet Protocol Stack",
      "Investigating web technologies such as HTML, XML, CSS, Javascript, and PHP",
      "Applying layout and styling using CSS",
      "Understanding scripting languages for the web, specifically Javascript",
      "Briefly studying PHP, a server-side scripting language",
      "Reviewing and summarizing the Internet Protocol Stack",
      "Beginning the study of network security",
    ],
    archived: true,
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },
  [ModuleDatabaseKeys.RHUL_MathematicalStructures]: {
    name: "Mathematical Structures (Discrete Mathematics)",
    category: ModuleYearGroupsEnum.Year1,
    skills: [
      SkillDatabaseKeys.Mathematics,
      SkillDatabaseKeys.Discrete,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the importance of Mathematical Structures for Computer Science",
      "Defining sets, elements of sets, and subset/superset relationships",
      "Performing operations on sets such as Union, Intersection, Cardinality, Power Set, and Cartesian Product",
      "Defining Partition of a Set and a Quotient Set",
      "Understanding Strings as elements of a special set",
      "Using Binary Strings to represent sets in a computer",
      "Studying Relations, Orderings, Functions and Cardinality of Infinite Sets",
      "Applying Recursion and Induction",
      "Exploring Graphs and Probability",
      "Understanding independent events and binomial distribution",
      "Calculating mean and variance of a random variable",
      "Studying geometric distribution",
    ],
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
    relatedMaterials: [CertificateDatabaseKeys.UdemyDiscreteMathematics],
  },
  [ModuleDatabaseKeys.RHUL_MachineFundamentals]: {
    name: "Machine Fundamentals",
    category: ModuleYearGroupsEnum.Year1,
    skills: [
      SkillDatabaseKeys.Mathematics,
      SkillDatabaseKeys.Logics,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the representation of numbers inside a computer",
      "Exploring unsigned, sign magnitude, two's complement representations, and floating point representation of real numbers",
      "Introducing basic propositional logic, logic operators and truth tables",
      "Understanding conjunctive and disjunctive normal forms (CNF and DNF), logical equivalences and proof by logical equivalences",
      "Studying predicate logic, domain of discourse, truth values of predicates, proof by existence and by contradiction, models and semantic entailment, and proofs by inference rules",
      "Designing Boolean logic circuits using AND, OR, NOT and NAND gates",
      "Constructing logic circuits using a DNF of minterms and Karnaugh maps",
      "Understanding full, half and ripple carry adders",
      "Exploring switching circuits, N-type and P-type transistors and canonical pull up/pull down circuit construction",
      "Programming in assembly language using the MIPS language",
      "Understanding regular expressions, nondeterministic and deterministic finite state automata",
      "Applying Thompson's construction and the subset construction",
      "Recognizing that not all sets can be defined by regular expressions",
      "Studying pushdown automata and Turing machines",
    ],
    archived: true,
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },
  [ModuleDatabaseKeys.RHUL_SoftwareDesign]: {
    name: "Software Design",
    category: ModuleYearGroupsEnum.Year1,
    skills: [
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.Leadership,
      SkillDatabaseKeys.Communication,
      SkillDatabaseKeys.ProjectManagement,
      SkillDatabaseKeys.TimeManagement,
      SkillDatabaseKeys.Creativity,
      SkillDatabaseKeys.Adaptability,
    ],
    learningOutcomes: [
      "Understanding the fundamentals of Software Engineering, including key concepts, activities, and the characteristics of good software.",
      "Describing the importance of User Experience (UX) in software development and its components, such as usability evaluation.",
      "Exploring various aspects of software requirements including elicitation, modelling, and evaluation processes.",
      "Analyzing and applying software design strategies to model, document, and review according to Software Architecture Documents.",
      "Conducting task analysis and organizing software development activities to support system delivery and management.",
      "Participating in lab sessions to apply theoretical knowledge in practical scenarios, focusing on Coursework 2 and task planning.",
      "Reflecting on learned concepts and applying them to real-world scenarios, particularly in software task analysis and planning, to prepare for the final summative quiz.",
    ],
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },

  //* Year 2
  [ModuleDatabaseKeys.RHUL_SoftwareEngineering]: {
    name: "Software Engineering",
    category: ModuleYearGroupsEnum.Year2,
    skills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.JUnit,
      SkillDatabaseKeys.Git,
      SkillDatabaseKeys.Maven,
      SkillDatabaseKeys.ObjectOrientedProgramming,
      SkillDatabaseKeys.DesignPatterns,
      SkillDatabaseKeys.VersionControlSystems,
      SkillDatabaseKeys.DevOps,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.Communication,
      SkillDatabaseKeys.ProjectManagement,
      SkillDatabaseKeys.TimeManagement,
      SkillDatabaseKeys.Adaptability,
    ],
    learningOutcomes: [
      "Tracing the evolution of software engineering from traditional practices to modern Agile methodologies",
      "Utilizing Eclipse IPSE and its tools (Maven, Symbolic Debugger, Javadoc) to enhance software development efficiency",
      "Applying Test-Driven Development (TDD) techniques to ensure the creation of readable and functional code",
      "Identifying and refactoring bad code smells to maintain code quality and standards using tools like CheckStyle",
      "Mastering software version control concepts and tools, including SVN and Git, for effective software release management",
      "Practicing SVN commands and workflows to manage and rectify coding errors efficiently",
      "Communicating software design effectively with UML diagrams and exploiting APIs for rapid application development (RAD)",
      "Analyzing and applying design patterns to prevent common software design problems",
      "Exploring various testing types, including integration and system testing, to ensure robust software functionality",
      "Understanding the role of Continuous Integration in maintaining a consistent testing regime",
      "Applying software measures to predict and improve the quality, productivity, and maintainability of software",
      "Differentiating between defects, faults, and failures to better manage software testing and complexity",
      "Comparing and contrasting Agile and Waterfall methodologies to determine their applicability in different software development scenarios",
      "Practicing SCRUM and other Agile techniques to enhance team collaboration and project management in software development",
    ],
    relatedMaterials: [ProjectDatabaseKeys.JavaCalculatorAssignment],
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },
  [ModuleDatabaseKeys.RHUL_TeamProject]: {
    name: "Team Project",
    category: ModuleYearGroupsEnum.Year2,
    skills: [
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.Prisma,
      SkillDatabaseKeys.NextAuth,
      SkillDatabaseKeys.NextJS,
      SkillDatabaseKeys.ReactJS,
      SkillDatabaseKeys.GraphQL,
      SkillDatabaseKeys.Apollo,
      SkillDatabaseKeys.Leadership,
      SkillDatabaseKeys.ObjectOrientedProgramming,
      SkillDatabaseKeys.DesignPatterns,
      SkillDatabaseKeys.VersionControlSystems,
      SkillDatabaseKeys.DevOps,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.Teamwork,
      SkillDatabaseKeys.Communication,
      SkillDatabaseKeys.ProjectManagement,
      SkillDatabaseKeys.TimeManagement,
      SkillDatabaseKeys.Adaptability,
    ],
    learningOutcomes: [
      "Understanding the basics and historical context of Software Engineering",
      "Familiarizing with the course structure and expectations",
      "Gaining knowledge of Scrum methodology and its application in Agile project management",
      "Understanding different architectural models and their significance in software design",
      "Learning techniques for code refactoring to improve software maintainability and reduce technical debt",
      "Exploring the core values of Scrum and their impact on professional software development practices",
      "Developing strategies for writing robust code that can handle unexpected system behavior",
      "Understanding the basics of Function Point Analysis and its role in measuring software size and complexity",
      "Learning about software security principles and best practices to protect against vulnerabilities",
      "Applying Function Point Analysis in practical scenarios to estimate software development effort",
      "Examining ethical considerations in software engineering, guided by professional codes of conduct and ethics",
      "Analyzing real-world case studies to understand the application of ethical principles and professional standards in software engineering",
      "Gaining in-depth knowledge of Function Point Analysis, including methodologies, applications, and its historical context",
    ],
    relatedMaterials: [ProjectDatabaseKeys.Noodle],
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },
  [ModuleDatabaseKeys.RHUL_OperatingSystems]: {
    name: "Operating Systems",
    category: ModuleYearGroupsEnum.Year2,
    skills: [
      SkillDatabaseKeys.C,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the basic components of an Operating System (OS) and their management",
      "Starting with C programming, focusing on general features and structure",
      "Grasping the concepts of processes and threads in an OS to manage multitasking",
      "Experimenting with C programming constructs like data types, variables, and functions",
      "Exploring Inter-Process Communication (IPC) and its implementation via busy waiting",
      "Understanding memory management in C, including strings, arrays, and pointers",
      "Studying advanced IPC methods and process communication over networks",
      "Learning system calls, low-level I/O, and process creation in C programming",
      "Analyzing classical IPC problems and the basics of OS scheduling algorithms",
      "Practicing with Unix shell and basic shell programming",
      "Concluding scheduling algorithms and initiating memory management topics",
      "Delving into dynamic memory allocation in C using standard library functions",
      "Understanding virtual memory, paging, and segmentation for efficient memory management",
      "Applying C programming to structures and linked lists for dynamic data storage",
      "Learning about file systems and their role in persistent storage management",
      "Implementing UNIX half-duplex pipes for process communication in C",
      "Understanding deadlocks in OS and strategies to prevent or resolve them",
      "Writing concurrent programs in C using threads and synchronization techniques",
      "Applying OS concepts in real-world Unix-based systems like Linux, MacOS, Android",
      "Reviewing C programming topics and implementing a circular list program",
      "Exploring Windows OS internals and virtualization concepts, including cloud computing",
      "Reviewing the course content and finalizing lab exercises",
      "Applying theoretical and practical knowledge in OS and C programming to solve quiz problems",
      "Creating a dynamic doubly-linked list in C to simulate virtual memory management in an OS",
    ],
    archived: true,
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },
  [ModuleDatabaseKeys.RHUL_Databases]: {
    name: "Databases",
    category: ModuleYearGroupsEnum.Year2,
    skills: [
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the logistics, overview, examples, and history of databases",
      "Learning ER modelling and ER design",
      "Understanding the relational model and translation of ER-diagrams to relational model",
      "Learning relational algebra, select, project, and queries",
      "Understanding the basics of SQL",
      "Learning intermediate SQL",
      "Understanding JDBC",
      "Learning normalisation theory",
    ],
    relatedMaterials: [
      ProjectDatabaseKeys.DatabasesMiniProject,
      CertificateDatabaseKeys.UdemyDatabaseManagementSystemAndSQL,
    ],
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },
  [ModuleDatabaseKeys.RHUL_AlgorithmsAndComplexity]: {
    name: "Algorithms & Complexity",
    category: ModuleYearGroupsEnum.Year2,
    skills: [
      SkillDatabaseKeys.Algorithms,
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding fundamental algorithms, including sorting and searching",
      "Grasping the concepts of algorithm analysis and efficiency, including Big-Oh notation",
      "Mastering the concepts and implementations of binary search trees (BSTs) and abstract data types (ADTs)",
      "Learning the basics of balanced trees, specifically AVL trees, and their rotations",
      "Expanding knowledge on advanced data structures, including hash tables, heaps, and priority queues",
      "Delving into graph theory basics, including graph representations and properties of depth-first search (DFS) and breadth-first search (BFS)",
      "Beginning with dynamic programming concepts, transitioning to graph algorithms",
      "Understanding the applications of min-cost spanning trees and the mechanics of Kruskal's and Prim's algorithms",
      "Gaining insights into graph search algorithms, specifically DFS and BFS, and their use in establishing connectivity",
      "Exploring the theory and application of min-cost spanning trees, Union-Find data structure, and greedy algorithms",
      "Learning shortest path algorithms, with a focus on Dijkstra’s algorithm",
      "Studying advanced graph algorithm topics, such as handling distances with negative weights and the Floyd-Warshall algorithm",
      "Investigating graph coloring and its algorithmic implementations",
    ],
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
    relatedMaterials: [
      ProjectDatabaseKeys.SearchingAndSortingAlgorithms,
      CertificateDatabaseKeys.UdemyTheCompleteDataStructuresAndAlgorithmsCourseInPython,
      CertificateDatabaseKeys.UdemyJavaScriptDataStructuresAndAlgorithms,
    ],
  },
  [ModuleDatabaseKeys.RHUL_MultidimensionalDataProcessing]: {
    name: "Multi-Dimensional Data Processing (Linear Algebra)",
    category: ModuleYearGroupsEnum.Year2,
    skills: [
      SkillDatabaseKeys.LinearAlgebra,
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the introduction and background of multidimensional data processing",
      "Learning about vectors",
      "Understanding rotations to matrix multiplication",
      "Learning about the inverse of a matrix, graphs, inner products",
      "Understanding matrix classifications",
      "Learning about orthogonal matrices, projection, linear independence",
      "Understanding Page rank",
      "Learning about singular value decomposition (SVD), least squares",
      "Understanding the introduction of principal components analysis (PCA)",
      "Learning about PCA and SVD, applications",
    ],
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
    relatedMaterials: [CertificateDatabaseKeys.UdemyBecomeALinearAlgebraMaster],
  },
  [ModuleDatabaseKeys.RHUL_ArtificialIntelligence]: {
    name: "Artificial Intelligence",
    category: ModuleYearGroupsEnum.Year2,
    skills: [
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.Algorithms,
      SkillDatabaseKeys.Logics,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the foundational concepts of AI and its historical background",
      "Gaining an overview of the course structure and the focus on symbolic (model-based) AI",
      "Learning the basic features of Prolog, including logic programming and declarative programming techniques",
      "Acquiring skills in writing Prolog programs and utilizing SWI-Prolog for AI development",
      "Formulating search problems using states, actions, and transitions in AI problem-solving",
      "Differentiating between uninformed and informed search algorithms, and understanding adversarial search for game-playing",
      "Modeling world aspects using propositional and predicate logic, and understanding their computational representations",
      "Applying symbolic logic for non-monotonic reasoning and decision-making in AI systems",
      "Utilizing situation calculus for reasoning about actions and their effects over time",
      "Comparing situation calculus with event calculus for state transition modeling in dynamic environments",
      "Understanding inductive learning and its role in AI, focusing on high-level symbolic learning",
      "Exploring decision tree learning and inductive logic programming, assessing their pros and cons",
      "Mastering SWI-Prolog for implementing AI solutions and completing course-related tasks",
      "Engaging with coursework to apply theoretical concepts in practical scenarios, receiving feedback to enhance learning",
    ],
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },
  [ModuleDatabaseKeys.RHUL_IntroductionToInformationSecurity]: {
    name: "Introduction to Information Security",
    category: ModuleYearGroupsEnum.Year2,
    skills: [
      SkillDatabaseKeys.CyberSecurity,
      SkillDatabaseKeys.Cryptography,
      SkillDatabaseKeys.Mathematics,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding basic concepts of information security and the historical perspective of classical cryptography",
      "Exploring fundamental cryptographic techniques including symmetric key cryptography, stream ciphers, and block ciphers",
      "Continuing with symmetric key cryptography, introduction to integrity mechanisms, hash functions, and public key cryptography",
      "Understanding the applications of cryptographic methods, particularly digital signatures and blockchain technologies",
      "Learning about identification and authentication processes, including the use of various biometric technologies",
      "Studying security protocols with a focus on authentication and key establishment, including the Kerberos protocol",
      "Exploring the fundamentals of access control in computer security and different models of access control systems",
      "Gaining insight into OS security measures, with a focus on access control in Unix and Windows operating systems",
      "Learning about software security issues, focusing on malware and buffer overflow attacks, and their prevention methods",
      "Covering basics of network security, including network protocols, architecture, firewalls, and secure communication using TLS",
      "Continuing with network security, including detailed discussions on firewall types, intrusion detection systems, and IPsec for virtual private networks",
    ],
    archived: true,
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },

  //* Year 3
  [ModuleDatabaseKeys.RHUL_UserCentredDesign]: {
    name: "User Centred Design",
    category: ModuleYearGroupsEnum.Year3,
    skills: [
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.Teamwork,
      SkillDatabaseKeys.Communication,
      SkillDatabaseKeys.Creativity,
      SkillDatabaseKeys.QualityManagement,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the principles and importance of User-Centred Design (UCD)",
      "Creating personas and user stories to represent the needs of users",
      "Recognizing how perception and cognition influence user interaction and design decisions",
      "Applying perception and cognition principles in design through practical exercises",
      "Grasping the core aspects of usability in user interface design",
      "Conducting usability evaluations and understanding their impact on user experience",
      "Exploring how human factors across the senses affect interaction design",
      "Performing task analysis to systematically evaluate interactions in designs",
      "Designing interactive systems with a focus on the user's experience",
      "Learning user research methodologies from UX professionals to inform design decisions",
      "Understanding the principles and design considerations for virtual and augmented reality experiences",
      "Gaining hands-on experience in virtual reality testing and interaction design",
      "Applying graphic design principles in the context of user interface and user experience design",
      "Understanding different testing methods and their applications in design",
      "Engaging in design and prototyping workshops to apply theoretical knowledge practically",
      "Integrating audio elements effectively into user interface design to enhance user experience",
      "Applying statistical analysis to interpret and evaluate usability testing data",
      "Presenting and critiquing prototypes to gather actionable feedback",
      "Gaining insights from industry alumni on practical applications of UX principles",
      "Understanding the UX industry landscape and employability skills through expert sessions",
    ],
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },
  [ModuleDatabaseKeys.RHUL_ITProjectManagement]: {
    name: "IT Project Management",
    category: ModuleYearGroupsEnum.Year3,
    skills: [
      SkillDatabaseKeys.ProjectManagement,
      SkillDatabaseKeys.Communication,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
      SkillDatabaseKeys.RiskManagement,
      SkillDatabaseKeys.StakeholderManagement,
      SkillDatabaseKeys.ScopeManagement,
      SkillDatabaseKeys.CostManagement,
      SkillDatabaseKeys.QualityManagement,
      SkillDatabaseKeys.ProcurementManagement,
      SkillDatabaseKeys.IntegrationManagement,
    ],
    learningOutcomes: [
      "Understanding what constitutes a project, its lifecycle, and key characteristics",
      "Analyzing the project triangle and its impact on project management, especially in technology sectors",
      "Mastering the concepts of business case development, investment appraisal, estimations, and budgeting",
      "Exploring IT systems acquisition models and procurement management processes",
      "Identifying project stakeholders and conducting stakeholder analysis",
      "Understanding project governance and the creation of a Project Charter",
      "Conducting requirements elicitation and defining project scope using Work Breakdown Structure (WBS)",
      "Creating project schedules, including network diagrams, critical path analysis, Gantt charts, and milestones",
      "Planning project resources using common tools and techniques",
      "Establishing project communications plans and management strategies",
      "Understanding the fundamentals of project risk management and developing a Risk Management Plan",
      "Implementing the Risk Management Process, including the use of a Risk Register",
      "Differentiating between Software Configuration Management and Project Configuration Management",
      "Managing project changes effectively through Change Management processes",
      "Applying S-Curve Analysis, Milestones, and Tracking Gantt Charts for project monitoring",
      "Utilizing Earned Value Management and Scrum/Agile methodologies for performance tracking",
      "Recognizing the characteristics of effective project teams and common reasons for team failure",
      "Applying the Tuckman Model, understanding leadership styles, goal-setting, time management, meetings management, and conflict management",
      "Grasping the basics of Project Quality Management and general Quality Management principles",
      "Gaining insight into the necessary skills, job market outlook for project managers, and the relevant code of ethics",
    ],
    archived: true,
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },
  [ModuleDatabaseKeys.RHUL_FunctionalProgramming]: {
    name: "Functional Programming",
    category: ModuleYearGroupsEnum.Year3,
    skills: [
      SkillDatabaseKeys.Haskell,
      SkillDatabaseKeys.Scala,
      SkillDatabaseKeys.FunctionalProgramming,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the history and development of functional programming",
      "Differentiating between imperative and functional programming paradigms",
      "Gaining foundational knowledge of the Haskell programming language",
      "Learning the basics of typing in Haskell",
      "Programming with functions in Haskell",
      "Deepening understanding of function-based programming in Haskell",
      "Utilizing list comprehensions in Haskell programming",
      "Studying higher-order functions and their applications in Haskell",
      "Exploring type declarations and type systems in Haskell",
      "Understanding the concept of multiparadigm programming languages",
      "Introduction to the Scala programming language",
      "Learning Scala's functional programming features",
      "Reviewing recursion in functional programming",
      "Understanding lazy evaluation in Haskell",
      "Exploring advanced topics in functional programming, including advanced type systems",
    ],
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },
  [ModuleDatabaseKeys.RHUL_FinalYearProject]: {
    name: "Final Year Project (Web Development)",
    category: ModuleYearGroupsEnum.Year3,
    skills: [
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.NextJS,
      SkillDatabaseKeys.ReactJS,
      SkillDatabaseKeys.ChakraUI,
      SkillDatabaseKeys.Firebase,
      SkillDatabaseKeys.Recoil,
      SkillDatabaseKeys.Docker,
      SkillDatabaseKeys.GitHubActions,
      SkillDatabaseKeys.GitHub,
      SkillDatabaseKeys.GCP,
      SkillDatabaseKeys.Git,
      SkillDatabaseKeys.HTML,
      SkillDatabaseKeys.CSS,
      SkillDatabaseKeys.Yarn,
      SkillDatabaseKeys.ESLint,
      SkillDatabaseKeys.Prettier,
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.SQLAlchemy,
      SkillDatabaseKeys.Flask,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.Poetry,
      SkillDatabaseKeys.REST,

      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.ProjectManagement,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.Creativity,
      SkillDatabaseKeys.Adaptability,
      SkillDatabaseKeys.TimeManagement,
      SkillDatabaseKeys.ScopeManagement,
      SkillDatabaseKeys.StakeholderManagement,
      SkillDatabaseKeys.Communication,
      SkillDatabaseKeys.RiskManagement,
      SkillDatabaseKeys.ObjectOrientedProgramming,
      SkillDatabaseKeys.DesignPatterns,
      SkillDatabaseKeys.Algorithms,
    ],
    learningOutcomes: [
      "Designing and implementing a full-stack web application realizing an online service",
      "Understanding and applying web development as a fundamental skill in computer science",
      "Using state-of-the-art technologies and established best practices in web development",
      "Developing a web application following an N-tier architectural pattern",
      "Implementing application logic and user interface using existing web application technologies/platforms",
      "Designing a relational database schema with sound constraints according to normalization rules",
      "Evaluating state-of-the-art options for web development technologies based on various comparison criteria",
      "Investigating and reflecting on a number of candidate technologies for web development",
      "Justifying the choices made in technology selection for the web application",
      "Implementing advanced features such as ACID transactions, comprehensive security/privacy analysis, and advanced security mechanisms",
      "Using NoSQL data stores to speed up user interaction while maintaining sound levels of transactional consistency",
      "Implementing advanced UI features such as push notifications",
      "Exploring the use of emerging platforms such as blockchain in web development",
    ],
    relatedMaterials: [
      ProjectDatabaseKeys.CircusDiscussions,
      ProjectDatabaseKeys.FlaskForumBackend,
    ],
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },
  [ModuleDatabaseKeys.RHUL_MachineLearning]: {
    name: "Machine Learning",
    category: ModuleYearGroupsEnum.Year3,
    skills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.ScikitLearn,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Jupyter,
      SkillDatabaseKeys.Algorithms,
      SkillDatabaseKeys.Algebra,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the fundamental concepts of Machine Learning",
      "Applying the Nearest Neighbours algorithm in Machine Learning problems",
      "Gaining introductory knowledge of conformal prediction and its significance in Machine Learning for reliable predictions",
      "Completing the discussion on full conformal prediction and its applications in Machine Learning",
      "Understanding the risks of overfitting and underfitting in Machine Learning models",
      "Learning about learning curves and their importance in evaluating Machine Learning models",
      "Discussing the method of Least Squares and its advancements, like Ridge Regression and Lasso",
      "Exploring the impact of data preprocessing and parameter selection on the quality of Machine Learning predictions",
      "Studying inductive conformal prediction and its computational efficiency",
      "Applying kernel methods to add flexibility to linear Machine Learning models",
      "Understanding the concepts and applications of neural networks and support vector machines",
      "Learning to use pipelines in Machine Learning workflows with scikit-learn",
      "Studying cross-conformal predictors and their efficiency",
      "Gaining a broad understanding of various prediction algorithms in Machine Learning",
    ],
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
    relatedMaterials: [
      ProjectDatabaseKeys.MachineLearningAssignment1,
      ProjectDatabaseKeys.MachineLearningAssignment2,
      ProjectDatabaseKeys.MachineLearningAssignment3,
      ProjectDatabaseKeys.MachineLearningLabs,
    ],
  },
  [ModuleDatabaseKeys.RHUL_ComputationalFinance]: {
    name: "Computational Finance",
    category: ModuleYearGroupsEnum.Year3,
    skills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Probability,
      SkillDatabaseKeys.Statistics,
      SkillDatabaseKeys.Calculus,
      SkillDatabaseKeys.Mechanics,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the main functions of the financial system and the role of this module within it",
      "Learning about major financial instruments, including bonds and shares, and their pricing mechanisms",
      "Grasping the basics of derivative products and the concept of pricing by arbitrage",
      "Understanding the uses of options and basic option pricing facts using arbitrage principles",
      "Learning to price European and American options using binomial trees",
      "Understanding the principle of risk-neutral valuation for option pricing",
      "Learning to simulate stock price behavior and Wiener processes using random walks",
      "Manipulating stochastic differential equations using Ito's lemma",
      "Understanding the role of Brownian motion and Markov processes in financial modeling",
      "Deriving the Black-Scholes differential equation and formulas for European call and put options pricing",
      "Understanding various numerical methods for option pricing, including trees, Monte-Carlo, and PDEs",
      "Estimating stock volatility from market data",
      "Learning about hedging strategies and the calculation of Greek letters to quantify risk exposure",
      "Applying the Black-Scholes theory in practical hedging scenarios",
      "Understanding the concept of Value at Risk (VaR) and how it quantifies investment portfolio risk",
      "Calculating VaR using different methods and understanding the impact of diversification on VaR",
      "Discussing the applicability and limitations of financial models in the real-world context",
      "Exploring market efficiency hypotheses and current trends in finance",
    ],
    relatedMaterials: [ProjectDatabaseKeys.ComputationalFinanceAssignment],
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },
  [ModuleDatabaseKeys.RHUL_SecurityManagement]: {
    name: "Security Management",
    category: ModuleYearGroupsEnum.Year3,
    skills: [
      SkillDatabaseKeys.CyberSecurity,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
      SkillDatabaseKeys.RiskManagement,
    ],
    learningOutcomes: [
      "Understanding the fundamental concepts of information security",
      "Learning about risk assessment and management in the context of information security",
      "Studying various standards and best practices for information security",
      "Understanding the implementation and importance of security controls",
      "Learning about incident management and disaster recovery strategies",
      "Analyzing case studies to understand real-world applications of security management",
      "Understanding the legal and ethical aspects of information security",
      "Learning about staff management in the context of information security",
      "Reviewing and revising the concepts learned throughout the module",
    ],
    archived: true,
    parentCourse: CourseDatabaseKeys.RHUL_ComputerScience,
  },

  //^ King's College London
  [ModuleDatabaseKeys.KCL_ArtificialIntelligenceReasoningAndDecisionMaking]: {
    name: "Artificial Intelligence, Reasoning & Decision Making",
    category: ModuleYearGroupsEnum.Year1,
    parentCourse: CourseDatabaseKeys.KCL_ArtificialIntelligence,
    skills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.IntelligentAgents,
      SkillDatabaseKeys.Probability,
      SkillDatabaseKeys.Statistics,
      SkillDatabaseKeys.Mathematics,
      SkillDatabaseKeys.Algorithms,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.Logics,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding fundamental concepts of AI agents, environments, and decision making",
      "Applying probability theory and Bayesian reasoning to AI problems",
      "Constructing and reasoning with Bayesian networks",
      "Implementing inference algorithms like variable elimination and sampling methods",
      "Analyzing sequential decision problems using Markov Decision Processes",
      "Solving MDPs through techniques like value iteration and policy iteration",
      "Exploring game theory concepts including Nash equilibria and Pareto optimality",
      "Developing argumentation frameworks and evaluating argument acceptability",
      "Implementing clustering algorithms like k-means and hierarchical clustering",
      "Applying dimensionality reduction techniques such as PCA",
      "Designing agent communication languages and dialogue protocols",
      "Examining ethical considerations in AI development and deployment",
      "Evaluating different AI approaches for reasoning under uncertainty",
      "Implementing search algorithms for problem solving in AI",
      "Understanding knowledge representation techniques in AI systems",
    ],
    relatedMaterials: [ProjectDatabaseKeys.MarkovDecisionAgent],
  },
  [ModuleDatabaseKeys.KCL_AgentsAndMultiAgentSystems]: {
    name: "Agents & Multi-Agent Systems",
    category: ModuleYearGroupsEnum.Year1,
    parentCourse: CourseDatabaseKeys.KCL_ArtificialIntelligence,
    skills: [
      SkillDatabaseKeys.IntelligentAgents,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.Logics,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.Algorithms,
      SkillDatabaseKeys.Probability,
      SkillDatabaseKeys.Statistics,
      SkillDatabaseKeys.Logics,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Defining the key characteristics and concepts of intelligent agents",
      "Analyzing different agent architectures and their capabilities",
      "Designing autonomous agents for specific environments and tasks",
      "Implementing agent communication and coordination mechanisms",
      "Evaluating multi-agent systems and their collective behaviors",
      "Applying game theory concepts to agent decision-making",
      "Developing strategies for negotiation between agents",
      "Constructing voting protocols for group decision-making",
      "Formulating auction mechanisms for resource allocation",
      "Reasoning with arguments in agent dialogues and debates",
      "Comparing different approaches to agent planning and learning",
    ],
  },
  [ModuleDatabaseKeys.KCL_ComputerVision]: {
    name: "Computer Vision",
    category: ModuleYearGroupsEnum.Year1,
    parentCourse: CourseDatabaseKeys.KCL_ArtificialIntelligence,
    skills: [
      SkillDatabaseKeys.Matlab,
      SkillDatabaseKeys.ComputerVision,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.Probability,
      SkillDatabaseKeys.Statistics,
      SkillDatabaseKeys.LinearAlgebra,
      SkillDatabaseKeys.Algorithms,
      SkillDatabaseKeys.DataStructures,
      SkillDatabaseKeys.ObjectOrientedProgramming,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the fundamentals of image formation and camera geometry",
      "Applying low-level image processing techniques such as filtering and edge detection",
      "Implementing segmentation algorithms to group image elements",
      "Solving the correspondence problem for stereo vision and motion analysis",
      "Calculating depth information from stereo image pairs",
      "Analyzing motion in video sequences using optical flow",
      "Recognizing objects using various machine learning and computer vision approaches",
      "Evaluating different object recognition techniques and their applications",
      "Interpreting biological vision processes and comparing them to artificial vision systems",
      "Implementing core computer vision algorithms and understanding their limitations",
    ],
    relatedMaterials: [
      ProjectDatabaseKeys.ComputerVisionImageSegmentation,
      ProjectDatabaseKeys.ComputerVisionQuizzes,
    ],
  },
  [ModuleDatabaseKeys.KCL_PhilosophyAndEthicsOfArtificialIntelligence]: {
    name: "Philosophy & Ethics of Artificial Intelligence",
    category: ModuleYearGroupsEnum.Year1,
    parentCourse: CourseDatabaseKeys.KCL_ArtificialIntelligence,
    skills: [
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
      SkillDatabaseKeys.Communication,
    ],
    learningOutcomes: [
      "Defining intelligence and exploring different types of AI (narrow, general, super).",
      "Examining theories of consciousness and their implications for AI.",
      "Analyzing approaches to reasoning in AI, including logic-based and machine learning methods.",
      "Evaluating ethical theories and their application to AI development.",
      "Investigating issues of algorithmic bias, accountability, and transparency.",
      "Assessing the impact of AI in specific domains like healthcare and warfare.",
      "Exploring potential paths to superintelligence and associated risks.",
      "Addressing the value alignment problem in AI development.",
      "Discussing the societal impacts of AI, including effects on work and human relationships.",
      "Analyzing phenomena like filter bubbles, echo chambers, and surveillance capitalism in relation to AI.",
      "Considering philosophical questions about the nature of intelligence, consciousness, and morality.",
      "Evaluating approaches to implementing moral agents in AI systems.",
      "Examining the challenges of AI decision-making in complex ethical scenarios.",
      "Exploring the concept of machine consciousness and its ethical implications.",
      "Discussing the potential for AI to enhance or alter human cognitive capabilities.",
      "Analyzing the role of AI in shaping public discourse and democratic processes.",
      "Considering the long-term implications of AI development for human society and identity.",
      "Examining frameworks for responsible AI development and deployment.",
    ],
  },
  [ModuleDatabaseKeys.KCL_DataMining]: {
    name: "Data Mining",
    category: ModuleYearGroupsEnum.Year1,
    parentCourse: CourseDatabaseKeys.KCL_ArtificialIntelligence,
    skills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.Statistics,
      SkillDatabaseKeys.Probability,
      SkillDatabaseKeys.LinearAlgebra,
      SkillDatabaseKeys.Algorithms,
      SkillDatabaseKeys.DataStructures,
      SkillDatabaseKeys.ScikitLearn,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.Testing,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Applying data mining techniques to extract meaningful patterns and knowledge from large datasets",
      "Implementing core algorithms for classification, clustering, and association rule mining",
      "Evaluating the performance and suitability of different data mining models",
      "Preprocessing and transforming data to improve mining results",
      "Interpreting and communicating insights gained from data mining analyses",
      "Comparing supervised and unsupervised learning approaches",
      "Handling challenges like high dimensionality, missing data, and noise",
      "Selecting appropriate features and reducing dimensionality of datasets",
      "Analyzing time series data and performing forecasting",
      "Understanding probabilistic and statistical foundations of data mining methods",
      "Applying text mining and information retrieval techniques",
      "Assessing ethical implications and limitations of data mining",
    ],
  },
  [ModuleDatabaseKeys.KCL_OptimizationMethods]: {
    name: "Optimization Methods",
    category: ModuleYearGroupsEnum.Year1,
    parentCourse: CourseDatabaseKeys.KCL_ArtificialIntelligence,
    skills: [
      SkillDatabaseKeys.Algorithms,
      SkillDatabaseKeys.DataStructures,
      SkillDatabaseKeys.LinearAlgebra,
      SkillDatabaseKeys.Calculus,
      SkillDatabaseKeys.Mathematics,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Formulating and solving shortest path problems in graphs",
      "Implementing network flow algorithms like Ford-Fulkerson and Edmonds-Karp",
      "Applying linear programming techniques to network flow problems",
      "Understanding convex sets, functions, and optimization principles",
      "Utilizing gradient descent methods for unconstrained optimization",
      "Employing stochastic optimization techniques like SGD",
      "Solving constrained optimization problems using projected gradient descent and Frank-Wolfe algorithm",
      "Analyzing duality and applying Lagrange multipliers in optimization",
      "Interpreting KKT conditions for optimality in constrained problems",
      "Modeling real-world scenarios as optimization problems across various domains",
    ],
  },
  [ModuleDatabaseKeys.KCL_PatternRecognitionNeuralNetworksDeepLearning]: {
    name: "Pattern Recognition, Neural Networks & Deep Learning",
    category: ModuleYearGroupsEnum.Year1,
    parentCourse: CourseDatabaseKeys.KCL_ArtificialIntelligence,
    skills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.ObjectOrientedProgramming,
      SkillDatabaseKeys.FunctionalProgramming,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.ComputerVision,
      SkillDatabaseKeys.ScikitLearn,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.TensorFlow,
      SkillDatabaseKeys.Jupyter,
      SkillDatabaseKeys.Probability,
      SkillDatabaseKeys.Statistics,
      SkillDatabaseKeys.Calculus,
      SkillDatabaseKeys.LinearAlgebra,
      SkillDatabaseKeys.Algorithms,
      SkillDatabaseKeys.DataStructures,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the fundamental concepts and techniques of pattern recognition and machine learning",
      "Analyzing datasets to extract relevant features for classification tasks",
      "Implementing linear and nonlinear classifiers like perceptrons and support vector machines",
      "Designing and training artificial neural networks for various learning tasks",
      "Applying dimensionality reduction techniques like PCA to preprocess high-dimensional data",
      "Evaluating the performance of machine learning models using appropriate metrics",
      "Implementing ensemble methods like bagging and boosting to improve classifier accuracy",
      "Utilizing deep learning architectures like convolutional neural networks for complex tasks",
      "Comparing different machine learning algorithms to select the most suitable for a given problem",
      "Interpreting the internal representations learned by deep neural networks",
      "Addressing common issues in machine learning like overfitting and class imbalance",
      "Implementing generative models like GANs to create synthetic data",
      "Applying transfer learning to leverage pretrained models for new tasks",
    ],
    relatedMaterials: [ProjectDatabaseKeys.HandWrittenDigitClassifier],
  },
  [ModuleDatabaseKeys.KCL_MachineLearning]: {
    name: "Machine Learning",
    category: ModuleYearGroupsEnum.Year1,
    parentCourse: CourseDatabaseKeys.KCL_ArtificialIntelligence,
    skills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.ReinforcementLearning,
      SkillDatabaseKeys.IntelligentAgents,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.ScikitLearn,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Jupyter,
      SkillDatabaseKeys.Probability,
      SkillDatabaseKeys.Statistics,
      SkillDatabaseKeys.LinearAlgebra,
      SkillDatabaseKeys.Calculus,
      SkillDatabaseKeys.Algorithms,
      SkillDatabaseKeys.DataStructures,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding fundamental machine learning concepts and algorithms",
      "Applying supervised and unsupervised learning techniques to real-world problems",
      "Implementing decision trees, linear regression, and logistic regression models",
      "Utilizing probabilistic methods like Naive Bayes and Hidden Markov Models",
      "Employing support vector machines and kernel methods for classification tasks",
      "Designing and training artificial neural networks",
      "Exploring evolutionary algorithms and genetic programming",
      "Developing reinforcement learning agents using various techniques",
      "Evaluating machine learning model performance using appropriate metrics",
      "Analyzing the ethical implications of machine learning applications",
      "Implementing learning from demonstration techniques",
      "Addressing challenges in machine learning such as overfitting and bias",
    ],
    relatedMaterials: [
      ProjectDatabaseKeys.CustomNeuralNetworkCoursework,
      ProjectDatabaseKeys.CustomQLearningAgent,
    ],
  },
  [ModuleDatabaseKeys.KCL_IndividualProject]: {
    name: "Individual Project",
    category: ModuleYearGroupsEnum.Year1,
    parentCourse: CourseDatabaseKeys.KCL_ArtificialIntelligence,
    skills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.ReinforcementLearning,
      SkillDatabaseKeys.IntelligentAgents,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.ScikitLearn,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.TensorFlow,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.Jupyter,
      SkillDatabaseKeys.Probability,
      SkillDatabaseKeys.Statistics,
      SkillDatabaseKeys.LinearAlgebra,
      SkillDatabaseKeys.Algorithms,
      SkillDatabaseKeys.DataStructures,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.TimeManagement,
    ],
    learningOutcomes: [
      "Designing and implementing a substantial AI-related project independently",
      "Applying advanced AI techniques and methodologies to solve complex problems",
      "Synthesizing knowledge from various AI subfields to create innovative solutions",
      "Evaluating and selecting appropriate AI tools, frameworks, and technologies for specific project requirements",
      "Analyzing and interpreting large datasets using AI and machine learning algorithms",
      "Developing critical thinking skills to address ethical considerations in AI applications",
      "Managing project timelines, resources, and deliverables effectively",
      "Conducting thorough literature reviews to establish the state-of-the-art in the chosen AI topic",
      "Formulating research questions and hypotheses relevant to the AI field",
      "Designing and executing experiments to validate AI models and algorithms",
      "Communicating complex AI concepts and project outcomes through written reports and oral presentations",
      "Demonstrating proficiency in programming languages commonly used in AI development",
      "Critically assessing the performance and limitations of implemented AI systems",
      "Adapting to challenges and setbacks encountered during the project development process",
      "Collaborating with supervisors and peers to refine project goals and methodologies",
    ],
  },
};

/**
 * List of all module keys that can uniquely identify each module.
 */
export const moduleDatabaseKeys: ModuleDatabaseKeys[] = Object.keys(
  modulesMap
) as ModuleDatabaseKeys[];

/**
 * Hashmap of the modules I have studied at university.
 * The keys are defined in {@link ModuleDatabaseKeys}.
 * The order of the modules is the order that will be used to display them.
 *
 * There are certain sub-skills for the skills that are directly listed under the skill objects within this hashmap.
 * For each of those skills, the sub-skill is added to the list of skills for the blog.
 * These sub-skills are specifically general skills related to the technologies but are not part of programming languages.
 * Programming languages have many sub-skills that are not directly related to the blogs above.
 */
const moduleDatabaseMap: Database<ModuleInterface> =
  addNestedSkillsMaterialList<ModuleInterface>(
    modulesMap,
    skillDatabaseMap,
    [SkillCategoriesEnum.ProgrammingLanguages],
    SkillTypesEnum.Technical,
    SkillTypesEnum.Technology
  );

export default moduleDatabaseMap;
