import Certificate from "@/types/certificates";

const programmingLanguages: Certificate[] = [
  {
    name: "Python Programming Masterclass",
    slug: "UC-a3c47af2-7eb8-4f5b-8309-08559c519d5a",
    category: "Programming Languages",
    issuer: "Udemy",
    credentialURL:
      "https://www.udemy.com/certificate/UC-a3c47af2-7eb8-4f5b-8309-08559c519d5a/",
    skills: [
      "Python",
      "Object-Oriented Programming",
      "Algorithms",
      "Data Structures",
    ],
    description: `
      The Python Programming Masterclass on Udemy is an all-encompassing course designed to impart a deep understanding of Python, one of the most sought-after programming languages in the tech industry. 
      This course is tailored for both beginners and existing programmers, focusing on core Python concepts, Object-Oriented Programming, algorithms, and data structures. It uniquely combines theoretical knowledge with practical coding exercises, preparing students for advanced areas like machine learning and data science. By the end of the course, learners will have mastered both Python 2 and 3, equipped with the skills to develop robust Python applications and the confidence to tackle real-world programming challenges.`,
    learningOutcomes: [
      "Understand Python syntax, keywords, and basic structures",
      "Implement Object-Oriented Programming in Python",
      "Write and understand complex Python algorithms",
      "Utilize various data structures in Python",
      "Develop functional Python applications",
      "Distinguish between Python 2 and Python 3",
      "Complete practical coding exercises for skill enhancement",
      "Build foundational skills for advanced Python fields like machine learning and data science",
    ],
  },
  {
    name: "Advanced Python",
    slug: "c235083fcf3a5aadda62a3aac5f1846098135e9058d9c5c72073ef88891b0395",
    category: "Programming Languages",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/c235083fcf3a5aadda62a3aac5f1846098135e9058d9c5c72073ef88891b0395",
    skills: ["Python"],
    archived: true,
    learningOutcomes: [
      "Learning about truth value testing in Python is a key aspect of this course.",
      "Understanding how to use template strings for simpler string formatting is a necessary skill in Python.",
      "The concept of iterators in Python will be explored.",
      "Covering Python's built-in functions for transforming data.",
      "A deep dive into Python functions and their advanced features will be a key learning outcome.",
      "Learning about Python's collections module and its powerful features is a part of this course.",
      "Understanding object-oriented programming in Python with a focus on advanced concepts will be covered.",
      "Delving into how to use Python's logging module to log errors and track code execution.",
      "Learning about list, dictionary, and set comprehensions in Python is a key aspect of this course.",
    ],
  },
  {
    name: "Python Object-Oriented Programming",
    slug: "3df6c589b5151377ce45f231cfacf8ca04a02875fa88996a8831c1c9b70c527a",
    category: "Programming Languages",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/3df6c589b5151377ce45f231cfacf8ca04a02875fa88996a8831c1c9b70c527a",
    skills: ["Python", "Object-Oriented Programming"],
    learningOutcomes: [
      "Learning how to define classes in Python is a key aspect of this course.",
      "Understanding how to check the type of an instance is a necessary skill in Python OOP.",
      "The concept of multiple inheritance in Python will be explored.",
      "Covering how to create objects using the concept of composition in Python.",
      "Leveraging magic methods in Python will be a key learning outcome.",
      "Understanding how and why to call objects like functions in Python is a part of this course.",
      "Defining data classes in Python will be covered.",
      "Delving into the concept of immutability and how to create immutable data classes in Python.",
    ],
  },
  {
    name: "Learning Python",
    slug: "71bbbecbbc9b1489e357c3a2091860ae5b02b3ff0e415ce5748b8746d990b8dd",
    category: "Programming Languages",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/71bbbecbbc9b1489e357c3a2091860ae5b02b3ff0e415ce5748b8746d990b8dd",
    skills: ["Python"],
    archived: true,
    learningOutcomes: [
      "Learning the basics of Python syntax and constructing and running a simple Python program is a key aspect of this course.",
      "Understanding how to work with dates and times, and using the date, time, and datetime classes is a necessary Python skill.",
      "Exploring how to read and write files, and using the OS path utilities and filesystem shell methods is part of this course.",
      "Fetching, parsing, and processing data from the web in JSON, HTML, and XML formats is included in this course.",
      "Practicing and improving programming skills with interactive code challenges and quizzes is a part of the curriculum.",
    ],
  },
  {
    name: "Java Programming Masterclass",
    slug: "UC-a14123c1-1def-4710-8836-7c05bfaa2fc7",
    category: "Programming Languages",
    issuer: "Udemy",
    credentialURL:
      "https://www.udemy.com/certificate/UC-a14123c1-1def-4710-8836-7c05bfaa2fc7/",
    skills: [
      "Java",
      "Object-Oriented Programming",
      "Algorithms",
      "Data Structures",
      "Spring",
      "Android Development",
    ],
    learningOutcomes: [
      "Learning the core Java skills needed to apply for Java developer positions is a key aspect of this course.",
      "Preparing to sit for and pass the Oracle Java Certificate exam is a part of this course.",
      "Demonstrating your understanding of Java to future employers is a goal of this course.",
      "Learning industry 'best practices' in Java software development from a professional Java developer is included in this course.",
      "Acquiring essential Java basics for transitioning to the Spring Framework, Java EE, Android development and more is a part of the curriculum.",
      "Obtaining proficiency in Java 17, as well as older versions including Java 11 and Java 8, is a key learning outcome.",
    ],
  },
  {
    name: "Java Object-Oriented Programming",
    slug: "77ad2602bbb22e29478a06792cd4bd0a91dda794cca7b2bbe4e333c193770a22",
    category: "Programming Languages",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/77ad2602bbb22e29478a06792cd4bd0a91dda794cca7b2bbe4e333c193770a22",
    skills: ["Java", "Object-Oriented Programming"],
  },

  {
    name: "Learning TypeScript",
    slug: "b1761a41ef8dd23125db776561db0b90ae53842518d029015374a2daee08e4e3",
    category: "Programming Languages",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/b1761a41ef8dd23125db776561db0b90ae53842518d029015374a2daee08e4e3",
    skills: ["TypeScript", "JavaScript"],
  },

  {
    name: "JavaScript Essential Training",
    slug: "ade3217d7cef3023f22c8ee034eff28705b7dbfd3981d8377c9b5f61ff39ea51",
    category: "Programming Languages",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/ade3217d7cef3023f22c8ee034eff28705b7dbfd3981d8377c9b5f61ff39ea51",
    skills: ["JavaScript"],
  },
  {
    name: "The Complete JavaScript Course 2023: From Zero to Expert!",
    slug: "UC-cf6c70b6-c34c-4400-b8f8-b9a7abc9f18a",
    category: "Programming Languages",
    issuer: "Udemy",
    credentialURL:
      "https://www.udemy.com/certificate/UC-cf6c70b6-c34c-4400-b8f8-b9a7abc9f18a/",
    skills: ["JavaScript"],
    learningOutcomes: [
      "Becoming an advanced JavaScript developer.",
      "Understanding JavaScript's workings.",
      "Learning developer problem-solving.",
      "Understanding JavaScript fundamentals.",
      "Learning modern ES6+.",
      "Understanding modern OOP concepts.",
      "Grasping complex JavaScript concepts.",
      "Learning asynchronous JavaScript.",
      "Architecting code using flowcharts and patterns.",
      "Using modern tools for 2022 and beyond.",
      "Practicing skills with 50+ challenges and assignments.",
      "Designing a unique learning path.",
    ],
  },
];

const machineLearning: Certificate[] = [
  {
    name: "Applied Machine Learning: Algorithms",
    slug: "964c3b1a049a60afa6bcbb55179e326c7e5cea11db0db7b8d3390be8fc5925e1",
    category: "Machine Learning",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/964c3b1a049a60afa6bcbb55179e326c7e5cea11db0db7b8d3390be8fc5925e1",
    skills: ["Machine Learning"],
    learningOutcomes: [
      "Understanding models vs. algorithms.",
      "Cleaning continuous and categorical variables.",
      "Tuning hyperparameters.",
      "Learning logistic regression basics.",
      "Fitting a support vector machines model.",
      "Understanding when to use a multi-layer perceptron model.",
      "Using the random forest algorithm.",
      "Fitting a basic boosting model.",
    ],
  },
  {
    name: "Applied Machine Learning: Foundations",
    slug: "50182c40b257c756e5d8aea70a9f69f14566da4d3cae7dab86f236554cc7238e",
    category: "Machine Learning",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/50182c40b257c756e5d8aea70a9f69f14566da4d3cae7dab86f236554cc7238e",
    skills: ["Machine Learning"],
    learningOutcomes: [
      "Understanding what is machine learning.",
      "Differentiating Machine Learning, Deep Learning, and Artificial Intelligence.",
      "Handling common challenges in Machine Learning.",
      "Plotting continuous and categorical features.",
      "Cleaning continuous and categorical data.",
      "Measuring success in Machine Learning.",
      "Identifying overfitting and underfitting.",
      "Tuning hyperparameters.",
      "Evaluating a model.",
    ],
  },
  {
    name: "Artificial Intelligence Foundations: Machine Learning",
    slug: "3610d0d7891a746bbe207505c8ec6cfab58723ca973e3082f139a349059248c9",
    category: "Machine Learning",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/3610d0d7891a746bbe207505c8ec6cfab58723ca973e3082f139a349059248c9",
    skills: ["Machine Learning"],
    learningOutcomes: [
      "Understanding machine learning.",
      "Implementing a machine learning solution.",
      "Preparing data for machine learning.",
      "Training a machine learning model.",
      "Evaluating model performance.",
      "Operationalizing a machine learning pipeline.",
    ],
  },
  {
    name: "Artificial Intelligence Foundations: Neural Networks",
    slug: "5dda55caa1ccf02b29f3c0f5d526c8c026f7fc346a6cad6d9c84f98aba3e2514",
    category: "Machine Learning",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/5dda55caa1ccf02b29f3c0f5d526c8c026f7fc346a6cad6d9c84f98aba3e2514",
    skills: ["Machine Learning", "Keras"],
    learningOutcomes: [
      "Understanding neural networks.",
      "Learning key components in neural network architecture.",
      "Exploring other types of neural networks.",
      "Building a neural network using Keras.",
      "Optimizing a neural network.",
    ],
  },
  {
    name: "Data Science Foundations: Fundamentals",
    slug: "e9cb305b4da5f38726226d31e5eef5da66504838131739c389a2d056ed31cf3f",
    category: "Machine Learning",
    issuer: "NASBA",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/e9cb305b4da5f38726226d31e5eef5da66504838131739c389a2d056ed31cf3f",
    skills: [
      "Data Science",
      "Machine Learning",
      "APIs",
      "Python",
      "R",
      "SQL",
      "Algebra",
      "Statistics",
      "Probability",
    ],
    learningOutcomes: [
      "Assessing skills for a data science career.",
      "Evaluating different data sources.",
      "Exploring data through graphs and statistics.",
      "Understanding use of R, Python, and SQL in data science.",
      "Assessing the role of algebra in data science.",
      "Understanding the role of applied statistics in data science.",
      "Understanding the role of machine learning in data science.",
      "Defining components of effective data visualization.",
    ],
  },
  {
    name: "Introduction to Artificial Intelligence",
    slug: "9f61617caf2fc21f029abd857a03a29758d7e822215d3677eb938b4e29e5da78",
    category: "Machine Learning",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/9f61617caf2fc21f029abd857a03a29758d7e822215d3677eb938b4e29e5da78",
    skills: ["Machine Learning"],
    learningOutcomes: [
      "Distinguishing between symbolic systems and machine learning.",
      "Identifying challenges in natural language processing.",
      "Defining types of machine learning.",
      "Understanding the role of algorithms in machine learning.",
      "Determining when to use artificial intelligence.",
      "Reviewing AI and ML differences impacting business decisions.",
      "Understanding data and big data phenomena.",
      "Learning about web technologies, cloud computing, and databases.",
      "Gaining insights into the data science process.",
      "Familiarizing with data science tools.",
      "Learning data cleaning and publishing techniques.",
      "Practicing data wrangling.",
      "Understanding data visualization principles.",
      "Exploring relational data visualization techniques.",
      "Using data visualization tools.",
      "Evaluating understanding of course material.",
    ],
  },
  {
    name: "Machine Learning Foundations: Calculus",
    slug: "94c788dba6f1c97ceee751315c30b6dc6f4267025733c3de55a315d83a36386d",
    category: "Machine Learning",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/94c788dba6f1c97ceee751315c30b6dc6f4267025733c3de55a315d83a36386d",
    skills: ["Machine Learning", "Calculus", "Mathematics"],
    learningOutcomes: [
      "Assessing skills for a data science career.",
      "Evaluating different data sources.",
      "Exploring data through graphs and statistics.",
      "Understanding use of R, Python, and SQL in data science.",
      "Assessing the role of algebra in data science.",
      "Understanding the role of machine learning in data science.",
      "Defining components of effective data visualization.",
      "Assessing the role of ethics and agency in data science.",
    ],
  },
  {
    name: "Machine Learning Foundations: Linear Algebra",
    slug: "ec6ac0178fb92ba75dd38a95ae48316efb6f4e0e9abcb6bf5431b48021ff8441",
    category: "Machine Learning",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/ec6ac0178fb92ba75dd38a95ae48316efb6f4e0e9abcb6bf5431b48021ff8441",
    skills: ["Machine Learning", "Linear Algebra", "Mathematics"],
    learningOutcomes: [
      "Understanding data and big data phenomena.",
      "Learning about web technologies, cloud computing, and databases.",
      "Gaining insights into the data science process.",
      "Familiarizing with data science tools.",
      "Learning data cleaning and publishing techniques.",
      "Practicing data wrangling.",
      "Understanding data visualization principles.",
      "Exploring relational data visualization techniques.",
      "Using data visualization tools.",
      "Evaluating understanding of course material.",
    ],
  },
  {
    name: "Machine Learning Foundations: Probability",
    slug: "b7334fe5b4d04bef6dab5d2ed69080e9ffc590475eba2057046b6ca4a6cf2fba",
    category: "Machine Learning",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/b7334fe5b4d04bef6dab5d2ed69080e9ffc590475eba2057046b6ca4a6cf2fba",
    skills: ["Machine Learning", "Probability", "Mathematics"],
    learningOutcomes: [
      "Learning basics of probability theory in machine learning.",
      "Understanding sum rule, product rule, and conditional probability.",
      "Calculating joint and marginal probability.",
      "Exploring common discrete probability distributions.",
      "Learning about continuous probability distribution.",
      "Discovering Bayes' theorem and its applications.",
    ],
  },
  {
    name: "Machine Learning with Scikit-Learn",
    slug: "3c31f8f11d8ecbd7156dd75b8ae2d7c7db59a8342e3ae7780496b637ac894bb8",
    category: "Machine Learning",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/3c31f8f11d8ecbd7156dd75b8ae2d7c7db59a8342e3ae7780496b637ac894bb8",
    skills: ["Machine Learning", "Scikit-Learn", "Python"],
    learningOutcomes: [
      "Understanding the benefits of using scikit-learn.",
      "Distinguishing between supervised and unsupervised learning.",
      "Learning linear and logistic regression techniques.",
      "Understanding decision trees and random forests.",
      "Learning K-means clustering technique.",
      "Understanding principal component analysis (PCA).",
    ],
  },
];

const devOps: Certificate[] = [
  {
    name: "DevOps Foundations",
    slug: "1c6fedf1993d58cfe2f906e4fe4db5b4eddda6ea5fa7f8999436b07682ffe3f7",
    category: "DevOps",
    issuer: "NASBA",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/1c6fedf1993d58cfe2f906e4fe4db5b4eddda6ea5fa7f8999436b07682ffe3f7",
    skills: ["DevOps"],
    learningOutcomes: [
      "Distinguishing between DevOps practice levels, values, and principles.",
      "Analyzing where to apply best practices.",
      "Managing cultural issues within a team and organization.",
      "Understanding lean in DevOps building blocks.",
      "Applying approaches for automating infrastructure.",
      "Understanding role of continuous integration and quality assurance.",
      "Explaining components of reliability for engineering's design operations.",
      "Describing resources to learn or apply DevOps.",
    ],
  },
  {
    name: "DevOps Foundations: Continuous Delivery/Continuous Integration",
    slug: "6bf47e122551142911c5a636edfee564ff0d57bd07a52888c6c52246946f7747",
    category: "DevOps",
    issuer: "NASBA",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/6bf47e122551142911c5a636edfee564ff0d57bd07a52888c6c52246946f7747",
    skills: ["DevOps", "Continuous Delivery", "Continuous Integration"],
    learningOutcomes: [
      "Exploring utilization of continuous delivery.",
      "Identifying components of the DevOps pipeline.",
      "Recognizing importance and uses of version control.",
      "Determining tools used for CI and CD.",
      "Recognizing terminology used with a DevOps pipeline.",
      "Exploring methods for software testing and best practices.",
    ],
  },
  {
    name: "Jenkins Essential Training",
    slug: "b1f7a0e46c3659d0d1c25396bbd7838b2374b12afcff7404a0d5077b68e9ebfc",
    category: "DevOps",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/b1f7a0e46c3659d0d1c25396bbd7838b2374b12afcff7404a0d5077b68e9ebfc",
    skills: ["Jenkins", "Continuous Integration", "Continuous Delivery"],
    learningOutcomes: [
      "Learning core functions of Jenkins.",
      "Understanding the Jenkins Pipeline.",
      "Integrating Jenkins with Version Control Systems.",
      "Learning about agents and distributed builds.",
      "Understanding artifacts and testing in Jenkins.",
      "Securing Jenkins with user accounts and permissions.",
    ],
  },
  {
    name: "Ansible Essential Training",
    slug: "5eed7f56e5d7dc61b17a3f5fb3cb9fc42130506e948df550bf00899b5868b0a1",
    category: "DevOps",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/5eed7f56e5d7dc61b17a3f5fb3cb9fc42130506e948df550bf00899b5868b0a1",
    skills: ["Ansible", "Infrastructure as Code"],
    learningOutcomes: [
      "Building effective and reusable tasks in Ansible.",
      "Organizing tasks into roles and managing roles with Ansible Galaxy.",
      "Encrypting sensitive information with Ansible Vault.",
      "Performing network management with Ansible.",
      "Understanding and leveraging idempotence in Ansible.",
    ],
  },
  {
    name: "GitHub Actions for CI/CD",
    slug: "679b3ba787209cd0d81d1d68e4bfc01e23ae14f9f2bdfa4e85f917025a8e732b",
    category: "DevOps",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/679b3ba787209cd0d81d1d68e4bfc01e23ae14f9f2bdfa4e85f917025a8e732b",
    skills: [
      "GitHub Actions",
      "DevOps",
      "Continuous Integration",
      "Continuous Delivery",
    ],
    learningOutcomes: [
      "Using GitHub Actions for CI/CD.",
      "Creating continuous integration workflows with GitHub Actions.",
      "Creating continuous delivery workflows with GitHub Actions.",
      "Creating continuous deployment workflows with GitHub Actions.",
    ],
  },
  {
    name: "Docker for Developers",
    slug: "bf3b572548b56f714cc70ee2c1447312a84869f6a93edb55e3d13b13337f3bd5",
    category: "DevOps",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/bf3b572548b56f714cc70ee2c1447312a84869f6a93edb55e3d13b13337f3bd5",
    skills: ["Docker", "Containerization"],
    learningOutcomes: [
      "Creating first Docker image.",
      "Setting up a full-stack environment with Docker.",
      "Deploying and adding nodes to a Docker swarm.",
      "Creating a cluster using Kubernetes.",
      "Setting up GitHub with Travis for Docker projects.",
    ],
  },
  {
    name: "Kubernetes: Provisioning with kind",
    slug: "a63c2359250f6a04bd19dab4ebd049edb511a1a9f2c3ef66a0a8d1df004f7d8d",
    category: "DevOps",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/a63c2359250f6a04bd19dab4ebd049edb511a1a9f2c3ef66a0a8d1df004f7d8d",
    skills: ["Kubernetes", "Containerization", "Clusterization"],
    learningOutcomes: [
      "Installing Kubernetes and its prerequisites.",
      "Deploying Kubernetes in Docker with kind.",
      "Choosing a strategy for provisioning Kubernetes clusters.",
    ],
  },
];

const webDevelopment: Certificate[] = [
  {
    name: "Building RESTful APIs with Flask",
    slug: "c5ccec418e67284d7945832543376e344173867d424cc1c7c7e7f4235b14debe",
    category: "Web Development",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/c5ccec418e67284d7945832543376e344173867d424cc1c7c7e7f4235b14debe",
    skills: ["Flask", "Python", "RESTful APIs", "APIs"],
    learningOutcomes: [
      "Creating a new Flask project.",
      "Working with databases in Flask.",
      "Implementing API security with JWT.",
      "Implementing CRUD operations in API.",
      "Exporting project's requirements file.",
      "Testing APIs with Postman.",
    ],
  },
  {
    name: "Learning REST APIs",
    slug: "d16b210de3459c563295c4868ac19097bdddf84976d2137fa08293ec698f3380",
    category: "Web Development",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/d16b210de3459c563295c4868ac19097bdddf84976d2137fa08293ec698f3380",
    skills: ["RESTful APIs", "APIs"],
    learningOutcomes: [
      "Understanding what is a REST API.",
      "Learning about the interaction with REST APIs.",
      "Exploring the anatomy of a REST request.",
      "Interpreting the response header.",
      "Understanding HTTP status messages.",
      "Learning about request/response pairs in REST.",
    ],
    archived: true,
  },
  {
    name: "Designing RESTful APIs",
    slug: "a54ec39fe8ae07277cfbfb553a61f1d6a0c95f23969a3f665d5e5c0afbd9fd68",
    category: "Web Development",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/a54ec39fe8ae07277cfbfb553a61f1d6a0c95f23969a3f665d5e5c0afbd9fd68",
    skills: ["RESTful APIs", "APIs"],
    learningOutcomes: [
      "Approaches to adding an API.",
      "Modeling tips for APIs.",
      "Identifying activities for API design.",
      "Creating and grouping API methods.",
      "Validating your API design.",
      "Understanding HTTP headers and response codes.",
      "Addressing common design challenges.",
      "Best practices for versioning.",
      "Approaches to hypermedia and documentation.",
    ],
  },
  {
    name: "RESTful APIs with Node.js and Express",
    slug: "c00cb40bda2152dd86d29b813b0d1b172123452a0b87b6017aec13115e693487",
    category: "Web Development",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/c00cb40bda2152dd86d29b813b0d1b172123452a0b87b6017aec13115e693487",
    skills: ["RESTful APIs", "APIs", "Node.js", "Express"],
    learningOutcomes: [
      "Building web API with Node.js and Express.",
      "Setting up project and creating endpoints.",
      "Serving static files with API.",
      "Exploring additional libraries for API development.",
      "Understanding basics of RESTful APIs and CRUD operations.",
    ],
  },
  {
    name: "CSS Fundamentals: Unlock the Power of Web Styling",
    slug: "ff054b4dd1a8fec0eb00ee80a59bc82e5fed3e50b11bba3e3cd33026f0a0eee0",
    category: "Web Development",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/ff054b4dd1a8fec0eb00ee80a59bc82e5fed3e50b11bba3e3cd33026f0a0eee0",
    skills: ["CSS"],
    learningOutcomes: [
      "Understanding what CSS is and how it works with HTML.",
      "Learning common CSS concepts.",
      "Exploring the cascade, specificity, and inheritance in CSS.",
      "Creating layouts with flexbox, grid, and frameworks.",
      "Using browser tools and validation tools for CSS.",
    ],
  },
  {
    name: "Firebase Essential Training",
    slug: "5b6b19227f501cb7dab97b2378a58bc7740bd590a2e44916bf07ba59fd2fc06f",
    category: "Web Development",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/5b6b19227f501cb7dab97b2378a58bc7740bd590a2e44916bf07ba59fd2fc06f",
    skills: [
      "Firebase",
      "Web Development",
      "Cloud Computing",
      "Google Cloud Platform",
      "Backend as a Service (BaaS)",
    ],
    learningOutcomes: [
      "Understanding Firebase and its usage.",
      "Learning Firebase Authentication.",
      "Using Firestore for data storage and query.",
      "Implementing Cloud Functions for back-end logic.",
      "Using Cloud Storage for file handling.",
      "Deploying web app with Firebase Hosting.",
    ],
  },
  {
    name: "Flask Essential Training",
    slug: "4585e03073dcdf552484e6a6d9bc407d1b7e0ad3872d6a3b114d3e3d0869e9ea",
    category: "Web Development",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/4585e03073dcdf552484e6a6d9bc407d1b7e0ad3872d6a3b114d3e3d0869e9ea",
    skills: ["Flask", "Python", "Gunicorn"],
    learningOutcomes: [
      "Understanding pros and cons of Flask.",
      "Creating first route in Flask.",
      "Working with Jinja templates in Flask.",
      "Using GET and POST requests in Flask.",
      "Understanding data flow in Flask.",
      "Setting up an API in Flask.",
      "Templating Flask with Bootstrap.",
      "Testing Flask app.",
      "Deploying app with Gunicorn.",
    ],
  },
  {
    name: "Learning Django",
    slug: "7b5e4d7314ff1b615a3ae959f0d936e66808a5f718a85e42813d957d4ec492d7",
    category: "Web Development",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/7b5e4d7314ff1b615a3ae959f0d936e66808a5f718a85e42813d957d4ec492d7",
    skills: ["Django", "Python"],
    learningOutcomes: [
      "Rapid web application development with Django.",
      "Setting up a Django project.",
      "Working with Django models and the admin.",
      "Building URL handlers and views in Django.",
      "Creating Django templates.",
    ],
  },
  {
    name: "GraphQL Essential Training",
    slug: "3c1654b23256c27553b9d6288d9592aa47fe825a7bf85714283f3e61e26f6f58",
    category: "Web Development",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/3c1654b23256c27553b9d6288d9592aa47fe825a7bf85714283f3e61e26f6f58",
    skills: ["GraphQL", "APIs"],
    learningOutcomes: [
      "Setting up GraphQL and using GraphiQL and Apollo Server.",
      "Exploring the GraphQL schema.",
      "Setting up persistence with SQL and MongoDB in GraphQL.",
      "Using advanced features in GraphQL queries.",
    ],
  },
  {
    name: "HTML Essential Training",
    slug: "983c6ba63131250c1d3df7e13f5e8f8951c02cb64c02c33d99e80df23cf3c869",
    category: "Web Development",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/983c6ba63131250c1d3df7e13f5e8f8951c02cb64c02c33d99e80df23cf3c869",
    skills: ["HTML"],
    learningOutcomes: [
      "Understanding basic syntax of HTML elements.",
      "Formatting content in HTML.",
      "Displaying images using HTML.",
      "Creating links in HTML.",
      "Understanding global HTML attributes.",
      "Building navigation in HTML.",
      "Structuring content with HTML.",
      "Building forms using HTML.",
      "Creating tables in HTML.",
    ],
  },
  {
    name: "Node.js Essential Training",
    slug: "ef41e5cf67f7657353febca7c6b206bf7dd8e28497c393790d8a266842c81132",
    category: "Web Development",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/ef41e5cf67f7657353febca7c6b206bf7dd8e28497c393790d8a266842c81132",
    skills: ["Node.js", "JavaScript"],
    learningOutcomes: [
      "Learning Node.js basics and core.",
      "Understanding what Node.js is and its usage.",
      "Learning about Node globals.",
      "Creating and using Node modules.",
      "Managing files and streams in Node.js.",
    ],
  },
  {
    name: "React.js Essential Training",
    slug: "f2226c0a5de58874e8b882b91fe8945f69d0f0b6de15fa70a09082a08bd464fd",
    category: "Web Development",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/f2226c0a5de58874e8b882b91fe8945f69d0f0b6de15fa70a09082a08bd464fd",
    skills: ["React", "JavaScript"],
    learningOutcomes: [
      "Learning basics of React.js.",
      "Creating reusable components in React.",
      "Handling forms and user input in React.",
      "Fetching data and using React Router.",
      "Testing and deploying React applications.",
    ],
  },
  {
    name: "Learning Next.js",
    slug: "a2ae9eb61db705535ebd73746bfe20e0988633b80ade57c12aa523a9bbdae3db",
    category: "Web Development",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/a2ae9eb61db705535ebd73746bfe20e0988633b80ade57c12aa523a9bbdae3db",
    skills: ["Next.js", "React", "JavaScript"],
    learningOutcomes: [
      "Learning the benefits of Next.js.",
      "Building a file-based routing system in Next.js.",
      "Pre-rendering and fetching data in Next.js.",
      "Styling a Next.js application.",
    ],
  },
  {
    name: "Using TypeScript with React",
    slug: "UC-431983c4-3861-46fc-866e-d97bd5edab77",
    category: "Web Development",
    issuer: "Udemy",
    credentialURL:
      "https://www.udemy.com/certificate/UC-431983c4-3861-46fc-866e-d97bd5edab77/",
    skills: ["TypeScript", "React", "JavaScript"],
    learningOutcomes: [
      "Understanding basic and advanced features of TypeScript.",
      "Using TypeScript in React projects.",
      "Writing types for React patterns.",
      "Integrating TypeScript into a Create React App with Redux.",
      "Building a NextJS web app with GraphQL API using TypeScript.",
      "Using types from third-party packages and creating custom type definitions.",
      "General usage of React with TypeScript.",
    ],
  },
];

const databases: Certificate[] = [
  {
    name: "Database Management System (DBMS) & SQL",
    slug: "UC-b49387a5-5a13-4b1a-aba1-73cac775c026",
    category: "Databases",
    issuer: "Udemy",
    credentialURL:
      "https://www.udemy.com/certificate/UC-b49387a5-5a13-4b1a-aba1-73cac775c026/",
    skills: [
      "SQL",
      "Database Management System",
      "Normalization",
      "Relational Database",
    ],

    description: `
      This comprehensive course offers an in-depth exploration of Database Management Systems (DBMS) and SQL,
      tailored for both beginners and advanced learners. 
      It covers fundamental to advanced concepts of relational databases, including ER modeling, normalization, SQL queries, concurrency control, and indexing with B and B+ Trees. 
      The course is designed to enhance practical skills in database design and query formulation, making it ideal for academic students, competitive exam aspirants, and professionals aiming to excel in the field of database engineering.`,
    learningOutcomes: [
      "Understand the basic concepts of Database Management System (DBMS)",
      "Explain the principles of the relational data model and entity-relationship model",
      "Design and implement effective database systems using normalization techniques",
      "Develop proficiency in SQL for complex query construction and database manipulation",
      "Understand and apply concepts of concurrency control and transaction management",
      "Learn about database indexing with a focus on B and B+ Trees",
      "Acquire the ability to design ER models for real-world database applications",
      "Gain insights into advanced database concepts for competitive exams and professional certification",
    ],
  },
  {
    name: "Database Foundations: Intro to Databases",
    slug: "8b2d47f66f59b8b9724a6c1f05f15e27a9b08c3caaf95169c1d6c64537a1d066",
    category: "Databases",
    issuer: "NASBA",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/8b2d47f66f59b8b9724a6c1f05f15e27a9b08c3caaf95169c1d6c64537a1d066",
    skills: ["SQL", "Database Management System", "Relational Database"],
    learningOutcomes: [
      "Explaining database core concepts.",
      "Constructing a database testing environment.",
      "Operating graphical tools to manage databases.",
      "Defining database table objects.",
      "Adding data to database tables.",
      "Exploring core SQL commands for data retrieval.",
      "Using SQL to manipulate retrieved database data.",
    ],
  },
  {
    name: "Introduction to MongoDB",
    slug: "f024344050a592ea0bb2ada78e0175fabecabab2248ffeb58671b9fe4adfc141",
    category: "Databases",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/f024344050a592ea0bb2ada78e0175fabecabab2248ffeb58671b9fe4adfc141",
    skills: [
      "MongoDB",
      "NoSQL",
      "Database Management System",
      "Document-Oriented Database",
    ],
    learningOutcomes: [
      "Introduction to MongoDB Atlas.",
      "Understanding MongoDB and the Document Model.",
      "Connecting to a MongoDB Database.",
      "Performing MongoDB CRUD Operations.",
      "Using MongoDB Aggregation.",
      "Creating and using MongoDB Indexes.",
      "Using MongoDB Atlas Search.",
      "Introduction to MongoDB Data Modeling.",
      "Using MongoDB Transactions.",
    ],
  },
  {
    name: "Redis Essential Training",
    slug: "209aec09fbb007c809840a071b5db71dc8e08da5b92799121e158ed1e185062b",
    category: "Databases",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/209aec09fbb007c809840a071b5db71dc8e08da5b92799121e158ed1e185062b",
    skills: ["Redis", "NoSQL", "Database Management System"],
    learningOutcomes: [
      "Learning core concepts and basic functionality of Redis.",
      "Understanding different data types and structures in Redis.",
      "Exploring various ways to read and represent data in Redis.",
      "Applying Redis knowledge to practical examples.",
      "Comparing Redis to relational databases and using key naming strategies.",
    ],
  },
];

const mathematics: Certificate[] = [
  {
    name: "Discrete Mathematics",
    slug: "UC-8d13c37d-5013-4873-b4fd-56a867ad853d",
    category: "Mathematics",
    issuer: "Udemy",
    credentialURL:
      "https://www.udemy.com/certificate/UC-8d13c37d-5013-4873-b4fd-56a867ad853d/",
    skills: [
      "Discrete Mathematics",
      "Logic",
      "Set Theory",
      "Sequences",
      "Series",
      "Relations",
      "Functions",
      "Graph Theory",
      "Combinatorics",
      "Probability",
      "Statistics",
    ],
    learningOutcomes: [
      "Developing ability to think, read and write abstractly and Mathematically.",
      "Learning fundamentals of Set Theory.",
      "Understanding tautologies, contradictions, De Morgan's Laws in Logic.",
      "Creating truth tables for compound statements.",
      "Writing, reading and proving Mathematical statements.",
      "Understanding boolean expressions, logical gates and digital circuits.",
      "Understanding the Fundamental Theorem of Arithmetics, modular arithmetic.",
      "Acquiring a solid foundation in functions.",
      "Finding equivalence relations and equivalence classes.",
      "Learning essential concepts in Statistics and Combinatorics.",
      "Mastering arithmetic and geometric sequences, and partial sums.",
      "Learning fundamental concepts in Graph Theory.",
    ],
  },
  {
    name: "A-Level Maths: Pure (Year 1 / AS)",
    slug: "UC-630e6292-a0ee-4ebb-94f0-ebaeedb101a8",
    category: "Mathematics",
    issuer: "Udemy",
    credentialURL:
      "https://www.udemy.com/certificate/UC-630e6292-a0ee-4ebb-94f0-ebaeedb101a8/",
    skills: [
      "Quadratics",
      "Polynomials",
      "Equations",
      "Inequalities",
      "Graphs",
      "Circle Theorems",
      "Proof",
      "Binomial Expansion",
      "Trigonometry",
      "Vectors",
      "Differentiation",
      "Integration",
      "Exponentials",
    ],
    learningOutcomes: [
      "Solving various types of equations.",
      "Solving linear and quadratic inequalities.",
      "Understanding circle equations and geometry.",
      "Learning binomial expansion.",
      "Studying graphs - polynomials, reciprocals and trigonometric.",
      "Exploring trigonometry - equations, identities, graphs and proofs.",
      "Learning calculus - differentiation and integration.",
      "Identifying stationary points and applications of differentiation.",
      "Understanding exponentials and logarithms - solving equations, modelling and graphs.",
      "Performing polynomial division.",
      "Learning proof.",
    ],
  },
  {
    name: "A-Level Maths: Pure (Year 2)",
    slug: "UC-f951f5eb-0e4c-4fd6-8db0-29c24e616a2b",
    category: "Mathematics",
    issuer: "Udemy",
    credentialURL:
      "https://www.udemy.com/certificate/UC-f951f5eb-0e4c-4fd6-8db0-29c24e616a2b/",
    skills: [
      "Partial Fractions",
      "Functions",
      "Graphs",
      "Sequences",
      "Series",
      "Binomial Expansion",
      "Radians",
      "Trigonometry",
      "Differentiation",
      "Integration",
      "Parametric Equations",
      "Numerical Methods",
      "Vectors",
    ],
    learningOutcomes: [
      "Learning differentiation: chain rule, product rule, quotient rule and more.",
      "Understanding integration: reverse chain rule, integration by parts, substitution, differential equations and more.",
      "Studying partial fractions.",
      "Exploring graphs and functions.",
      "Learning binomial expansion.",
      "Understanding radians.",
      "Studying advanced trigonometry, including sec, cosec and cot, and trigonometric identities.",
      "Learning parametric equations.",
      "Understanding vectors.",
      "Learning numerical methods, including iteration and Newton-Raphson.",
    ],
  },
  {
    name: "A-Level Maths: Mechanics (Year 1 / AS)",
    slug: "UC-84beb6d6-275d-41ff-8215-c4918454b846",
    category: "Mathematics",
    issuer: "Udemy",
    credentialURL:
      "https://www.udemy.com/certificate/UC-84beb6d6-275d-41ff-8215-c4918454b846/",
    skills: [
      "Mechanics",
      "Physics",
      "Kinematics",
      "Dynamics",
      "Variable Acceleration",
    ],
    learningOutcomes: [
      "Understanding A-level mechanics.",
      "Learning Newton's laws of motion.",
      "Applying constant acceleration formulae (SUVAT).",
      "Applying calculus to motion problems.",
      "Understanding vectors.",
      "Using calculator for A-level mechanics.",
    ],
  },
  {
    name: "A-Level Maths: Mechanics (Year 2)",
    slug: "UC-729218f1-da7b-4684-857f-78f9920686f2",
    category: "Mathematics",
    issuer: "Udemy",
    credentialURL:
      "https://www.udemy.com/certificate/UC-729218f1-da7b-4684-857f-78f9920686f2/",
    skills: [
      "Mechanics",
      "Physics",
      "Moments",
      "Forces",
      "Friction",
      "Projectiles",
      "Equilibrium",
      "Dynamics",
    ],
    learningOutcomes: [
      "Understanding moments.",
      "Learning kinematics.",
      "Studying statics and equilibrium.",
      "Understanding forces.",
      "Learning dynamics.",
      "Applying variable acceleration.",
      "Understanding vectors.",
    ],
  },
  {
    name: "A-Level Maths: Statistics (Year 1 / AS)",
    slug: "UC-4a1b790f-b0d8-430b-8dfd-d40a60c0ebee",
    category: "Mathematics",
    issuer: "Udemy",
    credentialURL:
      "https://www.udemy.com/certificate/UC-4a1b790f-b0d8-430b-8dfd-d40a60c0ebee/",
    skills: [
      "Statistics",
      "Measures of Location",
      "Measures of Spread",
      "Data Handling",
      "Data Representation",
      "Bivariable Data",
      "Probability",
      "Binomial Distribution",
      "Hypothesis Testing",
      "Sampling",
      "Large Data Sets",
    ],
    learningOutcomes: [
      "Understanding A-Level statistics.",
      "Learning probability.",
      "Performing hypothesis tests.",
      "Understanding binomial distribution.",
      "Learning measures of location and spread.",
      "Analyzing data.",
    ],
  },
  {
    name: "A-Level Maths: Statistics (Year 2)",
    slug: "UC-1efbccad-5f12-4002-85cc-1efebfb81e34",
    category: "Mathematics",
    issuer: "Udemy",
    credentialURL:
      "https://www.udemy.com/certificate/UC-1efbccad-5f12-4002-85cc-1efebfb81e34/",
    skills: [
      "Statistics",
      "Correlation",
      "Regression",
      "Conditional Probability",
      "Discrete Random Variables",
      "Normal Distribution",
      "Hypothesis Testing",
      "Data Analysis",
    ],
    learningOutcomes: [
      "Understanding A-Level statistics.",
      "Learning probability.",
      "Performing hypothesis tests.",
      "Understanding normal distribution.",
      "Learning conditional probability.",
      "Studying correlation.",
      "Understanding regression.",
      "Analyzing data.",
    ],
  },
  {
    name: "Complete A-Level Maths: Mechanics in 5 Lectures",
    slug: "UC-5aabeb79-4fb8-4cab-a5d5-3daa1b009170",
    category: "Mathematics",
    issuer: "Udemy",
    credentialURL:
      "https://www.udemy.com/certificate/UC-5aabeb79-4fb8-4cab-a5d5-3daa1b009170/",
    skills: [
      "Mechanics",
      "Physics",
      "Kinematics",
      "Dynamics",
      "Variable Acceleration",
      "Moments",
      "Forces",
      "Friction",
      "Projectiles",
      "Equilibrium",
      "Dynamics",
    ],
    learningOutcomes: [
      "Understanding A-Level Applied Mathematics: Mechanics topics.",
      "Learning Newton's laws of motion.",
      "Studying forces including weight, normal reaction, friction, tension, thrust/compression etc.",
      "Understanding moments.",
      "Applying constant acceleration kinematics, application of suvat formula.",
      "Learning projectiles.",
      "Applying variable acceleration kinematics.",
    ],
  },
  {
    name: "Complete A-Level Pure Maths Course in 10 Lectures",
    slug: "UC-e2179bc4-5760-4a77-88a4-a2738d22a96e",
    category: "Mathematics",
    issuer: "Udemy",
    credentialURL:
      "https://www.udemy.com/certificate/UC-e2179bc4-5760-4a77-88a4-a2738d22a96e/",
    skills: [
      "Quadratics",
      "Polynomials",
      "Equations",
      "Inequalities",
      "Graphs",
      "Circle Theorems",
      "Proof",
      "Binomial Expansion",
      "Trigonometry",
      "Vectors",
      "Partial Fractions",
      "Functions",
      "Graphs",
      "Sequences",
      "Series",
      "Binomial Expansion",
      "Radians",
      "Trigonometry",
      "Differentiation",
      "Integration",
      "Parametric Equations",
      "Numerical Methods",
      "Vectors",
    ],
    learningOutcomes: [
      "Understanding A-Level Mathematics: pure maths topics.",
      "Learning sequence and series.",
      "Understanding binomial expansion.",
      "Studying trigonometry.",
      "Learning algebra, functions, and parametric equations.",
      "Understanding differentiation.",
      "Learning integration.",
    ],
  },
  {
    name: "Complete A-Level Maths: Statistics in 6 Lectures",
    slug: "UC-fbc6d079-db3f-405f-8c32-f242b266d826",
    category: "Mathematics",
    issuer: "Udemy",
    credentialURL:
      "https://www.udemy.com/certificate/UC-fbc6d079-db3f-405f-8c32-f242b266d826/",
    skills: [
      "Statistics",
      "Measures of Location",
      "Measures of Spread",
      "Data Handling",
      "Data Representation",
      "Bivariable Data",
      "Probability",
      "Binomial Distribution",
      "Hypothesis Testing",
      "Sampling",
      "Large Data Sets",
      "Statistics",
      "Correlation",
      "Regression",
      "Conditional Probability",
      "Discrete Random Variables",
      "Normal Distribution",
      "Poison Distribution",
      "Continuous Random Variables",
      "Geometric Distribution",
    ],
    learningOutcomes: [
      "Understanding A-Level Applied Mathematics: Statistics topics.",
      "Learning statistical sampling: random vs. non-random sampling methods.",
      "Understanding statistical measures of location: median, mode, mean, quartiles and percentiles.",
      "Learning statistical measure of spread: interquartile range, percentile range, variance, standard deviation.",
      "Studying correlation, linear and exponential regression.",
      "Understanding discrete Probability Distribution: discrete uniform distribution, binomial distribution.",
      "Learning continuous Probability Distribution: normal distribution, standard normal distribution.",
      "Applying approximating binomial distribution with normal distribution.",
      "Performing hypothesis Testing of correlation, binomial and normal distribution parameters.",
      "Understanding Venn diagram, tree diagram, Conditional Probability.",
      "Analyzing large Data Set.",
    ],
  },
];

const softwareEngineering: Certificate[] = [
  {
    name: "Create an Open-Source Project in Python",
    slug: "6afc37d98889e1ed209d677fd7928ece257125ca8d538ed6b0fa0ed18e4e30d6",
    category: "Software Engineering",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/6afc37d98889e1ed209d677fd7928ece257125ca8d538ed6b0fa0ed18e4e30d6",
    skills: [
      "Python",
      "Poetry",
      "Pytest",
      "PyPI",
      "Tox",
      "GitHub Actions",
      "Continuous Integration",
      "Continuous Delivery",
      "Linting",
      "Black",
    ],
    learningOutcomes: [
      "Using Poetry for Python project and dependency management.",
      "Writing and running pytests for code quality and functionality.",
      "Using PEP 8, Black, Flake8, and pre-commit for code tidiness and style guide adherence.",
      "Using tox for standardized testing across Python versions and environments.",
      "Setting up a GitHub Action workflow for automated testing and code coverage.",
    ],
  },
  {
    name: "Introducing Maven",
    slug: "551778db5ecef81f732b9e48d50db3fe709f877f1ac9c834923b0c96bb636e72",
    category: "Software Engineering",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/551778db5ecef81f732b9e48d50db3fe709f877f1ac9c834923b0c96bb636e72",
    skills: ["Java", "Maven"],
    learningOutcomes: [
      "Exploring POM files.",
      "Understanding the build life cycle.",
      "Using build plugins.",
      "Managing dependencies with Maven.",
      "Generating Maven reports.",
      "Working with Maven sites.",
    ],
  },
  {
    name: "Software Testing Foundations: Test Techniques",
    slug: "f3297827ac972df2c87c56883f1217ba051a4f12df86886d33f902f2fda5614c",
    category: "Software Engineering",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/f3297827ac972df2c87c56883f1217ba051a4f12df86886d33f902f2fda5614c",
    skills: [
      "Software Testing",
      "Black-Box Testing",
      "White-Box Testing",
      "Experienced-Based Testing",
      "Python",
      "Poetry",
      "Pytest",
      "PEP 8",
      "Black",
      "Flake8",
      "Pre-commit",
      "Tox",
      "GitHub Actions",
    ],
    learningOutcomes: [
      "Creating an open-source project in Python using Poetry.",
      "Enhancing tests using pytest.",
      "Tidying up code using PEP 8, Black, Flake8, and pre-commit.",
      "Standardizing testing using tox.",
      "Setting up a workflow on GitHub Action.",
    ],
  },
  {
    name: "The Git & Github Bootcamp",
    slug: "UC-ba00c0c9-221d-4939-99b4-90244570a81b",
    category: "Software Engineering",
    issuer: "Udemy",
    credentialURL:
      "https://www.udemy.com/certificate/UC-ba00c0c9-221d-4939-99b4-90244570a81b/",
    skills: ["Git", "GitHub", "Version Control"],
    learningOutcomes: [
      "Understanding Git's internal workings.",
      "Explaining Git objects: trees, blobs, commits, and annotated tags.",
      "Mastering the essential Git workflow: adding & committing.",
      "Working with Git branches.",
      "Performing Git merges and resolving merge conflicts.",
      "Using Git diff to reveal changes over time.",
      "Mastering Git stashing.",
      "Undoing changes using git restore, git revert, and git reset.",
      "Working with local and remote repositories.",
      "Mastering collaboration workflows: pull requests, 'fork & clone', etc.",
      "Squashing, cleaning up, and rewriting history using interactive rebase.",
      "Retrieving 'lost' work using git reflogs.",
      "Writing custom and powerful Git aliases.",
      "Marking releases and versions using Git tags.",
      "Hosting static websites using Github Pages.",
      "Creating markdown READMEs.",
      "Sharing code and snippets using Github Gists.",
    ],
  },
];

const management: Certificate[] = [
  {
    name: "Project Management Foundations",
    slug: "8ab210e2af6b2df598aa3e27db515103158cd049367cf6afd9949d874b7677eb",
    category: "Management",
    issuer: "NASBA",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/8ab210e2af6b2df598aa3e27db515103158cd049367cf6afd9949d874b7677eb",
    skills: [
      "Project Management",
      "Time Management",
      "Risk Management",
      "Stakeholder Management",
      "Communication Management",
      "Scope Management",
      "Cost Management",
      "Quality Management",
      "Procurement Management",
      "Integration Management",
      "Human Resource Management",
    ],
    archived: true,
  },
  {
    name: "Project Management Foundations",
    slug: "23788be7119de6bc027865d8345bcd7e8c98563fc1a8a373351e05fa79e1b6ef",
    category: "Management",
    issuer: "PMI",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/23788be7119de6bc027865d8345bcd7e8c98563fc1a8a373351e05fa79e1b6ef",
    skills: [
      "Project Management",
      "Time Management",
      "Risk Management",
      "Stakeholder Management",
      "Communication Management",
      "Scope Management",
      "Cost Management",
      "Quality Management",
      "Procurement Management",
      "Integration Management",
      "Human Resource Management",
    ],
    archived: true,
  },
];

const cloudComputing: Certificate[] = [
  {
    name: "AWS Essential Training for Developers",
    slug: "29e1352bda64cbc78e2f3fbf7205d2761bd8c465925eba7c4cf699aab8cf72b4",
    category: "Cloud Computing",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/29e1352bda64cbc78e2f3fbf7205d2761bd8c465925eba7c4cf699aab8cf72b4",
    skills: ["Amazon Web Services (AWS)"],
  },

  {
    name: "Azure Essential Training for Developers",
    slug: "bf0cac80ff7e3f2b8148e20d6ea1fccb6eb15457a184229fee9ff439f652cfba",
    category: "Cloud Computing",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/bf0cac80ff7e3f2b8148e20d6ea1fccb6eb15457a184229fee9ff439f652cfba",
    skills: ["Microsoft Azure"],
  },

  {
    name: "Google Cloud Platform (GCP) Essential Training for Developers",
    slug: "1bc3074a5e84539c7bc5fdeeee83438602cc303ba648ec90ef5fc018693e62a1",
    category: "Cloud Computing",
    issuer: "LinkedIn",
    credentialURL:
      "https://www.linkedin.com/learning/certificates/1bc3074a5e84539c7bc5fdeeee83438602cc303ba648ec90ef5fc018693e62a1",
    skills: ["Google Cloud Platform (GCP)"],
  },
];

export { cloudComputing };

const allCertificates = [
  ...programmingLanguages,
  ...databases,
  ...softwareEngineering,
  ...webDevelopment,
  ...machineLearning,
  ...devOps,
  ...cloudComputing,
  ...mathematics,
  ...management,
];

export default allCertificates;
