import CertificateDatabaseKeys from "@/database/Certificates/CertificateDatabaseKeys";
import ProjectDatabaseKeys from "@/database/Projects/ProjectDatabaseKeys";
import RoleDatabaseKeys from "@/database/Roles/RoleDatabaseKeys";
import SkillDatabaseKeys from "@/database/Skills/SkillDatabaseKeys";
import ExperienceCategoriesEnum from "@/enums/Experience/ExperienceCategoriesEnum";
import ExperienceTypeEnum from "@/enums/Experience/ExperienceTypeEnum";
import RoleInterface from "@/database/Roles/RoleInterface";
import CompanyDatabaseKeys from "../Companies/CompanyDatabaseKeys";

const rolesMap: Database<RoleInterface> = {
  [RoleDatabaseKeys.CommerzbankDevOpsEngineer]: {
    name: "DevOps Engineer",
    category: ExperienceCategoriesEnum.Software,
    type: ExperienceTypeEnum.Professional,
    skills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.ShellScript,
      SkillDatabaseKeys.Groovy,
      SkillDatabaseKeys.ObjectOrientedProgramming,
      SkillDatabaseKeys.REST,
      SkillDatabaseKeys.APIs,
      SkillDatabaseKeys.SDKs,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MongoDB,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.Hibernate,
      SkillDatabaseKeys.TeamCity,
      SkillDatabaseKeys.Docker,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.IntegrationManagement,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.DevOps,
      SkillDatabaseKeys.Automation,
      SkillDatabaseKeys.Git,
      SkillDatabaseKeys.BitBucket,
      SkillDatabaseKeys.JUnit,
      SkillDatabaseKeys.Gradle,
      SkillDatabaseKeys.AWS,
      SkillDatabaseKeys.GCP,
      SkillDatabaseKeys.Azure,
      SkillDatabaseKeys.Symphony,
      SkillDatabaseKeys.Communication,
      SkillDatabaseKeys.Teamwork,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.Adaptability,
      SkillDatabaseKeys.TimeManagement,
      SkillDatabaseKeys.RiskManagement,
      SkillDatabaseKeys.StakeholderManagement,
      SkillDatabaseKeys.ScopeManagement,
      SkillDatabaseKeys.QualityManagement,
    ],
    startDate: "November 2023",
    endDate: "Present",
    relatedMaterials: [
      CertificateDatabaseKeys.SymphonyCertifiedBotDeveloperJava,
      CertificateDatabaseKeys.SymphonyCertifiedBotDeveloperJava,
    ],
    company: CompanyDatabaseKeys.Commerzbank,
    responsibilities: [
      "DevOps Engineer Role: Leveraging a broad range of skills in my current position, with a focus on Cloud Computing, Version Control, Continuous Integration and Continuous Delivery (CI/CD), Containerization, and DevOps methodologies.",
      "Innovative Database Management: Working with relational databases to enhance data management and accessibility, contributing to streamlined and efficient database operations.",
      "CI/CD Pipeline Development: Utilizing JetBrains TeamCity to develop and optimize CI/CD pipelines, facilitating smoother and more efficient development processes.",
      "Java and Gradle Proficiency: Employing Java and Gradle for building robust and scalable software solutions, demonstrating strong programming skills and system understanding.",
      "Front-End Development for Java APIs: Building user interfaces for Java APIs using NextJS, React, and TypeScript, enhancing user experience and interface functionality.",
      "Symphony Bot Development: Creating Symphony bots to improve communications efficiency between teams and departments, showcasing innovation in internal communication tools.",
      "Effective Team Collaboration: Demonstrating strong teamwork skills by working collaboratively with various departments to implement technology solutions.",
      "Adaptability and Problem-Solving: Quickly adapting to new technologies and environments, and employing creative problem-solving skills to overcome development challenges.",
      "Strong Planning and Time Management: Effectively managing time and planning tasks to meet project deadlines and objectives in a dynamic work environment.",
      "Clear Communication and Critical Thinking: Utilizing clear communication and critical thinking skills to convey complex technical ideas and collaborate effectively with team members.",
    ],
  },
  [RoleDatabaseKeys.GnomeFoundationCommunityMember]: {
    name: "Community Member",
    category: ExperienceCategoriesEnum.Software,
    type: ExperienceTypeEnum.Volunteering,
    company: CompanyDatabaseKeys.GnomeFoundation,
    startDate: "October 2022",
    endDate: "Present",
    skills: [
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.Git,
      SkillDatabaseKeys.LinuxDevelopment,
      SkillDatabaseKeys.GitLab,
      SkillDatabaseKeys.Communication,
      SkillDatabaseKeys.Teamwork,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.Adaptability,
      SkillDatabaseKeys.TimeManagement,
      SkillDatabaseKeys.RiskManagement,
      SkillDatabaseKeys.StakeholderManagement,
      SkillDatabaseKeys.ScopeManagement,
      SkillDatabaseKeys.QualityManagement,
    ],
    responsibilities: [
      "User Acceptance Testing Expertise: Extensively tested the GNOME Desktop environment, identifying key areas for improvement, and contributed to enhancing overall performance and user experience.",
      "Innovative Feature Implementation: Played a crucial role in the development and implementation of the new Quick Settings feature, significantly improving usability for GNOME Desktop and GNOME Mobile users.",
      "Visual Design and Communication: Created detailed mockups and visual representations to effectively communicate design requirements and feature enhancements, facilitating clearer understanding and smoother implementation.",
      "Insightful Feedback on Core Applications: Provided valuable insights and constructive feedback for core GNOME applications, including Files (Nautilus), Terminal, and Settings, leading to notable usability enhancements.",
      "Active Community Engagement: Engaged in regular dialogues with the GNOME community, collaborating on strategies and ideas to refine and optimize the GNOME ecosystem, thereby fostering a vibrant and productive community environment.",
      "Usability Testing and Analysis: Conducted in-depth usability tests, analyzing user interactions and feedback to identify areas for improvement, leading to a 20% increase in user satisfaction ratings for key GNOME components.",
      "Bug Reporting and Resolution Contribution: Diligently identified and reported numerous bugs, contributing to a 15% decrease in critical bugs in subsequent GNOME releases.",
      "Documentation and Guide Development: Authored comprehensive guides and documentation, aiding new users in navigating and utilizing GNOME effectively, which enhanced the community's overall knowledge base.",
      "Collaboration with Development Teams: Worked closely with GNOME developers, offering insights from a user's perspective that directly influenced feature development and prioritization.",
    ],
  },
  [RoleDatabaseKeys.GoogleRHULDevelopersClubSoftwareEngineer]: {
    name: "Software Engineer",
    category: ExperienceCategoriesEnum.Software,
    type: ExperienceTypeEnum.Volunteering,
    skills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.REST,
      SkillDatabaseKeys.GraphQL,
      SkillDatabaseKeys.Apollo,
      SkillDatabaseKeys.APIs,
      SkillDatabaseKeys.SDKs,
      SkillDatabaseKeys.Firebase,
      SkillDatabaseKeys.NextAuth,
      SkillDatabaseKeys.NextJS,
      SkillDatabaseKeys.ReactJS,
      SkillDatabaseKeys.HTML,
      SkillDatabaseKeys.CSS,
      SkillDatabaseKeys.TailwindCSS,
      SkillDatabaseKeys.ChakraUI,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.Prisma,
      SkillDatabaseKeys.GitHub,
      SkillDatabaseKeys.GitHubActions,
      SkillDatabaseKeys.Git,
      SkillDatabaseKeys.Prettier,
      SkillDatabaseKeys.DevOps,
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.Docker,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.Communication,
      SkillDatabaseKeys.Leadership,
      SkillDatabaseKeys.ProjectManagement,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.Adaptability,
      SkillDatabaseKeys.TimeManagement,
      SkillDatabaseKeys.Teamwork,
      SkillDatabaseKeys.RiskManagement,
      SkillDatabaseKeys.StakeholderManagement,
      SkillDatabaseKeys.ScopeManagement,
      SkillDatabaseKeys.QualityManagement,
    ],
    company: CompanyDatabaseKeys.GoogleRHULDevelopersClub,
    relatedMaterials: [ProjectDatabaseKeys.Noodle],
    startDate: "September 2022",
    endDate: "June 2023",
    responsibilities: [
      "Exceptional Communication Skills: Demonstrated outstanding communication skills by effectively articulating technical concepts to non-technical team members, leading to a 40% increase in understanding and collaboration across teams of different fields. Actively involved in presenting project updates and strategies, which enhanced team alignment and project clarity.",
      "Adaptability in Fast-Paced Environments: Showcased exceptional adaptability by swiftly adjusting to evolving project requirements and technological updates, leading to a 30% reduction in project turnaround time and ensuring timely and efficient project delivery.",
      "Collaboration & Team Dynamics: Excelled in collaborating with over 20+ diverse team members, fostering a culture of shared knowledge and support, which increased team efficiency by 25% and streamlined project workflows.",
      "Problem-Solving Excellence: Employed innovative strategies to tackle complex development scenarios, resolving over 50 critical issues, which enhanced project functionality and reliability by 35%.",
      "Self-Motivation & Initiative: Demonstrated self-motivation by initiating and completing 5+ self-directed projects, integrating them into the club's main portfolio and showcasing a dedication to continuous growth.",
      "Full Stack Development: Led key components of the 'Noodle' project using advanced tools like Next.js and React, achieving seamless integrations and targeted project objectives.",
      "Leadership in Tier 3: Recognized as a top-tier (Tier 3) developer, contributing to 35% of the club's major projects and consistently surpassing quality benchmarks.",
      "Continuous Learning & Upgradation: Regularly participated in workshops and seminars, gaining knowledge in the latest development trends and enhancing technical skills.",
      "Technical Mastery: Deepened experience with Next.js, React, MySQL, and expanded into Python and cloud technologies, showcasing versatility in full-stack development.",
      "Technical Mastery: Deepened experience with Next.js, React, MySQL, and expanded into Python and cloud technologies, showcasing versatility in full-stack development.",
    ],
  },
  [RoleDatabaseKeys.AJTuitionCentreTutor]: {
    name: "Mathematics Tutor",
    category: ExperienceCategoriesEnum.Other,
    type: ExperienceTypeEnum.Professional,
    company: CompanyDatabaseKeys.AJTuitionCentre,
    startDate: "September 2018",
    endDate: "March 2020",
    skills: [
      SkillDatabaseKeys.Communication,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.Creativity,
      SkillDatabaseKeys.Adaptability,
      SkillDatabaseKeys.TimeManagement,
    ],
    responsibilities: [
      "Elevated Academic Performance: Successfully elevated the grades of 80% of my students by at least one grade level through the design and implementation of customized lesson plans, tailored to individual learning needs and styles, significantly improving students' understanding and academic performance.",
      "Effective Time Management & Organization: Skillfully managed administrative responsibilities for a diverse roster of 15+ students. Implemented efficient organizational systems and progress tracking methods, ensuring timely completion of educational goals and seamless coordination of learning activities.",
      "Retention and Adaptability in Teaching Methods: Adapted teaching methods and materials to cater to various learning styles, which resulted in a remarkable 90% student retention rate. This adaptability highlights the ability to engage students effectively and address diverse educational needs.",
      "Stakeholder Communication and Relationship Building: Fostered a positive and productive learning environment by maintaining regular, transparent communication with both students and parents enhancing the overall educational experience.",
      "Skill Development in Education: Fine-tuned interpersonal skills, developed innovative problem-solving strategies, and strengthened abilities in rapport-building and effective communication, creating engaging and interactive learning experiences.",
      "Collaborative Development: Collaborated with fellow tutors to refine and enhance the curriculum, contributing to a more engaging and comprehensive educational program.",
      "Feedback & Continuous Improvement: Actively sought and incorporated feedback from students and parents, leading to a more responsive and effective teaching approach, and a 20% increase in satisfaction ratings from both students and parents.•",
    ],
    archived: true,
  },
  [RoleDatabaseKeys.MadhusTeamLeader]: {
    name: "Team Leader",
    category: ExperienceCategoriesEnum.Other,
    type: ExperienceTypeEnum.Professional,
    company: CompanyDatabaseKeys.Madhus,
    startDate: "June 2018",
    endDate: "December 2019",
    skills: [
      SkillDatabaseKeys.Leadership,
      SkillDatabaseKeys.Teamwork,
      SkillDatabaseKeys.Communication,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.Adaptability,
      SkillDatabaseKeys.TimeManagement,
      SkillDatabaseKeys.RiskManagement,
      SkillDatabaseKeys.StakeholderManagement,
      SkillDatabaseKeys.ScopeManagement,
      SkillDatabaseKeys.QualityManagement,
    ],
    responsibilities: [
      "Customer Satisfaction Enhancement: Increased customer satisfaction rates by 15% through quality enhancement initiatives, focusing on customer-centric solutions.",
      "Leadership and Conflict Resolution: Managed dynamic teams of up to 10 staff members during peak hours, effectively resolving conflicts under high-pressure situations.",
      "Efficient Event Management: Successfully coordinated logistics for 5+ events, demonstrating strong organizational and time management skills.",
      "Team Collaboration Enhancement: Improved client and colleague relationships through effective communication, fostering a collaborative work environment.",
      "Skill Development in Hospitality: Refined leadership, conflict resolution, and interpersonal skills in a high-pressure role, laying a foundation for career growth.",
      "Sales and Revenue Growth: Played a key role in achieving a 10% increase in sales through innovative customer engagement and team leadership strategies.",
      "Training & Mentorship Initiatives: Led training programs for new staff, ensuring high service standards and promoting a culture of continuous improvement.",
      "Effective Resource Management: Managed resources efficiently, optimizing operational efficiency and reducing waste.",
      "Customer Relationship Building: Strengthened customer loyalty and brand reputation through personalized service and attention to detail.•",
    ],
    archived: true,
  },
};

export const roleDatabaseKeys: RoleDatabaseKeys[] = Object.keys(
  rolesMap
) as RoleDatabaseKeys[];

const rolesDatabase: Database<RoleInterface> = rolesMap;

export default rolesDatabase;
