import addNestedSkillsMaterialList from "@/actions/material/addNestedSkillsMaterialList";
import ProjectKeysEnum from "@/enums/DatabaseKeysEnums/ProjectKeysEnum";
import SkillKeysEnum from "@/enums/DatabaseKeysEnums/SkillKeysEnum";
import UniversityModuleKeysEnum from "@/enums/DatabaseKeysEnums/UniversityModuleKeysEnum";
import ModuleYearGroups from "@/enums/ModuleYearGroups";
import SkillCategoriesEnum from "@/enums/SkillCategoriesEnum";
import SkillTypesEnum from "@/enums/SkillTypesEnum";
import UniversityModuleInterface from "@/interfaces/material/UniversityModuleInterface";
import skillDatabase from "./skills";

const modulesMap: Database<UniversityModuleInterface> = {
  //^ Royal Holloway University of London
  //* Year 1
  [UniversityModuleKeysEnum.RHUL_ObjectOrientedProgramming1]: {
    name: "Object Oriented Programming 1",
    category: ModuleYearGroups.Year1,
    skills: [
      SkillKeysEnum.Java,
      SkillKeysEnum.ObjectOrientedProgramming,
      SkillKeysEnum.DataStructures,
    ],
    relatedMaterials: [
      ProjectKeysEnum.TrackAndTraceAssignment,
      ProjectKeysEnum.HollomonAssignment,
    ],
    learningOutcomes: [
      "Introducing basic concepts of computer programming",
      "Understanding the importance and role of data in programming",
      "Mastering control flow mechanisms such as branching and iteration",
      "Learning to write and use methods, and handling exceptions",
      "Applying learned concepts to write complex programs",
      "Organizing code using classes and packages",
      "Implementing basic data structures for efficient data management",
      "Interacting with users and environment through input/output operations, file handling, and GUI creation",
      "Preparing for in-class tests and quizzes",
      "Solving challenging problems using linked lists",
      "Preparing for final in-class test and exercise class",
    ],
  },
  [UniversityModuleKeysEnum.RHUL_ObjectOrientedProgramming2]: {
    name: "Object Oriented Programming 2",
    category: ModuleYearGroups.Year1,
    skills: [
      SkillKeysEnum.Java,
      SkillKeysEnum.ObjectOrientedProgramming,
      SkillKeysEnum.DataStructures,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.TimeManagement,
    ],
    relatedMaterials: [ProjectKeysEnum.BotanicGardenPlannerAssignment],
    learningOutcomes: [
      "Exploring enumerated types and recursion in Java",
      "Defining recursive data types and handling exceptions",
      "Understanding I/O streams and implementing stacks and queues",
      "Applying recursive data types in a practical assignment",
      "Learning about Generics and Java's Collections library",
      "Studying searching algorithms and hashtables",
      "Delving into Java's object-oriented language features",
      "Applying Java Collections and inheritance in a practical assignment",
      "Organizing and documenting code in Java",
      "Examining various sorting algorithms",
      "Investigating tree data structures and algorithms",
      "Applying knowledge of streams, inheritance, sorting, and Java in a practical assignment",
      "Understanding threads and concurrency in Java",
    ],
  },
  [UniversityModuleKeysEnum.RHUL_ProgrammingLaboratory]: {
    name: "Programming Laboratory",
    category: ModuleYearGroups.Year1,
    skills: [
      SkillKeysEnum.Python,
      SkillKeysEnum.SimpleGUI,
      SkillKeysEnum.ObjectOrientedProgramming,
      SkillKeysEnum.DataStructures,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.Leadership,
      SkillKeysEnum.Communication,
      SkillKeysEnum.ProjectManagement,
      SkillKeysEnum.TimeManagement,
      SkillKeysEnum.Creativity,
      SkillKeysEnum.Adaptability,
    ],
    relatedMaterials: [ProjectKeysEnum.OsmosGame],
    learningOutcomes: [
      "Understanding computational thinking and basic coding",
      "Translating problem-solving thoughts into precise instructions for computers",
      "Creating interactive fiction as a means of practicing coding",
      "Applying the concept of abstraction to manage complexity in programming",
      "Managing and operating on large data sets with simple data types",
      "Decomposing problems into implementable steps for effective programming",
      "Improving testing approaches for larger programs and understanding test automation",
      "Developing debugging skills to identify and resolve programming issues",
      "Working effectively in programming teams",
      "Preparing for group projects and understanding the requirements for games projects",
    ],
  },
  [UniversityModuleKeysEnum.RHUL_InternetServices]: {
    name: "Internet Services",
    category: ModuleYearGroups.Year1,
    skills: [
      SkillKeysEnum.HTML,
      SkillKeysEnum.CSS,
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the organization and components of the course",
      "Engaging with self-guided non-assessed exercise sheets in lab sessions",
      "Surveying the history of the Internet and the Worldwide Web",
      "Exploring the basic concepts in networks",
      "Studying the Internet Protocol Stack and its layers",
      "Delving into applications and the transport layer",
      "Completing coursework assignment on Internet Basics and the Internet Protocol Stack",
      "Investigating web technologies such as HTML, XML, CSS, Javascript, and PHP",
      "Applying layout and styling using CSS",
      "Understanding scripting languages for the web, specifically Javascript",
      "Briefly studying PHP, a server-side scripting language",
      "Reviewing and summarizing the Internet Protocol Stack",
      "Beginning the study of network security",
    ],
    archived: true,
  },
  [UniversityModuleKeysEnum.RHUL_MathematicalStructures]: {
    name: "Mathematical Structures (Discrete Mathematics)",
    category: ModuleYearGroups.Year1,
    skills: [
      SkillKeysEnum.Mathematics,
      SkillKeysEnum.Discrete,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the importance of Mathematical Structures for Computer Science",
      "Defining sets, elements of sets, and subset/superset relationships",
      "Performing operations on sets such as Union, Intersection, Cardinality, Power Set, and Cartesian Product",
      "Defining Partition of a Set and a Quotient Set",
      "Understanding Strings as elements of a special set",
      "Using Binary Strings to represent sets in a computer",
      "Studying Relations, Orderings, Functions and Cardinality of Infinite Sets",
      "Applying Recursion and Induction",
      "Exploring Graphs and Probability",
      "Understanding independent events and binomial distribution",
      "Calculating mean and variance of a random variable",
      "Studying geometric distribution",
    ],
  },
  [UniversityModuleKeysEnum.RHUL_MachineFundamentals]: {
    name: "Machine Fundamentals",
    category: ModuleYearGroups.Year1,
    skills: [
      SkillKeysEnum.Mathematics,
      SkillKeysEnum.Logics,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the representation of numbers inside a computer",
      "Exploring unsigned, sign magnitude, two's complement representations, and floating point representation of real numbers",
      "Introducing basic propositional logic, logic operators and truth tables",
      "Understanding conjunctive and disjunctive normal forms (CNF and DNF), logical equivalences and proof by logical equivalences",
      "Studying predicate logic, domain of discourse, truth values of predicates, proof by existence and by contradiction, models and semantic entailment, and proofs by inference rules",
      "Designing Boolean logic circuits using AND, OR, NOT and NAND gates",
      "Constructing logic circuits using a DNF of minterms and Karnaugh maps",
      "Understanding full, half and ripple carry adders",
      "Exploring switching circuits, N-type and P-type transistors and canonical pull up/pull down circuit construction",
      "Programming in assembly language using the MIPS language",
      "Understanding regular expressions, nondeterministic and deterministic finite state automata",
      "Applying Thompson's construction and the subset construction",
      "Recognizing that not all sets can be defined by regular expressions",
      "Studying pushdown automata and Turing machines",
    ],
    archived: true,
  },
  [UniversityModuleKeysEnum.RHUL_SoftwareDesign]: {
    name: "Software Design",
    category: ModuleYearGroups.Year1,
    skills: [
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.Leadership,
      SkillKeysEnum.Communication,
      SkillKeysEnum.ProjectManagement,
      SkillKeysEnum.TimeManagement,
      SkillKeysEnum.Creativity,
      SkillKeysEnum.Adaptability,
    ],
    learningOutcomes: [
      "Understanding the fundamentals of Software Engineering, including key concepts, activities, and the characteristics of good software.",
      "Describing the importance of User Experience (UX) in software development and its components, such as usability evaluation.",
      "Exploring various aspects of software requirements including elicitation, modelling, and evaluation processes.",
      "Analyzing and applying software design strategies to model, document, and review according to Software Architecture Documents.",
      "Conducting task analysis and organizing software development activities to support system delivery and management.",
      "Participating in lab sessions to apply theoretical knowledge in practical scenarios, focusing on Coursework 2 and task planning.",
      "Reflecting on learned concepts and applying them to real-world scenarios, particularly in software task analysis and planning, to prepare for the final summative quiz.",
    ],
  },

  //* Year 2
  [UniversityModuleKeysEnum.RHUL_SoftwareEngineering]: {
    name: "Software Engineering",
    category: ModuleYearGroups.Year2,
    skills: [
      SkillKeysEnum.Java,
      SkillKeysEnum.JUnit,
      SkillKeysEnum.ObjectOrientedProgramming,
      SkillKeysEnum.DesignPatterns,
      SkillKeysEnum.VersionControlSystems,
      SkillKeysEnum.DevOps,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.Communication,
      SkillKeysEnum.ProjectManagement,
      SkillKeysEnum.TimeManagement,
      SkillKeysEnum.Adaptability,
    ],
    learningOutcomes: [
      "Tracing the evolution of software engineering from traditional practices to modern Agile methodologies",
      "Utilizing Eclipse IPSE and its tools (Maven, Symbolic Debugger, Javadoc) to enhance software development efficiency",
      "Applying Test-Driven Development (TDD) techniques to ensure the creation of readable and functional code",
      "Identifying and refactoring bad code smells to maintain code quality and standards using tools like CheckStyle",
      "Mastering software version control concepts and tools, including SVN and Git, for effective software release management",
      "Practicing SVN commands and workflows to manage and rectify coding errors efficiently",
      "Communicating software design effectively with UML diagrams and exploiting APIs for rapid application development (RAD)",
      "Analyzing and applying design patterns to prevent common software design problems",
      "Exploring various testing types, including integration and system testing, to ensure robust software functionality",
      "Understanding the role of Continuous Integration in maintaining a consistent testing regime",
      "Applying software measures to predict and improve the quality, productivity, and maintainability of software",
      "Differentiating between defects, faults, and failures to better manage software testing and complexity",
      "Comparing and contrasting Agile and Waterfall methodologies to determine their applicability in different software development scenarios",
      "Practicing SCRUM and other Agile techniques to enhance team collaboration and project management in software development",
    ],
  },
  [UniversityModuleKeysEnum.RHUL_TeamProject]: {
    name: "Team Project",
    category: ModuleYearGroups.Year2,
    skills: [
      SkillKeysEnum.TypeScript,
      SkillKeysEnum.Prisma,
      SkillKeysEnum.NextAuth,
      SkillKeysEnum.NextJS,
      SkillKeysEnum.ReactJS,
      SkillKeysEnum.GraphQL,
      SkillKeysEnum.Apollo,
      SkillKeysEnum.Leadership,
      SkillKeysEnum.ObjectOrientedProgramming,
      SkillKeysEnum.DesignPatterns,
      SkillKeysEnum.VersionControlSystems,
      SkillKeysEnum.DevOps,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.Teamwork,
      SkillKeysEnum.Communication,
      SkillKeysEnum.ProjectManagement,
      SkillKeysEnum.TimeManagement,
      SkillKeysEnum.Adaptability,
    ],
    learningOutcomes: [
      "Understanding the basics and historical context of Software Engineering",
      "Familiarizing with the course structure and expectations",
      "Gaining knowledge of Scrum methodology and its application in Agile project management",
      "Understanding different architectural models and their significance in software design",
      "Learning techniques for code refactoring to improve software maintainability and reduce technical debt",
      "Exploring the core values of Scrum and their impact on professional software development practices",
      "Developing strategies for writing robust code that can handle unexpected system behavior",
      "Understanding the basics of Function Point Analysis and its role in measuring software size and complexity",
      "Learning about software security principles and best practices to protect against vulnerabilities",
      "Applying Function Point Analysis in practical scenarios to estimate software development effort",
      "Examining ethical considerations in software engineering, guided by professional codes of conduct and ethics",
      "Analyzing real-world case studies to understand the application of ethical principles and professional standards in software engineering",
      "Gaining in-depth knowledge of Function Point Analysis, including methodologies, applications, and its historical context",
    ],
  },
  [UniversityModuleKeysEnum.RHUL_OperatingSystems]: {
    name: "Operating Systems",
    category: ModuleYearGroups.Year2,
    skills: [
      // SkillKeysEnum.C,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the basic components of an Operating System (OS) and their management",
      "Starting with C programming, focusing on general features and structure",
      "Grasping the concepts of processes and threads in an OS to manage multitasking",
      "Experimenting with C programming constructs like data types, variables, and functions",
      "Exploring Inter-Process Communication (IPC) and its implementation via busy waiting",
      "Understanding memory management in C, including strings, arrays, and pointers",
      "Studying advanced IPC methods and process communication over networks",
      "Learning system calls, low-level I/O, and process creation in C programming",
      "Analyzing classical IPC problems and the basics of OS scheduling algorithms",
      "Practicing with Unix shell and basic shell programming",
      "Concluding scheduling algorithms and initiating memory management topics",
      "Delving into dynamic memory allocation in C using standard library functions",
      "Understanding virtual memory, paging, and segmentation for efficient memory management",
      "Applying C programming to structures and linked lists for dynamic data storage",
      "Learning about file systems and their role in persistent storage management",
      "Implementing UNIX half-duplex pipes for process communication in C",
      "Understanding deadlocks in OS and strategies to prevent or resolve them",
      "Writing concurrent programs in C using threads and synchronization techniques",
      "Applying OS concepts in real-world Unix-based systems like Linux, MacOS, Android",
      "Reviewing C programming topics and implementing a circular list program",
      "Exploring Windows OS internals and virtualization concepts, including cloud computing",
      "Reviewing the course content and finalizing lab exercises",
      "Applying theoretical and practical knowledge in OS and C programming to solve quiz problems",
      "Creating a dynamic doubly-linked list in C to simulate virtual memory management in an OS",
    ],
    archived: true,
  },
  [UniversityModuleKeysEnum.RHUL_Databases]: {
    name: "Databases",
    category: ModuleYearGroups.Year2,
    skills: [
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.Normalisation,
      SkillKeysEnum.DatabaseIndexing,
      SkillKeysEnum.PostgreSQL,
      SkillKeysEnum.Java,
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the logistics, overview, examples, and history of databases",
      "Learning ER modelling and ER design",
      "Understanding the relational model and translation of ER-diagrams to relational model",
      "Learning relational algebra, select, project, and queries",
      "Understanding the basics of SQL",
      "Learning intermediate SQL",
      "Understanding JDBC",
      "Learning normalisation theory",
    ],
  },
  [UniversityModuleKeysEnum.RHUL_AlgorithmsAndComplexity]: {
    name: "Algorithms and Complexity",
    category: ModuleYearGroups.Year2,
    skills: [
      SkillKeysEnum.Algorithms,
      SkillKeysEnum.Java,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding fundamental algorithms, including sorting and searching",
      "Grasping the concepts of algorithm analysis and efficiency, including Big-Oh notation",
      "Mastering the concepts and implementations of binary search trees (BSTs) and abstract data types (ADTs)",
      "Learning the basics of balanced trees, specifically AVL trees, and their rotations",
      "Expanding knowledge on advanced data structures, including hash tables, heaps, and priority queues",
      "Delving into graph theory basics, including graph representations and properties of depth-first search (DFS) and breadth-first search (BFS)",
      "Beginning with dynamic programming concepts, transitioning to graph algorithms",
      "Understanding the applications of min-cost spanning trees and the mechanics of Kruskal's and Prim's algorithms",
      "Gaining insights into graph search algorithms, specifically DFS and BFS, and their use in establishing connectivity",
      "Exploring the theory and application of min-cost spanning trees, Union-Find data structure, and greedy algorithms",
      "Learning shortest path algorithms, with a focus on Dijkstra’s algorithm",
      "Studying advanced graph algorithm topics, such as handling distances with negative weights and the Floyd-Warshall algorithm",
      "Investigating graph coloring and its algorithmic implementations",
    ],
  },
  [UniversityModuleKeysEnum.RHUL_MultidimensionalDataProcessing]: {
    name: "Multidimensional Data Processing (Linear Algebra)",
    category: ModuleYearGroups.Year2,
    skills: [
      SkillKeysEnum.LinearAlgebra,
      SkillKeysEnum.Python,
      SkillKeysEnum.NumPy,
      SkillKeysEnum.Matplotlib,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the introduction and background of multidimensional data processing",
      "Learning about vectors",
      "Understanding rotations to matrix multiplication",
      "Learning about the inverse of a matrix, graphs, inner products",
      "Understanding matrix classifications",
      "Learning about orthogonal matrices, projection, linear independence",
      "Understanding Page rank",
      "Learning about singular value decomposition (SVD), least squares",
      "Understanding the introduction of principal components analysis (PCA)",
      "Learning about PCA and SVD, applications",
    ],
  },
  [UniversityModuleKeysEnum.RHUL_ArtificialIntelligence]: {
    name: "Artificial Intelligence",
    category: ModuleYearGroups.Year2,
    skills: [
      SkillKeysEnum.ArtificialIntelligence,
      SkillKeysEnum.Algorithms,
      SkillKeysEnum.Logics,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the foundational concepts of AI and its historical background",
      "Gaining an overview of the course structure and the focus on symbolic (model-based) AI",
      "Learning the basic features of Prolog, including logic programming and declarative programming techniques",
      "Acquiring skills in writing Prolog programs and utilizing SWI-Prolog for AI development",
      "Formulating search problems using states, actions, and transitions in AI problem-solving",
      "Differentiating between uninformed and informed search algorithms, and understanding adversarial search for game-playing",
      "Modeling world aspects using propositional and predicate logic, and understanding their computational representations",
      "Applying symbolic logic for non-monotonic reasoning and decision-making in AI systems",
      "Utilizing situation calculus for reasoning about actions and their effects over time",
      "Comparing situation calculus with event calculus for state transition modeling in dynamic environments",
      "Understanding inductive learning and its role in AI, focusing on high-level symbolic learning",
      "Exploring decision tree learning and inductive logic programming, assessing their pros and cons",
      "Mastering SWI-Prolog for implementing AI solutions and completing course-related tasks",
      "Engaging with coursework to apply theoretical concepts in practical scenarios, receiving feedback to enhance learning",
    ],
  },
  [UniversityModuleKeysEnum.RHUL_IntroductionToInformationSecurity]: {
    name: "Introduction to Information Security",
    category: ModuleYearGroups.Year2,
    skills: [
      // SkillKeysEnum.CyberSecurity,
      // SkillKeysEnum.Cryptography,
      SkillKeysEnum.Mathematics,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding basic concepts of information security and the historical perspective of classical cryptography",
      "Exploring fundamental cryptographic techniques including symmetric key cryptography, stream ciphers, and block ciphers",
      "Continuing with symmetric key cryptography, introduction to integrity mechanisms, hash functions, and public key cryptography",
      "Understanding the applications of cryptographic methods, particularly digital signatures and blockchain technologies",
      "Learning about identification and authentication processes, including the use of various biometric technologies",
      "Studying security protocols with a focus on authentication and key establishment, including the Kerberos protocol",
      "Exploring the fundamentals of access control in computer security and different models of access control systems",
      "Gaining insight into OS security measures, with a focus on access control in Unix and Windows operating systems",
      "Learning about software security issues, focusing on malware and buffer overflow attacks, and their prevention methods",
      "Covering basics of network security, including network protocols, architecture, firewalls, and secure communication using TLS",
      "Continuing with network security, including detailed discussions on firewall types, intrusion detection systems, and IPsec for virtual private networks",
    ],
    archived: true,
  },

  //* Year 3
  [UniversityModuleKeysEnum.RHUL_UserCentredDesign]: {
    name: "User Centred Design",
    category: ModuleYearGroups.Year3,
    skills: [
      SkillKeysEnum.UserCentricDesign,
      SkillKeysEnum.Teamwork,
      SkillKeysEnum.Communication,
      SkillKeysEnum.Creativity,
      SkillKeysEnum.QualityManagement,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the principles and importance of User-Centred Design (UCD)",
      "Creating personas and user stories to represent the needs of users",
      "Recognizing how perception and cognition influence user interaction and design decisions",
      "Applying perception and cognition principles in design through practical exercises",
      "Grasping the core aspects of usability in user interface design",
      "Conducting usability evaluations and understanding their impact on user experience",
      "Exploring how human factors across the senses affect interaction design",
      "Performing task analysis to systematically evaluate interactions in designs",
      "Designing interactive systems with a focus on the user's experience",
      "Learning user research methodologies from UX professionals to inform design decisions",
      "Understanding the principles and design considerations for virtual and augmented reality experiences",
      "Gaining hands-on experience in virtual reality testing and interaction design",
      "Applying graphic design principles in the context of user interface and user experience design",
      "Understanding different testing methods and their applications in design",
      "Engaging in design and prototyping workshops to apply theoretical knowledge practically",
      "Integrating audio elements effectively into user interface design to enhance user experience",
      "Applying statistical analysis to interpret and evaluate usability testing data",
      "Presenting and critiquing prototypes to gather actionable feedback",
      "Gaining insights from industry alumni on practical applications of UX principles",
      "Understanding the UX industry landscape and employability skills through expert sessions",
    ],
  },
  [UniversityModuleKeysEnum.RHUL_ITProjectManagement]: {
    name: "IT Project Management",
    category: ModuleYearGroups.Year3,
    skills: [
      SkillKeysEnum.ProjectManagement,
      SkillKeysEnum.Communication,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.TimeManagement,
      SkillKeysEnum.RiskManagement,
      SkillKeysEnum.StakeholderManagement,
      SkillKeysEnum.ScopeManagement,
      SkillKeysEnum.CostManagement,
      SkillKeysEnum.QualityManagement,
      SkillKeysEnum.ProcurementManagement,
      SkillKeysEnum.IntegrationManagement,
    ],
    learningOutcomes: [
      "Understanding what constitutes a project, its lifecycle, and key characteristics",
      "Analyzing the project triangle and its impact on project management, especially in technology sectors",
      "Mastering the concepts of business case development, investment appraisal, estimations, and budgeting",
      "Exploring IT systems acquisition models and procurement management processes",
      "Identifying project stakeholders and conducting stakeholder analysis",
      "Understanding project governance and the creation of a Project Charter",
      "Conducting requirements elicitation and defining project scope using Work Breakdown Structure (WBS)",
      "Creating project schedules, including network diagrams, critical path analysis, Gantt charts, and milestones",
      "Planning project resources using common tools and techniques",
      "Establishing project communications plans and management strategies",
      "Understanding the fundamentals of project risk management and developing a Risk Management Plan",
      "Implementing the Risk Management Process, including the use of a Risk Register",
      "Differentiating between Software Configuration Management and Project Configuration Management",
      "Managing project changes effectively through Change Management processes",
      "Applying S-Curve Analysis, Milestones, and Tracking Gantt Charts for project monitoring",
      "Utilizing Earned Value Management and Scrum/Agile methodologies for performance tracking",
      "Recognizing the characteristics of effective project teams and common reasons for team failure",
      "Applying the Tuckman Model, understanding leadership styles, goal-setting, time management, meetings management, and conflict management",
      "Grasping the basics of Project Quality Management and general Quality Management principles",
      "Gaining insight into the necessary skills, job market outlook for project managers, and the relevant code of ethics",
    ],
    archived: true,
  },
  [UniversityModuleKeysEnum.RHUL_FunctionalProgramming]: {
    name: "Functional Programming",
    category: ModuleYearGroups.Year3,
    skills: [
      SkillKeysEnum.FunctionalProgramming,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the history and development of functional programming",
      "Differentiating between imperative and functional programming paradigms",
      "Gaining foundational knowledge of the Haskell programming language",
      "Learning the basics of typing in Haskell",
      "Programming with functions in Haskell",
      "Deepening understanding of function-based programming in Haskell",
      "Utilizing list comprehensions in Haskell programming",
      "Studying higher-order functions and their applications in Haskell",
      "Exploring type declarations and type systems in Haskell",
      "Understanding the concept of multiparadigm programming languages",
      "Introduction to the Scala programming language",
      "Learning Scala's functional programming features",
      "Reviewing recursion in functional programming",
      "Understanding lazy evaluation in Haskell",
      "Exploring advanced topics in functional programming, including advanced type systems",
    ],
  },
  [UniversityModuleKeysEnum.RHUL_FinalYearProject]: {
    name: "Final Year Project (Web Development)",
    category: ModuleYearGroups.Year3,
    skills: [
      SkillKeysEnum.TypeScript,
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.NextJS,
      SkillKeysEnum.ReactJS,
      SkillKeysEnum.ChakraUI,
      SkillKeysEnum.Firebase,
      SkillKeysEnum.Recoil,
      SkillKeysEnum.Docker,
      SkillKeysEnum.GitHubActions,
      SkillKeysEnum.GitHub,
      SkillKeysEnum.GCP,
      SkillKeysEnum.Git,
      SkillKeysEnum.HTML,
      SkillKeysEnum.CSS,
      SkillKeysEnum.Yarn,
      SkillKeysEnum.ESLint,
      SkillKeysEnum.Prettier,
      SkillKeysEnum.Python,
      SkillKeysEnum.SQLAlchemy,
      SkillKeysEnum.Flask,
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.Normalisation,
      SkillKeysEnum.DatabaseIndexing,
      SkillKeysEnum.Poetry,
      SkillKeysEnum.REST,

      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.ProjectManagement,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.Creativity,
      SkillKeysEnum.Adaptability,
      SkillKeysEnum.TimeManagement,
      SkillKeysEnum.ScopeManagement,
      SkillKeysEnum.StakeholderManagement,
      SkillKeysEnum.Communication,
      SkillKeysEnum.RiskManagement,
      SkillKeysEnum.ObjectOrientedProgramming,
      SkillKeysEnum.DesignPatterns,
      SkillKeysEnum.Algorithms,
    ],
    learningOutcomes: [
      "Designing and implementing a full-stack web application realizing an online service",
      "Understanding and applying web development as a fundamental skill in computer science",
      "Using state-of-the-art technologies and established best practices in web development",
      "Developing a web application following an N-tier architectural pattern",
      "Implementing application logic and user interface using existing web application technologies/platforms",
      "Designing a relational database schema with sound constraints according to normalization rules",
      "Evaluating state-of-the-art options for web development technologies based on various comparison criteria",
      "Investigating and reflecting on a number of candidate technologies for web development",
      "Justifying the choices made in technology selection for the web application",
      "Implementing advanced features such as ACID transactions, comprehensive security/privacy analysis, and advanced security mechanisms",
      "Using NoSQL data stores to speed up user interaction while maintaining sound levels of transactional consistency",
      "Implementing advanced UI features such as push notifications",
      "Exploring the use of emerging platforms such as blockchain in web development",
    ],
  },
  [UniversityModuleKeysEnum.RHUL_MachineLearning]: {
    name: "Machine Learning",
    category: ModuleYearGroups.Year3,
    skills: [
      SkillKeysEnum.Python,
      SkillKeysEnum.MachineLearning,
      SkillKeysEnum.ScikitLearn,
      SkillKeysEnum.NumPy,
      SkillKeysEnum.Matplotlib,
      SkillKeysEnum.Jupyter,
      SkillKeysEnum.Algorithms,
      SkillKeysEnum.Algebra,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the fundamental concepts of Machine Learning",
      "Applying the Nearest Neighbours algorithm in Machine Learning problems",
      "Gaining introductory knowledge of conformal prediction and its significance in Machine Learning for reliable predictions",
      "Completing the discussion on full conformal prediction and its applications in Machine Learning",
      "Understanding the risks of overfitting and underfitting in Machine Learning models",
      "Learning about learning curves and their importance in evaluating Machine Learning models",
      "Discussing the method of Least Squares and its advancements, like Ridge Regression and Lasso",
      "Exploring the impact of data preprocessing and parameter selection on the quality of Machine Learning predictions",
      "Studying inductive conformal prediction and its computational efficiency",
      "Applying kernel methods to add flexibility to linear Machine Learning models",
      "Understanding the concepts and applications of neural networks and support vector machines",
      "Learning to use pipelines in Machine Learning workflows with scikit-learn",
      "Studying cross-conformal predictors and their efficiency",
      "Gaining a broad understanding of various prediction algorithms in Machine Learning",
    ],
  },
  [UniversityModuleKeysEnum.RHUL_ComputationalFinance]: {
    name: "Computational Finance",
    category: ModuleYearGroups.Year3,
    skills: [
      SkillKeysEnum.Python,
      SkillKeysEnum.Probability,
      SkillKeysEnum.Statistics,
      SkillKeysEnum.Calculus,
      SkillKeysEnum.Mechanics,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.TimeManagement,
    ],
    learningOutcomes: [
      "Understanding the main functions of the financial system and the role of this module within it",
      "Learning about major financial instruments, including bonds and shares, and their pricing mechanisms",
      "Grasping the basics of derivative products and the concept of pricing by arbitrage",
      "Understanding the uses of options and basic option pricing facts using arbitrage principles",
      "Learning to price European and American options using binomial trees",
      "Understanding the principle of risk-neutral valuation for option pricing",
      "Learning to simulate stock price behavior and Wiener processes using random walks",
      "Manipulating stochastic differential equations using Ito's lemma",
      "Deriving the Black-Scholes differential equation and formulas for European call and put options pricing",
      "Understanding various numerical methods for option pricing, including trees, Monte-Carlo, and PDEs",
      "Estimating stock volatility from market data",
      "Learning about hedging strategies and the calculation of Greek letters to quantify risk exposure",
      "Applying the Black-Scholes theory in practical hedging scenarios",
      "Understanding the concept of Value at Risk (VaR) and how it quantifies investment portfolio risk",
      "Calculating VaR using different methods and understanding the impact of diversification on VaR",
      "Discussing the applicability and limitations of financial models in the real-world context",
      "Exploring market efficiency hypotheses and current trends in finance",
    ],
  },
  [UniversityModuleKeysEnum.RHUL_SecurityManagement]: {
    name: "Security Management",
    category: ModuleYearGroups.Year3,
    skills: [
      // SkillKeysEnum.CyberSecurity,
      SkillKeysEnum.ProblemSolving,
      SkillKeysEnum.CriticalThinking,
      SkillKeysEnum.TimeManagement,
      SkillKeysEnum.RiskManagement,
    ],
    learningOutcomes: [
      "Understanding the fundamental concepts of information security",
      "Learning about risk assessment and management in the context of information security",
      "Studying various standards and best practices for information security",
      "Understanding the implementation and importance of security controls",
      "Learning about incident management and disaster recovery strategies",
      "Analyzing case studies to understand real-world applications of security management",
      "Understanding the legal and ethical aspects of information security",
      "Learning about staff management in the context of information security",
      "Reviewing and revising the concepts learned throughout the module",
    ],
    archived: true,
  },
};

export const moduleKeys: UniversityModuleKeysEnum[] = Object.keys(
  modulesMap
) as UniversityModuleKeysEnum[];

const moduleDatabase: Database<UniversityModuleInterface> =
  addNestedSkillsMaterialList<UniversityModuleInterface>(
    modulesMap,
    skillDatabase,
    [SkillCategoriesEnum.ProgrammingLanguages],
    SkillTypesEnum.General,
    SkillTypesEnum.Hard
  );

export default moduleDatabase;
