import SkillCategoriesEnum from "@/enums/SkillCategoriesEnum";
import SkillKeysEnum from "@/enums/DatabaseKeysEnums/SkillKeysEnum";
import SkillTypesEnum from "@/enums/SkillTypesEnum";
import SkillInterface from "@/interfaces/skills/SkillInterface";

/**
 * Hashmap of skills with keys as {@link SkillKeysEnum} and values as {@link SkillInterface}.
 * The order of skills and sub-skills is the order that is used when displaying the skills on the website.
 */
const skillDatabase: Database<SkillInterface> = {
  //^ Languages
  [SkillKeysEnum.Python]: {
    name: "Python",
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillKeysEnum.Flask,
      SkillKeysEnum.Django,
      SkillKeysEnum.Gunicorn,
      SkillKeysEnum.Jinja,
      SkillKeysEnum.SimpleGUI,
      SkillKeysEnum.SQLAlchemy,
      SkillKeysEnum.Black,
      SkillKeysEnum.PyLint,
      SkillKeysEnum.PyTest,
      SkillKeysEnum.UnitTest,
      SkillKeysEnum.Poetry,
      SkillKeysEnum.Pip,
      SkillKeysEnum.PyBuilder,
      SkillKeysEnum.ScikitLearn,
      SkillKeysEnum.Pandas,
      SkillKeysEnum.NumPy,
      SkillKeysEnum.Matplotlib,
      SkillKeysEnum.Seaborn,
      SkillKeysEnum.Jupyter,
      SkillKeysEnum.Keras,
      SkillKeysEnum.MachineLearning,
      SkillKeysEnum.DeepLearning,
      SkillKeysEnum.ArtificialIntelligence,
      SkillKeysEnum.DataScience,
      SkillKeysEnum.Hyperparameters,
      SkillKeysEnum.Boosting,
      SkillKeysEnum.DataVisualisation,
      SkillKeysEnum.NeuralNetworks,
      SkillKeysEnum.WebDevelopment,
    ],
  },
  [SkillKeysEnum.JavaScript]: {
    name: "JavaScript",
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillKeysEnum.ClerkAuth,
      SkillKeysEnum.NextAuth,
      SkillKeysEnum.ExpressJS,
      SkillKeysEnum.NextJS,
      SkillKeysEnum.SvelteKit,
      SkillKeysEnum.AngularJS,
      SkillKeysEnum.NuxtJS,
      SkillKeysEnum.ReactJS,
      SkillKeysEnum.SvelteJS,
      SkillKeysEnum.VueJS,
      SkillKeysEnum.Recoil,
      SkillKeysEnum.Redux,
      SkillKeysEnum.Mongoose,
      SkillKeysEnum.Prettier,
      SkillKeysEnum.ESLint,
      SkillKeysEnum.Jest,
      SkillKeysEnum.Vitest,
      SkillKeysEnum.NPM,
      SkillKeysEnum.Yarn,
      SkillKeysEnum.PNPM,
      SkillKeysEnum.NxJS,
    ],
  },
  [SkillKeysEnum.TypeScript]: {
    name: "TypeScript",
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillKeysEnum.ClerkAuth,
      SkillKeysEnum.NextAuth,
      SkillKeysEnum.ExpressJS,
      SkillKeysEnum.NextJS,
      SkillKeysEnum.SvelteKit,
      SkillKeysEnum.AngularJS,
      SkillKeysEnum.NuxtJS,
      SkillKeysEnum.ReactJS,
      SkillKeysEnum.SvelteJS,
      SkillKeysEnum.VueJS,
      SkillKeysEnum.Recoil,
      SkillKeysEnum.Redux,
      SkillKeysEnum.Mongoose,
      SkillKeysEnum.Prettier,
      SkillKeysEnum.ESLint,
      SkillKeysEnum.Jest,
      SkillKeysEnum.Vitest,
      SkillKeysEnum.NPM,
      SkillKeysEnum.Yarn,
      SkillKeysEnum.PNPM,
      SkillKeysEnum.NxJS,
      SkillKeysEnum.TypeORM,
      SkillKeysEnum.Zod,
    ],
  },
  [SkillKeysEnum.Java]: {
    name: "Java",
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillKeysEnum.Spring,
      SkillKeysEnum.SpringBoot,
      SkillKeysEnum.Hibernate,
      SkillKeysEnum.Checkstyle,
      SkillKeysEnum.JUnit,
      SkillKeysEnum.Gradle,
      SkillKeysEnum.Maven,
      SkillKeysEnum.AndroidDevelopment,
    ],
  },
  [SkillKeysEnum.GameMakerLanguage]: {
    name: "GameMaker Language",
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillKeysEnum.GameDevelopment,
      SkillKeysEnum.GameMakerStudio,
    ],
  },
  [SkillKeysEnum.ShellScript]: {
    name: "Shell Script",
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillKeysEnum.C]: {
    name: "C",
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillKeysEnum.Haskell]: {
    name: "Haskell",
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillKeysEnum.Scala]: {
    name: "Scala",
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillKeysEnum.RLanguage]: {
    name: "R",
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillKeysEnum.Groovy]: {
    name: "Groovy",
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [SkillKeysEnum.Gradle, SkillKeysEnum.Jenkins],
  },

  //^ Full Stack Web Development
  [SkillKeysEnum.NextJS]: {
    name: "Next.js",
    category: SkillCategoriesEnum.FullStackWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,

    relatedSkills: [
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
      SkillKeysEnum.ReactJS,
      SkillKeysEnum.NextAuth,
    ],
  },

  [SkillKeysEnum.AngularJS]: {
    name: "Angular",
    category: SkillCategoriesEnum.FullStackWebDevelopment,
    skillType: SkillTypesEnum.Hard,

    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
    ],
  },
  [SkillKeysEnum.NuxtJS]: {
    name: "Nuxt.js",
    category: SkillCategoriesEnum.FullStackWebDevelopment,
    skillType: SkillTypesEnum.Hard,

    relatedSkills: [
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
      SkillKeysEnum.VueJS,
    ],
  },
  [SkillKeysEnum.SvelteKit]: {
    name: "SvelteKit",
    category: SkillCategoriesEnum.FullStackWebDevelopment,
    skillType: SkillTypesEnum.Hard,

    relatedSkills: [
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
      SkillKeysEnum.SvelteJS,
    ],
  },

  //^ Frontend Web Development
  [SkillKeysEnum.Recoil]: {
    name: "Recoil",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.StateManagement,
    ],
  },
  [SkillKeysEnum.Zustand]: {
    name: "Zustand",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.StateManagement,
    ],
  },
  [SkillKeysEnum.Jotai]: {
    name: "Jotai",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.StateManagement,
    ],
  },

  [SkillKeysEnum.Redux]: {
    name: "Redux",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.StateManagement,
    ],
  },
  [SkillKeysEnum.TailwindCSS]: {
    name: "Tailwind CSS",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
    ],
  },
  [SkillKeysEnum.HTML]: {
    name: "HTML",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
    ],
  },
  [SkillKeysEnum.CSS]: {
    name: "CSS",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
    ],
  },
  [SkillKeysEnum.ReactJS]: {
    name: "React",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
      SkillKeysEnum.Recoil,
      SkillKeysEnum.Zustand,
      SkillKeysEnum.Jotai,
      SkillKeysEnum.Redux,
    ],
  },
  [SkillKeysEnum.SvelteJS]: {
    name: "Svelte",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
    ],
  },

  [SkillKeysEnum.VueJS]: {
    name: "Vue",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserAuthentication,
    ],
  },
  [SkillKeysEnum.ChakraUI]: {
    name: "Chakra UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
    ],
  },

  [SkillKeysEnum.HeadlessUI]: {
    name: "Headless UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
      SkillKeysEnum.ReactJS,
      SkillKeysEnum.VueJS,
    ],
  },
  [SkillKeysEnum.ShadcnUI]: {
    name: "Shadcn UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
      SkillKeysEnum.ReactJS,
    ],
  },
  [SkillKeysEnum.RadixUI]: {
    name: "Radix UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
      SkillKeysEnum.ReactJS,
    ],
  },

  [SkillKeysEnum.ReactQuery]: {
    name: "React Query",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
      SkillKeysEnum.ReactJS,
    ],
  },
  [SkillKeysEnum.NextUI]: {
    name: "Next UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
      SkillKeysEnum.ReactJS,
    ],
  },
  [SkillKeysEnum.Bootstrap]: {
    name: "Bootstrap",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
    ],
  },
  [SkillKeysEnum.MaterialUI]: {
    name: "Material UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
    ],
  },
  [SkillKeysEnum.SemanticUI]: {
    name: "Semantic UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
    ],
  },
  [SkillKeysEnum.AntDesign]: {
    name: "Ant Design",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
    ],
  },
  [SkillKeysEnum.StoryBooks]: {
    name: "Storybooks",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.UserCentricDesign,
    ],
  },
  [SkillKeysEnum.SimpleGUI]: {
    name: "Simple GUI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.UserCentricDesign],
  },
  [SkillKeysEnum.Axios]: {
    name: "Axios",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.WebDevelopment, SkillKeysEnum.APIs],
  },

  //^ Backend Web Development
  [SkillKeysEnum.Firebase]: {
    name: "Firebase",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.NonRelationalDatabases,
      SkillKeysEnum.Databases,
      SkillKeysEnum.DatabaseIndexing,
      SkillKeysEnum.CloudComputing,
      SkillKeysEnum.UserAuthentication,
      SkillKeysEnum.SDKs,
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.GCP,
      SkillKeysEnum.Security,
      SkillKeysEnum.CyberSecurity,
    ],
  },
  [SkillKeysEnum.Supabase]: {
    name: "Supabase",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.DatabaseIndexing,
      SkillKeysEnum.Databases,
      SkillKeysEnum.CloudComputing,
      SkillKeysEnum.UserAuthentication,
      SkillKeysEnum.SDKs,
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.PostgreSQL,
      SkillKeysEnum.Security,
      SkillKeysEnum.CyberSecurity,
    ],
  },
  [SkillKeysEnum.PocketBase]: {
    name: "PocketBase",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.Databases,
      SkillKeysEnum.DatabaseIndexing,
      SkillKeysEnum.CloudComputing,
      SkillKeysEnum.UserAuthentication,
      SkillKeysEnum.SDKs,
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.Security,
      SkillKeysEnum.CyberSecurity,
    ],
  },
  [SkillKeysEnum.Auth0]: {
    name: "Auth0",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.UserAuthentication,
      SkillKeysEnum.SDKs,
      SkillKeysEnum.Security,
      SkillKeysEnum.CyberSecurity,
    ],
  },
  [SkillKeysEnum.ClerkAuth]: {
    name: "Clerk Auth",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.UserAuthentication,
      SkillKeysEnum.SDKs,
      SkillKeysEnum.Security,
      SkillKeysEnum.CyberSecurity,
    ],
  },
  [SkillKeysEnum.NextAuth]: {
    name: "NextAuth",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
      SkillKeysEnum.UserAuthentication,
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.Security,
      SkillKeysEnum.CyberSecurity,
    ],
  },
  [SkillKeysEnum.Stripe]: {
    name: "Stripe",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.SDKs,
      SkillKeysEnum.Security,
      SkillKeysEnum.CyberSecurity,
    ],
  },
  [SkillKeysEnum.ExpressJS]: {
    name: "Express",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.APIs,
      SkillKeysEnum.Security,
      SkillKeysEnum.CyberSecurity,
    ],
  },
  [SkillKeysEnum.Flask]: {
    name: "Flask",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.APIs,
      SkillKeysEnum.Python,
      SkillKeysEnum.Security,
      SkillKeysEnum.CyberSecurity,
    ],
  },
  [SkillKeysEnum.Django]: {
    name: "Django",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.APIs,
      SkillKeysEnum.Python,
      SkillKeysEnum.Security,
      SkillKeysEnum.CyberSecurity,
    ],
  },
  [SkillKeysEnum.Spring]: {
    name: "Spring",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.APIs,
      SkillKeysEnum.Java,
      SkillKeysEnum.Security,
      SkillKeysEnum.CyberSecurity,
    ],
  },
  [SkillKeysEnum.SpringBoot]: {
    name: "Spring Boot",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.APIs,
      SkillKeysEnum.Java,
      SkillKeysEnum.Security,
      SkillKeysEnum.CyberSecurity,
    ],
  },
  [SkillKeysEnum.Cloudinary]: {
    name: "Cloudinary",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Cloudinary],
  },
  [SkillKeysEnum.EdgeStore]: {
    name: "Edge Store",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.WebDevelopment],
  },
  [SkillKeysEnum.Gunicorn]: {
    name: "Gunicorn",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Python, SkillKeysEnum.WebDevelopment],
  },
  [SkillKeysEnum.Jinja]: {
    name: "Jinja",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Python, SkillKeysEnum.WebDevelopment],
  },

  //^ Databases
  [SkillKeysEnum.Normalisation]: {
    name: "Normalisation",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.Databases,
    ],
  },
  [SkillKeysEnum.PostgreSQL]: {
    name: "PostgreSQL",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.Databases,
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.Normalisation,
      SkillKeysEnum.DatabaseIndexing,
    ],
  },
  [SkillKeysEnum.MySQL]: {
    name: "MySQL",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.Databases,
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.Normalisation,
      SkillKeysEnum.DatabaseIndexing,
    ],
  },
  [SkillKeysEnum.SQLite]: {
    name: "SQLite",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.Databases,
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.Normalisation,
      SkillKeysEnum.DatabaseIndexing,
    ],
  },
  [SkillKeysEnum.MongoDB]: {
    name: "MongoDB",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.Databases,
      SkillKeysEnum.NonRelationalDatabases,
      SkillKeysEnum.DatabaseIndexing,
    ],
  },
  [SkillKeysEnum.Redis]: {
    name: "Redis",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.Databases,
      SkillKeysEnum.NonRelationalDatabases,
      SkillKeysEnum.DatabaseIndexing,
    ],
  },
  [SkillKeysEnum.Convex]: {
    name: "Convex",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.Databases,
      SkillKeysEnum.NonRelationalDatabases,
      SkillKeysEnum.DatabaseIndexing,
    ],
  },

  //^ Object Relational Mapping
  [SkillKeysEnum.Mongoose]: {
    name: "Mongoose",
    category: SkillCategoriesEnum.ObjectRelationalMappers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.Databases,
      SkillKeysEnum.NonRelationalDatabases,
      SkillKeysEnum.DatabaseIndexing,
      SkillKeysEnum.ObjectRelationalMapping,
      SkillKeysEnum.MongoDB,
    ],
  },
  [SkillKeysEnum.Prisma]: {
    name: "Prisma",
    category: SkillCategoriesEnum.ObjectRelationalMappers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.Databases,
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.NonRelationalDatabases,
      SkillKeysEnum.DatabaseIndexing,
      SkillKeysEnum.ObjectOrientedProgramming,
      SkillKeysEnum.MongoDB,
      SkillKeysEnum.PostgreSQL,
      SkillKeysEnum.MySQL,
      SkillKeysEnum.SQLite,
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
    ],
  },
  [SkillKeysEnum.Drizzle]: {
    name: "Drizzle",
    category: SkillCategoriesEnum.ObjectRelationalMappers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.Databases,
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.DatabaseIndexing,
      SkillKeysEnum.TypeORM,
      SkillKeysEnum.PostgreSQL,
      SkillKeysEnum.MySQL,
      SkillKeysEnum.SQLite,
    ],
  },
  [SkillKeysEnum.TypeORM]: {
    name: "TypeORM",
    category: SkillCategoriesEnum.ObjectRelationalMappers,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.Databases,
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.DatabaseIndexing,
      SkillKeysEnum.ObjectRelationalMapping,
      SkillKeysEnum.PostgreSQL,
      SkillKeysEnum.MySQL,
      SkillKeysEnum.SQLite,
    ],
  },
  [SkillKeysEnum.SQLAlchemy]: {
    name: "SQLAlchemy",
    category: SkillCategoriesEnum.ObjectRelationalMappers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.Python,
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.Databases,
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.DatabaseIndexing,
      SkillKeysEnum.ObjectRelationalMapping,
      SkillKeysEnum.PostgreSQL,
      SkillKeysEnum.MySQL,
      SkillKeysEnum.SQLite,
    ],
  },
  [SkillKeysEnum.Hibernate]: {
    name: "Hibernate",
    category: SkillCategoriesEnum.ObjectRelationalMappers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.Java,
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.Databases,
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.DatabaseIndexing,
      SkillKeysEnum.ObjectRelationalMapping,
      SkillKeysEnum.PostgreSQL,
      SkillKeysEnum.MySQL,
      SkillKeysEnum.SQLite,
    ],
  },

  //^ DevOps
  [SkillKeysEnum.GitHubActions]: {
    name: "GitHub Actions",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.InfrastructureAsCode,
      SkillKeysEnum.ContinuousDelivery,
      SkillKeysEnum.ContinuousIntegration,
      SkillKeysEnum.ContinuousDeployment,
      SkillKeysEnum.DevOps,
      SkillKeysEnum.Automation,
      SkillKeysEnum.GitHub,
    ],
  },
  [SkillKeysEnum.GitLabCI]: {
    name: "GitLab CI",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.InfrastructureAsCode,
      SkillKeysEnum.ContinuousDelivery,
      SkillKeysEnum.ContinuousIntegration,
      SkillKeysEnum.ContinuousDeployment,
      SkillKeysEnum.DevOps,
      SkillKeysEnum.Automation,
      SkillKeysEnum.GitLab,
    ],
  },
  [SkillKeysEnum.Jenkins]: {
    name: "Jenkins",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.InfrastructureAsCode,
      SkillKeysEnum.ContinuousDelivery,
      SkillKeysEnum.ContinuousIntegration,
      SkillKeysEnum.ContinuousDeployment,
      SkillKeysEnum.DevOps,
      SkillKeysEnum.Automation,
      SkillKeysEnum.Groovy,
    ],
  },
  [SkillKeysEnum.TeamCity]: {
    name: "TeamCity",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.InfrastructureAsCode,
      SkillKeysEnum.ContinuousDelivery,
      SkillKeysEnum.ContinuousIntegration,
      SkillKeysEnum.ContinuousDeployment,
      SkillKeysEnum.DevOps,
      SkillKeysEnum.Automation,
    ],
  },
  [SkillKeysEnum.Docker]: {
    name: "Docker",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Containerisation, SkillKeysEnum.DevOps],
  },
  [SkillKeysEnum.Podman]: {
    name: "Podman",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Containerisation, SkillKeysEnum.DevOps],
  },
  [SkillKeysEnum.Kubernetes]: {
    name: "Kubernetes",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.Containerisation,
      SkillKeysEnum.DevOps,
      SkillKeysEnum.Clusterisation,
    ],
  },
  [SkillKeysEnum.Ansible]: {
    name: "Ansible",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.InfrastructureAsCode,
      SkillKeysEnum.DevOps,
      SkillKeysEnum.Automation,
    ],
  },
  [SkillKeysEnum.Terraform]: {
    name: "Terraform",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.InfrastructureAsCode,
      SkillKeysEnum.DevOps,
      SkillKeysEnum.Automation,
    ],
  },
  [SkillKeysEnum.Vagrant]: {
    name: "Vagrant",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.InfrastructureAsCode,
      SkillKeysEnum.DevOps,
      SkillKeysEnum.Automation,
    ],
  },

  //^ Artificial Intelligence, Machine Learning, and Data Science
  [SkillKeysEnum.ScikitLearn]: {
    name: "Scikit Learn",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.Python,
      SkillKeysEnum.MachineLearning,
      SkillKeysEnum.DataScience,
      SkillKeysEnum.ContinuousIntegration,
      SkillKeysEnum.Hyperparameters,
      SkillKeysEnum.Boosting,
      SkillKeysEnum.NeuralNetworks,
    ],
  },
  [SkillKeysEnum.Pandas]: {
    name: "Pandas",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.Python,
      SkillKeysEnum.DataScience,
      SkillKeysEnum.DataVisualisation,
    ],
  },
  [SkillKeysEnum.NumPy]: {
    name: "NumPy",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.Python,
      SkillKeysEnum.DataScience,
      SkillKeysEnum.Mathematics,
    ],
  },
  [SkillKeysEnum.Matplotlib]: {
    name: "Matplotlib",
    category: SkillCategoriesEnum.DataScience,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.Python,
      SkillKeysEnum.DataScience,
      SkillKeysEnum.DataVisualisation,
    ],
  },
  [SkillKeysEnum.Seaborn]: {
    name: "Seaborn",
    category: SkillCategoriesEnum.DataScience,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.Python,
      SkillKeysEnum.DataScience,
      SkillKeysEnum.DataVisualisation,
    ],
  },
  [SkillKeysEnum.Keras]: {
    name: "Keras",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.Python,
      SkillKeysEnum.MachineLearning,
      SkillKeysEnum.DataScience,
      SkillKeysEnum.ArtificialIntelligence,
      SkillKeysEnum.NeuralNetworks,
      SkillKeysEnum.DeepLearning,
    ],
  },
  [SkillKeysEnum.Jupyter]: {
    name: "Jupyter Notebooks",
    category: SkillCategoriesEnum.DataScience,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Python, SkillKeysEnum.DataScience],
  },

  //^ APIs and Web Services
  [SkillKeysEnum.REST]: {
    name: "REST",
    category: SkillCategoriesEnum.APIs,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.WebDevelopment, SkillKeysEnum.APIs],
  },
  [SkillKeysEnum.Apollo]: {
    name: "Apollo",
    category: SkillCategoriesEnum.APIs,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.WebDevelopment, SkillKeysEnum.APIs],
  },
  [SkillKeysEnum.GraphQL]: {
    name: "GraphQL",
    category: SkillCategoriesEnum.APIs,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.WebDevelopment,
      SkillKeysEnum.APIs,
      SkillKeysEnum.Apollo,
    ],
  },
  [SkillKeysEnum.TRPC]: {
    name: "tRPC",
    category: SkillCategoriesEnum.APIs,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.WebDevelopment, SkillKeysEnum.APIs],
  },
  [SkillKeysEnum.SocketIO]: {
    name: "Socket.IO",
    category: SkillCategoriesEnum.WebSockets,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.WebDevelopment, SkillKeysEnum.WebSockets],
  },
  [SkillKeysEnum.Pusher]: {
    name: "Pusher",
    category: SkillCategoriesEnum.WebSockets,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.WebDevelopment, SkillKeysEnum.WebSockets],
  },
  [SkillKeysEnum.OpenAI]: {
    name: "OpenAI",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.APIs, SkillKeysEnum.ArtificialIntelligence],
  },
  [SkillKeysEnum.ReplicateAI]: {
    name: "Replicate AI",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.APIs, SkillKeysEnum.ArtificialIntelligence],
  },

  //^ Testing
  [SkillKeysEnum.Jest]: {
    name: "Jest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.JavaScript, SkillKeysEnum.TypeScript],
  },
  [SkillKeysEnum.Vitest]: {
    name: "Vitest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.JavaScript, SkillKeysEnum.TypeScript],
  },
  [SkillKeysEnum.PyTest]: {
    name: "PyTest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Python],
  },
  [SkillKeysEnum.UnitTest]: {
    name: "UnitTest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Python],
  },
  [SkillKeysEnum.JUnit]: {
    name: "JUnit",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Java],
  },
  [SkillKeysEnum.Cypress]: {
    name: "Cypress",
    category: SkillCategoriesEnum.Testing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.JavaScript, SkillKeysEnum.TypeScript],
  },
  [SkillKeysEnum.ReactTestingLibrary]: {
    name: "React Testing Library",
    category: SkillCategoriesEnum.Testing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
      SkillKeysEnum.ReactJS,
    ],
  },

  //^ Code Quality
  [SkillKeysEnum.Black]: {
    name: "Black",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Python, SkillKeysEnum.Linting],
  },
  [SkillKeysEnum.Zod]: {
    name: "Zod",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.TypeScript],
  },
  [SkillKeysEnum.ESLint]: {
    name: "ESLint",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
      SkillKeysEnum.Linting,
    ],
  },
  [SkillKeysEnum.Prettier]: {
    name: "Prettier",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.JavaScript, SkillKeysEnum.TypeScript],
  },
  [SkillKeysEnum.PyLint]: {
    name: "PyLint",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Python, SkillKeysEnum.Linting],
  },
  [SkillKeysEnum.Checkstyle]: {
    name: "Checkstyle",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Java, SkillKeysEnum.Linting],
  },

  //^ Version Control Systems
  [SkillKeysEnum.Git]: {
    name: "Git",
    category: SkillCategoriesEnum.VersionControl,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.VersionControlSystems,
      SkillKeysEnum.GitHub,
      SkillKeysEnum.GitLab,
      SkillKeysEnum.BitBucket,
    ],
  },
  [SkillKeysEnum.GitHub]: {
    name: "GitHub",
    category: SkillCategoriesEnum.VersionControl,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.VersionControlSystems,
      SkillKeysEnum.GitHubActions,
    ],
  },
  [SkillKeysEnum.GitLab]: {
    name: "GitLab",
    category: SkillCategoriesEnum.VersionControl,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.VersionControlSystems,
      SkillKeysEnum.GitLabCI,
    ],
  },
  [SkillKeysEnum.BitBucket]: {
    name: "BitBucket",
    category: SkillCategoriesEnum.VersionControl,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.VersionControlSystems],
  },

  //^ Cloud Computing
  [SkillKeysEnum.AWS]: {
    name: "Amazon Web Services",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.CloudComputing,
      SkillKeysEnum.AWS_K3s,
      SkillKeysEnum.AWS_EC2,
      SkillKeysEnum.AWS_S3,
      SkillKeysEnum.AWS_VPC,
      SkillKeysEnum.AWS_Lambda,
      SkillKeysEnum.AWS_CloudFormation,
      SkillKeysEnum.AWS_CloudFront,
      SkillKeysEnum.AWS_ElasticBeanstalk,
    ],
  },
  [SkillKeysEnum.AWS_K3s]: {
    name: "K3s",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.Containerisation,
      SkillKeysEnum.Clusterisation,
      SkillKeysEnum.CloudComputing,
      SkillKeysEnum.AWS,
    ],
  },
  [SkillKeysEnum.AWS_CloudWatch]: {
    name: "CloudWatch",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.AWS],
  },
  [SkillKeysEnum.AWS_ApplicationLoadBalancer]: {
    name: "Application Load Balancer (ALB)",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Hard,
  },
  [SkillKeysEnum.AWS_ElasticCache]: {
    name: "Elastic Cache (EC)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.AWS],
  },

  [SkillKeysEnum.AWS_ElasticFileSystem]: {
    name: "Elastic File System (EFS)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.AWS],
  },
  [SkillKeysEnum.AWS_ElasticBlockStore]: {
    name: "Elastic Block Store (EBS)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.AWS],
  },
  [SkillKeysEnum.AWS_RelationalDatabaseService]: {
    name: "Relational Database Service (RDS)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.Databases,
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.DatabaseIndexing,
      SkillKeysEnum.CloudComputing,
      SkillKeysEnum.AWS,
    ],
  },
  [SkillKeysEnum.AWS_AutoScaling]: {
    name: "Auto Scaling",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.AWS],
  },
  [SkillKeysEnum.AWS_EC2]: {
    name: "Elastic Compute Cloud (EC2)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.AWS],
  },
  [SkillKeysEnum.AWS_S3]: {
    name: "Simple Storage Service (S3)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.AWS],
  },
  [SkillKeysEnum.AWS_VPC]: {
    name: "Virtual Private Cloud (VPC)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.AWS],
  },
  [SkillKeysEnum.AWS_Lambda]: {
    name: "Lambda",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.AWS],
  },
  [SkillKeysEnum.AWS_CloudFormation]: {
    name: "CloudFormation",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.AWS],
  },
  [SkillKeysEnum.AWS_CloudFront]: {
    name: "CloudFront",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.AWS],
  },
  [SkillKeysEnum.AWS_ElasticBeanstalk]: {
    name: "Elastic Beanstalk",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.AWS],
  },

  [SkillKeysEnum.Azure]: {
    name: "Microsoft Azure",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.CloudComputing,
      SkillKeysEnum.Azure_AppService,
      SkillKeysEnum.Azure_BlobStorage,
      SkillKeysEnum.Azure_DurableFunctions,
      SkillKeysEnum.Azure_Monitor,
      SkillKeysEnum.Azure_Functions,
      SkillKeysEnum.Azure_ResourceManager,
      SkillKeysEnum.Azure_ContainerRegistry,
    ],
  },
  [SkillKeysEnum.Azure_AppService]: {
    name: "Azure App Service",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.Azure],
  },
  [SkillKeysEnum.Azure_BlobStorage]: {
    name: "Azure Blob Storage",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.Azure],
  },
  [SkillKeysEnum.Azure_DurableFunctions]: {
    name: "Durable Functions",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.Azure],
  },
  [SkillKeysEnum.Azure_Monitor]: {
    name: "Azure Monitor",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.Azure],
  },
  [SkillKeysEnum.Azure_Functions]: {
    name: "Azure Functions",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.Azure],
  },
  [SkillKeysEnum.Azure_ResourceManager]: {
    name: "Azure Resource Manager",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.Azure],
  },
  [SkillKeysEnum.Azure_ContainerRegistry]: {
    name: "Azure Container Registry",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.CloudComputing,
      SkillKeysEnum.Azure,
      SkillKeysEnum.Containerisation,
      SkillKeysEnum.Clusterisation,
      SkillKeysEnum.Docker,
      SkillKeysEnum.Podman,
      SkillKeysEnum.Kubernetes,
    ],
  },

  [SkillKeysEnum.GCP]: {
    name: "Google Cloud Platform",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.CloudComputing,
      SkillKeysEnum.GCP_AppEngine,
      SkillKeysEnum.GCP_CloudSQL,
      SkillKeysEnum.GCP_CloudStorage,
      SkillKeysEnum.GCP_CloudTasks,
      SkillKeysEnum.GCP_CloudScheduler,
      SkillKeysEnum.GCP_Logging,
      SkillKeysEnum.Firebase,
    ],
  },
  [SkillKeysEnum.GCP_AppEngine]: {
    name: "App Engine",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.GCP],
  },
  [SkillKeysEnum.GCP_CloudSQL]: {
    name: "Cloud SQL",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.CloudComputing,
      SkillKeysEnum.GCP,
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.DatabaseIndexing,
    ],
  },
  [SkillKeysEnum.GCP_CloudStorage]: {
    name: "Cloud Storage",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.GCP],
  },
  [SkillKeysEnum.GCP_CloudTasks]: {
    name: "Cloud Tasks",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.GCP],
  },
  [SkillKeysEnum.GCP_CloudScheduler]: {
    name: "Cloud Scheduler",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.GCP],
  },
  [SkillKeysEnum.GCP_Logging]: {
    name: "Cloud Logging",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.CloudComputing, SkillKeysEnum.GCP],
  },

  //^ Mathematics
  [SkillKeysEnum.Probability]: {
    name: "Probability",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.Mathematics,
      SkillKeysEnum.MachineLearning,
      SkillKeysEnum.DeepLearning,
      SkillKeysEnum.ArtificialIntelligence,
    ],
  },
  [SkillKeysEnum.Statistics]: {
    name: "Statistics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.Mathematics,
      SkillKeysEnum.MachineLearning,
      SkillKeysEnum.DeepLearning,
      SkillKeysEnum.ArtificialIntelligence,
    ],
  },
  [SkillKeysEnum.Calculus]: {
    name: "Calculus",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.Mathematics,
      SkillKeysEnum.MachineLearning,
      SkillKeysEnum.DeepLearning,
      SkillKeysEnum.ArtificialIntelligence,
    ],
  },
  [SkillKeysEnum.Trigonometry]: {
    name: "Trigonometry",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Mathematics],
  },
  [SkillKeysEnum.Algebra]: {
    name: "Algebra",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.Mathematics,
      SkillKeysEnum.MachineLearning,
      SkillKeysEnum.DeepLearning,
      SkillKeysEnum.ArtificialIntelligence,
    ],
  },
  [SkillKeysEnum.LinearAlgebra]: {
    name: "Linear Algebra",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.Mathematics,
      SkillKeysEnum.MachineLearning,
      SkillKeysEnum.DeepLearning,
      SkillKeysEnum.ArtificialIntelligence,
    ],
  },
  [SkillKeysEnum.Discrete]: {
    name: "Discrete",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Mathematics],
  },
  [SkillKeysEnum.Geometry]: {
    name: "Geometry",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Mathematics],
  },
  [SkillKeysEnum.Logics]: {
    name: "Logics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Mathematics],
  },
  [SkillKeysEnum.Mechanics]: {
    name: "Mechanics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Mathematics],
  },

  //^ Project Management
  [SkillKeysEnum.NPM]: {
    name: "NPM",
    category: SkillCategoriesEnum.ProjectManagers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Java, SkillKeysEnum.TypeScript],
  },
  [SkillKeysEnum.Yarn]: {
    name: "Yarn",
    category: SkillCategoriesEnum.ProjectManagers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Java, SkillKeysEnum.TypeScript],
  },
  [SkillKeysEnum.PNPM]: {
    name: "PNPM",
    category: SkillCategoriesEnum.ProjectManagers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Java, SkillKeysEnum.TypeScript],
  },
  [SkillKeysEnum.Pip]: {
    name: "Pip",
    category: SkillCategoriesEnum.ProjectManagers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Python],
  },
  [SkillKeysEnum.Poetry]: {
    name: "Poetry",
    category: SkillCategoriesEnum.ProjectManagers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Python],
  },
  [SkillKeysEnum.PyBuilder]: {
    name: "PyBuilder",
    category: SkillCategoriesEnum.ProjectManagers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Python],
  },
  [SkillKeysEnum.Maven]: {
    name: "Maven",
    category: SkillCategoriesEnum.ProjectManagers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Java],
  },
  [SkillKeysEnum.Gradle]: {
    name: "Gradle",
    category: SkillCategoriesEnum.ProjectManagers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Java],
  },
  [SkillKeysEnum.Tox]: {
    name: "Tox",
    category: SkillCategoriesEnum.ProjectManagers,
    skillType: SkillTypesEnum.Hard,
  },
  [SkillKeysEnum.NxJS]: {
    name: "Nx.js",
    category: SkillCategoriesEnum.ProjectManagers,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.Java, SkillKeysEnum.TypeScript],
  },

  //^ Game Development
  [SkillKeysEnum.GameMakerStudio]: {
    name: "GameMaker Studio 2",
    category: SkillCategoriesEnum.GameDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillKeysEnum.GameDevelopment],
  },

  //^ Communication
  [SkillKeysEnum.Symphony]: {
    name: "Symphony Solutions",
    category: SkillCategoriesEnum.Automation,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.Java,
      SkillKeysEnum.Python,
      SkillKeysEnum.Automation,
      SkillKeysEnum.SDKs,
    ],
  },

  //^ Security
  [SkillKeysEnum.Cryptography]: {
    name: "Cryptography",
    category: SkillCategoriesEnum.Security,
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillKeysEnum.Security,
      SkillKeysEnum.CyberSecurity,
      SkillKeysEnum.Cryptography,
    ],
  },
  [SkillKeysEnum.CyberSecurity]: {
    name: "Cyber-Security",
    category: SkillCategoriesEnum.Security,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Security,
      SkillKeysEnum.CyberSecurity,
      SkillKeysEnum.Cryptography,
    ],
  },
  [SkillKeysEnum.Security]: {
    name: "Security",
    category: SkillCategoriesEnum.Security,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Security,
      SkillKeysEnum.CyberSecurity,
      SkillKeysEnum.Cryptography,
    ],
  },

  //^ Others
  [SkillKeysEnum.Networking]: {
    name: "Networking",
    category: SkillCategoriesEnum.Security,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
  },

  //^ General Technical Skills
  [SkillKeysEnum.ContinuousIntegration]: {
    name: "Continuous Integration",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.GitHubActions,
      SkillKeysEnum.GitLabCI,
      SkillKeysEnum.Jenkins,
      SkillKeysEnum.TeamCity,
    ],
  },

  [SkillKeysEnum.ContinuousDelivery]: {
    name: "Continuous Delivery",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.GitHubActions,
      SkillKeysEnum.GitLabCI,
      SkillKeysEnum.Jenkins,
      SkillKeysEnum.TeamCity,
    ],
  },

  [SkillKeysEnum.ContinuousDeployment]: {
    name: "Continuous Deployment",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.GitHubActions,
      SkillKeysEnum.GitLabCI,
      SkillKeysEnum.Jenkins,
      SkillKeysEnum.TeamCity,
    ],
  },

  [SkillKeysEnum.DevOps]: {
    name: "DevOps",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.GitHubActions,
      SkillKeysEnum.GitLabCI,
      SkillKeysEnum.Jenkins,
      SkillKeysEnum.TeamCity,
      SkillKeysEnum.Docker,
      SkillKeysEnum.Podman,
      SkillKeysEnum.Kubernetes,
      SkillKeysEnum.Ansible,
      SkillKeysEnum.Vagrant,
      SkillKeysEnum.Terraform,
      SkillKeysEnum.ContinuousIntegration,
      SkillKeysEnum.ContinuousDeployment,
      SkillKeysEnum.ContinuousDelivery,
      SkillKeysEnum.Containerisation,
      SkillKeysEnum.Clusterisation,
      SkillKeysEnum.InfrastructureAsCode,
      SkillKeysEnum.Automation,
    ],
  },

  [SkillKeysEnum.Linting]: {
    name: "Linting",
    category: SkillCategoriesEnum.CodeQuality,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Black,
      SkillKeysEnum.PyLint,
      SkillKeysEnum.Zod,
      SkillKeysEnum.Prettier,
      SkillKeysEnum.Checkstyle,
      SkillKeysEnum.ESLint,
    ],
  },
  [SkillKeysEnum.ObjectOrientedProgramming]: {
    name: "Object Oriented Programming",
    category: SkillCategoriesEnum.ProgrammingParadigms,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Python,
      SkillKeysEnum.Java,
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
    ],
  },
  [SkillKeysEnum.FunctionalProgramming]: {
    name: "Functional Programming",
    category: SkillCategoriesEnum.ProgrammingParadigms,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Python,
      SkillKeysEnum.Java,
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
    ],
  },
  [SkillKeysEnum.Algorithms]: {
    name: "Algorithms",
    category: SkillCategoriesEnum.CoreComputerScience,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Python,
      SkillKeysEnum.Java,
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
    ],
  },
  [SkillKeysEnum.DataStructures]: {
    name: "Data Structures",
    category: SkillCategoriesEnum.CoreComputerScience,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Python,
      SkillKeysEnum.Java,
      SkillKeysEnum.JavaScript,
      SkillKeysEnum.TypeScript,
    ],
  },
  [SkillKeysEnum.AndroidDevelopment]: {
    name: "Android Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [SkillKeysEnum.Java],
  },
  [SkillKeysEnum.iOSDevelopment]: {
    name: "iOS Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
  },
  [SkillKeysEnum.WindowsDevelopment]: {
    name: "Windows Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
  },
  [SkillKeysEnum.MacDevelopment]: {
    name: "Mac Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
  },
  [SkillKeysEnum.LinuxDevelopment]: {
    name: "Linux Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
  },
  [SkillKeysEnum.MachineLearning]: {
    name: "Machine Learning",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.DeepLearning,
      SkillKeysEnum.ArtificialIntelligence,
      SkillKeysEnum.DataScience,
      SkillKeysEnum.Hyperparameters,
      SkillKeysEnum.Boosting,
      SkillKeysEnum.DataVisualisation,
      SkillKeysEnum.NeuralNetworks,
      SkillKeysEnum.Keras,
      SkillKeysEnum.Pandas,
      SkillKeysEnum.NumPy,
      SkillKeysEnum.Matplotlib,
      SkillKeysEnum.Seaborn,
      SkillKeysEnum.ScikitLearn,
      SkillKeysEnum.Jupyter,
    ],
  },
  [SkillKeysEnum.DeepLearning]: {
    name: "Deep Learning",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.ArtificialIntelligence,
      SkillKeysEnum.DataScience,
      SkillKeysEnum.Hyperparameters,
      SkillKeysEnum.Boosting,
      SkillKeysEnum.DataVisualisation,
      SkillKeysEnum.NeuralNetworks,
      SkillKeysEnum.Keras,
      SkillKeysEnum.Pandas,
      SkillKeysEnum.NumPy,
      SkillKeysEnum.Matplotlib,
      SkillKeysEnum.Seaborn,
      SkillKeysEnum.ScikitLearn,
      SkillKeysEnum.Jupyter,
    ],
  },
  [SkillKeysEnum.ArtificialIntelligence]: {
    name: "Artificial Intelligence",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.DeepLearning,
      SkillKeysEnum.ArtificialIntelligence,
      SkillKeysEnum.DataScience,
      SkillKeysEnum.Hyperparameters,
      SkillKeysEnum.Boosting,
      SkillKeysEnum.DataVisualisation,
      SkillKeysEnum.NeuralNetworks,
      SkillKeysEnum.Keras,
      SkillKeysEnum.Pandas,
      SkillKeysEnum.NumPy,
      SkillKeysEnum.Matplotlib,
      SkillKeysEnum.Seaborn,
      SkillKeysEnum.ScikitLearn,
      SkillKeysEnum.Jupyter,
      SkillKeysEnum.OpenAI,
      SkillKeysEnum.ReplicateAI,
    ],
  },
  [SkillKeysEnum.DataScience]: {
    name: "Data Science",
    category: SkillCategoriesEnum.DataScience,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.DataVisualisation,
      SkillKeysEnum.Pandas,
      SkillKeysEnum.NumPy,
      SkillKeysEnum.Matplotlib,
      SkillKeysEnum.Seaborn,
      SkillKeysEnum.Jupyter,
    ],
  },
  [SkillKeysEnum.Hyperparameters]: {
    name: "Hyperparameters",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.DeepLearning,
      SkillKeysEnum.ArtificialIntelligence,
      SkillKeysEnum.DataScience,
      SkillKeysEnum.DataVisualisation,
      SkillKeysEnum.NeuralNetworks,
      SkillKeysEnum.Keras,
      SkillKeysEnum.Pandas,
      SkillKeysEnum.NumPy,
      SkillKeysEnum.Matplotlib,
      SkillKeysEnum.Seaborn,
      SkillKeysEnum.ScikitLearn,
    ],
  },
  [SkillKeysEnum.Boosting]: {
    name: "Boosting",
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    category: SkillCategoriesEnum.ArtificialIntelligence,
    relatedSkills: [
      SkillKeysEnum.DeepLearning,
      SkillKeysEnum.ArtificialIntelligence,
      SkillKeysEnum.DataScience,
      SkillKeysEnum.DataVisualisation,
      SkillKeysEnum.NeuralNetworks,
      SkillKeysEnum.Keras,
      SkillKeysEnum.Pandas,
      SkillKeysEnum.NumPy,
      SkillKeysEnum.Matplotlib,
      SkillKeysEnum.Seaborn,
      SkillKeysEnum.ScikitLearn,
    ],
  },
  [SkillKeysEnum.DataVisualisation]: {
    name: "Data Visualisation",
    category: SkillCategoriesEnum.DataScience,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.DeepLearning,
      SkillKeysEnum.ArtificialIntelligence,
      SkillKeysEnum.DataScience,
      SkillKeysEnum.DataVisualisation,
      SkillKeysEnum.NeuralNetworks,
      SkillKeysEnum.Pandas,
      SkillKeysEnum.NumPy,
      SkillKeysEnum.Matplotlib,
      SkillKeysEnum.Seaborn,
    ],
  },
  [SkillKeysEnum.NeuralNetworks]: {
    name: "Neural Networks",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.DeepLearning,
      SkillKeysEnum.ArtificialIntelligence,
      SkillKeysEnum.DataScience,
      SkillKeysEnum.DataVisualisation,
      SkillKeysEnum.NeuralNetworks,
      SkillKeysEnum.Keras,
      SkillKeysEnum.Pandas,
      SkillKeysEnum.NumPy,
      SkillKeysEnum.Matplotlib,
      SkillKeysEnum.Seaborn,
      SkillKeysEnum.ScikitLearn,
    ],
  },
  [SkillKeysEnum.APIs]: {
    name: "APIs",
    category: SkillCategoriesEnum.APIs,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.REST,
      SkillKeysEnum.GraphQL,
      SkillKeysEnum.TRPC,
      SkillKeysEnum.ReplicateAI,
      SkillKeysEnum.OpenAI,
    ],
  },
  [SkillKeysEnum.Databases]: {
    name: "Databases",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.NonRelationalDatabases,
      SkillKeysEnum.ObjectRelationalMapping,
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.DatabaseIndexing,
      SkillKeysEnum.Normalisation,
      SkillKeysEnum.PostgreSQL,
      SkillKeysEnum.MySQL,
      SkillKeysEnum.SQLite,
      SkillKeysEnum.MongoDB,
      SkillKeysEnum.Redis,
      SkillKeysEnum.Convex,
    ],
  },
  [SkillKeysEnum.WebSockets]: {
    name: "Web Sockets",
    category: SkillCategoriesEnum.WebSockets,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [SkillKeysEnum.SocketIO, SkillKeysEnum.Pusher],
  },
  [SkillKeysEnum.RelationalDatabases]: {
    name: "Relational Databases (SQL)",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.ObjectRelationalMapping,
      SkillKeysEnum.DatabaseIndexing,
      SkillKeysEnum.Normalisation,
      SkillKeysEnum.PostgreSQL,
      SkillKeysEnum.MySQL,
      SkillKeysEnum.SQLite,
    ],
  },

  [SkillKeysEnum.NonRelationalDatabases]: {
    name: "Non Relational Databases (NoSQL)",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.DatabaseIndexing,
      SkillKeysEnum.MongoDB,
      SkillKeysEnum.Redis,
      SkillKeysEnum.Convex,
    ],
  },
  [SkillKeysEnum.ObjectRelationalMapping]: {
    name: "Object Relational Mapping",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Mongoose,
      SkillKeysEnum.Prisma,
      SkillKeysEnum.Drizzle,
      SkillKeysEnum.SQLAlchemy,
      SkillKeysEnum.TypeORM,
      SkillKeysEnum.Hibernate,
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.DatabaseIndexing,
    ],
  },
  [SkillKeysEnum.Testing]: {
    name: "Testing",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Jest,
      SkillKeysEnum.Vitest,
      SkillKeysEnum.PyTest,
      SkillKeysEnum.UnitTest,
      SkillKeysEnum.JUnit,
      SkillKeysEnum.Cypress,
      SkillKeysEnum.ReactTestingLibrary,
    ],
  },
  [SkillKeysEnum.Containerisation]: {
    name: "Containerization",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Docker,
      SkillKeysEnum.Podman,
      SkillKeysEnum.Kubernetes,
      SkillKeysEnum.Clusterisation,
      SkillKeysEnum.Azure_ContainerRegistry,
    ],
  },
  [SkillKeysEnum.Clusterisation]: {
    name: "Clusterisation",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Kubernetes,
      SkillKeysEnum.Azure_ContainerRegistry,
    ],
  },
  [SkillKeysEnum.InfrastructureAsCode]: {
    name: "Infrastructure as Code",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Ansible,
      SkillKeysEnum.Vagrant,
      SkillKeysEnum.Terraform,
    ],
  },
  [SkillKeysEnum.Automation]: {
    name: "Automation",
    category: SkillCategoriesEnum.Automation,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Ansible,
      SkillKeysEnum.Vagrant,
      SkillKeysEnum.Terraform,
    ],
  },
  [SkillKeysEnum.DatabaseManagementSystems]: {
    name: "Database Management Systems",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.DatabaseIndexing,
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.NonRelationalDatabases,
      SkillKeysEnum.ObjectRelationalMapping,
      SkillKeysEnum.Normalisation,
      SkillKeysEnum.Databases,
    ],
  },
  [SkillKeysEnum.DatabaseIndexing]: {
    name: "Indexing",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.RelationalDatabases,
      SkillKeysEnum.NonRelationalDatabases,
      SkillKeysEnum.ObjectRelationalMapping,
      SkillKeysEnum.Normalisation,
      SkillKeysEnum.Databases,
      SkillKeysEnum.DatabaseManagementSystems,
      SkillKeysEnum.PostgreSQL,
      SkillKeysEnum.MySQL,
      SkillKeysEnum.SQLite,
      SkillKeysEnum.MongoDB,
      SkillKeysEnum.Redis,
      SkillKeysEnum.Convex,
    ],
  },
  [SkillKeysEnum.CloudComputing]: {
    name: "Cloud Computing",
    category: SkillCategoriesEnum.CloudComputing,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.AWS,
      SkillKeysEnum.Azure,
      SkillKeysEnum.GCP,
      SkillKeysEnum.CloudComputing,
      SkillKeysEnum.AWS_K3s,
      SkillKeysEnum.AWS_EC2,
      SkillKeysEnum.AWS_S3,
      SkillKeysEnum.AWS_VPC,
      SkillKeysEnum.AWS_Lambda,
      SkillKeysEnum.AWS_CloudFormation,
      SkillKeysEnum.AWS_CloudFront,
      SkillKeysEnum.AWS_ElasticBeanstalk,
      SkillKeysEnum.CloudComputing,
      SkillKeysEnum.Azure_AppService,
      SkillKeysEnum.Azure_BlobStorage,
      SkillKeysEnum.Azure_DurableFunctions,
      SkillKeysEnum.Azure_Monitor,
      SkillKeysEnum.Azure_Functions,
      SkillKeysEnum.Azure_ResourceManager,
      SkillKeysEnum.Azure_ContainerRegistry,
      SkillKeysEnum.CloudComputing,
      SkillKeysEnum.GCP_AppEngine,
      SkillKeysEnum.GCP_CloudSQL,
      SkillKeysEnum.GCP_CloudStorage,
      SkillKeysEnum.GCP_CloudTasks,
      SkillKeysEnum.GCP_CloudScheduler,
      SkillKeysEnum.GCP_Logging,
      SkillKeysEnum.Firebase,
    ],
  },

  [SkillKeysEnum.DesignPatterns]: {
    name: "Design Patterns",
    category: SkillCategoriesEnum.CodeQuality,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Python,
      SkillKeysEnum.Java,
      SkillKeysEnum.TypeScript,
      SkillKeysEnum.JavaScript,
    ],
  },
  [SkillKeysEnum.UserAuthentication]: {
    name: "User Authentication",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Firebase,
      SkillKeysEnum.PocketBase,
      SkillKeysEnum.Supabase,
      SkillKeysEnum.Auth0,
      SkillKeysEnum.ClerkAuth,
      SkillKeysEnum.NextAuth,
    ],
  },
  [SkillKeysEnum.WebDevelopment]: {
    name: "Web Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.REST,
      SkillKeysEnum.GraphQL,
      SkillKeysEnum.TRPC,
      SkillKeysEnum.WebSockets,
      SkillKeysEnum.SocketIO,
      SkillKeysEnum.Pusher,
      SkillKeysEnum.Firebase,
      SkillKeysEnum.PocketBase,
      SkillKeysEnum.Supabase,
      SkillKeysEnum.Auth0,
      SkillKeysEnum.ClerkAuth,
      SkillKeysEnum.NextAuth,
      SkillKeysEnum.Stripe,
      SkillKeysEnum.ExpressJS,
      SkillKeysEnum.Flask,
      SkillKeysEnum.Django,
      SkillKeysEnum.Spring,
      SkillKeysEnum.SpringBoot,
      SkillKeysEnum.Cloudinary,
      SkillKeysEnum.EdgeStore,
      SkillKeysEnum.Gunicorn,
      SkillKeysEnum.Jinja,
      SkillKeysEnum.UserAuthentication,
      SkillKeysEnum.NextJS,
      SkillKeysEnum.SvelteKit,
      SkillKeysEnum.AngularJS,
      SkillKeysEnum.NuxtJS,
      SkillKeysEnum.ReactJS,
      SkillKeysEnum.SvelteJS,
      SkillKeysEnum.VueJS,
      SkillKeysEnum.Recoil,
      SkillKeysEnum.Zustand,
      SkillKeysEnum.Jotai,
      SkillKeysEnum.Redux,
      SkillKeysEnum.TailwindCSS,
      SkillKeysEnum.HTML,
      SkillKeysEnum.CSS,
      SkillKeysEnum.ChakraUI,
      SkillKeysEnum.HeadlessUI,
      SkillKeysEnum.ShadcnUI,
      SkillKeysEnum.RadixUI,
      SkillKeysEnum.ReactQuery,
      SkillKeysEnum.NextUI,
      SkillKeysEnum.StateManagement,
      SkillKeysEnum.Bootstrap,
      SkillKeysEnum.MaterialUI,
      SkillKeysEnum.SemanticUI,
      SkillKeysEnum.AntDesign,
      SkillKeysEnum.StoryBooks,
      SkillKeysEnum.Axios,
      SkillKeysEnum.UserCentricDesign,
      SkillKeysEnum.StateManagement,
    ],
  },
  [SkillKeysEnum.SDKs]: {
    name: "SDK",
    category: SkillCategoriesEnum.SDKs,
    isMainSkill: true,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Firebase,
      SkillKeysEnum.Supabase,
      SkillKeysEnum.PocketBase,
      SkillKeysEnum.Auth0,
      SkillKeysEnum.ClerkAuth,
      SkillKeysEnum.NextAuth,
      SkillKeysEnum.Stripe,
      SkillKeysEnum.Cloudinary,
      SkillKeysEnum.EdgeStore,
      SkillKeysEnum.Symphony,
    ],
  },
  [SkillKeysEnum.UserCentricDesign]: {
    name: "User Centric Design",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.REST,
      SkillKeysEnum.GraphQL,
      SkillKeysEnum.TRPC,
      SkillKeysEnum.WebSockets,
      SkillKeysEnum.SocketIO,
      SkillKeysEnum.Pusher,
      SkillKeysEnum.Firebase,
      SkillKeysEnum.PocketBase,
      SkillKeysEnum.Supabase,
      SkillKeysEnum.Auth0,
      SkillKeysEnum.ClerkAuth,
      SkillKeysEnum.NextAuth,
      SkillKeysEnum.Stripe,
      SkillKeysEnum.ExpressJS,
      SkillKeysEnum.Flask,
      SkillKeysEnum.Django,
      SkillKeysEnum.Spring,
      SkillKeysEnum.SpringBoot,
      SkillKeysEnum.Cloudinary,
      SkillKeysEnum.EdgeStore,
      SkillKeysEnum.Gunicorn,
      SkillKeysEnum.Jinja,
      SkillKeysEnum.UserAuthentication,
      SkillKeysEnum.NextJS,
      SkillKeysEnum.SvelteKit,
      SkillKeysEnum.AngularJS,
      SkillKeysEnum.NuxtJS,
      SkillKeysEnum.ReactJS,
      SkillKeysEnum.SvelteJS,
      SkillKeysEnum.VueJS,
      SkillKeysEnum.Recoil,
      SkillKeysEnum.Zustand,
      SkillKeysEnum.Jotai,
      SkillKeysEnum.Redux,
      SkillKeysEnum.TailwindCSS,
      SkillKeysEnum.HTML,
      SkillKeysEnum.CSS,
      SkillKeysEnum.ChakraUI,
      SkillKeysEnum.HeadlessUI,
      SkillKeysEnum.ShadcnUI,
      SkillKeysEnum.RadixUI,
      SkillKeysEnum.ReactQuery,
      SkillKeysEnum.NextUI,
      SkillKeysEnum.StateManagement,
      SkillKeysEnum.Bootstrap,
      SkillKeysEnum.MaterialUI,
      SkillKeysEnum.SemanticUI,
      SkillKeysEnum.AntDesign,
      SkillKeysEnum.StoryBooks,
      SkillKeysEnum.Axios,
      SkillKeysEnum.StateManagement,
    ],
  },
  [SkillKeysEnum.GameDevelopment]: {
    name: "Game Development",
    category: SkillCategoriesEnum.GameDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.GameMakerLanguage,
      SkillKeysEnum.GameMakerLanguage,
    ],
  },
  [SkillKeysEnum.Mathematics]: {
    name: "Mathematics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Probability,
      SkillKeysEnum.Statistics,
      SkillKeysEnum.Calculus,
      SkillKeysEnum.Trigonometry,
      SkillKeysEnum.Algebra,
      SkillKeysEnum.LinearAlgebra,
      SkillKeysEnum.Discrete,
      SkillKeysEnum.Geometry,
      SkillKeysEnum.Mechanics,
      SkillKeysEnum.Logics,
    ],
  },
  [SkillKeysEnum.VersionControlSystems]: {
    name: "Version Control",
    category: SkillCategoriesEnum.VersionControl,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Git,
      SkillKeysEnum.GitHub,
      SkillKeysEnum.GitLab,
      SkillKeysEnum.BitBucket,
    ],
  },
  [SkillKeysEnum.StateManagement]: {
    name: "State Management",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillKeysEnum.Recoil,
      SkillKeysEnum.Zustand,
      SkillKeysEnum.Jotai,
      SkillKeysEnum.Redux,
    ],
  },

  //^ Soft Skills
  [SkillKeysEnum.Communication]: {
    name: "Communication",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillKeysEnum.ProjectManagement]: {
    name: "Project Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillKeysEnum.Teamwork]: {
    name: "Teamwork",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillKeysEnum.Leadership]: {
    name: "Leadership",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillKeysEnum.ProblemSolving]: {
    name: "Problem Solving",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillKeysEnum.CriticalThinking]: {
    name: "Critical Thinking",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillKeysEnum.Creativity]: {
    name: "Creativity",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillKeysEnum.Adaptability]: {
    name: "Adaptability",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillKeysEnum.TimeManagement]: {
    name: "Time Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillKeysEnum.RiskManagement]: {
    name: "Risk Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillKeysEnum.StakeholderManagement]: {
    name: "Stakeholder Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillKeysEnum.ScopeManagement]: {
    name: "Scope Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillKeysEnum.CostManagement]: {
    name: "Cost Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillKeysEnum.QualityManagement]: {
    name: "Quality Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillKeysEnum.ProcurementManagement]: {
    name: "Procurement Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillKeysEnum.IntegrationManagement]: {
    name: "Integration Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillKeysEnum.HumanResourceManagement]: {
    name: "Human Resource Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
};

export default skillDatabase;

/**
 * List of keys for the skills that can be used to uniquely identify the skills.
 */
export const skillKeys: SkillKeysEnum[] = Object.keys(
  skillDatabase
) as SkillKeysEnum[];
