import SkillCategoriesEnum from "@/enums/SkillCategoriesEnum";
import SkillSlugEnum from "@/enums/SkillSlugEnum";
import SkillTypesEnum from "@/enums/SkillTypesEnum";
import SkillInterface from "@/interfaces/skills/SkillInterface";

const generalSkills: { [key: string]: SkillInterface } = {
  [SkillSlugEnum.ContinuousIntegration]: {
    name: "Continuous Integration",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.GitHubActions,
      SkillSlugEnum.GitLabCI,
      SkillSlugEnum.Jenkins,
      SkillSlugEnum.TeamCity,
    ],
  },

  [SkillSlugEnum.ContinuousDelivery]: {
    name: "Continuous Delivery",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.GitHubActions,
      SkillSlugEnum.GitLabCI,
      SkillSlugEnum.Jenkins,
      SkillSlugEnum.TeamCity,
    ],
  },

  [SkillSlugEnum.ContinuousDeployment]: {
    name: "Continuous Deployment",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.GitHubActions,
      SkillSlugEnum.GitLabCI,
      SkillSlugEnum.Jenkins,
      SkillSlugEnum.TeamCity,
    ],
  },

  [SkillSlugEnum.DevOps]: {
    name: "DevOps",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.GitHubActions,
      SkillSlugEnum.GitLabCI,
      SkillSlugEnum.Jenkins,
      SkillSlugEnum.TeamCity,
      SkillSlugEnum.Docker,
      SkillSlugEnum.Podman,
      SkillSlugEnum.Kubernetes,
      SkillSlugEnum.Ansible,
      SkillSlugEnum.Vagrant,
      SkillSlugEnum.Terraform,
      SkillSlugEnum.ContinuousIntegration,
      SkillSlugEnum.ContinuousDeployment,
      SkillSlugEnum.ContinuousDelivery,
      SkillSlugEnum.Containerisation,
      SkillSlugEnum.Clusterisation,
      SkillSlugEnum.InfrastructureAsCode,
      SkillSlugEnum.Automation,
    ],
  },

  [SkillSlugEnum.Linting]: {
    name: "Linting",
    category: SkillCategoriesEnum.CodeQuality,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Black,
      SkillSlugEnum.PyLint,
      SkillSlugEnum.Zod,
      SkillSlugEnum.Prettier,
      SkillSlugEnum.Checkstyle,
      SkillSlugEnum.ESLint,
    ],
  },
  [SkillSlugEnum.ObjectOrientedProgramming]: {
    name: "Object Oriented Programming",
    category: SkillCategoriesEnum.ProgrammingParadigms,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Python,
      SkillSlugEnum.Java,
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
    ],
  },
  [SkillSlugEnum.FunctionalProgramming]: {
    name: "Functional Programming",
    category: SkillCategoriesEnum.ProgrammingParadigms,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Python,
      SkillSlugEnum.Java,
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
    ],
  },
  [SkillSlugEnum.Algorithms]: {
    name: "Algorithms",
    category: SkillCategoriesEnum.CoreComputerScience,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Python,
      SkillSlugEnum.Java,
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
    ],
  },
  [SkillSlugEnum.DataStructures]: {
    name: "Data Structures",
    category: SkillCategoriesEnum.CoreComputerScience,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Python,
      SkillSlugEnum.Java,
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
    ],
  },
  [SkillSlugEnum.AndroidDevelopment]: {
    name: "Android Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [SkillSlugEnum.Java],
  },
  [SkillSlugEnum.iOSDevelopment]: {
    name: "iOS Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
  },
  [SkillSlugEnum.WindowsDevelopment]: {
    name: "Windows Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
  },
  [SkillSlugEnum.MacDevelopment]: {
    name: "Mac Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
  },
  [SkillSlugEnum.LinuxDevelopment]: {
    name: "Linux Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
  },
  [SkillSlugEnum.MachineLearning]: {
    name: "Machine Learning",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.Hyperparameters,
      SkillSlugEnum.Boosting,
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.NeuralNetworks,
      SkillSlugEnum.Keras,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
      SkillSlugEnum.ScikitLearn,
      SkillSlugEnum.Jupyter,
    ],
  },
  [SkillSlugEnum.DeepLearning]: {
    name: "Deep Learning",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.ArtificialIntelligence,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.Hyperparameters,
      SkillSlugEnum.Boosting,
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.NeuralNetworks,
      SkillSlugEnum.Keras,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
      SkillSlugEnum.ScikitLearn,
      SkillSlugEnum.Jupyter,
    ],
  },
  [SkillSlugEnum.ArtificialIntelligence]: {
    name: "Artificial Intelligence",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.Hyperparameters,
      SkillSlugEnum.Boosting,
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.NeuralNetworks,
      SkillSlugEnum.Keras,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
      SkillSlugEnum.ScikitLearn,
      SkillSlugEnum.Jupyter,
      SkillSlugEnum.OpenAI,
      SkillSlugEnum.ReplicateAI,
    ],
  },
  [SkillSlugEnum.DataScience]: {
    name: "Data Science",
    category: SkillCategoriesEnum.DataScience,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
      SkillSlugEnum.Jupyter,
    ],
  },
  [SkillSlugEnum.Hyperparameters]: {
    name: "Hyperparameters",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.NeuralNetworks,
      SkillSlugEnum.Keras,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
      SkillSlugEnum.ScikitLearn,
    ],
  },
  [SkillSlugEnum.Boosting]: {
    name: "Boosting",
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    category: SkillCategoriesEnum.ArtificialIntelligence,
    relatedSkills: [
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.NeuralNetworks,
      SkillSlugEnum.Keras,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
      SkillSlugEnum.ScikitLearn,
    ],
  },
  [SkillSlugEnum.DataVisualisation]: {
    name: "Data Visualisation",
    category: SkillCategoriesEnum.DataScience,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.NeuralNetworks,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
    ],
  },
  [SkillSlugEnum.NeuralNetworks]: {
    name: "Neural Networks",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.NeuralNetworks,
      SkillSlugEnum.Keras,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
      SkillSlugEnum.ScikitLearn,
    ],
  },
  [SkillSlugEnum.APIs]: {
    name: "APIs",
    category: SkillCategoriesEnum.APIs,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.REST,
      SkillSlugEnum.GraphQL,
      SkillSlugEnum.TRPC,
      SkillSlugEnum.ReplicateAI,
      SkillSlugEnum.OpenAI,
    ],
  },
  [SkillSlugEnum.Databases]: {
    name: "Databases",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.NonRelationalDatabases,
      SkillSlugEnum.ObjectRelationalMapping,
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.DatabaseIndexing,
      SkillSlugEnum.Normalisation,
      SkillSlugEnum.PostgreSQL,
      SkillSlugEnum.MySQL,
      SkillSlugEnum.SQLite,
      SkillSlugEnum.MongoDB,
      SkillSlugEnum.Redis,
      SkillSlugEnum.Convex,
    ],
  },
  [SkillSlugEnum.WebSockets]: {
    name: "Web Sockets",
    category: SkillCategoriesEnum.WebSockets,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [SkillSlugEnum.SocketIO, SkillSlugEnum.Pusher],
  },
  [SkillSlugEnum.RelationalDatabases]: {
    name: "Relational Databases (SQL)",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.ObjectRelationalMapping,
      SkillSlugEnum.DatabaseIndexing,
      SkillSlugEnum.Normalisation,
      SkillSlugEnum.PostgreSQL,
      SkillSlugEnum.MySQL,
      SkillSlugEnum.SQLite,
    ],
  },

  [SkillSlugEnum.NonRelationalDatabases]: {
    name: "Non Relational Databases (NoSQL)",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.DatabaseIndexing,
      SkillSlugEnum.MongoDB,
      SkillSlugEnum.Redis,
      SkillSlugEnum.Convex,
    ],
  },
  [SkillSlugEnum.ObjectRelationalMapping]: {
    name: "Object Relational Mapping",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Monoose,
      SkillSlugEnum.Prisma,
      SkillSlugEnum.Drizzle,
      SkillSlugEnum.SQLAlchemy,
      SkillSlugEnum.TypeORM,
      SkillSlugEnum.Hibernate,
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.DatabaseIndexing,
    ],
  },
  [SkillSlugEnum.Testing]: {
    name: "Testing",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Jest,
      SkillSlugEnum.Vitest,
      SkillSlugEnum.PyTest,
      SkillSlugEnum.UnitTest,
      SkillSlugEnum.JUnit,
      SkillSlugEnum.Cypress,
      SkillSlugEnum.ReactTestingLibrary,
    ],
  },
  [SkillSlugEnum.Containerisation]: {
    name: "Containerization",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Docker,
      SkillSlugEnum.Podman,
      SkillSlugEnum.Kubernetes,
      SkillSlugEnum.Clusterisation,
      SkillSlugEnum.Azure_ContainerRegistry,
    ],
  },
  [SkillSlugEnum.Clusterisation]: {
    name: "Clusterisation",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Kubernetes,
      SkillSlugEnum.Azure_ContainerRegistry,
    ],
  },
  [SkillSlugEnum.InfrastructureAsCode]: {
    name: "Infrastructure as Code",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Ansible,
      SkillSlugEnum.Vagrant,
      SkillSlugEnum.Terraform,
    ],
  },
  [SkillSlugEnum.Automation]: {
    name: "Automation",
    category: SkillCategoriesEnum.Automation,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Ansible,
      SkillSlugEnum.Vagrant,
      SkillSlugEnum.Terraform,
    ],
  },
  [SkillSlugEnum.DatabaseManagementSystems]: {
    name: "Database Management Systems",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.DatabaseIndexing,
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.NonRelationalDatabases,
      SkillSlugEnum.ObjectRelationalMapping,
      SkillSlugEnum.Normalisation,
      SkillSlugEnum.Databases,
    ],
  },
  [SkillSlugEnum.DatabaseIndexing]: {
    name: "Indexing",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.NonRelationalDatabases,
      SkillSlugEnum.ObjectRelationalMapping,
      SkillSlugEnum.Normalisation,
      SkillSlugEnum.Databases,
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.PostgreSQL,
      SkillSlugEnum.MySQL,
      SkillSlugEnum.SQLite,
      SkillSlugEnum.MongoDB,
      SkillSlugEnum.Redis,
      SkillSlugEnum.Convex,
    ],
  },
  [SkillSlugEnum.CloudComputing]: {
    name: "Cloud Computing",
    category: SkillCategoriesEnum.CloudComputing,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.AWS,
      SkillSlugEnum.Azure,
      SkillSlugEnum.GCP,
      SkillSlugEnum.CloudComputing,
      SkillSlugEnum.AWS_K3s,
      SkillSlugEnum.AWS_EC2,
      SkillSlugEnum.AWS_S3,
      SkillSlugEnum.AWS_VPC,
      SkillSlugEnum.AWS_Lambda,
      SkillSlugEnum.AWS_CloudFormation,
      SkillSlugEnum.AWS_CloudFront,
      SkillSlugEnum.AWS_ElasticBeanstalk,
      SkillSlugEnum.CloudComputing,
      SkillSlugEnum.Azure_AppService,
      SkillSlugEnum.Azure_BlobStorage,
      SkillSlugEnum.Azure_DurableFunctions,
      SkillSlugEnum.Azure_Monitor,
      SkillSlugEnum.Azure_Functions,
      SkillSlugEnum.Azure_ResourceManager,
      SkillSlugEnum.Azure_ContainerRegistry,
      SkillSlugEnum.CloudComputing,
      SkillSlugEnum.GCP_AppEngine,
      SkillSlugEnum.GCP_CloudSQL,
      SkillSlugEnum.GCP_CloudStorage,
      SkillSlugEnum.GCP_CloudTasks,
      SkillSlugEnum.GCP_CloudScheduler,
      SkillSlugEnum.GCP_Logging,
      SkillSlugEnum.Firebase,
    ],
  },

  [SkillSlugEnum.DesignPatterns]: {
    name: "Design Patterns",
    category: SkillCategoriesEnum.CodeQuality,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Python,
      SkillSlugEnum.Java,
      SkillSlugEnum.TypeScript,
      SkillSlugEnum.JavaScript,
    ],
  },
  [SkillSlugEnum.UserAuthentication]: {
    name: "User Authentication",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Firebase,
      SkillSlugEnum.PocketBase,
      SkillSlugEnum.Supabase,
      SkillSlugEnum.Auth0,
      SkillSlugEnum.ClerkAuth,
      SkillSlugEnum.NextAuth,
    ],
  },
  [SkillSlugEnum.WebDevelopment]: {
    name: "Web Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.REST,
      SkillSlugEnum.GraphQL,
      SkillSlugEnum.TRPC,
      SkillSlugEnum.WebSockets,
      SkillSlugEnum.SocketIO,
      SkillSlugEnum.Pusher,
      SkillSlugEnum.Firebase,
      SkillSlugEnum.PocketBase,
      SkillSlugEnum.Supabase,
      SkillSlugEnum.Auth0,
      SkillSlugEnum.ClerkAuth,
      SkillSlugEnum.NextAuth,
      SkillSlugEnum.Stripe,
      SkillSlugEnum.ExpressJS,
      SkillSlugEnum.Flask,
      SkillSlugEnum.Django,
      SkillSlugEnum.Spring,
      SkillSlugEnum.SpringBoot,
      SkillSlugEnum.Cloudinary,
      SkillSlugEnum.EdgeStore,
      SkillSlugEnum.Gunicorn,
      SkillSlugEnum.Jinja,
      SkillSlugEnum.UserAuthentication,
      SkillSlugEnum.NextJS,
      SkillSlugEnum.SvelteKit,
      SkillSlugEnum.AngularJS,
      SkillSlugEnum.NuxtJS,
      SkillSlugEnum.ReactJS,
      SkillSlugEnum.SvelteJS,
      SkillSlugEnum.VueJS,
      SkillSlugEnum.Recoil,
      SkillSlugEnum.Zustand,
      SkillSlugEnum.Jotai,
      SkillSlugEnum.Redux,
      SkillSlugEnum.TailwindCSS,
      SkillSlugEnum.HTML,
      SkillSlugEnum.CSS,
      SkillSlugEnum.ChakraUI,
      SkillSlugEnum.HeadlessUI,
      SkillSlugEnum.ShadcnUI,
      SkillSlugEnum.RadixUI,
      SkillSlugEnum.ReactQuery,
      SkillSlugEnum.NextUI,
      SkillSlugEnum.StateManagement,
      SkillSlugEnum.Bootstrap,
      SkillSlugEnum.MaterialUI,
      SkillSlugEnum.SemanticUI,
      SkillSlugEnum.AntDesign,
      SkillSlugEnum.StoryBooks,
      SkillSlugEnum.Axios,
      SkillSlugEnum.UserCentricDesign,
      SkillSlugEnum.StateManagement,
    ],
  },
  [SkillSlugEnum.SDKs]: {
    name: "SDK",
    category: SkillCategoriesEnum.SDKs,
    isMainSkill: true,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Firebase,
      SkillSlugEnum.Supabase,
      SkillSlugEnum.PocketBase,
      SkillSlugEnum.Auth0,
      SkillSlugEnum.ClerkAuth,
      SkillSlugEnum.NextAuth,
      SkillSlugEnum.Stripe,
      SkillSlugEnum.Cloudinary,
      SkillSlugEnum.EdgeStore,
      SkillSlugEnum.Symphony,
    ],
  },
  [SkillSlugEnum.UserCentricDesign]: {
    name: "User Centric Design",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.REST,
      SkillSlugEnum.GraphQL,
      SkillSlugEnum.TRPC,
      SkillSlugEnum.WebSockets,
      SkillSlugEnum.SocketIO,
      SkillSlugEnum.Pusher,
      SkillSlugEnum.Firebase,
      SkillSlugEnum.PocketBase,
      SkillSlugEnum.Supabase,
      SkillSlugEnum.Auth0,
      SkillSlugEnum.ClerkAuth,
      SkillSlugEnum.NextAuth,
      SkillSlugEnum.Stripe,
      SkillSlugEnum.ExpressJS,
      SkillSlugEnum.Flask,
      SkillSlugEnum.Django,
      SkillSlugEnum.Spring,
      SkillSlugEnum.SpringBoot,
      SkillSlugEnum.Cloudinary,
      SkillSlugEnum.EdgeStore,
      SkillSlugEnum.Gunicorn,
      SkillSlugEnum.Jinja,
      SkillSlugEnum.UserAuthentication,
      SkillSlugEnum.NextJS,
      SkillSlugEnum.SvelteKit,
      SkillSlugEnum.AngularJS,
      SkillSlugEnum.NuxtJS,
      SkillSlugEnum.ReactJS,
      SkillSlugEnum.SvelteJS,
      SkillSlugEnum.VueJS,
      SkillSlugEnum.Recoil,
      SkillSlugEnum.Zustand,
      SkillSlugEnum.Jotai,
      SkillSlugEnum.Redux,
      SkillSlugEnum.TailwindCSS,
      SkillSlugEnum.HTML,
      SkillSlugEnum.CSS,
      SkillSlugEnum.ChakraUI,
      SkillSlugEnum.HeadlessUI,
      SkillSlugEnum.ShadcnUI,
      SkillSlugEnum.RadixUI,
      SkillSlugEnum.ReactQuery,
      SkillSlugEnum.NextUI,
      SkillSlugEnum.StateManagement,
      SkillSlugEnum.Bootstrap,
      SkillSlugEnum.MaterialUI,
      SkillSlugEnum.SemanticUI,
      SkillSlugEnum.AntDesign,
      SkillSlugEnum.StoryBooks,
      SkillSlugEnum.Axios,
      SkillSlugEnum.StateManagement,
    ],
  },
  [SkillSlugEnum.GameDevelopment]: {
    name: "Game Development",
    category: SkillCategoriesEnum.GameDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.GameMakerLanguage,
      SkillSlugEnum.GameMakerLanguage,
    ],
  },
  [SkillSlugEnum.Mathematics]: {
    name: "Mathematics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Probability,
      SkillSlugEnum.Statistics,
      SkillSlugEnum.Calculus,
      SkillSlugEnum.Trigonometry,
      SkillSlugEnum.Algebra,
      SkillSlugEnum.LinearAlgebra,
      SkillSlugEnum.Discrete,
      SkillSlugEnum.Geometry,
      SkillSlugEnum.Mechanics,
      SkillSlugEnum.Logics,
    ],
  },
  [SkillSlugEnum.VersionControlSystems]: {
    name: "Version Control",
    category: SkillCategoriesEnum.VersionControl,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Git,
      SkillSlugEnum.GitHub,
      SkillSlugEnum.GitLab,
      SkillSlugEnum.BitBucket,
    ],
  },
  [SkillSlugEnum.StateManagement]: {
    name: "State Management",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Recoil,
      SkillSlugEnum.Zustand,
      SkillSlugEnum.Jotai,
      SkillSlugEnum.Redux,
    ],
  },
};

export default generalSkills;
