import SkillCategoriesEnum from "@/enums/SkillCategoriesEnum";
import SkillInterface from "@/interfaces/skills/SkillInterface";
import SkillTypesEnum from "@/enums/SkillTypesEnum";
import SkillSlugEnum from "@/enums/SkillSlugEnum";

/**
 * Array of languages.
 * Each skill has an array of skills and repositories.
 */
const languages: { [key: string]: SkillInterface } = {
  [SkillSlugEnum.Python]: {
    name: "Python",
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillSlugEnum.Flask,
      SkillSlugEnum.Django,
      SkillSlugEnum.Gunicorn,
      SkillSlugEnum.Jinja,
      SkillSlugEnum.SimpleGUI,
      SkillSlugEnum.SQLAlchemy,
      SkillSlugEnum.Black,
      SkillSlugEnum.PyLint,
      SkillSlugEnum.PyTest,
      SkillSlugEnum.UnitTest,
      SkillSlugEnum.Poetry,
      SkillSlugEnum.Pip,
      SkillSlugEnum.PyBuilder,
      SkillSlugEnum.ScikitLearn,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
      SkillSlugEnum.Jupyter,
      SkillSlugEnum.Keras,
      SkillSlugEnum.MachineLearning,
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.Hyperparameters,
      SkillSlugEnum.Boosting,
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.NeuralNetworks,
      SkillSlugEnum.WebDevelopment,
    ],
  },
  [SkillSlugEnum.JavaScript]: {
    name: "JavaScript",
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillSlugEnum.ClerkAuth,
      SkillSlugEnum.NextAuth,
      SkillSlugEnum.ExpressJS,
      SkillSlugEnum.NextJS,
      SkillSlugEnum.SvelteKit,
      SkillSlugEnum.AngularJS,
      SkillSlugEnum.NuxtJS,
      SkillSlugEnum.ReactJS,
      SkillSlugEnum.SvelteJS,
      SkillSlugEnum.VueJS,
      SkillSlugEnum.Recoil,
      SkillSlugEnum.Redux,
      SkillSlugEnum.Monoose,
      SkillSlugEnum.Prettier,
      SkillSlugEnum.ESLint,
      SkillSlugEnum.Jest,
      SkillSlugEnum.Vitest,
      SkillSlugEnum.NPM,
      SkillSlugEnum.Yarn,
      SkillSlugEnum.PNPM,
      SkillSlugEnum.NxJS,
    ],
  },
  [SkillSlugEnum.TypeScript]: {
    name: "TypeScript",
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillSlugEnum.ClerkAuth,
      SkillSlugEnum.NextAuth,
      SkillSlugEnum.ExpressJS,
      SkillSlugEnum.NextJS,
      SkillSlugEnum.SvelteKit,
      SkillSlugEnum.AngularJS,
      SkillSlugEnum.NuxtJS,
      SkillSlugEnum.ReactJS,
      SkillSlugEnum.SvelteJS,
      SkillSlugEnum.VueJS,
      SkillSlugEnum.Recoil,
      SkillSlugEnum.Redux,
      SkillSlugEnum.Monoose,
      SkillSlugEnum.Prettier,
      SkillSlugEnum.ESLint,
      SkillSlugEnum.Jest,
      SkillSlugEnum.Vitest,
      SkillSlugEnum.NPM,
      SkillSlugEnum.Yarn,
      SkillSlugEnum.PNPM,
      SkillSlugEnum.NxJS,
      SkillSlugEnum.TypeORM,
      SkillSlugEnum.Zod,
    ],
  },
  [SkillSlugEnum.Java]: {
    name: "Java",
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillSlugEnum.Spring,
      SkillSlugEnum.SpringBoot,
      SkillSlugEnum.Hibernate,
      SkillSlugEnum.Checkstyle,
      SkillSlugEnum.JUnit,
      SkillSlugEnum.Gradle,
      SkillSlugEnum.Maven,
      SkillSlugEnum.AndroidDevelopment,
    ],
  },
  [SkillSlugEnum.GameMakerLanguage]: {
    name: "GameMaker Language",
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillSlugEnum.GameDevelopment,
      SkillSlugEnum.GameMakerStudio,
    ],
  },
  [SkillSlugEnum.ShellScript]: {
    name: "Shell Script",
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillSlugEnum.RLanguage]: {
    name: "R",
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillSlugEnum.Groovy]: {
    name: "Groovy",
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [SkillSlugEnum.Gradle, SkillSlugEnum.Jenkins],
  },
};

export { languages };
