/**
 * This enum is used to represent the keys of the skills in the database.
 * This enum is used to avoid hardcoding the keys in the code, getting autocompletion support and avoiding typos.
 * These keys are used within MaterialInterface and its children to represents skills associated with the material.
 * The order of the skills is the order that is used when displaying the skills on the website.
 *
 * @see {@link skillDatabaseMap} at `interfaces/skills.ts`
 */
enum SkillDatabaseKeys {
  //^ Languages
  Python = "python",
  JavaScript = "javascript",
  TypeScript = "typescript",
  Java = "java",
  ShellScript = "shell",
  C = "c",
  Haskell = "haskell",
  Scala = "scala",
  Groovy = "groovy",
  Kotlin = "kotlin",
  ObjectOrientedProgramming = "oop",
  FunctionalProgramming = "fp",
  Matlab = "matlab",

  //^ Artificial Intelligence, Machine Learning, and Data Science
  ScikitLearn = "scikit-learn",
  Pandas = "pandas",
  NumPy = "numpy",
  Matplotlib = "matplotlib",
  Seaborn = "seaborn",
  Keras = "keras",
  TensorFlow = "tensorflow",
  PyTorch = "pytorch",
  Jupyter = "jupyter",
  ApacheSpark = "apache-spark",
  MLLib = "ml-lib",
  MachineLearning = "machine-learning",
  DeepLearning = "deep-learning",
  ArtificialIntelligence = "artificial-intelligence",
  ReinforcementLearning = "reinforcement-learning",
  IntelligentAgents = "intelligent-agents",
  DataScience = "data-science",
  DataVisualisation = "data-visualisation",
  NeuralNetworks = "neural-networks",
  ComputerVision = "computer-vision",

  //^ Full Stack Web Development
  NextJS = "next-js",

  //^ Backend Web Development
  Firebase = "firebase",
  Supabase = "supabase",
  PocketBase = "pocketbase",
  Auth0 = "auth0",
  ClerkAuth = "clerk-auth",
  NextAuth = "next-auth",
  Stripe = "stripe",
  ExpressJS = "express-js",
  Flask = "flask",
  Django = "django",
  Spring = "spring",
  SpringBoot = "spring-boot",
  SpringDataLDAP = "spring-data-ldap",
  Cloudinary = "cloudinary",
  EdgeStore = "edge-store",
  WebSockets = "web-sockets",
  UserAuthentication = "user-authentication",

  //^ Frontend Web Development
  ReactJS = "react",
  Recoil = "recoil",
  Zustand = "zustand",
  Jotai = "jotai",
  Redux = "redux",
  TailwindCSS = "tailwind-css",
  HTML = "html",
  CSS = "css",
  ChakraUI = "chakra-ui",
  HeadlessUI = "headless-ui",
  ShadcnUI = "shadcn-ui",
  RadixUI = "radix-ui",
  NextUI = "next-ui",
  Bootstrap = "bootstrap",
  SimpleGUI = "simple-gui",
  Axios = "axios",
  UserCentricDesign = "user-centric-design",
  StateManagement = "state-management",

  //^ Database
  Normalisation = "normalisation",
  PostgreSQL = "postgresql",
  MySQL = "mysql",
  SQLite = "sqlite",
  MongoDB = "mongodb",
  Redis = "redis",
  Convex = "convex",
  Databases = "databases",
  RelationalDatabases = "relational-databases",
  NonRelationalDatabases = "non-relational-databases",
  DatabaseManagementSystems = "database-management-systems",
  DatabaseIndexing = "indexing",

  //^ Object-Relational Mappers
  Mongoose = "moongose",
  Prisma = "prisma",
  Drizzle = "drizzle",
  SQLAlchemy = "sqlalchemy",
  TypeORM = "typeorm",
  Hibernate = "hibernate",
  SpringDataJPA = "spring-data-jpa",
  SpringDataMongoDB = "spring-data-mongodb",
  ObjectRelationalMapping = "object-relational-mapping",

  //^ DevOps
  GitHubActions = "github-actions",
  GitLabCI = "gitlab-ci",
  Jenkins = "jenkins",
  TeamCity = "team-city",
  Docker = "docker",
  Podman = "podman",
  Kubernetes = "kubernetes",
  Ansible = "ansible",
  Vagrant = "vagrant",
  Terraform = "terraform",
  ContinuousIntegration = "continuous-integration",
  ContinuousDeployment = "continuous-deployment",
  ContinuousDelivery = "continuous-delivery",
  DevOps = "dev-ops",
  Containerisation = "containerisation",
  InfrastructureAsCode = "infrastructure-as-code",
  Clusterisation = "clusterisation",
  Automation = "automation",

  //^ APIs
  REST = "rest-api",
  Apollo = "apollo",
  GraphQL = "graphql-api",
  SocketIO = "socket-io",
  Pusher = "pusher",
  OpenAI = "open-ai",
  ReplicateAI = "replicate-ai",

  //^ Version Control Systems
  Git = "git",
  GitHub = "github",
  GitLab = "gitlab",
  BitBucket = "bit-bucket",
  VersionControlSystems = "version-control-systems",

  //^ Testing
  Jest = "jest",
  Vitest = "vitest",
  PyTest = "pytest",
  UnitTest = "unittest",
  JUnit = "junit",
  Cypress = "cypress",
  ReactTestingLibrary = "react-testing-library",
  Testing = "testing",

  //^ Project and Dependency Management
  NPM = "npm",
  Yarn = "yarn",
  PNPM = "pnpm",
  Poetry = "poetry",
  Pip = "pip",
  Maven = "maven",
  Gradle = "gradle",
  NxJS = "nx-js",

  //^ Mathematics
  Probability = "probability",
  Statistics = "statistics",
  Calculus = "calculus",
  Trigonometry = "trigonometry",
  Algebra = "algebra",
  LinearAlgebra = "linear-algebra",
  Discrete = "discrete",
  Geometry = "geometry",
  Mechanics = "mechanics",
  Logics = "logics",
  Mathematics = "mathematics",

  //^ Cloud Computing
  AWS = "aws",
  AWS_CloudWatch = "aws-cloudwatch",
  AWS_ApplicationLoadBalancer = "aws-application-load-balancer",
  AWS_ElasticCache = "aws-elastic-cache",
  AWS_K3s = "aws-k3s",
  AWS_EC2 = "aws-ec2",
  AWS_S3 = "aws-s3",
  AWS_VPC = "aws-vpc",
  AWS_Lambda = "aws-lambda",
  AWS_ElasticFileSystem = "aws-elastic-filesystem",
  AWS_ElasticBlockStore = "aws-elastic-block-store",
  AWS_RelationalDatabaseService = "aws-relational-database-service",
  AWS_AutoScaling = "aws-auto-scaling",
  AWS_CloudFormation = "aws-cloudformation",
  AWS_CloudFront = "aws-cloudfront",
  AWS_ElasticBeanstalk = "aws-elastic-beanstalk",
  Azure = "azure",
  Azure_AppService = "azure-app-service",
  Azure_Monitor = "azure-monitor",
  Azure_BlobStorage = "azure-blob-storage",
  Azure_DurableFunctions = "azure-durable-functions",
  Azure_Functions = "azure-functions",
  Azure_ResourceManager = "azure-resource-manager",
  Azure_ContainerRegistry = "azure-container-registry",
  GCP = "gcp",
  GCP_AppEngine = "gcp-app-engine",
  GCP_CloudSQL = "gcp-cloud-sql",
  GCP_CloudStorage = "gcp-cloud-storage",
  GCP_CloudTasks = "gcp-cloud-tasks",
  GCP_CloudScheduler = "gcp-cloud-scheduler",
  GCP_Logging = "gcp-logging",
  CloudComputing = "cloud-computing",

  //^ Algorithms & Data Structures
  Algorithms = "algorithms",
  DataStructures = "data-structures",

  //^ Others
  Symphony = "symphony",

  //^ Soft Skills
  Communication = "communication",
  ProjectManagement = "project-management",
  Teamwork = "teamwork",
  Leadership = "leadership",
  ProblemSolving = "problem-solving",
  CriticalThinking = "critical-thinking",
  Creativity = "creativity",
  Adaptability = "adaptability",
  TimeManagement = "time-management",
  RiskManagement = "risk-management",
  StakeholderManagement = "stakeholder-management",
  ScopeManagement = "scope-management",
  CostManagement = "cost-management",
  QualityManagement = "quality-management",
  ProcurementManagement = "procurement-management",
  IntegrationManagement = "integration-management",
  HumanResourceManagement = "human-resource-management",
}

export default SkillDatabaseKeys;
