import SkillDatabaseKeys from "@/database/skills/SkillDatabaseKeys";
import SkillInterface from "@/database/skills/SkillInterface";
import SkillCategoriesEnum from "@/enums/skill/SkillCategoriesEnum";
import SkillTypesEnum from "@/enums/skill/SkillTypesEnum";
import Database from "@/interfaces/Database";

/**
 * Hashmap of skills with keys as {@link SkillDatabaseKeys} and values as {@link SkillInterface}.
 * The order of skills and sub-skills is the order that is used when displaying the skills on the website.
 */
const skillDatabaseMap: Database<SkillInterface> = {
  //^ Languages
  [SkillDatabaseKeys.Python]: {
    name: "Python",
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillDatabaseKeys.Flask,
      SkillDatabaseKeys.Django,
      SkillDatabaseKeys.SimpleGui,
      SkillDatabaseKeys.SqlAlchemy,
      SkillDatabaseKeys.Symphony,
      SkillDatabaseKeys.PyTest,
      SkillDatabaseKeys.UnitTest,
      SkillDatabaseKeys.ScikitLearn,
      SkillDatabaseKeys.TensorFlow,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.Transformers,
      SkillDatabaseKeys.HuggingFace,
      SkillDatabaseKeys.LargeLanguageModels,
      SkillDatabaseKeys.ModelContextProtocol,
      SkillDatabaseKeys.NaturalLanguageProcessing,
      SkillDatabaseKeys.FineTuning,
      SkillDatabaseKeys.Benchmarking,
      SkillDatabaseKeys.Quantization,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ReinforcementLearning,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },
  [SkillDatabaseKeys.JavaScript]: {
    name: "JavaScript",
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillDatabaseKeys.ClerkAuth,
      SkillDatabaseKeys.AuthJs,
      SkillDatabaseKeys.ExpressJs,
      SkillDatabaseKeys.NextJs,
      SkillDatabaseKeys.ReactJs,
      SkillDatabaseKeys.Zod,
      SkillDatabaseKeys.Mongoose,
      SkillDatabaseKeys.Jest,
      SkillDatabaseKeys.Vitest,
      SkillDatabaseKeys.Drizzle,
      SkillDatabaseKeys.Auth0,
    ],
  },
  [SkillDatabaseKeys.TypeScript]: {
    name: "TypeScript",
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillDatabaseKeys.ClerkAuth,
      SkillDatabaseKeys.AuthJs,
      SkillDatabaseKeys.ExpressJs,
      SkillDatabaseKeys.NextJs,
      SkillDatabaseKeys.ReactJs,
      SkillDatabaseKeys.Zod,
      SkillDatabaseKeys.ChakraUi,
      SkillDatabaseKeys.ShadcnUi,
      SkillDatabaseKeys.RadixUi,
      SkillDatabaseKeys.NextUi,
      SkillDatabaseKeys.Drizzle,
      SkillDatabaseKeys.TypeOrm,
      SkillDatabaseKeys.Mongoose,
      SkillDatabaseKeys.Zustand,
      SkillDatabaseKeys.Jotai,
      SkillDatabaseKeys.Prisma,
      SkillDatabaseKeys.Jest,
      SkillDatabaseKeys.Vitest,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.ModelContextProtocol,
    ],
  },
  [SkillDatabaseKeys.Java]: {
    name: "Java",
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Hibernate,
      SkillDatabaseKeys.SpringDataJpa,
      SkillDatabaseKeys.SpringDataMongoDb,
      SkillDatabaseKeys.SpringDataLdap,
      SkillDatabaseKeys.SpringSecurity,
      SkillDatabaseKeys.Symphony,
      SkillDatabaseKeys.JUnit,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.ModelContextProtocol,
    ],
  },
  [SkillDatabaseKeys.Kotlin]: {
    name: "Kotlin",
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Hibernate,
      SkillDatabaseKeys.SpringDataJpa,
      SkillDatabaseKeys.SpringDataMongoDb,
      SkillDatabaseKeys.SpringDataLdap,
      SkillDatabaseKeys.SpringSecurity,
      SkillDatabaseKeys.Symphony,
      SkillDatabaseKeys.JUnit,
      SkillDatabaseKeys.TeamCity,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.ModelContextProtocol,
    ],
  },
  [SkillDatabaseKeys.ShellScript]: {
    name: "Shell Script",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillDatabaseKeys.C]: {
    name: "C",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillDatabaseKeys.Haskell]: {
    name: "Haskell",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillDatabaseKeys.Scala]: {
    name: "Scala",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [SkillDatabaseKeys.ApacheSpark],
  },
  [SkillDatabaseKeys.Groovy]: {
    name: "Groovy",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [SkillDatabaseKeys.Jenkins],
  },
  [SkillDatabaseKeys.Matlab]: {
    name: "Matlab",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },

  //^ Artificial Intelligence, Machine Learning, and Data Science
  [SkillDatabaseKeys.ScikitLearn]: {
    name: "Scikit Learn",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },
  [SkillDatabaseKeys.PyTorch]: {
    name: "PyTorch",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Transformers,
      SkillDatabaseKeys.HuggingFace,
      SkillDatabaseKeys.LargeLanguageModels,
      SkillDatabaseKeys.NaturalLanguageProcessing,
      SkillDatabaseKeys.FineTuning,
      SkillDatabaseKeys.Benchmarking,
      SkillDatabaseKeys.Quantization,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ReinforcementLearning,
      SkillDatabaseKeys.IntelligentAgents,
      SkillDatabaseKeys.DataScience,
    ],
  },
  [SkillDatabaseKeys.Keras]: {
    name: "Keras",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.TensorFlow,
      SkillDatabaseKeys.ReinforcementLearning,
    ],
  },
  [SkillDatabaseKeys.TensorFlow]: {
    name: "TensorFlow",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.ReinforcementLearning,
    ],
  },
  [SkillDatabaseKeys.Transformers]: {
    name: "Transformers",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.HuggingFace,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.LargeLanguageModels,
      SkillDatabaseKeys.NaturalLanguageProcessing,
      SkillDatabaseKeys.FineTuning,
      SkillDatabaseKeys.Quantization,
      SkillDatabaseKeys.Benchmarking,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },
  [SkillDatabaseKeys.Pandas]: {
    name: "Pandas",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
    ],
  },
  [SkillDatabaseKeys.NumPy]: {
    name: "NumPy",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.Mathematics,
    ],
  },
  [SkillDatabaseKeys.Matplotlib]: {
    name: "Matplotlib",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
    ],
  },
  [SkillDatabaseKeys.Seaborn]: {
    name: "Seaborn",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
    ],
  },
  [SkillDatabaseKeys.HuggingFace]: {
    name: "Hugging Face",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Transformers,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.LargeLanguageModels,
      SkillDatabaseKeys.NaturalLanguageProcessing,
      SkillDatabaseKeys.FineTuning,
      SkillDatabaseKeys.Quantization,
      SkillDatabaseKeys.Benchmarking,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },
  [SkillDatabaseKeys.ApacheSpark]: {
    name: "Apache Spark",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Scala,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.MlLib,
    ],
  },
  [SkillDatabaseKeys.MlLib]: {
    name: "MLLib",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ApacheSpark,
    ],
  },
  [SkillDatabaseKeys.ModelContextProtocol]: {
    name: "Model Context Protocol (MCP)",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.Kotlin,
    ],
  },
  [SkillDatabaseKeys.ReinforcementLearning]: {
    name: "Reinforcement Learning",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.IntelligentAgents,
    ],
  },

  [SkillDatabaseKeys.IntelligentAgents]: {
    name: "Intelligent Agents",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.ReinforcementLearning,
    ],
  },
  [SkillDatabaseKeys.LargeLanguageModels]: {
    name: "Large Language Models (LLMs)",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.Transformers,
      SkillDatabaseKeys.HuggingFace,
      SkillDatabaseKeys.NaturalLanguageProcessing,
      SkillDatabaseKeys.FineTuning,
      SkillDatabaseKeys.Quantization,
      SkillDatabaseKeys.Benchmarking,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },
  [SkillDatabaseKeys.NaturalLanguageProcessing]: {
    name: "Natural Language Processing (NLP)",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.Transformers,
      SkillDatabaseKeys.HuggingFace,
      SkillDatabaseKeys.LargeLanguageModels,
      SkillDatabaseKeys.FineTuning,
      SkillDatabaseKeys.Quantization,
      SkillDatabaseKeys.Benchmarking,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },
  [SkillDatabaseKeys.FineTuning]: {
    name: "Fine-Tuning",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.Transformers,
      SkillDatabaseKeys.HuggingFace,
      SkillDatabaseKeys.LargeLanguageModels,
      SkillDatabaseKeys.NaturalLanguageProcessing,
      SkillDatabaseKeys.Quantization,
      SkillDatabaseKeys.Benchmarking,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },
  [SkillDatabaseKeys.Benchmarking]: {
    name: "Benchmarking",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.Transformers,
      SkillDatabaseKeys.HuggingFace,
      SkillDatabaseKeys.LargeLanguageModels,
      SkillDatabaseKeys.NaturalLanguageProcessing,
      SkillDatabaseKeys.FineTuning,
      SkillDatabaseKeys.Quantization,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },
  [SkillDatabaseKeys.Quantization]: {
    name: "Quantization",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.Transformers,
      SkillDatabaseKeys.HuggingFace,
      SkillDatabaseKeys.LargeLanguageModels,
      SkillDatabaseKeys.NaturalLanguageProcessing,
      SkillDatabaseKeys.FineTuning,
      SkillDatabaseKeys.Benchmarking,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },

  //^ Full Stack Web Development
  [SkillDatabaseKeys.NextJs]: {
    name: "Next.JS",
    category: SkillCategoriesEnum.FullStackWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.ReactJs,
      SkillDatabaseKeys.Zod,
      SkillDatabaseKeys.ChakraUi,
      SkillDatabaseKeys.ShadcnUi,
      SkillDatabaseKeys.RadixUi,
      SkillDatabaseKeys.NextUi,
      SkillDatabaseKeys.Drizzle,
      SkillDatabaseKeys.TypeOrm,
      SkillDatabaseKeys.Mongoose,
      SkillDatabaseKeys.Zustand,
      SkillDatabaseKeys.Jotai,
      SkillDatabaseKeys.Prisma,
      SkillDatabaseKeys.Jest,
      SkillDatabaseKeys.Vitest,
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.AuthJs,
      SkillDatabaseKeys.Auth0,
    ],
  },

  //^ Backend Web Development
  [SkillDatabaseKeys.Firebase]: {
    name: "Firebase",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.Gcp,
    ],
  },
  [SkillDatabaseKeys.Supabase]: {
    name: "Supabase",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.PostgreSql,
    ],
  },
  [SkillDatabaseKeys.Auth0]: {
    name: "Auth0",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.Django,
      SkillDatabaseKeys.Flask,
      SkillDatabaseKeys.ExpressJs,
      SkillDatabaseKeys.NextJs,
      SkillDatabaseKeys.ReactJs,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
    ],
  },
  [SkillDatabaseKeys.ClerkAuth]: {
    name: "Clerk Auth",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.NextJs,
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.NextJs,
      SkillDatabaseKeys.ExpressJs,
      SkillDatabaseKeys.ReactJs,
    ],
  },
  [SkillDatabaseKeys.AuthJs]: {
    name: "Auth.JS",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.NextJs,
      SkillDatabaseKeys.ExpressJs,
      SkillDatabaseKeys.UserAuthentication,
    ],
  },
  [SkillDatabaseKeys.BetterAuth]: {
    name: "Better Auth",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.NextJs,
      SkillDatabaseKeys.ExpressJs,
      SkillDatabaseKeys.UserAuthentication,
    ],
  },
  [SkillDatabaseKeys.Stripe]: {
    name: "Stripe",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [],
  },
  [SkillDatabaseKeys.ExpressJs]: {
    name: "Express.JS",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.Mongoose,
      SkillDatabaseKeys.Drizzle,
    ],
  },
  [SkillDatabaseKeys.Flask]: {
    name: "Flask",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.SqlAlchemy,
    ],
  },
  [SkillDatabaseKeys.Django]: {
    name: "Django",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Python, SkillDatabaseKeys.Auth0],
  },
  [SkillDatabaseKeys.Spring]: {
    name: "Spring",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.SpringDataJpa,
      SkillDatabaseKeys.SpringDataMongoDb,
      SkillDatabaseKeys.Hibernate,
      SkillDatabaseKeys.Symphony,
      SkillDatabaseKeys.Auth0,
    ],
  },
  [SkillDatabaseKeys.SpringBoot]: {
    name: "Spring Boot",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringDataJpa,
      SkillDatabaseKeys.SpringDataMongoDb,
      SkillDatabaseKeys.SpringDataLdap,
      SkillDatabaseKeys.Hibernate,
      SkillDatabaseKeys.Symphony,
      SkillDatabaseKeys.Auth0,
    ],
  },
  [SkillDatabaseKeys.SpringDataLdap]: {
    name: "Spring Data LDAP",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
    ],
  },
  [SkillDatabaseKeys.SpringSecurity]: {
    name: "Spring Security",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
    ],
  },
  [SkillDatabaseKeys.SpringOAuth]: {
    name: "Spring OAuth",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
    ],
  },
  [SkillDatabaseKeys.Convex]: {
    name: "Convex",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.Cloudinary]: {
    name: "Cloudinary",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Cloudinary],
  },
  [SkillDatabaseKeys.EdgeStore]: {
    name: "Edge Store",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [],
  },
  [SkillDatabaseKeys.Rest]: {
    name: "REST APIs",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [],
  },
  [SkillDatabaseKeys.Apollo]: {
    name: "Apollo",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [],
  },
  [SkillDatabaseKeys.GraphQl]: {
    name: "GraphQL APIs",
    isMainSkill: true,
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Apollo],
  },
  [SkillDatabaseKeys.SocketIo]: {
    name: "Socket.IO",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.WebSockets],
  },
  [SkillDatabaseKeys.Pusher]: {
    name: "Pusher",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.WebSockets],
  },
  [SkillDatabaseKeys.WebSockets]: {
    name: "Web Sockets",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.SocketIo, SkillDatabaseKeys.Pusher],
  },

  //^ Frontend Web Development
  [SkillDatabaseKeys.Zod]: {
    name: "Zod",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.ReactJs,
      SkillDatabaseKeys.NextJs,
    ],
  },
  [SkillDatabaseKeys.Jotai]: {
    name: "Jotai",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.StateManagement],
  },
  [SkillDatabaseKeys.Zustand]: {
    name: "Zustand",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.StateManagement],
  },
  [SkillDatabaseKeys.ReactJs]: {
    name: "React.JS",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.Zod,
      SkillDatabaseKeys.Jotai,
      SkillDatabaseKeys.Zustand,
      SkillDatabaseKeys.UserCentricDesign,
    ],
  },
  [SkillDatabaseKeys.Html]: {
    name: "HTML",
    isMainSkill: true,
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.UserCentricDesign],
  },
  [SkillDatabaseKeys.Css]: {
    name: "CSS",
    isMainSkill: true,
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.TailwindCSS,
    ],
  },
  [SkillDatabaseKeys.TailwindCSS]: {
    name: "Tailwind CSS",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Css, SkillDatabaseKeys.UserCentricDesign],
  },
  [SkillDatabaseKeys.ChakraUi]: {
    name: "Chakra UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.UserCentricDesign],
  },

  [SkillDatabaseKeys.HeadlessUi]: {
    name: "Headless UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.ReactJs,
    ],
  },
  [SkillDatabaseKeys.ShadcnUi]: {
    name: "Shadcn UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.ReactJs,
    ],
  },
  [SkillDatabaseKeys.RadixUi]: {
    name: "Radix UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.ReactJs,
    ],
  },
  [SkillDatabaseKeys.NextUi]: {
    name: "Next UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.ReactJs,
    ],
  },
  [SkillDatabaseKeys.SimpleGui]: {
    name: "Simple GUI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.UserCentricDesign],
  },
  [SkillDatabaseKeys.Axios]: {
    name: "Axios",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [],
  },

  //^ Databases
  [SkillDatabaseKeys.MongoDb]: {
    name: "MongoDB",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.Normalisation]: {
    name: "Normalisation",
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.Databases,
    ],
  },
  [SkillDatabaseKeys.PostgreSql]: {
    name: "PostgreSQL",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.MySql]: {
    name: "MySQL",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.SqLite]: {
    name: "SQLite",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.Redis]: {
    name: "Redis",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },

  [SkillDatabaseKeys.Mongoose]: {
    name: "Mongoose ODM",
    isMainSkill: false,
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.MongoDb,
    ],
  },
  [SkillDatabaseKeys.Prisma]: {
    name: "Prisma ORM",
    isMainSkill: false,
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.MongoDb,
      SkillDatabaseKeys.PostgreSql,
      SkillDatabaseKeys.MySql,
      SkillDatabaseKeys.SqLite,
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
    ],
  },
  [SkillDatabaseKeys.Drizzle]: {
    name: "Drizzle ORM",
    isMainSkill: false,
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.TypeOrm,
      SkillDatabaseKeys.PostgreSql,
      SkillDatabaseKeys.MySql,
      SkillDatabaseKeys.SqLite,
    ],
  },
  [SkillDatabaseKeys.TypeOrm]: {
    name: "TypeORM",
    isMainSkill: false,
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.PostgreSql,
      SkillDatabaseKeys.MySql,
      SkillDatabaseKeys.SqLite,
    ],
  },
  [SkillDatabaseKeys.SqlAlchemy]: {
    name: "SQLAlchemy",
    isMainSkill: false,
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.PostgreSql,
      SkillDatabaseKeys.MySql,
      SkillDatabaseKeys.SqLite,
    ],
  },
  [SkillDatabaseKeys.Hibernate]: {
    name: "Hibernate",
    isMainSkill: false,
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.PostgreSql,
      SkillDatabaseKeys.MySql,
      SkillDatabaseKeys.SqLite,
      SkillDatabaseKeys.SpringDataJpa,
    ],
  },
  [SkillDatabaseKeys.SpringDataJpa]: {
    name: "Spring Data JPA",
    isMainSkill: false,
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.PostgreSql,
      SkillDatabaseKeys.MySql,
      SkillDatabaseKeys.SqLite,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Hibernate,
    ],
  },
  [SkillDatabaseKeys.SpringDataMongoDb]: {
    name: "Spring Data MongoDB",
    isMainSkill: false,
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.MongoDb,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
    ],
  },

  //^ DevOps
  [SkillDatabaseKeys.GitHubActions]: {
    name: "GitHub Actions",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    isMainSkill: true,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.DevOps,
    ],
  },
  [SkillDatabaseKeys.GitLabCi]: {
    name: "GitLab CI",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.DevOps,
    ],
  },
  [SkillDatabaseKeys.Jenkins]: {
    name: "Jenkins",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    isMainSkill: true,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.DevOps,
      SkillDatabaseKeys.Groovy,
    ],
  },
  [SkillDatabaseKeys.TeamCity]: {
    name: "TeamCity",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    isMainSkill: true,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.DevOps,
    ],
  },
  [SkillDatabaseKeys.Docker]: {
    name: "Docker",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.DevOps,
    ],
  },
  [SkillDatabaseKeys.Podman]: {
    name: "Podman",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.DevOps,
    ],
  },
  [SkillDatabaseKeys.Kubernetes]: {
    name: "Kubernetes",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.DevOps,
      SkillDatabaseKeys.Clusterisation,
    ],
  },
  [SkillDatabaseKeys.Ansible]: {
    name: "Ansible",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.DevOps,
    ],
  },
  [SkillDatabaseKeys.Terraform]: {
    name: "Terraform",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.DevOps,
    ],
  },
  [SkillDatabaseKeys.Vagrant]: {
    name: "Vagrant",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.DevOps,
    ],
  },

  //^ Testing
  [SkillDatabaseKeys.Jest]: {
    name: "Jest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.JavaScript, SkillDatabaseKeys.TypeScript],
  },
  [SkillDatabaseKeys.Vitest]: {
    name: "Vitest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.JavaScript, SkillDatabaseKeys.TypeScript],
  },
  [SkillDatabaseKeys.PyTest]: {
    name: "PyTest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Python],
  },
  [SkillDatabaseKeys.UnitTest]: {
    name: "UnitTest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Python],
  },
  [SkillDatabaseKeys.JUnit]: {
    name: "JUnit",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Java],
  },
  [SkillDatabaseKeys.Mockito]: {
    name: "Mockito",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.UnitTest,
      SkillDatabaseKeys.JUnit,
      SkillDatabaseKeys.PyTest,
      SkillDatabaseKeys.Jest,
      SkillDatabaseKeys.Vitest,
      SkillDatabaseKeys.Cypress,
      SkillDatabaseKeys.ReactTestingLibrary,
      SkillDatabaseKeys.Testing,
    ],
  },
  [SkillDatabaseKeys.Cypress]: {
    name: "Cypress",
    category: SkillCategoriesEnum.Testing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.JavaScript, SkillDatabaseKeys.TypeScript],
  },
  [SkillDatabaseKeys.ReactTestingLibrary]: {
    name: "React Testing Library",
    category: SkillCategoriesEnum.Testing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.ReactJs,
    ],
  },

  //^ Cloud Computing
  [SkillDatabaseKeys.Aws]: {
    name: "Amazon Web Services (AWS)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.AwsK3s,
      SkillDatabaseKeys.AwsEc2,
      SkillDatabaseKeys.AwsS3,
      SkillDatabaseKeys.AwsVcp,
      SkillDatabaseKeys.AwsLambda,
      SkillDatabaseKeys.AwsCloudFormation,
      SkillDatabaseKeys.AwsCloudFront,
      SkillDatabaseKeys.AwsElasticBeanstalk,
    ],
  },
  [SkillDatabaseKeys.AwsK3s]: {
    name: "K3s",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.Clusterisation,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.Aws,
    ],
  },
  [SkillDatabaseKeys.AwsCloudWatch]: {
    name: "CloudWatch",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Aws],
  },
  [SkillDatabaseKeys.AwsApplicationLoadBalancer]: {
    name: "Application Load Balancer (ALB)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
  },
  [SkillDatabaseKeys.AwsElasticCache]: {
    name: "Elastic Cache (EC)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Aws],
  },

  [SkillDatabaseKeys.AwsElasticFileSystem]: {
    name: "Elastic File System (EFS)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Aws],
  },
  [SkillDatabaseKeys.AwsElasticBlockStore]: {
    name: "Elastic Block Store (EBS)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Aws],
  },
  [SkillDatabaseKeys.AwsRelationalDatabaseService]: {
    name: "Relational Database Service (RDS)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.Aws,
    ],
  },
  [SkillDatabaseKeys.AwsAutoScaling]: {
    name: "Auto Scaling",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Aws],
  },
  [SkillDatabaseKeys.AwsEc2]: {
    name: "Elastic Compute Cloud (EC2)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Aws],
  },
  [SkillDatabaseKeys.AwsS3]: {
    name: "Simple Storage Service (S3)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Aws],
  },
  [SkillDatabaseKeys.AwsVcp]: {
    name: "Virtual Private Cloud (VPC)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Aws],
  },
  [SkillDatabaseKeys.AwsLambda]: {
    name: "Lambda",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Aws],
  },
  [SkillDatabaseKeys.AwsCloudFormation]: {
    name: "CloudFormation",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Aws],
  },
  [SkillDatabaseKeys.AwsCloudFront]: {
    name: "CloudFront",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Aws],
  },
  [SkillDatabaseKeys.AwsElasticBeanstalk]: {
    name: "Elastic Beanstalk",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Aws],
  },

  [SkillDatabaseKeys.Azure]: {
    name: "Microsoft Azure",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.Azure_AppService,
      SkillDatabaseKeys.Azure_BlobStorage,
      SkillDatabaseKeys.Azure_DurableFunctions,
      SkillDatabaseKeys.Azure_Monitor,
      SkillDatabaseKeys.Azure_Functions,
      SkillDatabaseKeys.Azure_ResourceManager,
      SkillDatabaseKeys.Azure_ContainerRegistry,
    ],
  },
  [SkillDatabaseKeys.Azure_AppService]: {
    name: "Azure App Service",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_BlobStorage]: {
    name: "Azure Blob Storage",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_DurableFunctions]: {
    name: "Durable Functions",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_Monitor]: {
    name: "Azure Monitor",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_Functions]: {
    name: "Azure Functions",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_ResourceManager]: {
    name: "Azure Resource Manager",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_ContainerRegistry]: {
    name: "Azure Container Registry",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.Azure,
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.Clusterisation,
      SkillDatabaseKeys.Docker,
      SkillDatabaseKeys.Podman,
      SkillDatabaseKeys.Kubernetes,
    ],
  },

  [SkillDatabaseKeys.Gcp]: {
    name: "Google Cloud Platform (GCP)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.GcpAppEngine,
      SkillDatabaseKeys.GcpCloudSQL,
      SkillDatabaseKeys.GcpCloudStorage,
      SkillDatabaseKeys.GcpCloudTasks,
      SkillDatabaseKeys.GcpCloudScheduler,
      SkillDatabaseKeys.GcpLogging,
      SkillDatabaseKeys.Firebase,
    ],
  },
  [SkillDatabaseKeys.GcpAppEngine]: {
    name: "App Engine",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Gcp],
  },
  [SkillDatabaseKeys.GcpCloudSQL]: {
    name: "Cloud SQL",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.Gcp,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.GcpCloudStorage]: {
    name: "Cloud Storage",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Gcp],
  },
  [SkillDatabaseKeys.GcpCloudTasks]: {
    name: "Cloud Tasks",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Gcp],
  },
  [SkillDatabaseKeys.GcpCloudScheduler]: {
    name: "Cloud Scheduler",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Gcp],
  },
  [SkillDatabaseKeys.GcpLogging]: {
    name: "Cloud Logging",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Gcp],
  },

  //^ Mathematics
  [SkillDatabaseKeys.Probability]: {
    name: "Probability",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Mathematics,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
    ],
  },
  [SkillDatabaseKeys.Statistics]: {
    name: "Statistics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Mathematics,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
    ],
  },
  [SkillDatabaseKeys.Calculus]: {
    name: "Calculus",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Mathematics,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
    ],
  },
  [SkillDatabaseKeys.Trigonometry]: {
    name: "Trigonometry",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },
  [SkillDatabaseKeys.Algebra]: {
    name: "Algebra",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },
  [SkillDatabaseKeys.LinearAlgebra]: {
    name: "Linear Algebra",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Mathematics,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
    ],
  },
  [SkillDatabaseKeys.Discrete]: {
    name: "Discrete",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },
  [SkillDatabaseKeys.Geometry]: {
    name: "Geometry",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },
  [SkillDatabaseKeys.Logics]: {
    name: "Logics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },
  [SkillDatabaseKeys.Mechanics]: {
    name: "Mechanics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },

  //^ Communication
  [SkillDatabaseKeys.Symphony]: {
    name: "Symphony BDK",
    category: SkillCategoriesEnum.FullStackWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Python,
    ],
  },

  //^ General Technical Skills
  [SkillDatabaseKeys.ContinuousIntegration]: {
    name: "Continuous Integration",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.GitHubActions,
      SkillDatabaseKeys.GitLabCi,
      SkillDatabaseKeys.Jenkins,
      SkillDatabaseKeys.TeamCity,
    ],
  },

  [SkillDatabaseKeys.ContinuousDelivery]: {
    name: "Continuous Delivery",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.GitHubActions,
      SkillDatabaseKeys.GitLabCi,
      SkillDatabaseKeys.Jenkins,
      SkillDatabaseKeys.TeamCity,
    ],
  },

  [SkillDatabaseKeys.ContinuousDeployment]: {
    name: "Continuous Deployment",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.GitHubActions,
      SkillDatabaseKeys.GitLabCi,
      SkillDatabaseKeys.Jenkins,
      SkillDatabaseKeys.TeamCity,
    ],
  },

  [SkillDatabaseKeys.DevOps]: {
    name: "DevOps",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.GitHubActions,
      SkillDatabaseKeys.GitLabCi,
      SkillDatabaseKeys.Jenkins,
      SkillDatabaseKeys.TeamCity,
      SkillDatabaseKeys.Docker,
      SkillDatabaseKeys.Podman,
      SkillDatabaseKeys.Kubernetes,
      SkillDatabaseKeys.Ansible,
      SkillDatabaseKeys.Vagrant,
      SkillDatabaseKeys.Terraform,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.Clusterisation,
      SkillDatabaseKeys.InfrastructureAsCode,
    ],
  },

  [SkillDatabaseKeys.MachineLearning]: {
    name: "Machine Learning",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,

      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.TensorFlow,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.ScikitLearn,

      SkillDatabaseKeys.ComputerVision,
    ],
  },
  [SkillDatabaseKeys.DeepLearning]: {
    name: "Deep Learning",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,

      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.TensorFlow,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.ScikitLearn,

      SkillDatabaseKeys.ComputerVision,
    ],
  },
  [SkillDatabaseKeys.ArtificialIntelligence]: {
    name: "Artificial Intelligence",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technical,
    isMainSkill: true,
    relatedSkills: [
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,

      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.ScikitLearn,

      SkillDatabaseKeys.ComputerVision,
    ],
  },
  [SkillDatabaseKeys.DataScience]: {
    name: "Data Science",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
    ],
  },
  [SkillDatabaseKeys.DataVisualisation]: {
    name: "Data Visualisation",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
    ],
  },
  [SkillDatabaseKeys.NeuralNetworks]: {
    name: "Neural Networks",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.ScikitLearn,
    ],
  },
  [SkillDatabaseKeys.ComputerVision]: {
    name: "Computer Vision",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.ScikitLearn,
    ],
  },
  [SkillDatabaseKeys.Databases]: {
    name: "Databases",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.PostgreSql,
      SkillDatabaseKeys.MySql,
      SkillDatabaseKeys.SqLite,
      SkillDatabaseKeys.MongoDb,
      SkillDatabaseKeys.Redis,
      SkillDatabaseKeys.Convex,
    ],
  },
  [SkillDatabaseKeys.RelationalDatabases]: {
    name: "Relational Databases (SQL)",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.PostgreSql,
      SkillDatabaseKeys.MySql,
      SkillDatabaseKeys.SqLite,
    ],
  },

  [SkillDatabaseKeys.NonRelationalDatabases]: {
    name: "Non Relational Databases (NoSQL)",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.MongoDb,
      SkillDatabaseKeys.Redis,
      SkillDatabaseKeys.Convex,
    ],
  },
  [SkillDatabaseKeys.ObjectRelationalMapping]: {
    name: "Object Relational Mapping",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Mongoose,
      SkillDatabaseKeys.Prisma,
      SkillDatabaseKeys.Drizzle,
      SkillDatabaseKeys.SqlAlchemy,
      SkillDatabaseKeys.TypeOrm,
      SkillDatabaseKeys.Hibernate,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.Testing]: {
    name: "Testing",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Jest,
      SkillDatabaseKeys.Vitest,
      SkillDatabaseKeys.PyTest,
      SkillDatabaseKeys.UnitTest,
      SkillDatabaseKeys.JUnit,
      SkillDatabaseKeys.Cypress,
      SkillDatabaseKeys.ReactTestingLibrary,
    ],
  },
  [SkillDatabaseKeys.Containerisation]: {
    name: "Containerization",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Docker,
      SkillDatabaseKeys.Podman,
      SkillDatabaseKeys.Kubernetes,
      SkillDatabaseKeys.Clusterisation,
      SkillDatabaseKeys.Azure_ContainerRegistry,
    ],
  },
  [SkillDatabaseKeys.Clusterisation]: {
    name: "Clusterisation",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Kubernetes,
      SkillDatabaseKeys.Azure_ContainerRegistry,
    ],
  },
  [SkillDatabaseKeys.InfrastructureAsCode]: {
    name: "Infrastructure as Code",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Ansible,
      SkillDatabaseKeys.Vagrant,
      SkillDatabaseKeys.Terraform,
    ],
  },
  [SkillDatabaseKeys.DatabaseManagementSystems]: {
    name: "Database Management Systems",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.Databases,
    ],
  },
  [SkillDatabaseKeys.DatabaseIndexing]: {
    name: "Indexing",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.PostgreSql,
      SkillDatabaseKeys.MySql,
      SkillDatabaseKeys.SqLite,
      SkillDatabaseKeys.MongoDb,
      SkillDatabaseKeys.Redis,
      SkillDatabaseKeys.Convex,
    ],
  },
  [SkillDatabaseKeys.CloudComputing]: {
    name: "Cloud Computing",
    category: SkillCategoriesEnum.CloudComputing,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Aws,
      SkillDatabaseKeys.Azure,
      SkillDatabaseKeys.Gcp,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.AwsK3s,
      SkillDatabaseKeys.AwsEc2,
      SkillDatabaseKeys.AwsS3,
      SkillDatabaseKeys.AwsVcp,
      SkillDatabaseKeys.AwsLambda,
      SkillDatabaseKeys.AwsCloudFormation,
      SkillDatabaseKeys.AwsCloudFront,
      SkillDatabaseKeys.AwsElasticBeanstalk,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.Azure_AppService,
      SkillDatabaseKeys.Azure_BlobStorage,
      SkillDatabaseKeys.Azure_DurableFunctions,
      SkillDatabaseKeys.Azure_Monitor,
      SkillDatabaseKeys.Azure_Functions,
      SkillDatabaseKeys.Azure_ResourceManager,
      SkillDatabaseKeys.Azure_ContainerRegistry,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.GcpAppEngine,
      SkillDatabaseKeys.GcpCloudSQL,
      SkillDatabaseKeys.GcpCloudStorage,
      SkillDatabaseKeys.GcpCloudTasks,
      SkillDatabaseKeys.GcpCloudScheduler,
      SkillDatabaseKeys.GcpLogging,
      SkillDatabaseKeys.Firebase,
    ],
  },
  [SkillDatabaseKeys.UserAuthentication]: {
    name: "User Authentication",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Firebase,
      SkillDatabaseKeys.Supabase,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.ClerkAuth,
      SkillDatabaseKeys.AuthJs,
    ],
  },
  [SkillDatabaseKeys.UserCentricDesign]: {
    name: "User Centric Design",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Rest,
      SkillDatabaseKeys.GraphQl,
      SkillDatabaseKeys.WebSockets,
      SkillDatabaseKeys.SocketIo,
      SkillDatabaseKeys.Pusher,
      SkillDatabaseKeys.Firebase,
      SkillDatabaseKeys.Supabase,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.ClerkAuth,
      SkillDatabaseKeys.AuthJs,
      SkillDatabaseKeys.Stripe,
      SkillDatabaseKeys.ExpressJs,
      SkillDatabaseKeys.Flask,
      SkillDatabaseKeys.Django,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Cloudinary,
      SkillDatabaseKeys.EdgeStore,
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.NextJs,
      SkillDatabaseKeys.ReactJs,
      SkillDatabaseKeys.Jotai,
      SkillDatabaseKeys.Zustand,
      SkillDatabaseKeys.TailwindCSS,
      SkillDatabaseKeys.Html,
      SkillDatabaseKeys.Css,
      SkillDatabaseKeys.ChakraUi,
      SkillDatabaseKeys.HeadlessUi,
      SkillDatabaseKeys.ShadcnUi,
      SkillDatabaseKeys.RadixUi,
      SkillDatabaseKeys.NextUi,
      SkillDatabaseKeys.StateManagement,
      SkillDatabaseKeys.Axios,
      SkillDatabaseKeys.StateManagement,
    ],
  },
  [SkillDatabaseKeys.Mathematics]: {
    name: "Mathematics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Probability,
      SkillDatabaseKeys.Statistics,
      SkillDatabaseKeys.Calculus,
      SkillDatabaseKeys.Trigonometry,
      SkillDatabaseKeys.Algebra,
      SkillDatabaseKeys.LinearAlgebra,
      SkillDatabaseKeys.Discrete,
      SkillDatabaseKeys.Geometry,
      SkillDatabaseKeys.Mechanics,
      SkillDatabaseKeys.Logics,
    ],
  },

  [SkillDatabaseKeys.StateManagement]: {
    name: "State Management",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Jotai, SkillDatabaseKeys.Zustand],
  },
};

export default skillDatabaseMap;

/**
 * List of keys for the skills that can be used to uniquely identify the skills.
 */
export const skillDatabaseKeys: SkillDatabaseKeys[] = Object.keys(
  skillDatabaseMap
) as SkillDatabaseKeys[];
