import SkillCategoriesEnum from "@/enums/Skill/SkillCategoriesEnum";
import SkillDatabaseKeys from "@/database/Skills/SkillDatabaseKeys";
import SkillTypesEnum from "@/enums/Skill/SkillTypesEnum";
import SkillInterface from "@/database/Skills/SkillInterface";

/**
 * Hashmap of skills with keys as {@link SkillDatabaseKeys} and values as {@link SkillInterface}.
 * The order of skills and sub-skills is the order that is used when displaying the skills on the website.
 */
const skillDatabaseMap: Database<SkillInterface> = {
  //^ Languages
  [SkillDatabaseKeys.Python]: {
    name: "Python",
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillDatabaseKeys.Flask,
      SkillDatabaseKeys.Django,
      SkillDatabaseKeys.SimpleGUI,
      SkillDatabaseKeys.SQLAlchemy,
      SkillDatabaseKeys.Symphony,
      SkillDatabaseKeys.PyTest,
      SkillDatabaseKeys.UnitTest,
      SkillDatabaseKeys.ScikitLearn,
      SkillDatabaseKeys.TensorFlow,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.Transformers,
      SkillDatabaseKeys.HuggingFace,
      SkillDatabaseKeys.LLMs,
      SkillDatabaseKeys.NaturalLanguageProcessing,
      SkillDatabaseKeys.FineTuning,
      SkillDatabaseKeys.Benchmarking,
      SkillDatabaseKeys.Quantization,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ReinforcementLearning,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },
  [SkillDatabaseKeys.JavaScript]: {
    name: "JavaScript",
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillDatabaseKeys.ClerkAuth,
      SkillDatabaseKeys.AuthJs,
      SkillDatabaseKeys.ExpressJS,
      SkillDatabaseKeys.NextJS,
      SkillDatabaseKeys.ReactJS,
      SkillDatabaseKeys.Mongoose,
      SkillDatabaseKeys.Jest,
      SkillDatabaseKeys.Vitest,
      SkillDatabaseKeys.Drizzle,
      SkillDatabaseKeys.Auth0,
    ],
  },
  [SkillDatabaseKeys.TypeScript]: {
    name: "TypeScript",
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillDatabaseKeys.ClerkAuth,
      SkillDatabaseKeys.AuthJs,
      SkillDatabaseKeys.ExpressJS,
      SkillDatabaseKeys.NextJS,
      SkillDatabaseKeys.ReactJS,
      SkillDatabaseKeys.ChakraUI,
      SkillDatabaseKeys.ShadcnUI,
      SkillDatabaseKeys.RadixUI,
      SkillDatabaseKeys.NextUI,
      SkillDatabaseKeys.Drizzle,
      SkillDatabaseKeys.TypeORM,
      SkillDatabaseKeys.Mongoose,
      SkillDatabaseKeys.Zustand,
      SkillDatabaseKeys.Recoil,
      SkillDatabaseKeys.Prisma,
      SkillDatabaseKeys.Jest,
      SkillDatabaseKeys.Vitest,
      SkillDatabaseKeys.Auth0,
    ],
  },
  [SkillDatabaseKeys.Java]: {
    name: "Java",
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Hibernate,
      SkillDatabaseKeys.SpringDataJPA,
      SkillDatabaseKeys.SpringDataMongoDB,
      SkillDatabaseKeys.SpringDataLDAP,
      SkillDatabaseKeys.SpringSecurity,
      SkillDatabaseKeys.Symphony,
      SkillDatabaseKeys.JUnit,
      SkillDatabaseKeys.Auth0,
    ],
  },
  [SkillDatabaseKeys.Kotlin]: {
    name: "Kotlin",
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Hibernate,
      SkillDatabaseKeys.SpringDataJPA,
      SkillDatabaseKeys.SpringDataMongoDB,
      SkillDatabaseKeys.SpringDataLDAP,
      SkillDatabaseKeys.SpringSecurity,
      SkillDatabaseKeys.Symphony,
      SkillDatabaseKeys.JUnit,
      SkillDatabaseKeys.TeamCity,
      SkillDatabaseKeys.Auth0,
    ],
  },
  [SkillDatabaseKeys.ShellScript]: {
    name: "Shell Script",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillDatabaseKeys.C]: {
    name: "C",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillDatabaseKeys.Haskell]: {
    name: "Haskell",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillDatabaseKeys.Scala]: {
    name: "Scala",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [SkillDatabaseKeys.ApacheSpark],
  },
  [SkillDatabaseKeys.Groovy]: {
    name: "Groovy",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [SkillDatabaseKeys.Jenkins],
  },
  [SkillDatabaseKeys.Matlab]: {
    name: "Matlab",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },

  //^ Artificial Intelligence, Machine Learning, and Data Science
  [SkillDatabaseKeys.ScikitLearn]: {
    name: "Scikit Learn",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },
  [SkillDatabaseKeys.PyTorch]: {
    name: "PyTorch",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Transformers,
      SkillDatabaseKeys.HuggingFace,
      SkillDatabaseKeys.LLMs,
      SkillDatabaseKeys.NaturalLanguageProcessing,
      SkillDatabaseKeys.FineTuning,
      SkillDatabaseKeys.Benchmarking,
      SkillDatabaseKeys.Quantization,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ReinforcementLearning,
      SkillDatabaseKeys.IntelligentAgents,
      SkillDatabaseKeys.DataScience,
    ],
  },
  [SkillDatabaseKeys.Keras]: {
    name: "Keras",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.TensorFlow,
      SkillDatabaseKeys.ReinforcementLearning,
    ],
  },
  [SkillDatabaseKeys.TensorFlow]: {
    name: "TensorFlow",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.ReinforcementLearning,
    ],
  },
  [SkillDatabaseKeys.Transformers]: {
    name: "Transformers",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.HuggingFace,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.LLMs,
      SkillDatabaseKeys.NaturalLanguageProcessing,
      SkillDatabaseKeys.FineTuning,
      SkillDatabaseKeys.Quantization,
      SkillDatabaseKeys.Benchmarking,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },
  [SkillDatabaseKeys.Pandas]: {
    name: "Pandas",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
    ],
  },
  [SkillDatabaseKeys.NumPy]: {
    name: "NumPy",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.Mathematics,
    ],
  },
  [SkillDatabaseKeys.Matplotlib]: {
    name: "Matplotlib",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
    ],
  },
  [SkillDatabaseKeys.Seaborn]: {
    name: "Seaborn",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
    ],
  },
  [SkillDatabaseKeys.HuggingFace]: {
    name: "Hugging Face",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Transformers,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.LLMs,
      SkillDatabaseKeys.NaturalLanguageProcessing,
      SkillDatabaseKeys.FineTuning,
      SkillDatabaseKeys.Quantization,
      SkillDatabaseKeys.Benchmarking,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },
  [SkillDatabaseKeys.ApacheSpark]: {
    name: "Apache Spark",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Scala,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.MLLib,
    ],
  },
  [SkillDatabaseKeys.MLLib]: {
    name: "MLLib",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ApacheSpark,
    ],
  },

  [SkillDatabaseKeys.ReinforcementLearning]: {
    name: "Reinforcement Learning",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.IntelligentAgents,
    ],
  },

  [SkillDatabaseKeys.IntelligentAgents]: {
    name: "Intelligent Agents",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.ReinforcementLearning,
    ],
  },
  [SkillDatabaseKeys.LLMs]: {
    name: "Large Language Models (LLMs)",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.Transformers,
      SkillDatabaseKeys.HuggingFace,
      SkillDatabaseKeys.NaturalLanguageProcessing,
      SkillDatabaseKeys.FineTuning,
      SkillDatabaseKeys.Quantization,
      SkillDatabaseKeys.Benchmarking,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },
  [SkillDatabaseKeys.NaturalLanguageProcessing]: {
    name: "Natural Language Processing (NLP)",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.Transformers,
      SkillDatabaseKeys.HuggingFace,
      SkillDatabaseKeys.LLMs,
      SkillDatabaseKeys.FineTuning,
      SkillDatabaseKeys.Quantization,
      SkillDatabaseKeys.Benchmarking,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },
  [SkillDatabaseKeys.FineTuning]: {
    name: "Fine-Tuning",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.Transformers,
      SkillDatabaseKeys.HuggingFace,
      SkillDatabaseKeys.LLMs,
      SkillDatabaseKeys.NaturalLanguageProcessing,
      SkillDatabaseKeys.Quantization,
      SkillDatabaseKeys.Benchmarking,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },
  [SkillDatabaseKeys.Benchmarking]: {
    name: "Benchmarking",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.Transformers,
      SkillDatabaseKeys.HuggingFace,
      SkillDatabaseKeys.LLMs,
      SkillDatabaseKeys.NaturalLanguageProcessing,
      SkillDatabaseKeys.FineTuning,
      SkillDatabaseKeys.Quantization,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },
  [SkillDatabaseKeys.Quantization]: {
    name: "Quantization",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.Transformers,
      SkillDatabaseKeys.HuggingFace,
      SkillDatabaseKeys.LLMs,
      SkillDatabaseKeys.NaturalLanguageProcessing,
      SkillDatabaseKeys.FineTuning,
      SkillDatabaseKeys.Benchmarking,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },

  //^ Full Stack Web Development
  [SkillDatabaseKeys.NextJS]: {
    name: "Next.js",
    category: SkillCategoriesEnum.FullStackWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.ChakraUI,
      SkillDatabaseKeys.ShadcnUI,
      SkillDatabaseKeys.RadixUI,
      SkillDatabaseKeys.NextUI,
      SkillDatabaseKeys.Drizzle,
      SkillDatabaseKeys.TypeORM,
      SkillDatabaseKeys.Mongoose,
      SkillDatabaseKeys.Zustand,
      SkillDatabaseKeys.Recoil,
      SkillDatabaseKeys.Prisma,
      SkillDatabaseKeys.Jest,
      SkillDatabaseKeys.Vitest,
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.ReactJS,
      SkillDatabaseKeys.AuthJs,
      SkillDatabaseKeys.Auth0,
    ],
  },

  //^ Backend Web Development
  [SkillDatabaseKeys.Firebase]: {
    name: "Firebase",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.GCP,
    ],
  },
  [SkillDatabaseKeys.Supabase]: {
    name: "Supabase",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.PostgreSQL,
    ],
  },
  [SkillDatabaseKeys.Auth0]: {
    name: "Auth0",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.Django,
      SkillDatabaseKeys.Flask,
      SkillDatabaseKeys.ExpressJS,
      SkillDatabaseKeys.NextJS,
      SkillDatabaseKeys.ReactJS,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
    ],
  },
  [SkillDatabaseKeys.ClerkAuth]: {
    name: "Clerk Auth",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.NextJS,
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.NextJS,
      SkillDatabaseKeys.ExpressJS,
      SkillDatabaseKeys.ReactJS,
    ],
  },
  [SkillDatabaseKeys.AuthJs]: {
    name: "Auth.JS",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.NextJS,
      SkillDatabaseKeys.ExpressJS,
      SkillDatabaseKeys.UserAuthentication,
    ],
  },
  [SkillDatabaseKeys.Stripe]: {
    name: "Stripe",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [],
  },
  [SkillDatabaseKeys.ExpressJS]: {
    name: "Express.JS",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.Mongoose,
      SkillDatabaseKeys.Drizzle,
    ],
  },
  [SkillDatabaseKeys.Flask]: {
    name: "Flask",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.SQLAlchemy,
    ],
  },
  [SkillDatabaseKeys.Django]: {
    name: "Django",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Python, SkillDatabaseKeys.Auth0],
  },
  [SkillDatabaseKeys.Spring]: {
    name: "Spring",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.SpringDataJPA,
      SkillDatabaseKeys.SpringDataMongoDB,
      SkillDatabaseKeys.Hibernate,
      SkillDatabaseKeys.Symphony,
      SkillDatabaseKeys.Auth0,
    ],
  },
  [SkillDatabaseKeys.SpringBoot]: {
    name: "Spring Boot",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringDataJPA,
      SkillDatabaseKeys.SpringDataMongoDB,
      SkillDatabaseKeys.SpringDataLDAP,
      SkillDatabaseKeys.Hibernate,
      SkillDatabaseKeys.Symphony,
      SkillDatabaseKeys.Auth0,
    ],
  },
  [SkillDatabaseKeys.SpringDataLDAP]: {
    name: "Spring Data LDAP",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Symphony,
    ],
  },
  [SkillDatabaseKeys.SpringSecurity]: {
    name: "Spring Security",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Symphony,
    ],
  },
  [SkillDatabaseKeys.Cloudinary]: {
    name: "Cloudinary",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Cloudinary],
  },
  [SkillDatabaseKeys.EdgeStore]: {
    name: "Edge Store",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [],
  },

  //^ Frontend Web Development
  [SkillDatabaseKeys.Recoil]: {
    name: "Recoil",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.StateManagement],
  },
  [SkillDatabaseKeys.Zustand]: {
    name: "Zustand",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.StateManagement],
  },
  [SkillDatabaseKeys.ReactJS]: {
    name: "React",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,

      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.Recoil,
      SkillDatabaseKeys.Zustand,
    ],
  },
  [SkillDatabaseKeys.HTML]: {
    name: "HTML",
    isMainSkill: true,
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.UserCentricDesign],
  },
  [SkillDatabaseKeys.CSS]: {
    name: "CSS",
    isMainSkill: true,
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.TailwindCSS,
    ],
  },
  [SkillDatabaseKeys.TailwindCSS]: {
    name: "Tailwind CSS",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CSS, SkillDatabaseKeys.UserCentricDesign],
  },
  [SkillDatabaseKeys.ChakraUI]: {
    name: "Chakra UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.UserCentricDesign],
  },

  [SkillDatabaseKeys.HeadlessUI]: {
    name: "Headless UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.ReactJS,
    ],
  },
  [SkillDatabaseKeys.ShadcnUI]: {
    name: "Shadcn UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.ReactJS,
    ],
  },
  [SkillDatabaseKeys.RadixUI]: {
    name: "Radix UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.ReactJS,
    ],
  },
  [SkillDatabaseKeys.NextUI]: {
    name: "Next UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.ReactJS,
    ],
  },
  [SkillDatabaseKeys.SimpleGUI]: {
    name: "Simple GUI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.UserCentricDesign],
  },
  [SkillDatabaseKeys.Axios]: {
    name: "Axios",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [],
  },

  //^ Databases
  [SkillDatabaseKeys.MongoDB]: {
    name: "MongoDB",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.Normalisation]: {
    name: "Normalisation",
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.Databases,
    ],
  },
  [SkillDatabaseKeys.PostgreSQL]: {
    name: "PostgreSQL",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.MySQL]: {
    name: "MySQL",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.SQLite]: {
    name: "SQLite",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.Redis]: {
    name: "Redis",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.Convex]: {
    name: "Convex",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },

  [SkillDatabaseKeys.Mongoose]: {
    name: "Mongoose ODM",
    isMainSkill: false,
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.MongoDB,
    ],
  },
  [SkillDatabaseKeys.Prisma]: {
    name: "Prisma ORM",
    isMainSkill: false,
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.MongoDB,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
    ],
  },
  [SkillDatabaseKeys.Drizzle]: {
    name: "Drizzle ORM",
    isMainSkill: false,
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.TypeORM,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
    ],
  },
  [SkillDatabaseKeys.TypeORM]: {
    name: "TypeORM",
    isMainSkill: false,
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
    ],
  },
  [SkillDatabaseKeys.SQLAlchemy]: {
    name: "SQLAlchemy",
    isMainSkill: false,
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
    ],
  },
  [SkillDatabaseKeys.Hibernate]: {
    name: "Hibernate",
    isMainSkill: false,
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
      SkillDatabaseKeys.SpringDataJPA,
    ],
  },
  [SkillDatabaseKeys.SpringDataJPA]: {
    name: "Spring Data JPA",
    isMainSkill: false,
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Hibernate,
    ],
  },
  [SkillDatabaseKeys.SpringDataMongoDB]: {
    name: "Spring Data MongoDB",
    isMainSkill: false,
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.MongoDB,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
    ],
  },

  //^ DevOps
  [SkillDatabaseKeys.GitHubActions]: {
    name: "GitHub Actions",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    isMainSkill: true,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.DevOps,
    ],
  },
  [SkillDatabaseKeys.GitLabCI]: {
    name: "GitLab CI",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.DevOps,
    ],
  },
  [SkillDatabaseKeys.Jenkins]: {
    name: "Jenkins",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    isMainSkill: true,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.DevOps,
      SkillDatabaseKeys.Groovy,
    ],
  },
  [SkillDatabaseKeys.TeamCity]: {
    name: "TeamCity",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    isMainSkill: true,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.DevOps,
    ],
  },
  [SkillDatabaseKeys.Docker]: {
    name: "Docker",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.DevOps,
    ],
  },
  [SkillDatabaseKeys.Podman]: {
    name: "Podman",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.DevOps,
    ],
  },
  [SkillDatabaseKeys.Kubernetes]: {
    name: "Kubernetes",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.DevOps,
      SkillDatabaseKeys.Clusterisation,
    ],
  },
  [SkillDatabaseKeys.Ansible]: {
    name: "Ansible",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.DevOps,
    ],
  },
  [SkillDatabaseKeys.Terraform]: {
    name: "Terraform",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.DevOps,
    ],
  },
  [SkillDatabaseKeys.Vagrant]: {
    name: "Vagrant",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.DevOps,
    ],
  },

  //^ APIs and Web Services
  [SkillDatabaseKeys.REST]: {
    name: "REST APIs",
    category: SkillCategoriesEnum.CommunicationProtocolsLibraries,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [],
  },
  [SkillDatabaseKeys.Apollo]: {
    name: "Apollo",
    category: SkillCategoriesEnum.CommunicationProtocolsLibraries,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [],
  },
  [SkillDatabaseKeys.GraphQL]: {
    name: "GraphQL APIs",
    isMainSkill: true,
    category: SkillCategoriesEnum.CommunicationProtocolsLibraries,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Apollo],
  },
  [SkillDatabaseKeys.SocketIO]: {
    name: "Socket.IO",
    category: SkillCategoriesEnum.CommunicationProtocolsLibraries,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.WebSockets],
  },
  [SkillDatabaseKeys.Pusher]: {
    name: "Pusher",
    category: SkillCategoriesEnum.CommunicationProtocolsLibraries,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.WebSockets],
  },

  //^ Testing
  [SkillDatabaseKeys.Jest]: {
    name: "Jest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.JavaScript, SkillDatabaseKeys.TypeScript],
  },
  [SkillDatabaseKeys.Vitest]: {
    name: "Vitest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.JavaScript, SkillDatabaseKeys.TypeScript],
  },
  [SkillDatabaseKeys.PyTest]: {
    name: "PyTest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Python],
  },
  [SkillDatabaseKeys.UnitTest]: {
    name: "UnitTest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Python],
  },
  [SkillDatabaseKeys.JUnit]: {
    name: "JUnit",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Java],
  },
  [SkillDatabaseKeys.Mockito]: {
    name: "Mockito",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.UnitTest,
      SkillDatabaseKeys.JUnit,
      SkillDatabaseKeys.PyTest,
      SkillDatabaseKeys.Jest,
      SkillDatabaseKeys.Vitest,
      SkillDatabaseKeys.Cypress,
      SkillDatabaseKeys.ReactTestingLibrary,
      SkillDatabaseKeys.Testing,
    ],
  },
  [SkillDatabaseKeys.Cypress]: {
    name: "Cypress",
    category: SkillCategoriesEnum.Testing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.JavaScript, SkillDatabaseKeys.TypeScript],
  },
  [SkillDatabaseKeys.ReactTestingLibrary]: {
    name: "React Testing Library",
    category: SkillCategoriesEnum.Testing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.ReactJS,
    ],
  },

  //^ Cloud Computing
  [SkillDatabaseKeys.AWS]: {
    name: "Amazon Web Services (AWS)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.AWS_K3s,
      SkillDatabaseKeys.AWS_EC2,
      SkillDatabaseKeys.AWS_S3,
      SkillDatabaseKeys.AWS_VPC,
      SkillDatabaseKeys.AWS_Lambda,
      SkillDatabaseKeys.AWS_CloudFormation,
      SkillDatabaseKeys.AWS_CloudFront,
      SkillDatabaseKeys.AWS_ElasticBeanstalk,
    ],
  },
  [SkillDatabaseKeys.AWS_K3s]: {
    name: "K3s",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.Clusterisation,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.AWS,
    ],
  },
  [SkillDatabaseKeys.AWS_CloudWatch]: {
    name: "CloudWatch",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_ApplicationLoadBalancer]: {
    name: "Application Load Balancer (ALB)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
  },
  [SkillDatabaseKeys.AWS_ElasticCache]: {
    name: "Elastic Cache (EC)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },

  [SkillDatabaseKeys.AWS_ElasticFileSystem]: {
    name: "Elastic File System (EFS)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_ElasticBlockStore]: {
    name: "Elastic Block Store (EBS)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_RelationalDatabaseService]: {
    name: "Relational Database Service (RDS)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.AWS,
    ],
  },
  [SkillDatabaseKeys.AWS_AutoScaling]: {
    name: "Auto Scaling",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_EC2]: {
    name: "Elastic Compute Cloud (EC2)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_S3]: {
    name: "Simple Storage Service (S3)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_VPC]: {
    name: "Virtual Private Cloud (VPC)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_Lambda]: {
    name: "Lambda",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_CloudFormation]: {
    name: "CloudFormation",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_CloudFront]: {
    name: "CloudFront",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_ElasticBeanstalk]: {
    name: "Elastic Beanstalk",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },

  [SkillDatabaseKeys.Azure]: {
    name: "Microsoft Azure",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.Azure_AppService,
      SkillDatabaseKeys.Azure_BlobStorage,
      SkillDatabaseKeys.Azure_DurableFunctions,
      SkillDatabaseKeys.Azure_Monitor,
      SkillDatabaseKeys.Azure_Functions,
      SkillDatabaseKeys.Azure_ResourceManager,
      SkillDatabaseKeys.Azure_ContainerRegistry,
    ],
  },
  [SkillDatabaseKeys.Azure_AppService]: {
    name: "Azure App Service",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_BlobStorage]: {
    name: "Azure Blob Storage",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_DurableFunctions]: {
    name: "Durable Functions",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_Monitor]: {
    name: "Azure Monitor",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_Functions]: {
    name: "Azure Functions",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_ResourceManager]: {
    name: "Azure Resource Manager",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_ContainerRegistry]: {
    name: "Azure Container Registry",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.Azure,
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.Clusterisation,
      SkillDatabaseKeys.Docker,
      SkillDatabaseKeys.Podman,
      SkillDatabaseKeys.Kubernetes,
    ],
  },

  [SkillDatabaseKeys.GCP]: {
    name: "Google Cloud Platform (GCP)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.GCP_AppEngine,
      SkillDatabaseKeys.GCP_CloudSQL,
      SkillDatabaseKeys.GCP_CloudStorage,
      SkillDatabaseKeys.GCP_CloudTasks,
      SkillDatabaseKeys.GCP_CloudScheduler,
      SkillDatabaseKeys.GCP_Logging,
      SkillDatabaseKeys.Firebase,
    ],
  },
  [SkillDatabaseKeys.GCP_AppEngine]: {
    name: "App Engine",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.GCP],
  },
  [SkillDatabaseKeys.GCP_CloudSQL]: {
    name: "Cloud SQL",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.GCP,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.GCP_CloudStorage]: {
    name: "Cloud Storage",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.GCP],
  },
  [SkillDatabaseKeys.GCP_CloudTasks]: {
    name: "Cloud Tasks",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.GCP],
  },
  [SkillDatabaseKeys.GCP_CloudScheduler]: {
    name: "Cloud Scheduler",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.GCP],
  },
  [SkillDatabaseKeys.GCP_Logging]: {
    name: "Cloud Logging",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.GCP],
  },

  //^ Mathematics
  [SkillDatabaseKeys.Probability]: {
    name: "Probability",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Mathematics,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
    ],
  },
  [SkillDatabaseKeys.Statistics]: {
    name: "Statistics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Mathematics,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
    ],
  },
  [SkillDatabaseKeys.Calculus]: {
    name: "Calculus",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Mathematics,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
    ],
  },
  [SkillDatabaseKeys.Trigonometry]: {
    name: "Trigonometry",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },
  [SkillDatabaseKeys.Algebra]: {
    name: "Algebra",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },
  [SkillDatabaseKeys.LinearAlgebra]: {
    name: "Linear Algebra",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Mathematics,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
    ],
  },
  [SkillDatabaseKeys.Discrete]: {
    name: "Discrete",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },
  [SkillDatabaseKeys.Geometry]: {
    name: "Geometry",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },
  [SkillDatabaseKeys.Logics]: {
    name: "Logics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },
  [SkillDatabaseKeys.Mechanics]: {
    name: "Mechanics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },

  //^ Communication
  [SkillDatabaseKeys.Symphony]: {
    name: "Symphony BDK",
    category: SkillCategoriesEnum.FullStackWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Python,
    ],
  },

  //^ General Technical Skills
  [SkillDatabaseKeys.ContinuousIntegration]: {
    name: "Continuous Integration",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.GitHubActions,
      SkillDatabaseKeys.GitLabCI,
      SkillDatabaseKeys.Jenkins,
      SkillDatabaseKeys.TeamCity,
    ],
  },

  [SkillDatabaseKeys.ContinuousDelivery]: {
    name: "Continuous Delivery",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.GitHubActions,
      SkillDatabaseKeys.GitLabCI,
      SkillDatabaseKeys.Jenkins,
      SkillDatabaseKeys.TeamCity,
    ],
  },

  [SkillDatabaseKeys.ContinuousDeployment]: {
    name: "Continuous Deployment",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.GitHubActions,
      SkillDatabaseKeys.GitLabCI,
      SkillDatabaseKeys.Jenkins,
      SkillDatabaseKeys.TeamCity,
    ],
  },

  [SkillDatabaseKeys.DevOps]: {
    name: "DevOps",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.GitHubActions,
      SkillDatabaseKeys.GitLabCI,
      SkillDatabaseKeys.Jenkins,
      SkillDatabaseKeys.TeamCity,
      SkillDatabaseKeys.Docker,
      SkillDatabaseKeys.Podman,
      SkillDatabaseKeys.Kubernetes,
      SkillDatabaseKeys.Ansible,
      SkillDatabaseKeys.Vagrant,
      SkillDatabaseKeys.Terraform,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.Clusterisation,
      SkillDatabaseKeys.InfrastructureAsCode,
    ],
  },

  [SkillDatabaseKeys.MachineLearning]: {
    name: "Machine Learning",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,

      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.TensorFlow,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.ScikitLearn,

      SkillDatabaseKeys.ComputerVision,
    ],
  },
  [SkillDatabaseKeys.DeepLearning]: {
    name: "Deep Learning",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,

      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.TensorFlow,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.ScikitLearn,

      SkillDatabaseKeys.ComputerVision,
    ],
  },
  [SkillDatabaseKeys.ArtificialIntelligence]: {
    name: "Artificial Intelligence",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technical,
    isMainSkill: true,
    relatedSkills: [
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,

      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.ScikitLearn,

      SkillDatabaseKeys.ComputerVision,
    ],
  },
  [SkillDatabaseKeys.DataScience]: {
    name: "Data Science",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
    ],
  },
  [SkillDatabaseKeys.DataVisualisation]: {
    name: "Data Visualisation",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
    ],
  },
  [SkillDatabaseKeys.NeuralNetworks]: {
    name: "Neural Networks",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.ScikitLearn,
    ],
  },
  [SkillDatabaseKeys.ComputerVision]: {
    name: "Computer Vision",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.ScikitLearn,
    ],
  },
  [SkillDatabaseKeys.Databases]: {
    name: "Databases",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
      SkillDatabaseKeys.MongoDB,
      SkillDatabaseKeys.Redis,
      SkillDatabaseKeys.Convex,
    ],
  },
  [SkillDatabaseKeys.WebSockets]: {
    name: "Web Sockets",
    category: SkillCategoriesEnum.CommunicationProtocolsLibraries,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.SocketIO, SkillDatabaseKeys.Pusher],
  },
  [SkillDatabaseKeys.RelationalDatabases]: {
    name: "Relational Databases (SQL)",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
    ],
  },

  [SkillDatabaseKeys.NonRelationalDatabases]: {
    name: "Non Relational Databases (NoSQL)",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.MongoDB,
      SkillDatabaseKeys.Redis,
      SkillDatabaseKeys.Convex,
    ],
  },
  [SkillDatabaseKeys.ObjectRelationalMapping]: {
    name: "Object Relational Mapping",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Mongoose,
      SkillDatabaseKeys.Prisma,
      SkillDatabaseKeys.Drizzle,
      SkillDatabaseKeys.SQLAlchemy,
      SkillDatabaseKeys.TypeORM,
      SkillDatabaseKeys.Hibernate,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.Testing]: {
    name: "Testing",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Jest,
      SkillDatabaseKeys.Vitest,
      SkillDatabaseKeys.PyTest,
      SkillDatabaseKeys.UnitTest,
      SkillDatabaseKeys.JUnit,
      SkillDatabaseKeys.Cypress,
      SkillDatabaseKeys.ReactTestingLibrary,
    ],
  },
  [SkillDatabaseKeys.Containerisation]: {
    name: "Containerization",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Docker,
      SkillDatabaseKeys.Podman,
      SkillDatabaseKeys.Kubernetes,
      SkillDatabaseKeys.Clusterisation,
      SkillDatabaseKeys.Azure_ContainerRegistry,
    ],
  },
  [SkillDatabaseKeys.Clusterisation]: {
    name: "Clusterisation",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Kubernetes,
      SkillDatabaseKeys.Azure_ContainerRegistry,
    ],
  },
  [SkillDatabaseKeys.InfrastructureAsCode]: {
    name: "Infrastructure as Code",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Ansible,
      SkillDatabaseKeys.Vagrant,
      SkillDatabaseKeys.Terraform,
    ],
  },
  [SkillDatabaseKeys.DatabaseManagementSystems]: {
    name: "Database Management Systems",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.Databases,
    ],
  },
  [SkillDatabaseKeys.DatabaseIndexing]: {
    name: "Indexing",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
      SkillDatabaseKeys.MongoDB,
      SkillDatabaseKeys.Redis,
      SkillDatabaseKeys.Convex,
    ],
  },
  [SkillDatabaseKeys.CloudComputing]: {
    name: "Cloud Computing",
    category: SkillCategoriesEnum.CloudComputing,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.AWS,
      SkillDatabaseKeys.Azure,
      SkillDatabaseKeys.GCP,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.AWS_K3s,
      SkillDatabaseKeys.AWS_EC2,
      SkillDatabaseKeys.AWS_S3,
      SkillDatabaseKeys.AWS_VPC,
      SkillDatabaseKeys.AWS_Lambda,
      SkillDatabaseKeys.AWS_CloudFormation,
      SkillDatabaseKeys.AWS_CloudFront,
      SkillDatabaseKeys.AWS_ElasticBeanstalk,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.Azure_AppService,
      SkillDatabaseKeys.Azure_BlobStorage,
      SkillDatabaseKeys.Azure_DurableFunctions,
      SkillDatabaseKeys.Azure_Monitor,
      SkillDatabaseKeys.Azure_Functions,
      SkillDatabaseKeys.Azure_ResourceManager,
      SkillDatabaseKeys.Azure_ContainerRegistry,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.GCP_AppEngine,
      SkillDatabaseKeys.GCP_CloudSQL,
      SkillDatabaseKeys.GCP_CloudStorage,
      SkillDatabaseKeys.GCP_CloudTasks,
      SkillDatabaseKeys.GCP_CloudScheduler,
      SkillDatabaseKeys.GCP_Logging,
      SkillDatabaseKeys.Firebase,
    ],
  },
  [SkillDatabaseKeys.UserAuthentication]: {
    name: "User Authentication",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Firebase,
      SkillDatabaseKeys.Supabase,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.ClerkAuth,
      SkillDatabaseKeys.AuthJs,
    ],
  },
  [SkillDatabaseKeys.UserCentricDesign]: {
    name: "User Centric Design",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.REST,
      SkillDatabaseKeys.GraphQL,
      SkillDatabaseKeys.WebSockets,
      SkillDatabaseKeys.SocketIO,
      SkillDatabaseKeys.Pusher,
      SkillDatabaseKeys.Firebase,
      SkillDatabaseKeys.Supabase,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.ClerkAuth,
      SkillDatabaseKeys.AuthJs,
      SkillDatabaseKeys.Stripe,
      SkillDatabaseKeys.ExpressJS,
      SkillDatabaseKeys.Flask,
      SkillDatabaseKeys.Django,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Cloudinary,
      SkillDatabaseKeys.EdgeStore,
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.NextJS,
      SkillDatabaseKeys.ReactJS,
      SkillDatabaseKeys.Recoil,
      SkillDatabaseKeys.Zustand,
      SkillDatabaseKeys.TailwindCSS,
      SkillDatabaseKeys.HTML,
      SkillDatabaseKeys.CSS,
      SkillDatabaseKeys.ChakraUI,
      SkillDatabaseKeys.HeadlessUI,
      SkillDatabaseKeys.ShadcnUI,
      SkillDatabaseKeys.RadixUI,
      SkillDatabaseKeys.NextUI,
      SkillDatabaseKeys.StateManagement,
      SkillDatabaseKeys.Axios,
      SkillDatabaseKeys.StateManagement,
    ],
  },
  [SkillDatabaseKeys.Mathematics]: {
    name: "Mathematics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Probability,
      SkillDatabaseKeys.Statistics,
      SkillDatabaseKeys.Calculus,
      SkillDatabaseKeys.Trigonometry,
      SkillDatabaseKeys.Algebra,
      SkillDatabaseKeys.LinearAlgebra,
      SkillDatabaseKeys.Discrete,
      SkillDatabaseKeys.Geometry,
      SkillDatabaseKeys.Mechanics,
      SkillDatabaseKeys.Logics,
    ],
  },

  [SkillDatabaseKeys.StateManagement]: {
    name: "State Management",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Recoil, SkillDatabaseKeys.Zustand],
  },

  //^ Soft Skills
  [SkillDatabaseKeys.Communication]: {
    name: "Communication",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.ProjectManagement]: {
    name: "Project Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.Teamwork]: {
    name: "Teamwork",
    isMainSkill: true,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.Leadership]: {
    name: "Leadership",
    isMainSkill: true,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.ProblemSolving]: {
    name: "Problem Solving",
    isMainSkill: true,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.CriticalThinking]: {
    name: "Critical Thinking",
    isMainSkill: true,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.Creativity]: {
    name: "Creativity",
    isMainSkill: true,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.Adaptability]: {
    name: "Adaptability",
    isMainSkill: true,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.TimeManagement]: {
    name: "Time Management",
    isMainSkill: true,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.RiskManagement]: {
    name: "Risk Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.StakeholderManagement]: {
    name: "Stakeholder Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.ScopeManagement]: {
    name: "Scope Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.CostManagement]: {
    name: "Cost Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.QualityManagement]: {
    name: "Quality Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.ProcurementManagement]: {
    name: "Procurement Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.IntegrationManagement]: {
    name: "Integration Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.HumanResourceManagement]: {
    name: "Human Resource Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
};

export default skillDatabaseMap;

/**
 * List of keys for the skills that can be used to uniquely identify the skills.
 */
export const skillDatabaseKeys: SkillDatabaseKeys[] = Object.keys(
  skillDatabaseMap
) as SkillDatabaseKeys[];
