/**
 * This enum is used to represent the keys of the skills in the database.
 * This enum is used to avoid hardcoding the keys in the code, getting autocompletion support and avoiding typos.
 * These keys are used within MaterialInterface and its children to represents skills associated with the material.
 * The order of the skills is the order that is used when displaying the skills on the website.
 *
 * @see {@link skillDatabaseMap} at `interfaces/skills.ts`
 */
enum SkillDatabaseKeys {
  //^ Languages
  Python = "python",
  JavaScript = "javascript",
  TypeScript = "typescript",
  Java = "java",
  ShellScript = "shell",
  C = "c",
  Haskell = "haskell",
  Scala = "scala",
  Groovy = "groovy",
  Kotlin = "kotlin",
  Matlab = "matlab",

  //^ Artificial Intelligence, Machine Learning, and Data Science
  ScikitLearn = "scikit-learn",
  Pandas = "pandas",
  NumPy = "numpy",
  Matplotlib = "matplotlib",
  Seaborn = "seaborn",
  Keras = "keras",
  TensorFlow = "tensorflow",
  PyTorch = "pytorch",
  Transformers = "transformers",
  HuggingFace = "hugging-face",
  LargeLanguageModels = "large-language-models",
  ApacheSpark = "apache-spark",
  MlLib = "ml-lib",
  MachineLearning = "machine-learning",
  DeepLearning = "deep-learning",
  ArtificialIntelligence = "artificial-intelligence",
  ReinforcementLearning = "reinforcement-learning",
  IntelligentAgents = "intelligent-agents",
  DataScience = "data-science",
  DataVisualisation = "data-visualisation",
  NeuralNetworks = "neural-networks",
  ComputerVision = "computer-vision",
  NaturalLanguageProcessing = "natural-language-processing",
  FineTuning = "fine-tuning",
  Benchmarking = "benchmarking",
  Quantization = "quantization",
  ModelContextProtocol = "model-context-protocol",

  //^ Full Stack Web Development
  NextJs = "next-js",

  //^ Backend Web Development
  Firebase = "firebase",
  Firestore = "firestore",
  Supabase = "supabase",
  Auth0 = "auth0",
  ClerkAuth = "clerk-auth",
  AuthJs = "auth-js",
  BetterAuth = "better-auth",
  Stripe = "stripe",
  ExpressJs = "express-js",
  Flask = "flask",
  Django = "django",
  Spring = "spring",
  SpringBoot = "spring-boot",
  SpringDataLdap = "spring-data-ldap",
  SpringSecurity = "spring-security",
  SpringOAuth = "spring-oauth",
  Cloudinary = "cloudinary",
  EdgeStore = "edge-store",
  WebSockets = "web-sockets",
  UserAuthentication = "user-authentication",

  //^ Frontend Web Development
  ReactJs = "react",
  Jotai = "jotai",
  Zustand = "zustand",
  Zod = "zod",
  TailwindCSS = "tailwind-css",
  Html = "html",
  Css = "css",
  ChakraUi = "chakra-ui",
  HeadlessUi = "headless-ui",
  ShadcnUi = "shadcn-ui",
  RadixUi = "radix-ui",
  NextUi = "next-ui",
  SimpleGui = "simple-gui",
  Axios = "axios",
  UserCentricDesign = "user-centric-design",
  StateManagement = "state-management",

  //^ Database
  Normalisation = "normalisation",
  PostgreSql = "postgresql",
  MySql = "mysql",
  SqLite = "sqlite",
  MongoDb = "mongodb",
  Redis = "redis",
  Convex = "convex",
  Databases = "databases",
  RelationalDatabases = "relational-databases",
  NonRelationalDatabases = "non-relational-databases",
  DatabaseManagementSystems = "database-management-systems",
  DatabaseIndexing = "indexing",

  //^ Object-Relational Mappers
  Mongoose = "moongose",
  Prisma = "prisma",
  Drizzle = "drizzle",
  SqlAlchemy = "sqlalchemy",
  TypeOrm = "typeorm",
  Hibernate = "hibernate",
  SpringDataJpa = "spring-data-jpa",
  SpringDataMongoDb = "spring-data-mongodb",
  ObjectRelationalMapping = "object-relational-mapping",

  //^ DevOps
  GitHubActions = "github-actions",
  GitLabCi = "gitlab-ci",
  Jenkins = "jenkins",
  TeamCity = "team-city",
  Docker = "docker",
  Podman = "podman",
  Kubernetes = "kubernetes",
  Ansible = "ansible",
  Vagrant = "vagrant",
  Terraform = "terraform",
  ContinuousIntegration = "continuous-integration",
  ContinuousDeployment = "continuous-deployment",
  ContinuousDelivery = "continuous-delivery",
  DevOps = "dev-ops",
  Containerisation = "containerisation",
  InfrastructureAsCode = "infrastructure-as-code",
  Clusterisation = "clusterisation",

  //^ APIs
  Rest = "rest-api",
  Apollo = "apollo",
  GraphQl = "graphql-api",
  SocketIo = "socket-io",
  Pusher = "pusher",

  //^ Testing
  Jest = "jest",
  Vitest = "vitest",
  PyTest = "pytest",
  UnitTest = "unittest",
  JUnit = "junit",
  Mockito = "mockito",
  Cypress = "cypress",
  ReactTestingLibrary = "react-testing-library",
  Testing = "testing",

  //^ Mathematics
  Probability = "probability",
  Statistics = "statistics",
  Calculus = "calculus",
  Trigonometry = "trigonometry",
  Algebra = "algebra",
  LinearAlgebra = "linear-algebra",
  Discrete = "discrete",
  Geometry = "geometry",
  Mechanics = "mechanics",
  Logics = "logics",
  Mathematics = "mathematics",

  //^ Cloud Computing
  Aws = "aws",
  AwsCloudWatch = "aws-cloudwatch",
  AwsApplicationLoadBalancer = "aws-application-load-balancer",
  AwsElasticCache = "aws-elastic-cache",
  AwsK3s = "aws-k3s",
  AwsEc2 = "aws-ec2",
  AwsS3 = "aws-s3",
  AwsVcp = "aws-vpc",
  AwsLambda = "aws-lambda",
  AwsElasticFileSystem = "aws-elastic-filesystem",
  AwsElasticBlockStore = "aws-elastic-block-store",
  AwsRelationalDatabaseService = "aws-relational-database-service",
  AwsAutoScaling = "aws-auto-scaling",
  AwsCloudFormation = "aws-cloudformation",
  AwsCloudFront = "aws-cloudfront",
  AwsElasticBeanstalk = "aws-elastic-beanstalk",
  Azure = "azure",
  Azure_AppService = "azure-app-service",
  Azure_Monitor = "azure-monitor",
  Azure_BlobStorage = "azure-blob-storage",
  Azure_DurableFunctions = "azure-durable-functions",
  Azure_Functions = "azure-functions",
  Azure_ResourceManager = "azure-resource-manager",
  Azure_ContainerRegistry = "azure-container-registry",
  Gcp = "gcp",
  GcpAppEngine = "gcp-app-engine",
  GcpCloudSQL = "gcp-cloud-sql",
  GcpCloudStorage = "gcp-cloud-storage",
  GcpCloudTasks = "gcp-cloud-tasks",
  GcpCloudScheduler = "gcp-cloud-scheduler",
  GcpLogging = "gcp-logging",
  CloudComputing = "cloud-computing",

  //^ Others
  Symphony = "symphony",
}

export default SkillDatabaseKeys;
