import SkillCategoriesEnum from "@/enums/Skill/SkillCategoriesEnum";
import SkillDatabaseKeys from "@/database/Skills/SkillDatabaseKeys";
import SkillTypesEnum from "@/enums/Skill/SkillTypesEnum";
import SkillInterface from "@/database/Skills/SkillInterface";

/**
 * Hashmap of skills with keys as {@link SkillDatabaseKeys} and values as {@link SkillInterface}.
 * The order of skills and sub-skills is the order that is used when displaying the skills on the website.
 */
const skillDatabaseMap: Database<SkillInterface> = {
  //^ Languages
  [SkillDatabaseKeys.Python]: {
    name: "Python",
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillDatabaseKeys.Flask,
      SkillDatabaseKeys.Django,
      SkillDatabaseKeys.Gunicorn,
      SkillDatabaseKeys.Jinja,
      SkillDatabaseKeys.SimpleGUI,
      SkillDatabaseKeys.SQLAlchemy,
      SkillDatabaseKeys.Symphony,
      SkillDatabaseKeys.Black,
      SkillDatabaseKeys.PyLint,
      SkillDatabaseKeys.PyTest,
      SkillDatabaseKeys.UnitTest,
      SkillDatabaseKeys.Poetry,
      SkillDatabaseKeys.Pip,
      SkillDatabaseKeys.PyBuilder,
      SkillDatabaseKeys.ScikitLearn,
      SkillDatabaseKeys.TensorFlow,
      SkillDatabaseKeys.PyTorch,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.Jupyter,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.Hyperparameters,
      SkillDatabaseKeys.Boosting,
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.WebDevelopment,
    ],
  },
  [SkillDatabaseKeys.JavaScript]: {
    name: "JavaScript",
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillDatabaseKeys.ClerkAuth,
      SkillDatabaseKeys.NextAuth,
      SkillDatabaseKeys.ExpressJS,
      SkillDatabaseKeys.NextJS,
      SkillDatabaseKeys.SvelteKit,
      SkillDatabaseKeys.AngularJS,
      SkillDatabaseKeys.NuxtJS,
      SkillDatabaseKeys.ReactJS,
      SkillDatabaseKeys.SvelteJS,
      SkillDatabaseKeys.VueJS,
      SkillDatabaseKeys.Recoil,
      SkillDatabaseKeys.Redux,
      SkillDatabaseKeys.Mongoose,
      SkillDatabaseKeys.Prettier,
      SkillDatabaseKeys.ESLint,
      SkillDatabaseKeys.Jest,
      SkillDatabaseKeys.Vitest,
      SkillDatabaseKeys.NPM,
      SkillDatabaseKeys.Yarn,
      SkillDatabaseKeys.PNPM,
      SkillDatabaseKeys.NxJS,
    ],
  },
  [SkillDatabaseKeys.TypeScript]: {
    name: "TypeScript",
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillDatabaseKeys.ClerkAuth,
      SkillDatabaseKeys.NextAuth,
      SkillDatabaseKeys.ExpressJS,
      SkillDatabaseKeys.NextJS,
      SkillDatabaseKeys.SvelteKit,
      SkillDatabaseKeys.AngularJS,
      SkillDatabaseKeys.NuxtJS,
      SkillDatabaseKeys.ReactJS,
      SkillDatabaseKeys.SvelteJS,
      SkillDatabaseKeys.VueJS,
      SkillDatabaseKeys.Recoil,
      SkillDatabaseKeys.Redux,
      SkillDatabaseKeys.Mongoose,
      SkillDatabaseKeys.Prettier,
      SkillDatabaseKeys.ESLint,
      SkillDatabaseKeys.Jest,
      SkillDatabaseKeys.Vitest,
      SkillDatabaseKeys.NPM,
      SkillDatabaseKeys.Yarn,
      SkillDatabaseKeys.PNPM,
      SkillDatabaseKeys.NxJS,
      SkillDatabaseKeys.TypeORM,
      SkillDatabaseKeys.Zod,
    ],
  },
  [SkillDatabaseKeys.Java]: {
    name: "Java",
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Hibernate,
      SkillDatabaseKeys.SpringDataJPA,
      SkillDatabaseKeys.SpringDataMongoDB,
      SkillDatabaseKeys.Symphony,
      SkillDatabaseKeys.Checkstyle,
      SkillDatabaseKeys.JUnit,
      SkillDatabaseKeys.Gradle,
      SkillDatabaseKeys.Maven,
      SkillDatabaseKeys.AndroidDevelopment,
    ],
  },
  [SkillDatabaseKeys.Kotlin]: {
    name: "Kotlin",
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillDatabaseKeys.JUnit,
      SkillDatabaseKeys.Gradle,
      SkillDatabaseKeys.TeamCity,
      SkillDatabaseKeys.AndroidDevelopment,
    ],
  },
  [SkillDatabaseKeys.ShellScript]: {
    name: "Shell Script",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillDatabaseKeys.C]: {
    name: "C",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillDatabaseKeys.Haskell]: {
    name: "Haskell",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillDatabaseKeys.Scala]: {
    name: "Scala",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [SkillDatabaseKeys.ApacheSpark],
  },
  [SkillDatabaseKeys.RLanguage]: {
    name: "R",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillDatabaseKeys.Groovy]: {
    name: "Groovy",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [SkillDatabaseKeys.Gradle, SkillDatabaseKeys.Jenkins],
  },
  [SkillDatabaseKeys.Matlab]: {
    name: "Matlab",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },

  //^ Full Stack Web Development
  [SkillDatabaseKeys.NextJS]: {
    name: "Next.js",
    category: SkillCategoriesEnum.FullStackWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.ReactJS,
      SkillDatabaseKeys.NextAuth,
    ],
  },

  [SkillDatabaseKeys.AngularJS]: {
    name: "Angular",
    category: SkillCategoriesEnum.FullStackWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
    ],
  },
  [SkillDatabaseKeys.NuxtJS]: {
    name: "Nuxt.js",
    category: SkillCategoriesEnum.FullStackWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.VueJS,
    ],
  },
  [SkillDatabaseKeys.SvelteKit]: {
    name: "SvelteKit",
    category: SkillCategoriesEnum.FullStackWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.SvelteJS,
    ],
  },

  //^ Frontend Web Development
  [SkillDatabaseKeys.Recoil]: {
    name: "Recoil",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.StateManagement,
    ],
  },
  [SkillDatabaseKeys.Zustand]: {
    name: "Zustand",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.StateManagement,
    ],
  },
  [SkillDatabaseKeys.Jotai]: {
    name: "Jotai",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.StateManagement,
    ],
  },

  [SkillDatabaseKeys.Redux]: {
    name: "Redux",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.StateManagement,
    ],
  },
  [SkillDatabaseKeys.ReactJS]: {
    name: "React",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.Recoil,
      SkillDatabaseKeys.Zustand,
      SkillDatabaseKeys.Jotai,
      SkillDatabaseKeys.Redux,
    ],
  },
  [SkillDatabaseKeys.HTML]: {
    name: "HTML",
    isMainSkill: true,
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
    ],
  },
  [SkillDatabaseKeys.CSS]: {
    name: "CSS",
    isMainSkill: true,
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.TailwindCSS,
    ],
  },
  [SkillDatabaseKeys.TailwindCSS]: {
    name: "Tailwind CSS",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.CSS,
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
    ],
  },
  [SkillDatabaseKeys.SvelteJS]: {
    name: "Svelte",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
    ],
  },

  [SkillDatabaseKeys.VueJS]: {
    name: "Vue",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserAuthentication,
    ],
  },
  [SkillDatabaseKeys.ChakraUI]: {
    name: "Chakra UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
    ],
  },

  [SkillDatabaseKeys.HeadlessUI]: {
    name: "Headless UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.ReactJS,
      SkillDatabaseKeys.VueJS,
    ],
  },
  [SkillDatabaseKeys.ShadcnUI]: {
    name: "Shadcn UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.ReactJS,
    ],
  },
  [SkillDatabaseKeys.RadixUI]: {
    name: "Radix UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.ReactJS,
    ],
  },

  [SkillDatabaseKeys.ReactQuery]: {
    name: "React Query",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.ReactJS,
    ],
  },
  [SkillDatabaseKeys.NextUI]: {
    name: "Next UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.ReactJS,
    ],
  },
  [SkillDatabaseKeys.Bootstrap]: {
    name: "Bootstrap",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
    ],
  },
  [SkillDatabaseKeys.MaterialUI]: {
    name: "Material UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
    ],
  },
  [SkillDatabaseKeys.SemanticUI]: {
    name: "Semantic UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
    ],
  },
  [SkillDatabaseKeys.AntDesign]: {
    name: "Ant Design",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
    ],
  },
  [SkillDatabaseKeys.StoryBooks]: {
    name: "Storybooks",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.UserCentricDesign,
    ],
  },
  [SkillDatabaseKeys.SimpleGUI]: {
    name: "Simple GUI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.UserCentricDesign],
  },
  [SkillDatabaseKeys.Axios]: {
    name: "Axios",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.WebDevelopment, SkillDatabaseKeys.APIs],
  },

  //^ Backend Web Development
  [SkillDatabaseKeys.Firebase]: {
    name: "Firebase",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.SDKs,
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.GCP,
      SkillDatabaseKeys.Security,
      SkillDatabaseKeys.CyberSecurity,
    ],
  },
  [SkillDatabaseKeys.Supabase]: {
    name: "Supabase",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.SDKs,
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.Security,
      SkillDatabaseKeys.CyberSecurity,
    ],
  },
  [SkillDatabaseKeys.PocketBase]: {
    name: "PocketBase",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.SDKs,
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.Security,
      SkillDatabaseKeys.CyberSecurity,
    ],
  },
  [SkillDatabaseKeys.Auth0]: {
    name: "Auth0",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.SDKs,
      SkillDatabaseKeys.Security,
      SkillDatabaseKeys.CyberSecurity,
    ],
  },
  [SkillDatabaseKeys.ClerkAuth]: {
    name: "Clerk Auth",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.SDKs,
      SkillDatabaseKeys.Security,
      SkillDatabaseKeys.CyberSecurity,
    ],
  },
  [SkillDatabaseKeys.NextAuth]: {
    name: "NextAuth",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.Security,
      SkillDatabaseKeys.CyberSecurity,
    ],
  },
  [SkillDatabaseKeys.Stripe]: {
    name: "Stripe",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.SDKs,
      SkillDatabaseKeys.Security,
      SkillDatabaseKeys.CyberSecurity,
    ],
  },
  [SkillDatabaseKeys.ExpressJS]: {
    name: "Express",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.APIs,
      SkillDatabaseKeys.Security,
      SkillDatabaseKeys.CyberSecurity,
    ],
  },
  [SkillDatabaseKeys.Flask]: {
    name: "Flask",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.APIs,
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Security,
      SkillDatabaseKeys.CyberSecurity,
    ],
  },
  [SkillDatabaseKeys.Django]: {
    name: "Django",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.APIs,
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Security,
      SkillDatabaseKeys.CyberSecurity,
    ],
  },
  [SkillDatabaseKeys.Spring]: {
    name: "Spring",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.SpringDataJPA,
      SkillDatabaseKeys.SpringDataMongoDB,
      SkillDatabaseKeys.Hibernate,
      SkillDatabaseKeys.Symphony,
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.APIs,
      SkillDatabaseKeys.Security,
      SkillDatabaseKeys.CyberSecurity,
    ],
  },
  [SkillDatabaseKeys.SpringBoot]: {
    name: "Spring Boot",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringDataJPA,
      SkillDatabaseKeys.SpringDataMongoDB,
      SkillDatabaseKeys.Hibernate,
      SkillDatabaseKeys.Symphony,
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.APIs,
      SkillDatabaseKeys.Security,
      SkillDatabaseKeys.CyberSecurity,
    ],
  },
  [SkillDatabaseKeys.Cloudinary]: {
    name: "Cloudinary",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Cloudinary],
  },
  [SkillDatabaseKeys.EdgeStore]: {
    name: "Edge Store",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.WebDevelopment],
  },
  [SkillDatabaseKeys.Gunicorn]: {
    name: "Gunicorn",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Python, SkillDatabaseKeys.WebDevelopment],
  },
  [SkillDatabaseKeys.Jinja]: {
    name: "Jinja",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Python, SkillDatabaseKeys.WebDevelopment],
  },

  //^ Databases
  [SkillDatabaseKeys.Normalisation]: {
    name: "Normalisation",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.Databases,
    ],
  },
  [SkillDatabaseKeys.PostgreSQL]: {
    name: "PostgreSQL",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.MySQL]: {
    name: "MySQL",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.SQLite]: {
    name: "SQLite",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.MongoDB]: {
    name: "MongoDB",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.Redis]: {
    name: "Redis",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.Convex]: {
    name: "Convex",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },

  [SkillDatabaseKeys.Mongoose]: {
    name: "Mongoose",
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.MongoDB,
    ],
  },
  [SkillDatabaseKeys.Prisma]: {
    name: "Prisma",
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectOrientedProgramming,
      SkillDatabaseKeys.MongoDB,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
    ],
  },
  [SkillDatabaseKeys.Drizzle]: {
    name: "Drizzle",
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.TypeORM,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
    ],
  },
  [SkillDatabaseKeys.TypeORM]: {
    name: "TypeORM",
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
    ],
  },
  [SkillDatabaseKeys.SQLAlchemy]: {
    name: "SQLAlchemy",
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
    ],
  },
  [SkillDatabaseKeys.Hibernate]: {
    name: "Hibernate",
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
      SkillDatabaseKeys.SpringDataJPA,
    ],
  },
  [SkillDatabaseKeys.SpringDataJPA]: {
    name: "Spring Data JPA",
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    isMainSkill: true,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Hibernate,
    ],
  },
  [SkillDatabaseKeys.SpringDataMongoDB]: {
    name: "Spring Data MongoDB",
    category: SkillCategoriesEnum.DatabaseManagement,
    skillType: SkillTypesEnum.Technology,
    isMainSkill: true,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.MongoDB,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
    ],
  },

  //^ DevOps
  [SkillDatabaseKeys.GitHubActions]: {
    name: "GitHub Actions",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    isMainSkill: true,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.DevOps,
      SkillDatabaseKeys.Automation,
      SkillDatabaseKeys.GitHub,
    ],
  },
  [SkillDatabaseKeys.GitLabCI]: {
    name: "GitLab CI",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.DevOps,
      SkillDatabaseKeys.Automation,
      SkillDatabaseKeys.GitLab,
    ],
  },
  [SkillDatabaseKeys.Jenkins]: {
    name: "Jenkins",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    isMainSkill: true,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.DevOps,
      SkillDatabaseKeys.Automation,
      SkillDatabaseKeys.Groovy,
    ],
  },
  [SkillDatabaseKeys.TeamCity]: {
    name: "TeamCity",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    isMainSkill: true,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.DevOps,
      SkillDatabaseKeys.Automation,
    ],
  },
  [SkillDatabaseKeys.Docker]: {
    name: "Docker",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.DevOps,
    ],
  },
  [SkillDatabaseKeys.Podman]: {
    name: "Podman",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.DevOps,
    ],
  },
  [SkillDatabaseKeys.Kubernetes]: {
    name: "Kubernetes",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.DevOps,
      SkillDatabaseKeys.Clusterisation,
    ],
  },
  [SkillDatabaseKeys.Ansible]: {
    name: "Ansible",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.DevOps,
      SkillDatabaseKeys.Automation,
    ],
  },
  [SkillDatabaseKeys.Terraform]: {
    name: "Terraform",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.DevOps,
      SkillDatabaseKeys.Automation,
    ],
  },
  [SkillDatabaseKeys.Vagrant]: {
    name: "Vagrant",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.DevOps,
      SkillDatabaseKeys.Automation,
    ],
  },

  //^ Artificial Intelligence, Machine Learning, and Data Science
  [SkillDatabaseKeys.ScikitLearn]: {
    name: "Scikit Learn",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.Hyperparameters,
      SkillDatabaseKeys.Boosting,
      SkillDatabaseKeys.NeuralNetworks,
    ],
  },
  [SkillDatabaseKeys.Pandas]: {
    name: "Pandas",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
    ],
  },
  [SkillDatabaseKeys.NumPy]: {
    name: "NumPy",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.Mathematics,
    ],
  },
  [SkillDatabaseKeys.Matplotlib]: {
    name: "Matplotlib",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
    ],
  },
  [SkillDatabaseKeys.Seaborn]: {
    name: "Seaborn",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
    ],
  },
  [SkillDatabaseKeys.Keras]: {
    name: "Keras",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.DeepLearning,
    ],
  },
  [SkillDatabaseKeys.TensorFlow]: {
    name: "TensorFlow",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.Keras,
    ],
  },
  [SkillDatabaseKeys.PyTorch]: {
    name: "PyTorch",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.DeepLearning,
    ],
  },
  [SkillDatabaseKeys.Jupyter]: {
    name: "Jupyter Notebooks",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Python, SkillDatabaseKeys.DataScience],
  },
  [SkillDatabaseKeys.ApacheSpark]: {
    name: "Apache Spark",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Scala,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.MLLib,
    ],
  },
  [SkillDatabaseKeys.MLLib]: {
    name: "MLLib",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ApacheSpark,
    ],
  },

  [SkillDatabaseKeys.ReinforcementLearning]: {
    name: "Reinforcement Learning",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.IntelligentAgents,
    ],
  },

  [SkillDatabaseKeys.IntelligentAgents]: {
    name: "Intelligent Agents",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.ReinforcementLearning,
    ],
  },

  //^ APIs and Web Services
  [SkillDatabaseKeys.REST]: {
    name: "REST APIs",
    category: SkillCategoriesEnum.CommunicationProtocolsLibraries,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.WebDevelopment, SkillDatabaseKeys.APIs],
  },
  [SkillDatabaseKeys.Apollo]: {
    name: "Apollo",
    category: SkillCategoriesEnum.CommunicationProtocolsLibraries,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.WebDevelopment, SkillDatabaseKeys.APIs],
  },
  [SkillDatabaseKeys.GraphQL]: {
    name: "GraphQL APIs",
    isMainSkill: true,
    category: SkillCategoriesEnum.CommunicationProtocolsLibraries,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.APIs,
      SkillDatabaseKeys.Apollo,
    ],
  },
  [SkillDatabaseKeys.TRPC]: {
    name: "tRPC APIs",
    category: SkillCategoriesEnum.CommunicationProtocolsLibraries,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.WebDevelopment, SkillDatabaseKeys.APIs],
  },
  [SkillDatabaseKeys.SocketIO]: {
    name: "Socket.IO",
    category: SkillCategoriesEnum.CommunicationProtocolsLibraries,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.WebSockets,
    ],
  },
  [SkillDatabaseKeys.Pusher]: {
    name: "Pusher",
    category: SkillCategoriesEnum.CommunicationProtocolsLibraries,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.WebDevelopment,
      SkillDatabaseKeys.WebSockets,
    ],
  },
  [SkillDatabaseKeys.OpenAI]: {
    name: "OpenAI",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.APIs,
      SkillDatabaseKeys.ArtificialIntelligence,
    ],
  },
  [SkillDatabaseKeys.ReplicateAI]: {
    name: "Replicate AI",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.APIs,
      SkillDatabaseKeys.ArtificialIntelligence,
    ],
  },

  //^ Testing
  [SkillDatabaseKeys.Jest]: {
    name: "Jest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.JavaScript, SkillDatabaseKeys.TypeScript],
  },
  [SkillDatabaseKeys.Vitest]: {
    name: "Vitest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.JavaScript, SkillDatabaseKeys.TypeScript],
  },
  [SkillDatabaseKeys.PyTest]: {
    name: "PyTest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Python],
  },
  [SkillDatabaseKeys.UnitTest]: {
    name: "UnitTest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Python],
  },
  [SkillDatabaseKeys.JUnit]: {
    name: "JUnit",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Java],
  },
  [SkillDatabaseKeys.Cypress]: {
    name: "Cypress",
    category: SkillCategoriesEnum.Testing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.JavaScript, SkillDatabaseKeys.TypeScript],
  },
  [SkillDatabaseKeys.ReactTestingLibrary]: {
    name: "React Testing Library",
    category: SkillCategoriesEnum.Testing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.ReactJS,
    ],
  },

  //^ Code Quality
  [SkillDatabaseKeys.Black]: {
    name: "Black",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Python, SkillDatabaseKeys.Linting],
  },
  [SkillDatabaseKeys.Zod]: {
    name: "Zod",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.TypeScript],
  },
  [SkillDatabaseKeys.ESLint]: {
    name: "ESLint",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.Linting,
    ],
  },
  [SkillDatabaseKeys.Prettier]: {
    name: "Prettier",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.JavaScript, SkillDatabaseKeys.TypeScript],
  },
  [SkillDatabaseKeys.PyLint]: {
    name: "PyLint",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Python, SkillDatabaseKeys.Linting],
  },
  [SkillDatabaseKeys.Checkstyle]: {
    name: "Checkstyle",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Java, SkillDatabaseKeys.Linting],
  },

  //^ Version Control Systems
  [SkillDatabaseKeys.Git]: {
    name: "Git",
    category: SkillCategoriesEnum.VersionControl,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.VersionControlSystems,
      SkillDatabaseKeys.GitHub,
      SkillDatabaseKeys.GitLab,
      SkillDatabaseKeys.BitBucket,
    ],
  },
  [SkillDatabaseKeys.GitHub]: {
    name: "GitHub",
    category: SkillCategoriesEnum.VersionControl,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.VersionControlSystems,
      SkillDatabaseKeys.GitHubActions,
    ],
  },
  [SkillDatabaseKeys.GitLab]: {
    name: "GitLab",
    category: SkillCategoriesEnum.VersionControl,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.VersionControlSystems,
      SkillDatabaseKeys.GitLabCI,
    ],
  },
  [SkillDatabaseKeys.BitBucket]: {
    name: "BitBucket",
    category: SkillCategoriesEnum.VersionControl,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.VersionControlSystems],
  },

  //^ Cloud Computing
  [SkillDatabaseKeys.AWS]: {
    name: "Amazon Web Services",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.AWS_K3s,
      SkillDatabaseKeys.AWS_EC2,
      SkillDatabaseKeys.AWS_S3,
      SkillDatabaseKeys.AWS_VPC,
      SkillDatabaseKeys.AWS_Lambda,
      SkillDatabaseKeys.AWS_CloudFormation,
      SkillDatabaseKeys.AWS_CloudFront,
      SkillDatabaseKeys.AWS_ElasticBeanstalk,
    ],
  },
  [SkillDatabaseKeys.AWS_K3s]: {
    name: "K3s",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.Clusterisation,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.AWS,
    ],
  },
  [SkillDatabaseKeys.AWS_CloudWatch]: {
    name: "CloudWatch",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_ApplicationLoadBalancer]: {
    name: "Application Load Balancer (ALB)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
  },
  [SkillDatabaseKeys.AWS_ElasticCache]: {
    name: "Elastic Cache (EC)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },

  [SkillDatabaseKeys.AWS_ElasticFileSystem]: {
    name: "Elastic File System (EFS)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_ElasticBlockStore]: {
    name: "Elastic Block Store (EBS)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_RelationalDatabaseService]: {
    name: "Relational Database Service (RDS)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.AWS,
    ],
  },
  [SkillDatabaseKeys.AWS_AutoScaling]: {
    name: "Auto Scaling",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_EC2]: {
    name: "Elastic Compute Cloud (EC2)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_S3]: {
    name: "Simple Storage Service (S3)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_VPC]: {
    name: "Virtual Private Cloud (VPC)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_Lambda]: {
    name: "Lambda",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_CloudFormation]: {
    name: "CloudFormation",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_CloudFront]: {
    name: "CloudFront",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },
  [SkillDatabaseKeys.AWS_ElasticBeanstalk]: {
    name: "Elastic Beanstalk",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.AWS],
  },

  [SkillDatabaseKeys.Azure]: {
    name: "Microsoft Azure",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.Azure_AppService,
      SkillDatabaseKeys.Azure_BlobStorage,
      SkillDatabaseKeys.Azure_DurableFunctions,
      SkillDatabaseKeys.Azure_Monitor,
      SkillDatabaseKeys.Azure_Functions,
      SkillDatabaseKeys.Azure_ResourceManager,
      SkillDatabaseKeys.Azure_ContainerRegistry,
    ],
  },
  [SkillDatabaseKeys.Azure_AppService]: {
    name: "Azure App Service",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_BlobStorage]: {
    name: "Azure Blob Storage",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_DurableFunctions]: {
    name: "Durable Functions",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_Monitor]: {
    name: "Azure Monitor",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_Functions]: {
    name: "Azure Functions",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_ResourceManager]: {
    name: "Azure Resource Manager",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.Azure],
  },
  [SkillDatabaseKeys.Azure_ContainerRegistry]: {
    name: "Azure Container Registry",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.Azure,
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.Clusterisation,
      SkillDatabaseKeys.Docker,
      SkillDatabaseKeys.Podman,
      SkillDatabaseKeys.Kubernetes,
    ],
  },

  [SkillDatabaseKeys.GCP]: {
    name: "Google Cloud Platform",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.GCP_AppEngine,
      SkillDatabaseKeys.GCP_CloudSQL,
      SkillDatabaseKeys.GCP_CloudStorage,
      SkillDatabaseKeys.GCP_CloudTasks,
      SkillDatabaseKeys.GCP_CloudScheduler,
      SkillDatabaseKeys.GCP_Logging,
      SkillDatabaseKeys.Firebase,
    ],
  },
  [SkillDatabaseKeys.GCP_AppEngine]: {
    name: "App Engine",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.GCP],
  },
  [SkillDatabaseKeys.GCP_CloudSQL]: {
    name: "Cloud SQL",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.GCP,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.GCP_CloudStorage]: {
    name: "Cloud Storage",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.GCP],
  },
  [SkillDatabaseKeys.GCP_CloudTasks]: {
    name: "Cloud Tasks",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.GCP],
  },
  [SkillDatabaseKeys.GCP_CloudScheduler]: {
    name: "Cloud Scheduler",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.GCP],
  },
  [SkillDatabaseKeys.GCP_Logging]: {
    name: "Cloud Logging",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.CloudComputing, SkillDatabaseKeys.GCP],
  },

  //^ Mathematics
  [SkillDatabaseKeys.Probability]: {
    name: "Probability",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Mathematics,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
    ],
  },
  [SkillDatabaseKeys.Statistics]: {
    name: "Statistics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Mathematics,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
    ],
  },
  [SkillDatabaseKeys.Calculus]: {
    name: "Calculus",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Mathematics,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
    ],
  },
  [SkillDatabaseKeys.Trigonometry]: {
    name: "Trigonometry",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },
  [SkillDatabaseKeys.Algebra]: {
    name: "Algebra",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },
  [SkillDatabaseKeys.LinearAlgebra]: {
    name: "Linear Algebra",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Mathematics,
      SkillDatabaseKeys.MachineLearning,
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
    ],
  },
  [SkillDatabaseKeys.Discrete]: {
    name: "Discrete",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },
  [SkillDatabaseKeys.Geometry]: {
    name: "Geometry",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },
  [SkillDatabaseKeys.Logics]: {
    name: "Logics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },
  [SkillDatabaseKeys.Mechanics]: {
    name: "Mechanics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Mathematics],
  },

  //^ Project Management
  [SkillDatabaseKeys.NPM]: {
    name: "NPM",
    category: SkillCategoriesEnum.ProjectManagers,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Java, SkillDatabaseKeys.TypeScript],
  },
  [SkillDatabaseKeys.Yarn]: {
    name: "Yarn",
    category: SkillCategoriesEnum.ProjectManagers,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Java, SkillDatabaseKeys.TypeScript],
  },
  [SkillDatabaseKeys.PNPM]: {
    name: "PNPM",
    category: SkillCategoriesEnum.ProjectManagers,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Java, SkillDatabaseKeys.TypeScript],
  },
  [SkillDatabaseKeys.Pip]: {
    name: "Pip",
    category: SkillCategoriesEnum.ProjectManagers,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Python],
  },
  [SkillDatabaseKeys.Poetry]: {
    name: "Poetry",
    category: SkillCategoriesEnum.ProjectManagers,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Python],
  },
  [SkillDatabaseKeys.PyBuilder]: {
    name: "PyBuilder",
    category: SkillCategoriesEnum.ProjectManagers,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Python],
  },
  [SkillDatabaseKeys.Maven]: {
    name: "Maven",
    category: SkillCategoriesEnum.ProjectManagers,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Java],
  },
  [SkillDatabaseKeys.Gradle]: {
    name: "Gradle",
    category: SkillCategoriesEnum.ProjectManagers,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Java],
  },
  [SkillDatabaseKeys.Tox]: {
    name: "Tox",
    category: SkillCategoriesEnum.ProjectManagers,
    skillType: SkillTypesEnum.Technology,
  },
  [SkillDatabaseKeys.NxJS]: {
    name: "Nx.js",
    category: SkillCategoriesEnum.ProjectManagers,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [SkillDatabaseKeys.Java, SkillDatabaseKeys.TypeScript],
  },

  //^ Communication
  [SkillDatabaseKeys.Symphony]: {
    name: "Symphony BDK",
    category: SkillCategoriesEnum.Automation,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Automation,
      SkillDatabaseKeys.SDKs,
    ],
  },

  //^ Security
  [SkillDatabaseKeys.Cryptography]: {
    name: "Cryptography",
    category: SkillCategoriesEnum.Security,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technology,
    relatedSkills: [
      SkillDatabaseKeys.Security,
      SkillDatabaseKeys.CyberSecurity,
      SkillDatabaseKeys.Cryptography,
    ],
  },
  [SkillDatabaseKeys.CyberSecurity]: {
    name: "Cyber-Security",
    category: SkillCategoriesEnum.Security,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Security,
      SkillDatabaseKeys.CyberSecurity,
      SkillDatabaseKeys.Cryptography,
    ],
  },
  [SkillDatabaseKeys.Security]: {
    name: "Security",
    category: SkillCategoriesEnum.Security,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Security,
      SkillDatabaseKeys.CyberSecurity,
      SkillDatabaseKeys.Cryptography,
    ],
  },

  //^ Others
  [SkillDatabaseKeys.Networking]: {
    name: "Networking",
    category: SkillCategoriesEnum.Security,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
  },

  //^ General Technical Skills
  [SkillDatabaseKeys.ContinuousIntegration]: {
    name: "Continuous Integration",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.GitHubActions,
      SkillDatabaseKeys.GitLabCI,
      SkillDatabaseKeys.Jenkins,
      SkillDatabaseKeys.TeamCity,
    ],
  },

  [SkillDatabaseKeys.ContinuousDelivery]: {
    name: "Continuous Delivery",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.GitHubActions,
      SkillDatabaseKeys.GitLabCI,
      SkillDatabaseKeys.Jenkins,
      SkillDatabaseKeys.TeamCity,
    ],
  },

  [SkillDatabaseKeys.ContinuousDeployment]: {
    name: "Continuous Deployment",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.GitHubActions,
      SkillDatabaseKeys.GitLabCI,
      SkillDatabaseKeys.Jenkins,
      SkillDatabaseKeys.TeamCity,
    ],
  },

  [SkillDatabaseKeys.DevOps]: {
    name: "DevOps",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.GitHubActions,
      SkillDatabaseKeys.GitLabCI,
      SkillDatabaseKeys.Jenkins,
      SkillDatabaseKeys.TeamCity,
      SkillDatabaseKeys.Docker,
      SkillDatabaseKeys.Podman,
      SkillDatabaseKeys.Kubernetes,
      SkillDatabaseKeys.Ansible,
      SkillDatabaseKeys.Vagrant,
      SkillDatabaseKeys.Terraform,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.Clusterisation,
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.Automation,
    ],
  },

  [SkillDatabaseKeys.Linting]: {
    name: "Linting",
    category: SkillCategoriesEnum.CodeQuality,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Black,
      SkillDatabaseKeys.PyLint,
      SkillDatabaseKeys.Zod,
      SkillDatabaseKeys.Prettier,
      SkillDatabaseKeys.Checkstyle,
      SkillDatabaseKeys.ESLint,
    ],
  },
  [SkillDatabaseKeys.ObjectOrientedProgramming]: {
    name: "Object Oriented Programming",
    category: SkillCategoriesEnum.ComputerScienceConcepts,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
    ],
  },
  [SkillDatabaseKeys.FunctionalProgramming]: {
    name: "Functional Programming",
    category: SkillCategoriesEnum.ComputerScienceConcepts,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
    ],
  },
  [SkillDatabaseKeys.Algorithms]: {
    name: "Algorithms",
    category: SkillCategoriesEnum.ComputerScienceConcepts,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
    ],
  },
  [SkillDatabaseKeys.DataStructures]: {
    name: "Data Structures",
    category: SkillCategoriesEnum.ComputerScienceConcepts,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
    ],
  },
  [SkillDatabaseKeys.AndroidDevelopment]: {
    name: "Android Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.Java],
  },
  [SkillDatabaseKeys.iOSDevelopment]: {
    name: "iOS Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
  },
  [SkillDatabaseKeys.WindowsDevelopment]: {
    name: "Windows Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
  },
  [SkillDatabaseKeys.MacDevelopment]: {
    name: "Mac Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
  },
  [SkillDatabaseKeys.LinuxDevelopment]: {
    name: "Linux Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
  },
  [SkillDatabaseKeys.MachineLearning]: {
    name: "Machine Learning",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.Hyperparameters,
      SkillDatabaseKeys.Boosting,
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.TensorFlow,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.ScikitLearn,
      SkillDatabaseKeys.Jupyter,
      SkillDatabaseKeys.ComputerVision,
    ],
  },
  [SkillDatabaseKeys.DeepLearning]: {
    name: "Deep Learning",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.Hyperparameters,
      SkillDatabaseKeys.Boosting,
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.TensorFlow,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.ScikitLearn,
      SkillDatabaseKeys.Jupyter,
      SkillDatabaseKeys.ComputerVision,
    ],
  },
  [SkillDatabaseKeys.ArtificialIntelligence]: {
    name: "Artificial Intelligence",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.Hyperparameters,
      SkillDatabaseKeys.Boosting,
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.ScikitLearn,
      SkillDatabaseKeys.Jupyter,
      SkillDatabaseKeys.OpenAI,
      SkillDatabaseKeys.ReplicateAI,
      SkillDatabaseKeys.ComputerVision,
    ],
  },
  [SkillDatabaseKeys.DataScience]: {
    name: "Data Science",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.Jupyter,
    ],
  },
  [SkillDatabaseKeys.Hyperparameters]: {
    name: "Hyperparameters",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.ScikitLearn,
    ],
  },
  [SkillDatabaseKeys.Boosting]: {
    name: "Boosting",
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    category: SkillCategoriesEnum.ArtificialIntelligence,
    relatedSkills: [
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.ScikitLearn,
    ],
  },
  [SkillDatabaseKeys.DataVisualisation]: {
    name: "Data Visualisation",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
    ],
  },
  [SkillDatabaseKeys.NeuralNetworks]: {
    name: "Neural Networks",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.ScikitLearn,
    ],
  },
  [SkillDatabaseKeys.ComputerVision]: {
    name: "Computer Vision",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DeepLearning,
      SkillDatabaseKeys.ArtificialIntelligence,
      SkillDatabaseKeys.DataScience,
      SkillDatabaseKeys.DataVisualisation,
      SkillDatabaseKeys.NeuralNetworks,
      SkillDatabaseKeys.Keras,
      SkillDatabaseKeys.Pandas,
      SkillDatabaseKeys.NumPy,
      SkillDatabaseKeys.Matplotlib,
      SkillDatabaseKeys.Seaborn,
      SkillDatabaseKeys.ScikitLearn,
    ],
  },
  [SkillDatabaseKeys.APIs]: {
    name: "APIs",
    category: SkillCategoriesEnum.CommunicationProtocolsLibraries,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.REST,
      SkillDatabaseKeys.GraphQL,
      SkillDatabaseKeys.TRPC,
      SkillDatabaseKeys.ReplicateAI,
      SkillDatabaseKeys.OpenAI,
    ],
  },
  [SkillDatabaseKeys.Databases]: {
    name: "Databases",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
      SkillDatabaseKeys.MongoDB,
      SkillDatabaseKeys.Redis,
      SkillDatabaseKeys.Convex,
    ],
  },
  [SkillDatabaseKeys.WebSockets]: {
    name: "Web Sockets",
    category: SkillCategoriesEnum.CommunicationProtocolsLibraries,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [SkillDatabaseKeys.SocketIO, SkillDatabaseKeys.Pusher],
  },
  [SkillDatabaseKeys.RelationalDatabases]: {
    name: "Relational Databases (SQL)",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
    ],
  },

  [SkillDatabaseKeys.NonRelationalDatabases]: {
    name: "Non Relational Databases (NoSQL)",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.MongoDB,
      SkillDatabaseKeys.Redis,
      SkillDatabaseKeys.Convex,
    ],
  },
  [SkillDatabaseKeys.ObjectRelationalMapping]: {
    name: "Object Relational Mapping",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Mongoose,
      SkillDatabaseKeys.Prisma,
      SkillDatabaseKeys.Drizzle,
      SkillDatabaseKeys.SQLAlchemy,
      SkillDatabaseKeys.TypeORM,
      SkillDatabaseKeys.Hibernate,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.DatabaseIndexing,
    ],
  },
  [SkillDatabaseKeys.Testing]: {
    name: "Testing",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Jest,
      SkillDatabaseKeys.Vitest,
      SkillDatabaseKeys.PyTest,
      SkillDatabaseKeys.UnitTest,
      SkillDatabaseKeys.JUnit,
      SkillDatabaseKeys.Cypress,
      SkillDatabaseKeys.ReactTestingLibrary,
    ],
  },
  [SkillDatabaseKeys.Containerisation]: {
    name: "Containerization",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Docker,
      SkillDatabaseKeys.Podman,
      SkillDatabaseKeys.Kubernetes,
      SkillDatabaseKeys.Clusterisation,
      SkillDatabaseKeys.Azure_ContainerRegistry,
    ],
  },
  [SkillDatabaseKeys.Clusterisation]: {
    name: "Clusterisation",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Kubernetes,
      SkillDatabaseKeys.Azure_ContainerRegistry,
    ],
  },
  [SkillDatabaseKeys.InfrastructureAsCode]: {
    name: "Infrastructure as Code",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Ansible,
      SkillDatabaseKeys.Vagrant,
      SkillDatabaseKeys.Terraform,
    ],
  },
  [SkillDatabaseKeys.Automation]: {
    name: "Automation",
    category: SkillCategoriesEnum.Automation,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Ansible,
      SkillDatabaseKeys.Vagrant,
      SkillDatabaseKeys.Terraform,
    ],
  },
  [SkillDatabaseKeys.DatabaseManagementSystems]: {
    name: "Database Management Systems",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.Databases,
    ],
  },
  [SkillDatabaseKeys.DatabaseIndexing]: {
    name: "Indexing",
    category: SkillCategoriesEnum.DatabaseManagement,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.ObjectRelationalMapping,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
      SkillDatabaseKeys.MongoDB,
      SkillDatabaseKeys.Redis,
      SkillDatabaseKeys.Convex,
    ],
  },
  [SkillDatabaseKeys.CloudComputing]: {
    name: "Cloud Computing",
    category: SkillCategoriesEnum.CloudComputing,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.AWS,
      SkillDatabaseKeys.Azure,
      SkillDatabaseKeys.GCP,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.AWS_K3s,
      SkillDatabaseKeys.AWS_EC2,
      SkillDatabaseKeys.AWS_S3,
      SkillDatabaseKeys.AWS_VPC,
      SkillDatabaseKeys.AWS_Lambda,
      SkillDatabaseKeys.AWS_CloudFormation,
      SkillDatabaseKeys.AWS_CloudFront,
      SkillDatabaseKeys.AWS_ElasticBeanstalk,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.Azure_AppService,
      SkillDatabaseKeys.Azure_BlobStorage,
      SkillDatabaseKeys.Azure_DurableFunctions,
      SkillDatabaseKeys.Azure_Monitor,
      SkillDatabaseKeys.Azure_Functions,
      SkillDatabaseKeys.Azure_ResourceManager,
      SkillDatabaseKeys.Azure_ContainerRegistry,
      SkillDatabaseKeys.CloudComputing,
      SkillDatabaseKeys.GCP_AppEngine,
      SkillDatabaseKeys.GCP_CloudSQL,
      SkillDatabaseKeys.GCP_CloudStorage,
      SkillDatabaseKeys.GCP_CloudTasks,
      SkillDatabaseKeys.GCP_CloudScheduler,
      SkillDatabaseKeys.GCP_Logging,
      SkillDatabaseKeys.Firebase,
    ],
  },

  [SkillDatabaseKeys.DesignPatterns]: {
    name: "Design Patterns",
    category: SkillCategoriesEnum.CodeQuality,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.JavaScript,
    ],
  },
  [SkillDatabaseKeys.UserAuthentication]: {
    name: "User Authentication",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Firebase,
      SkillDatabaseKeys.PocketBase,
      SkillDatabaseKeys.Supabase,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.ClerkAuth,
      SkillDatabaseKeys.NextAuth,
    ],
  },
  [SkillDatabaseKeys.WebDevelopment]: {
    name: "Web Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.REST,
      SkillDatabaseKeys.GraphQL,
      SkillDatabaseKeys.TRPC,
      SkillDatabaseKeys.WebSockets,
      SkillDatabaseKeys.SocketIO,
      SkillDatabaseKeys.Pusher,
      SkillDatabaseKeys.Firebase,
      SkillDatabaseKeys.PocketBase,
      SkillDatabaseKeys.Supabase,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.ClerkAuth,
      SkillDatabaseKeys.NextAuth,
      SkillDatabaseKeys.Stripe,
      SkillDatabaseKeys.ExpressJS,
      SkillDatabaseKeys.Flask,
      SkillDatabaseKeys.Django,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Cloudinary,
      SkillDatabaseKeys.EdgeStore,
      SkillDatabaseKeys.Gunicorn,
      SkillDatabaseKeys.Jinja,
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.NextJS,
      SkillDatabaseKeys.SvelteKit,
      SkillDatabaseKeys.AngularJS,
      SkillDatabaseKeys.NuxtJS,
      SkillDatabaseKeys.ReactJS,
      SkillDatabaseKeys.SvelteJS,
      SkillDatabaseKeys.VueJS,
      SkillDatabaseKeys.Recoil,
      SkillDatabaseKeys.Zustand,
      SkillDatabaseKeys.Jotai,
      SkillDatabaseKeys.Redux,
      SkillDatabaseKeys.TailwindCSS,
      SkillDatabaseKeys.HTML,
      SkillDatabaseKeys.CSS,
      SkillDatabaseKeys.ChakraUI,
      SkillDatabaseKeys.HeadlessUI,
      SkillDatabaseKeys.ShadcnUI,
      SkillDatabaseKeys.RadixUI,
      SkillDatabaseKeys.ReactQuery,
      SkillDatabaseKeys.NextUI,
      SkillDatabaseKeys.StateManagement,
      SkillDatabaseKeys.Bootstrap,
      SkillDatabaseKeys.MaterialUI,
      SkillDatabaseKeys.SemanticUI,
      SkillDatabaseKeys.AntDesign,
      SkillDatabaseKeys.StoryBooks,
      SkillDatabaseKeys.Axios,
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.StateManagement,
    ],
  },
  [SkillDatabaseKeys.SDKs]: {
    name: "SDK",
    category: SkillCategoriesEnum.CommunicationProtocolsLibraries,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Firebase,
      SkillDatabaseKeys.Supabase,
      SkillDatabaseKeys.PocketBase,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.ClerkAuth,
      SkillDatabaseKeys.NextAuth,
      SkillDatabaseKeys.Stripe,
      SkillDatabaseKeys.Cloudinary,
      SkillDatabaseKeys.EdgeStore,
      SkillDatabaseKeys.Symphony,
    ],
  },
  [SkillDatabaseKeys.UserCentricDesign]: {
    name: "User Centric Design",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.REST,
      SkillDatabaseKeys.GraphQL,
      SkillDatabaseKeys.TRPC,
      SkillDatabaseKeys.WebSockets,
      SkillDatabaseKeys.SocketIO,
      SkillDatabaseKeys.Pusher,
      SkillDatabaseKeys.Firebase,
      SkillDatabaseKeys.PocketBase,
      SkillDatabaseKeys.Supabase,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.ClerkAuth,
      SkillDatabaseKeys.NextAuth,
      SkillDatabaseKeys.Stripe,
      SkillDatabaseKeys.ExpressJS,
      SkillDatabaseKeys.Flask,
      SkillDatabaseKeys.Django,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Cloudinary,
      SkillDatabaseKeys.EdgeStore,
      SkillDatabaseKeys.Gunicorn,
      SkillDatabaseKeys.Jinja,
      SkillDatabaseKeys.UserAuthentication,
      SkillDatabaseKeys.NextJS,
      SkillDatabaseKeys.SvelteKit,
      SkillDatabaseKeys.AngularJS,
      SkillDatabaseKeys.NuxtJS,
      SkillDatabaseKeys.ReactJS,
      SkillDatabaseKeys.SvelteJS,
      SkillDatabaseKeys.VueJS,
      SkillDatabaseKeys.Recoil,
      SkillDatabaseKeys.Zustand,
      SkillDatabaseKeys.Jotai,
      SkillDatabaseKeys.Redux,
      SkillDatabaseKeys.TailwindCSS,
      SkillDatabaseKeys.HTML,
      SkillDatabaseKeys.CSS,
      SkillDatabaseKeys.ChakraUI,
      SkillDatabaseKeys.HeadlessUI,
      SkillDatabaseKeys.ShadcnUI,
      SkillDatabaseKeys.RadixUI,
      SkillDatabaseKeys.ReactQuery,
      SkillDatabaseKeys.NextUI,
      SkillDatabaseKeys.StateManagement,
      SkillDatabaseKeys.Bootstrap,
      SkillDatabaseKeys.MaterialUI,
      SkillDatabaseKeys.SemanticUI,
      SkillDatabaseKeys.AntDesign,
      SkillDatabaseKeys.StoryBooks,
      SkillDatabaseKeys.Axios,
      SkillDatabaseKeys.StateManagement,
    ],
  },
  [SkillDatabaseKeys.Mathematics]: {
    name: "Mathematics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Probability,
      SkillDatabaseKeys.Statistics,
      SkillDatabaseKeys.Calculus,
      SkillDatabaseKeys.Trigonometry,
      SkillDatabaseKeys.Algebra,
      SkillDatabaseKeys.LinearAlgebra,
      SkillDatabaseKeys.Discrete,
      SkillDatabaseKeys.Geometry,
      SkillDatabaseKeys.Mechanics,
      SkillDatabaseKeys.Logics,
    ],
  },
  [SkillDatabaseKeys.VersionControlSystems]: {
    name: "Version Control",
    category: SkillCategoriesEnum.VersionControl,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Git,
      SkillDatabaseKeys.GitHub,
      SkillDatabaseKeys.GitLab,
      SkillDatabaseKeys.BitBucket,
    ],
  },
  [SkillDatabaseKeys.StateManagement]: {
    name: "State Management",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.Technical,
    relatedSkills: [
      SkillDatabaseKeys.Recoil,
      SkillDatabaseKeys.Zustand,
      SkillDatabaseKeys.Jotai,
      SkillDatabaseKeys.Redux,
    ],
  },

  //^ Soft Skills
  [SkillDatabaseKeys.Communication]: {
    name: "Communication",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.ProjectManagement]: {
    name: "Project Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.Teamwork]: {
    name: "Teamwork",
    isMainSkill: true,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.Leadership]: {
    name: "Leadership",
    isMainSkill: true,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.ProblemSolving]: {
    name: "Problem Solving",
    isMainSkill: true,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.CriticalThinking]: {
    name: "Critical Thinking",
    isMainSkill: true,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.Creativity]: {
    name: "Creativity",
    isMainSkill: true,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.Adaptability]: {
    name: "Adaptability",
    isMainSkill: true,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.TimeManagement]: {
    name: "Time Management",
    isMainSkill: true,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.RiskManagement]: {
    name: "Risk Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.StakeholderManagement]: {
    name: "Stakeholder Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.ScopeManagement]: {
    name: "Scope Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.CostManagement]: {
    name: "Cost Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.QualityManagement]: {
    name: "Quality Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.ProcurementManagement]: {
    name: "Procurement Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.IntegrationManagement]: {
    name: "Integration Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillDatabaseKeys.HumanResourceManagement]: {
    name: "Human Resource Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
};

export default skillDatabaseMap;

/**
 * List of keys for the skills that can be used to uniquely identify the skills.
 */
export const skillDatabaseKeys: SkillDatabaseKeys[] = Object.keys(
  skillDatabaseMap
) as SkillDatabaseKeys[];
