import SkillCategoriesEnum from "@/enums/SkillCategoriesEnum";
import SkillSlugEnum from "@/enums/SkillSlugEnum";
import SkillTypesEnum from "@/enums/SkillTypesEnum";
import SkillInterface from "@/interfaces/skills/SkillInterface";

const skillsHashmap: Database<SkillInterface> = {
  //^ Languages
  [SkillSlugEnum.Python]: {
    name: "Python",
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillSlugEnum.Flask,
      SkillSlugEnum.Django,
      SkillSlugEnum.Gunicorn,
      SkillSlugEnum.Jinja,
      SkillSlugEnum.SimpleGUI,
      SkillSlugEnum.SQLAlchemy,
      SkillSlugEnum.Black,
      SkillSlugEnum.PyLint,
      SkillSlugEnum.PyTest,
      SkillSlugEnum.UnitTest,
      SkillSlugEnum.Poetry,
      SkillSlugEnum.Pip,
      SkillSlugEnum.PyBuilder,
      SkillSlugEnum.ScikitLearn,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
      SkillSlugEnum.Jupyter,
      SkillSlugEnum.Keras,
      SkillSlugEnum.MachineLearning,
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.Hyperparameters,
      SkillSlugEnum.Boosting,
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.NeuralNetworks,
      SkillSlugEnum.WebDevelopment,
    ],
  },
  [SkillSlugEnum.JavaScript]: {
    name: "JavaScript",
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillSlugEnum.ClerkAuth,
      SkillSlugEnum.NextAuth,
      SkillSlugEnum.ExpressJS,
      SkillSlugEnum.NextJS,
      SkillSlugEnum.SvelteKit,
      SkillSlugEnum.AngularJS,
      SkillSlugEnum.NuxtJS,
      SkillSlugEnum.ReactJS,
      SkillSlugEnum.SvelteJS,
      SkillSlugEnum.VueJS,
      SkillSlugEnum.Recoil,
      SkillSlugEnum.Redux,
      SkillSlugEnum.Mongoose,
      SkillSlugEnum.Prettier,
      SkillSlugEnum.ESLint,
      SkillSlugEnum.Jest,
      SkillSlugEnum.Vitest,
      SkillSlugEnum.NPM,
      SkillSlugEnum.Yarn,
      SkillSlugEnum.PNPM,
      SkillSlugEnum.NxJS,
    ],
  },
  [SkillSlugEnum.TypeScript]: {
    name: "TypeScript",
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillSlugEnum.ClerkAuth,
      SkillSlugEnum.NextAuth,
      SkillSlugEnum.ExpressJS,
      SkillSlugEnum.NextJS,
      SkillSlugEnum.SvelteKit,
      SkillSlugEnum.AngularJS,
      SkillSlugEnum.NuxtJS,
      SkillSlugEnum.ReactJS,
      SkillSlugEnum.SvelteJS,
      SkillSlugEnum.VueJS,
      SkillSlugEnum.Recoil,
      SkillSlugEnum.Redux,
      SkillSlugEnum.Mongoose,
      SkillSlugEnum.Prettier,
      SkillSlugEnum.ESLint,
      SkillSlugEnum.Jest,
      SkillSlugEnum.Vitest,
      SkillSlugEnum.NPM,
      SkillSlugEnum.Yarn,
      SkillSlugEnum.PNPM,
      SkillSlugEnum.NxJS,
      SkillSlugEnum.TypeORM,
      SkillSlugEnum.Zod,
    ],
  },
  [SkillSlugEnum.Java]: {
    name: "Java",
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillSlugEnum.Spring,
      SkillSlugEnum.SpringBoot,
      SkillSlugEnum.Hibernate,
      SkillSlugEnum.Checkstyle,
      SkillSlugEnum.JUnit,
      SkillSlugEnum.Gradle,
      SkillSlugEnum.Maven,
      SkillSlugEnum.AndroidDevelopment,
    ],
  },
  [SkillSlugEnum.GameMakerLanguage]: {
    name: "GameMaker Language",
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [
      SkillSlugEnum.GameDevelopment,
      SkillSlugEnum.GameMakerStudio,
    ],
  },
  [SkillSlugEnum.ShellScript]: {
    name: "Shell Script",
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillSlugEnum.RLanguage]: {
    name: "R",
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
  },
  [SkillSlugEnum.Groovy]: {
    name: "Groovy",
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    category: SkillCategoriesEnum.ProgrammingLanguages,
    relatedSkills: [SkillSlugEnum.Gradle, SkillSlugEnum.Jenkins],
  },

  //^ Full Stack Web Development
  [SkillSlugEnum.NextJS]: {
    name: "Next.js",
    category: SkillCategoriesEnum.FullStackWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,

    relatedSkills: [
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
      SkillSlugEnum.ReactJS,
      SkillSlugEnum.NextAuth,
    ],
  },

  [SkillSlugEnum.AngularJS]: {
    name: "Angular",
    category: SkillCategoriesEnum.FullStackWebDevelopment,
    skillType: SkillTypesEnum.Hard,

    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
    ],
  },
  [SkillSlugEnum.NuxtJS]: {
    name: "Nuxt.js",
    category: SkillCategoriesEnum.FullStackWebDevelopment,
    skillType: SkillTypesEnum.Hard,

    relatedSkills: [
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
      SkillSlugEnum.VueJS,
    ],
  },
  [SkillSlugEnum.SvelteKit]: {
    name: "SvelteKit",
    category: SkillCategoriesEnum.FullStackWebDevelopment,
    skillType: SkillTypesEnum.Hard,

    relatedSkills: [
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
      SkillSlugEnum.SvelteJS,
    ],
  },

  //^ Frontend Web Development
  [SkillSlugEnum.Recoil]: {
    name: "Recoil",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.StateManagement,
    ],
  },
  [SkillSlugEnum.Zustand]: {
    name: "Zustand",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.StateManagement,
    ],
  },
  [SkillSlugEnum.Jotai]: {
    name: "Jotai",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.StateManagement,
    ],
  },

  [SkillSlugEnum.Redux]: {
    name: "Redux",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.StateManagement,
    ],
  },
  [SkillSlugEnum.TailwindCSS]: {
    name: "Tailwind CSS",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
    ],
  },
  [SkillSlugEnum.HTML]: {
    name: "HTML",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
    ],
  },
  [SkillSlugEnum.CSS]: {
    name: "CSS",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
    ],
  },
  [SkillSlugEnum.ReactJS]: {
    name: "React",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
      SkillSlugEnum.Recoil,
      SkillSlugEnum.Zustand,
      SkillSlugEnum.Jotai,
      SkillSlugEnum.Redux,
    ],
  },
  [SkillSlugEnum.SvelteJS]: {
    name: "Svelte",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
    ],
  },

  [SkillSlugEnum.VueJS]: {
    name: "Vue",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserAuthentication,
    ],
  },
  [SkillSlugEnum.ChakraUI]: {
    name: "Chakra UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
    ],
  },

  [SkillSlugEnum.HeadlessUI]: {
    name: "Headless UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
      SkillSlugEnum.ReactJS,
      SkillSlugEnum.VueJS,
    ],
  },
  [SkillSlugEnum.ShadcnUI]: {
    name: "Shadcn UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
      SkillSlugEnum.ReactJS,
    ],
  },
  [SkillSlugEnum.RadixUI]: {
    name: "Radix UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
      SkillSlugEnum.ReactJS,
    ],
  },

  [SkillSlugEnum.ReactQuery]: {
    name: "React Query",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
      SkillSlugEnum.ReactJS,
    ],
  },
  [SkillSlugEnum.NextUI]: {
    name: "Next UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
      SkillSlugEnum.ReactJS,
    ],
  },
  [SkillSlugEnum.Bootstrap]: {
    name: "Bootstrap",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
    ],
  },
  [SkillSlugEnum.MaterialUI]: {
    name: "Material UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
    ],
  },
  [SkillSlugEnum.SemanticUI]: {
    name: "Semantic UI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
    ],
  },
  [SkillSlugEnum.AntDesign]: {
    name: "Ant Design",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
    ],
  },
  [SkillSlugEnum.StoryBooks]: {
    name: "Storybooks",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.UserCentricDesign,
    ],
  },
  [SkillSlugEnum.SimpleGUI]: {
    name: "Simple GUI",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.UserCentricDesign],
  },
  [SkillSlugEnum.Axios]: {
    name: "Axios",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.WebDevelopment, SkillSlugEnum.APIs],
  },

  //^ Backend Web Development
  [SkillSlugEnum.Firebase]: {
    name: "Firebase",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.NonRelationalDatabases,
      SkillSlugEnum.Databases,
      SkillSlugEnum.DatabaseIndexing,
      SkillSlugEnum.CloudComputing,
      SkillSlugEnum.UserAuthentication,
      SkillSlugEnum.SDKs,
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.GCP,
    ],
  },
  [SkillSlugEnum.Supabase]: {
    name: "Supabase",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.DatabaseIndexing,
      SkillSlugEnum.Databases,
      SkillSlugEnum.CloudComputing,
      SkillSlugEnum.UserAuthentication,
      SkillSlugEnum.SDKs,
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.PostgreSQL,
    ],
  },
  [SkillSlugEnum.PocketBase]: {
    name: "PocketBase",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.Databases,
      SkillSlugEnum.DatabaseIndexing,
      SkillSlugEnum.CloudComputing,
      SkillSlugEnum.UserAuthentication,
      SkillSlugEnum.SDKs,
      SkillSlugEnum.WebDevelopment,
    ],
  },
  [SkillSlugEnum.Auth0]: {
    name: "Auth0",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.UserAuthentication, SkillSlugEnum.SDKs],
  },
  [SkillSlugEnum.ClerkAuth]: {
    name: "Clerk Auth",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.UserAuthentication, SkillSlugEnum.SDKs],
  },
  [SkillSlugEnum.NextAuth]: {
    name: "NextAuth",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
      SkillSlugEnum.UserAuthentication,
      SkillSlugEnum.WebDevelopment,
    ],
  },
  [SkillSlugEnum.Stripe]: {
    name: "Stripe",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.SDKs],
  },
  [SkillSlugEnum.ExpressJS]: {
    name: "Express",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.APIs,
    ],
  },
  [SkillSlugEnum.Flask]: {
    name: "Flask",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.APIs,
      SkillSlugEnum.Python,
    ],
  },
  [SkillSlugEnum.Django]: {
    name: "Django",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.APIs,
      SkillSlugEnum.Python,
    ],
  },
  [SkillSlugEnum.Spring]: {
    name: "Spring",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.APIs,
      SkillSlugEnum.Java,
    ],
  },
  [SkillSlugEnum.SpringBoot]: {
    name: "Spring Boot",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.APIs,
      SkillSlugEnum.Java,
    ],
  },
  [SkillSlugEnum.Cloudinary]: {
    name: "Cloudinary",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Cloudinary],
  },
  [SkillSlugEnum.EdgeStore]: {
    name: "Edge Store",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.WebDevelopment],
  },
  [SkillSlugEnum.Gunicorn]: {
    name: "Gunicorn",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Python, SkillSlugEnum.WebDevelopment],
  },
  [SkillSlugEnum.Jinja]: {
    name: "Jinja",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Python, SkillSlugEnum.WebDevelopment],
  },

  //^ Databases
  [SkillSlugEnum.Normalisation]: {
    name: "Normalisation",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.Databases,
    ],
  },
  [SkillSlugEnum.PostgreSQL]: {
    name: "PostgreSQL",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.Databases,
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.Normalisation,
      SkillSlugEnum.DatabaseIndexing,
    ],
  },
  [SkillSlugEnum.MySQL]: {
    name: "MySQL",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.Databases,
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.Normalisation,
      SkillSlugEnum.DatabaseIndexing,
    ],
  },
  [SkillSlugEnum.SQLite]: {
    name: "SQLite",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.Databases,
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.Normalisation,
      SkillSlugEnum.DatabaseIndexing,
    ],
  },
  [SkillSlugEnum.MongoDB]: {
    name: "MongoDB",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.Databases,
      SkillSlugEnum.NonRelationalDatabases,
      SkillSlugEnum.DatabaseIndexing,
    ],
  },
  [SkillSlugEnum.Redis]: {
    name: "Redis",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.Databases,
      SkillSlugEnum.NonRelationalDatabases,
      SkillSlugEnum.DatabaseIndexing,
    ],
  },
  [SkillSlugEnum.Convex]: {
    name: "Convex",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.Databases,
      SkillSlugEnum.NonRelationalDatabases,
      SkillSlugEnum.DatabaseIndexing,
    ],
  },

  //^ Object Relational Mapping
  [SkillSlugEnum.Mongoose]: {
    name: "Mongoose",
    category: SkillCategoriesEnum.ObjectRelationalMappers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.Databases,
      SkillSlugEnum.NonRelationalDatabases,
      SkillSlugEnum.DatabaseIndexing,
      SkillSlugEnum.ObjectRelationalMapping,
      SkillSlugEnum.MongoDB,
    ],
  },
  [SkillSlugEnum.Prisma]: {
    name: "Prisma",
    category: SkillCategoriesEnum.ObjectRelationalMappers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.Databases,
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.NonRelationalDatabases,
      SkillSlugEnum.DatabaseIndexing,
      SkillSlugEnum.ObjectOrientedProgramming,
      SkillSlugEnum.MongoDB,
      SkillSlugEnum.PostgreSQL,
      SkillSlugEnum.MySQL,
      SkillSlugEnum.SQLite,
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
    ],
  },
  [SkillSlugEnum.Drizzle]: {
    name: "Drizzle",
    category: SkillCategoriesEnum.ObjectRelationalMappers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.Databases,
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.DatabaseIndexing,
      SkillSlugEnum.TypeORM,
      SkillSlugEnum.PostgreSQL,
      SkillSlugEnum.MySQL,
      SkillSlugEnum.SQLite,
    ],
  },
  [SkillSlugEnum.TypeORM]: {
    name: "TypeORM",
    category: SkillCategoriesEnum.ObjectRelationalMappers,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.Databases,
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.DatabaseIndexing,
      SkillSlugEnum.ObjectRelationalMapping,
      SkillSlugEnum.PostgreSQL,
      SkillSlugEnum.MySQL,
      SkillSlugEnum.SQLite,
    ],
  },
  [SkillSlugEnum.SQLAlchemy]: {
    name: "SQLAlchemy",
    category: SkillCategoriesEnum.ObjectRelationalMappers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.Python,
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.Databases,
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.DatabaseIndexing,
      SkillSlugEnum.ObjectRelationalMapping,
      SkillSlugEnum.PostgreSQL,
      SkillSlugEnum.MySQL,
      SkillSlugEnum.SQLite,
    ],
  },
  [SkillSlugEnum.Hibernate]: {
    name: "Hibernate",
    category: SkillCategoriesEnum.ObjectRelationalMappers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.Java,
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.Databases,
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.DatabaseIndexing,
      SkillSlugEnum.ObjectRelationalMapping,
      SkillSlugEnum.PostgreSQL,
      SkillSlugEnum.MySQL,
      SkillSlugEnum.SQLite,
    ],
  },

  //^ DevOps
  [SkillSlugEnum.GitHubActions]: {
    name: "GitHub Actions",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.InfrastructureAsCode,
      SkillSlugEnum.ContinuousDelivery,
      SkillSlugEnum.ContinuousIntegration,
      SkillSlugEnum.ContinuousDeployment,
      SkillSlugEnum.DevOps,
      SkillSlugEnum.Automation,
      SkillSlugEnum.GitHub,
    ],
  },
  [SkillSlugEnum.GitLabCI]: {
    name: "GitLab CI",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.InfrastructureAsCode,
      SkillSlugEnum.ContinuousDelivery,
      SkillSlugEnum.ContinuousIntegration,
      SkillSlugEnum.ContinuousDeployment,
      SkillSlugEnum.DevOps,
      SkillSlugEnum.Automation,
      SkillSlugEnum.GitLab,
    ],
  },
  [SkillSlugEnum.Jenkins]: {
    name: "Jenkins",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.InfrastructureAsCode,
      SkillSlugEnum.ContinuousDelivery,
      SkillSlugEnum.ContinuousIntegration,
      SkillSlugEnum.ContinuousDeployment,
      SkillSlugEnum.DevOps,
      SkillSlugEnum.Automation,
      SkillSlugEnum.Groovy,
    ],
  },
  [SkillSlugEnum.TeamCity]: {
    name: "TeamCity",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.InfrastructureAsCode,
      SkillSlugEnum.ContinuousDelivery,
      SkillSlugEnum.ContinuousIntegration,
      SkillSlugEnum.ContinuousDeployment,
      SkillSlugEnum.DevOps,
      SkillSlugEnum.Automation,
    ],
  },
  [SkillSlugEnum.Docker]: {
    name: "Docker",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Containerisation, SkillSlugEnum.DevOps],
  },
  [SkillSlugEnum.Podman]: {
    name: "Podman",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Containerisation, SkillSlugEnum.DevOps],
  },
  [SkillSlugEnum.Kubernetes]: {
    name: "Kubernetes",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.Containerisation,
      SkillSlugEnum.DevOps,
      SkillSlugEnum.Clusterisation,
    ],
  },
  [SkillSlugEnum.Ansible]: {
    name: "Ansible",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.InfrastructureAsCode,
      SkillSlugEnum.DevOps,
      SkillSlugEnum.Automation,
    ],
  },
  [SkillSlugEnum.Terraform]: {
    name: "Terraform",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.InfrastructureAsCode,
      SkillSlugEnum.DevOps,
      SkillSlugEnum.Automation,
    ],
  },
  [SkillSlugEnum.Vagrant]: {
    name: "Vagrant",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.InfrastructureAsCode,
      SkillSlugEnum.DevOps,
      SkillSlugEnum.Automation,
    ],
  },

  //^ Artificial Intelligence, Machine Learning, and Data Science
  [SkillSlugEnum.ScikitLearn]: {
    name: "Scikit Learn",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.Python,
      SkillSlugEnum.MachineLearning,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.ContinuousIntegration,
      SkillSlugEnum.Hyperparameters,
      SkillSlugEnum.Boosting,
      SkillSlugEnum.NeuralNetworks,
    ],
  },
  [SkillSlugEnum.Pandas]: {
    name: "Pandas",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.Python,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.DataVisualisation,
    ],
  },
  [SkillSlugEnum.NumPy]: {
    name: "NumPy",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.Python,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.Mathematics,
    ],
  },
  [SkillSlugEnum.Matplotlib]: {
    name: "Matplotlib",
    category: SkillCategoriesEnum.DataScience,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.Python,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.DataVisualisation,
    ],
  },
  [SkillSlugEnum.Seaborn]: {
    name: "Seaborn",
    category: SkillCategoriesEnum.DataScience,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.Python,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.DataVisualisation,
    ],
  },
  [SkillSlugEnum.Keras]: {
    name: "Keras",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.Python,
      SkillSlugEnum.MachineLearning,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.ArtificialIntelligence,
      SkillSlugEnum.NeuralNetworks,
      SkillSlugEnum.DeepLearning,
    ],
  },
  [SkillSlugEnum.Jupyter]: {
    name: "Jupyter Notebooks",
    category: SkillCategoriesEnum.DataScience,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Python, SkillSlugEnum.DataScience],
  },

  //^ APIs and Web Services
  [SkillSlugEnum.REST]: {
    name: "REST",
    category: SkillCategoriesEnum.APIs,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.WebDevelopment, SkillSlugEnum.APIs],
  },
  [SkillSlugEnum.Apollo]: {
    name: "Apollo",
    category: SkillCategoriesEnum.APIs,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.WebDevelopment, SkillSlugEnum.APIs],
  },
  [SkillSlugEnum.GraphQL]: {
    name: "GraphQL",
    category: SkillCategoriesEnum.APIs,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.WebDevelopment,
      SkillSlugEnum.APIs,
      SkillSlugEnum.Apollo,
    ],
  },
  [SkillSlugEnum.TRPC]: {
    name: "tRPC",
    category: SkillCategoriesEnum.APIs,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.WebDevelopment, SkillSlugEnum.APIs],
  },
  [SkillSlugEnum.SocketIO]: {
    name: "Socket.IO",
    category: SkillCategoriesEnum.WebSockets,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.WebDevelopment, SkillSlugEnum.WebSockets],
  },
  [SkillSlugEnum.Pusher]: {
    name: "Pusher",
    category: SkillCategoriesEnum.WebSockets,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.WebDevelopment, SkillSlugEnum.WebSockets],
  },
  [SkillSlugEnum.OpenAI]: {
    name: "OpenAI",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.APIs, SkillSlugEnum.ArtificialIntelligence],
  },
  [SkillSlugEnum.ReplicateAI]: {
    name: "Replicate AI",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.APIs, SkillSlugEnum.ArtificialIntelligence],
  },

  //^ Testing
  [SkillSlugEnum.Jest]: {
    name: "Jest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.JavaScript, SkillSlugEnum.TypeScript],
  },
  [SkillSlugEnum.Vitest]: {
    name: "Vitest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.JavaScript, SkillSlugEnum.TypeScript],
  },
  [SkillSlugEnum.PyTest]: {
    name: "PyTest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Python],
  },
  [SkillSlugEnum.UnitTest]: {
    name: "UnitTest",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Python],
  },
  [SkillSlugEnum.JUnit]: {
    name: "JUnit",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Java],
  },
  [SkillSlugEnum.Cypress]: {
    name: "Cypress",
    category: SkillCategoriesEnum.Testing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.JavaScript, SkillSlugEnum.TypeScript],
  },
  [SkillSlugEnum.ReactTestingLibrary]: {
    name: "React Testing Library",
    category: SkillCategoriesEnum.Testing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
      SkillSlugEnum.ReactJS,
    ],
  },

  //^ Code Quality
  [SkillSlugEnum.Black]: {
    name: "Black",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Python, SkillSlugEnum.Linting],
  },
  [SkillSlugEnum.Zod]: {
    name: "Zod",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.TypeScript],
  },
  [SkillSlugEnum.ESLint]: {
    name: "ESLint",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
      SkillSlugEnum.Linting,
    ],
  },
  [SkillSlugEnum.Prettier]: {
    name: "Prettier",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.JavaScript, SkillSlugEnum.TypeScript],
  },
  [SkillSlugEnum.PyLint]: {
    name: "PyLint",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Python, SkillSlugEnum.Linting],
  },
  [SkillSlugEnum.Checkstyle]: {
    name: "Checkstyle",
    category: SkillCategoriesEnum.CodeQuality,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Java, SkillSlugEnum.Linting],
  },

  //^ Version Control Systems
  [SkillSlugEnum.Git]: {
    name: "Git",
    category: SkillCategoriesEnum.VersionControl,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.VersionControlSystems,
      SkillSlugEnum.GitHub,
      SkillSlugEnum.GitLab,
      SkillSlugEnum.BitBucket,
    ],
  },
  [SkillSlugEnum.GitHub]: {
    name: "GitHub",
    category: SkillCategoriesEnum.VersionControl,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.VersionControlSystems,
      SkillSlugEnum.GitHubActions,
    ],
  },
  [SkillSlugEnum.GitLab]: {
    name: "GitLab",
    category: SkillCategoriesEnum.VersionControl,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.VersionControlSystems,
      SkillSlugEnum.GitLabCI,
    ],
  },
  [SkillSlugEnum.BitBucket]: {
    name: "BitBucket",
    category: SkillCategoriesEnum.VersionControl,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.VersionControlSystems],
  },

  //^ Cloud Computing
  [SkillSlugEnum.AWS]: {
    name: "Amazon Web Services",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.CloudComputing,
      SkillSlugEnum.AWS_K3s,
      SkillSlugEnum.AWS_EC2,
      SkillSlugEnum.AWS_S3,
      SkillSlugEnum.AWS_VPC,
      SkillSlugEnum.AWS_Lambda,
      SkillSlugEnum.AWS_CloudFormation,
      SkillSlugEnum.AWS_CloudFront,
      SkillSlugEnum.AWS_ElasticBeanstalk,
    ],
  },
  [SkillSlugEnum.AWS_K3s]: {
    name: "K3s",
    category: SkillCategoriesEnum.DevOps,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.Containerisation,
      SkillSlugEnum.Clusterisation,
      SkillSlugEnum.CloudComputing,
    ],
  },
  [SkillSlugEnum.AWS_EC2]: {
    name: "Elastic Compute Cloud (EC2)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },
  [SkillSlugEnum.AWS_S3]: {
    name: "Simple Storage Service (S3)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },
  [SkillSlugEnum.AWS_VPC]: {
    name: "Virtual Private Cloud (VPC)",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },
  [SkillSlugEnum.AWS_Lambda]: {
    name: "Lambda",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },
  [SkillSlugEnum.AWS_CloudFormation]: {
    name: "CloudFormation",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },
  [SkillSlugEnum.AWS_CloudFront]: {
    name: "CloudFront",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },
  [SkillSlugEnum.AWS_ElasticBeanstalk]: {
    name: "Elastic Beanstalk",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },

  [SkillSlugEnum.Azure]: {
    name: "Microsoft Azure",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.CloudComputing,
      SkillSlugEnum.Azure_AppService,
      SkillSlugEnum.Azure_BlobStorage,
      SkillSlugEnum.Azure_DurableFunctions,
      SkillSlugEnum.Azure_Monitor,
      SkillSlugEnum.Azure_Functions,
      SkillSlugEnum.Azure_ResourceManager,
      SkillSlugEnum.Azure_ContainerRegistry,
    ],
  },
  [SkillSlugEnum.Azure_AppService]: {
    name: "Azure App Service",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },
  [SkillSlugEnum.Azure_BlobStorage]: {
    name: "Azure Blob Storage",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },
  [SkillSlugEnum.Azure_DurableFunctions]: {
    name: "Durable Functions",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },
  [SkillSlugEnum.Azure_Monitor]: {
    name: "Azure Monitor",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },
  [SkillSlugEnum.Azure_Functions]: {
    name: "Azure Functions",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },
  [SkillSlugEnum.Azure_ResourceManager]: {
    name: "Azure Resource Manager",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },
  [SkillSlugEnum.Azure_ContainerRegistry]: {
    name: "Azure Container Registry",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.CloudComputing,
      SkillSlugEnum.Containerisation,
      SkillSlugEnum.Clusterisation,
      SkillSlugEnum.Docker,
      SkillSlugEnum.Podman,
      SkillSlugEnum.Kubernetes,
    ],
  },

  [SkillSlugEnum.GCP]: {
    name: "Google Cloud Platform",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.CloudComputing,
      SkillSlugEnum.GCP_AppEngine,
      SkillSlugEnum.GCP_CloudSQL,
      SkillSlugEnum.GCP_CloudStorage,
      SkillSlugEnum.GCP_CloudTasks,
      SkillSlugEnum.GCP_CloudScheduler,
      SkillSlugEnum.GCP_Logging,
      SkillSlugEnum.Firebase,
    ],
  },
  [SkillSlugEnum.GCP_AppEngine]: {
    name: "App Engine",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },
  [SkillSlugEnum.GCP_CloudSQL]: {
    name: "Cloud SQL",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.CloudComputing,
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.DatabaseIndexing,
    ],
  },
  [SkillSlugEnum.GCP_CloudStorage]: {
    name: "Cloud Storage",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },
  [SkillSlugEnum.GCP_CloudTasks]: {
    name: "Cloud Tasks",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },
  [SkillSlugEnum.GCP_CloudScheduler]: {
    name: "Cloud Scheduler",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },
  [SkillSlugEnum.GCP_Logging]: {
    name: "Cloud Logging",
    category: SkillCategoriesEnum.CloudComputing,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.CloudComputing],
  },

  //^ Mathematics
  [SkillSlugEnum.Probability]: {
    name: "Probability",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.Mathematics,
      SkillSlugEnum.MachineLearning,
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
    ],
  },
  [SkillSlugEnum.Statistics]: {
    name: "Statistics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.Mathematics,
      SkillSlugEnum.MachineLearning,
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
    ],
  },
  [SkillSlugEnum.Calculus]: {
    name: "Calculus",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.Mathematics,
      SkillSlugEnum.MachineLearning,
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
    ],
  },
  [SkillSlugEnum.Trigonometry]: {
    name: "Trigonometry",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Mathematics],
  },
  [SkillSlugEnum.Algebra]: {
    name: "Algebra",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.Mathematics,
      SkillSlugEnum.MachineLearning,
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
    ],
  },
  [SkillSlugEnum.LinearAlgebra]: {
    name: "Linear Algebra",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.Mathematics,
      SkillSlugEnum.MachineLearning,
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
    ],
  },
  [SkillSlugEnum.Discrete]: {
    name: "Discrete",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Mathematics],
  },
  [SkillSlugEnum.Geometry]: {
    name: "Geometry",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Mathematics],
  },
  [SkillSlugEnum.Logics]: {
    name: "Logics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Mathematics],
  },
  [SkillSlugEnum.Mechanics]: {
    name: "Mechanics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Mathematics],
  },

  //^ Project Management
  [SkillSlugEnum.NPM]: {
    name: "NPM",
    category: SkillCategoriesEnum.ProjectManagers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Java, SkillSlugEnum.TypeScript],
  },
  [SkillSlugEnum.Yarn]: {
    name: "Yarn",
    category: SkillCategoriesEnum.ProjectManagers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Java, SkillSlugEnum.TypeScript],
  },
  [SkillSlugEnum.PNPM]: {
    name: "PNPM",
    category: SkillCategoriesEnum.ProjectManagers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Java, SkillSlugEnum.TypeScript],
  },
  [SkillSlugEnum.Pip]: {
    name: "Pip",
    category: SkillCategoriesEnum.ProjectManagers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Python],
  },
  [SkillSlugEnum.Poetry]: {
    name: "Poetry",
    category: SkillCategoriesEnum.ProjectManagers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Python],
  },
  [SkillSlugEnum.PyBuilder]: {
    name: "PyBuilder",
    category: SkillCategoriesEnum.ProjectManagers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Python],
  },
  [SkillSlugEnum.Maven]: {
    name: "Maven",
    category: SkillCategoriesEnum.ProjectManagers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Java],
  },
  [SkillSlugEnum.Gradle]: {
    name: "Gradle",
    category: SkillCategoriesEnum.ProjectManagers,
    isMainSkill: true,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Java],
  },
  [SkillSlugEnum.Tox]: {
    name: "Tox",
    category: SkillCategoriesEnum.ProjectManagers,
    skillType: SkillTypesEnum.Hard,
  },
  [SkillSlugEnum.NxJS]: {
    name: "Nx.js",
    category: SkillCategoriesEnum.ProjectManagers,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.Java, SkillSlugEnum.TypeScript],
  },

  //^ Game Development
  [SkillSlugEnum.GameMakerStudio]: {
    name: "GameMaker Studio 2",
    category: SkillCategoriesEnum.GameDevelopment,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [SkillSlugEnum.GameDevelopment],
  },

  //^ Communication
  [SkillSlugEnum.Symphony]: {
    name: "Symphony Solutions",
    category: SkillCategoriesEnum.Automation,
    skillType: SkillTypesEnum.Hard,
    relatedSkills: [
      SkillSlugEnum.Java,
      SkillSlugEnum.Python,
      SkillSlugEnum.Automation,
      SkillSlugEnum.SDKs,
    ],
  },

  //^ General Technical Skills
  [SkillSlugEnum.ContinuousIntegration]: {
    name: "Continuous Integration",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.GitHubActions,
      SkillSlugEnum.GitLabCI,
      SkillSlugEnum.Jenkins,
      SkillSlugEnum.TeamCity,
    ],
  },

  [SkillSlugEnum.ContinuousDelivery]: {
    name: "Continuous Delivery",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.GitHubActions,
      SkillSlugEnum.GitLabCI,
      SkillSlugEnum.Jenkins,
      SkillSlugEnum.TeamCity,
    ],
  },

  [SkillSlugEnum.ContinuousDeployment]: {
    name: "Continuous Deployment",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.GitHubActions,
      SkillSlugEnum.GitLabCI,
      SkillSlugEnum.Jenkins,
      SkillSlugEnum.TeamCity,
    ],
  },

  [SkillSlugEnum.DevOps]: {
    name: "DevOps",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.GitHubActions,
      SkillSlugEnum.GitLabCI,
      SkillSlugEnum.Jenkins,
      SkillSlugEnum.TeamCity,
      SkillSlugEnum.Docker,
      SkillSlugEnum.Podman,
      SkillSlugEnum.Kubernetes,
      SkillSlugEnum.Ansible,
      SkillSlugEnum.Vagrant,
      SkillSlugEnum.Terraform,
      SkillSlugEnum.ContinuousIntegration,
      SkillSlugEnum.ContinuousDeployment,
      SkillSlugEnum.ContinuousDelivery,
      SkillSlugEnum.Containerisation,
      SkillSlugEnum.Clusterisation,
      SkillSlugEnum.InfrastructureAsCode,
      SkillSlugEnum.Automation,
    ],
  },

  [SkillSlugEnum.Linting]: {
    name: "Linting",
    category: SkillCategoriesEnum.CodeQuality,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Black,
      SkillSlugEnum.PyLint,
      SkillSlugEnum.Zod,
      SkillSlugEnum.Prettier,
      SkillSlugEnum.Checkstyle,
      SkillSlugEnum.ESLint,
    ],
  },
  [SkillSlugEnum.ObjectOrientedProgramming]: {
    name: "Object Oriented Programming",
    category: SkillCategoriesEnum.ProgrammingParadigms,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Python,
      SkillSlugEnum.Java,
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
    ],
  },
  [SkillSlugEnum.FunctionalProgramming]: {
    name: "Functional Programming",
    category: SkillCategoriesEnum.ProgrammingParadigms,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Python,
      SkillSlugEnum.Java,
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
    ],
  },
  [SkillSlugEnum.Algorithms]: {
    name: "Algorithms",
    category: SkillCategoriesEnum.CoreComputerScience,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Python,
      SkillSlugEnum.Java,
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
    ],
  },
  [SkillSlugEnum.DataStructures]: {
    name: "Data Structures",
    category: SkillCategoriesEnum.CoreComputerScience,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Python,
      SkillSlugEnum.Java,
      SkillSlugEnum.JavaScript,
      SkillSlugEnum.TypeScript,
    ],
  },
  [SkillSlugEnum.AndroidDevelopment]: {
    name: "Android Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [SkillSlugEnum.Java],
  },
  [SkillSlugEnum.iOSDevelopment]: {
    name: "iOS Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
  },
  [SkillSlugEnum.WindowsDevelopment]: {
    name: "Windows Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
  },
  [SkillSlugEnum.MacDevelopment]: {
    name: "Mac Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
  },
  [SkillSlugEnum.LinuxDevelopment]: {
    name: "Linux Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
  },
  [SkillSlugEnum.MachineLearning]: {
    name: "Machine Learning",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.Hyperparameters,
      SkillSlugEnum.Boosting,
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.NeuralNetworks,
      SkillSlugEnum.Keras,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
      SkillSlugEnum.ScikitLearn,
      SkillSlugEnum.Jupyter,
    ],
  },
  [SkillSlugEnum.DeepLearning]: {
    name: "Deep Learning",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.ArtificialIntelligence,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.Hyperparameters,
      SkillSlugEnum.Boosting,
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.NeuralNetworks,
      SkillSlugEnum.Keras,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
      SkillSlugEnum.ScikitLearn,
      SkillSlugEnum.Jupyter,
    ],
  },
  [SkillSlugEnum.ArtificialIntelligence]: {
    name: "Artificial Intelligence",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.Hyperparameters,
      SkillSlugEnum.Boosting,
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.NeuralNetworks,
      SkillSlugEnum.Keras,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
      SkillSlugEnum.ScikitLearn,
      SkillSlugEnum.Jupyter,
      SkillSlugEnum.OpenAI,
      SkillSlugEnum.ReplicateAI,
    ],
  },
  [SkillSlugEnum.DataScience]: {
    name: "Data Science",
    category: SkillCategoriesEnum.DataScience,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
      SkillSlugEnum.Jupyter,
    ],
  },
  [SkillSlugEnum.Hyperparameters]: {
    name: "Hyperparameters",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.NeuralNetworks,
      SkillSlugEnum.Keras,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
      SkillSlugEnum.ScikitLearn,
    ],
  },
  [SkillSlugEnum.Boosting]: {
    name: "Boosting",
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    category: SkillCategoriesEnum.ArtificialIntelligence,
    relatedSkills: [
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.NeuralNetworks,
      SkillSlugEnum.Keras,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
      SkillSlugEnum.ScikitLearn,
    ],
  },
  [SkillSlugEnum.DataVisualisation]: {
    name: "Data Visualisation",
    category: SkillCategoriesEnum.DataScience,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.NeuralNetworks,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
    ],
  },
  [SkillSlugEnum.NeuralNetworks]: {
    name: "Neural Networks",
    category: SkillCategoriesEnum.ArtificialIntelligence,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.DeepLearning,
      SkillSlugEnum.ArtificialIntelligence,
      SkillSlugEnum.DataScience,
      SkillSlugEnum.DataVisualisation,
      SkillSlugEnum.NeuralNetworks,
      SkillSlugEnum.Keras,
      SkillSlugEnum.Pandas,
      SkillSlugEnum.NumPy,
      SkillSlugEnum.Matplotlib,
      SkillSlugEnum.Seaborn,
      SkillSlugEnum.ScikitLearn,
    ],
  },
  [SkillSlugEnum.APIs]: {
    name: "APIs",
    category: SkillCategoriesEnum.APIs,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.REST,
      SkillSlugEnum.GraphQL,
      SkillSlugEnum.TRPC,
      SkillSlugEnum.ReplicateAI,
      SkillSlugEnum.OpenAI,
    ],
  },
  [SkillSlugEnum.Databases]: {
    name: "Databases",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.NonRelationalDatabases,
      SkillSlugEnum.ObjectRelationalMapping,
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.DatabaseIndexing,
      SkillSlugEnum.Normalisation,
      SkillSlugEnum.PostgreSQL,
      SkillSlugEnum.MySQL,
      SkillSlugEnum.SQLite,
      SkillSlugEnum.MongoDB,
      SkillSlugEnum.Redis,
      SkillSlugEnum.Convex,
    ],
  },
  [SkillSlugEnum.WebSockets]: {
    name: "Web Sockets",
    category: SkillCategoriesEnum.WebSockets,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [SkillSlugEnum.SocketIO, SkillSlugEnum.Pusher],
  },
  [SkillSlugEnum.RelationalDatabases]: {
    name: "Relational Databases (SQL)",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.ObjectRelationalMapping,
      SkillSlugEnum.DatabaseIndexing,
      SkillSlugEnum.Normalisation,
      SkillSlugEnum.PostgreSQL,
      SkillSlugEnum.MySQL,
      SkillSlugEnum.SQLite,
    ],
  },

  [SkillSlugEnum.NonRelationalDatabases]: {
    name: "Non Relational Databases (NoSQL)",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.DatabaseIndexing,
      SkillSlugEnum.MongoDB,
      SkillSlugEnum.Redis,
      SkillSlugEnum.Convex,
    ],
  },
  [SkillSlugEnum.ObjectRelationalMapping]: {
    name: "Object Relational Mapping",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Mongoose,
      SkillSlugEnum.Prisma,
      SkillSlugEnum.Drizzle,
      SkillSlugEnum.SQLAlchemy,
      SkillSlugEnum.TypeORM,
      SkillSlugEnum.Hibernate,
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.DatabaseIndexing,
    ],
  },
  [SkillSlugEnum.Testing]: {
    name: "Testing",
    category: SkillCategoriesEnum.Testing,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Jest,
      SkillSlugEnum.Vitest,
      SkillSlugEnum.PyTest,
      SkillSlugEnum.UnitTest,
      SkillSlugEnum.JUnit,
      SkillSlugEnum.Cypress,
      SkillSlugEnum.ReactTestingLibrary,
    ],
  },
  [SkillSlugEnum.Containerisation]: {
    name: "Containerization",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Docker,
      SkillSlugEnum.Podman,
      SkillSlugEnum.Kubernetes,
      SkillSlugEnum.Clusterisation,
      SkillSlugEnum.Azure_ContainerRegistry,
    ],
  },
  [SkillSlugEnum.Clusterisation]: {
    name: "Clusterisation",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Kubernetes,
      SkillSlugEnum.Azure_ContainerRegistry,
    ],
  },
  [SkillSlugEnum.InfrastructureAsCode]: {
    name: "Infrastructure as Code",
    category: SkillCategoriesEnum.DevOps,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Ansible,
      SkillSlugEnum.Vagrant,
      SkillSlugEnum.Terraform,
    ],
  },
  [SkillSlugEnum.Automation]: {
    name: "Automation",
    category: SkillCategoriesEnum.Automation,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Ansible,
      SkillSlugEnum.Vagrant,
      SkillSlugEnum.Terraform,
    ],
  },
  [SkillSlugEnum.DatabaseManagementSystems]: {
    name: "Database Management Systems",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.DatabaseIndexing,
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.NonRelationalDatabases,
      SkillSlugEnum.ObjectRelationalMapping,
      SkillSlugEnum.Normalisation,
      SkillSlugEnum.Databases,
    ],
  },
  [SkillSlugEnum.DatabaseIndexing]: {
    name: "Indexing",
    category: SkillCategoriesEnum.Databases,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.RelationalDatabases,
      SkillSlugEnum.NonRelationalDatabases,
      SkillSlugEnum.ObjectRelationalMapping,
      SkillSlugEnum.Normalisation,
      SkillSlugEnum.Databases,
      SkillSlugEnum.DatabaseManagementSystems,
      SkillSlugEnum.PostgreSQL,
      SkillSlugEnum.MySQL,
      SkillSlugEnum.SQLite,
      SkillSlugEnum.MongoDB,
      SkillSlugEnum.Redis,
      SkillSlugEnum.Convex,
    ],
  },
  [SkillSlugEnum.CloudComputing]: {
    name: "Cloud Computing",
    category: SkillCategoriesEnum.CloudComputing,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.AWS,
      SkillSlugEnum.Azure,
      SkillSlugEnum.GCP,
      SkillSlugEnum.CloudComputing,
      SkillSlugEnum.AWS_K3s,
      SkillSlugEnum.AWS_EC2,
      SkillSlugEnum.AWS_S3,
      SkillSlugEnum.AWS_VPC,
      SkillSlugEnum.AWS_Lambda,
      SkillSlugEnum.AWS_CloudFormation,
      SkillSlugEnum.AWS_CloudFront,
      SkillSlugEnum.AWS_ElasticBeanstalk,
      SkillSlugEnum.CloudComputing,
      SkillSlugEnum.Azure_AppService,
      SkillSlugEnum.Azure_BlobStorage,
      SkillSlugEnum.Azure_DurableFunctions,
      SkillSlugEnum.Azure_Monitor,
      SkillSlugEnum.Azure_Functions,
      SkillSlugEnum.Azure_ResourceManager,
      SkillSlugEnum.Azure_ContainerRegistry,
      SkillSlugEnum.CloudComputing,
      SkillSlugEnum.GCP_AppEngine,
      SkillSlugEnum.GCP_CloudSQL,
      SkillSlugEnum.GCP_CloudStorage,
      SkillSlugEnum.GCP_CloudTasks,
      SkillSlugEnum.GCP_CloudScheduler,
      SkillSlugEnum.GCP_Logging,
      SkillSlugEnum.Firebase,
    ],
  },

  [SkillSlugEnum.DesignPatterns]: {
    name: "Design Patterns",
    category: SkillCategoriesEnum.CodeQuality,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Python,
      SkillSlugEnum.Java,
      SkillSlugEnum.TypeScript,
      SkillSlugEnum.JavaScript,
    ],
  },
  [SkillSlugEnum.UserAuthentication]: {
    name: "User Authentication",
    category: SkillCategoriesEnum.BackEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Firebase,
      SkillSlugEnum.PocketBase,
      SkillSlugEnum.Supabase,
      SkillSlugEnum.Auth0,
      SkillSlugEnum.ClerkAuth,
      SkillSlugEnum.NextAuth,
    ],
  },
  [SkillSlugEnum.WebDevelopment]: {
    name: "Web Development",
    category: SkillCategoriesEnum.PlatformDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.REST,
      SkillSlugEnum.GraphQL,
      SkillSlugEnum.TRPC,
      SkillSlugEnum.WebSockets,
      SkillSlugEnum.SocketIO,
      SkillSlugEnum.Pusher,
      SkillSlugEnum.Firebase,
      SkillSlugEnum.PocketBase,
      SkillSlugEnum.Supabase,
      SkillSlugEnum.Auth0,
      SkillSlugEnum.ClerkAuth,
      SkillSlugEnum.NextAuth,
      SkillSlugEnum.Stripe,
      SkillSlugEnum.ExpressJS,
      SkillSlugEnum.Flask,
      SkillSlugEnum.Django,
      SkillSlugEnum.Spring,
      SkillSlugEnum.SpringBoot,
      SkillSlugEnum.Cloudinary,
      SkillSlugEnum.EdgeStore,
      SkillSlugEnum.Gunicorn,
      SkillSlugEnum.Jinja,
      SkillSlugEnum.UserAuthentication,
      SkillSlugEnum.NextJS,
      SkillSlugEnum.SvelteKit,
      SkillSlugEnum.AngularJS,
      SkillSlugEnum.NuxtJS,
      SkillSlugEnum.ReactJS,
      SkillSlugEnum.SvelteJS,
      SkillSlugEnum.VueJS,
      SkillSlugEnum.Recoil,
      SkillSlugEnum.Zustand,
      SkillSlugEnum.Jotai,
      SkillSlugEnum.Redux,
      SkillSlugEnum.TailwindCSS,
      SkillSlugEnum.HTML,
      SkillSlugEnum.CSS,
      SkillSlugEnum.ChakraUI,
      SkillSlugEnum.HeadlessUI,
      SkillSlugEnum.ShadcnUI,
      SkillSlugEnum.RadixUI,
      SkillSlugEnum.ReactQuery,
      SkillSlugEnum.NextUI,
      SkillSlugEnum.StateManagement,
      SkillSlugEnum.Bootstrap,
      SkillSlugEnum.MaterialUI,
      SkillSlugEnum.SemanticUI,
      SkillSlugEnum.AntDesign,
      SkillSlugEnum.StoryBooks,
      SkillSlugEnum.Axios,
      SkillSlugEnum.UserCentricDesign,
      SkillSlugEnum.StateManagement,
    ],
  },
  [SkillSlugEnum.SDKs]: {
    name: "SDK",
    category: SkillCategoriesEnum.SDKs,
    isMainSkill: true,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Firebase,
      SkillSlugEnum.Supabase,
      SkillSlugEnum.PocketBase,
      SkillSlugEnum.Auth0,
      SkillSlugEnum.ClerkAuth,
      SkillSlugEnum.NextAuth,
      SkillSlugEnum.Stripe,
      SkillSlugEnum.Cloudinary,
      SkillSlugEnum.EdgeStore,
      SkillSlugEnum.Symphony,
    ],
  },
  [SkillSlugEnum.UserCentricDesign]: {
    name: "User Centric Design",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.REST,
      SkillSlugEnum.GraphQL,
      SkillSlugEnum.TRPC,
      SkillSlugEnum.WebSockets,
      SkillSlugEnum.SocketIO,
      SkillSlugEnum.Pusher,
      SkillSlugEnum.Firebase,
      SkillSlugEnum.PocketBase,
      SkillSlugEnum.Supabase,
      SkillSlugEnum.Auth0,
      SkillSlugEnum.ClerkAuth,
      SkillSlugEnum.NextAuth,
      SkillSlugEnum.Stripe,
      SkillSlugEnum.ExpressJS,
      SkillSlugEnum.Flask,
      SkillSlugEnum.Django,
      SkillSlugEnum.Spring,
      SkillSlugEnum.SpringBoot,
      SkillSlugEnum.Cloudinary,
      SkillSlugEnum.EdgeStore,
      SkillSlugEnum.Gunicorn,
      SkillSlugEnum.Jinja,
      SkillSlugEnum.UserAuthentication,
      SkillSlugEnum.NextJS,
      SkillSlugEnum.SvelteKit,
      SkillSlugEnum.AngularJS,
      SkillSlugEnum.NuxtJS,
      SkillSlugEnum.ReactJS,
      SkillSlugEnum.SvelteJS,
      SkillSlugEnum.VueJS,
      SkillSlugEnum.Recoil,
      SkillSlugEnum.Zustand,
      SkillSlugEnum.Jotai,
      SkillSlugEnum.Redux,
      SkillSlugEnum.TailwindCSS,
      SkillSlugEnum.HTML,
      SkillSlugEnum.CSS,
      SkillSlugEnum.ChakraUI,
      SkillSlugEnum.HeadlessUI,
      SkillSlugEnum.ShadcnUI,
      SkillSlugEnum.RadixUI,
      SkillSlugEnum.ReactQuery,
      SkillSlugEnum.NextUI,
      SkillSlugEnum.StateManagement,
      SkillSlugEnum.Bootstrap,
      SkillSlugEnum.MaterialUI,
      SkillSlugEnum.SemanticUI,
      SkillSlugEnum.AntDesign,
      SkillSlugEnum.StoryBooks,
      SkillSlugEnum.Axios,
      SkillSlugEnum.StateManagement,
    ],
  },
  [SkillSlugEnum.GameDevelopment]: {
    name: "Game Development",
    category: SkillCategoriesEnum.GameDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.GameMakerLanguage,
      SkillSlugEnum.GameMakerLanguage,
    ],
  },
  [SkillSlugEnum.Mathematics]: {
    name: "Mathematics",
    category: SkillCategoriesEnum.Mathematics,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Probability,
      SkillSlugEnum.Statistics,
      SkillSlugEnum.Calculus,
      SkillSlugEnum.Trigonometry,
      SkillSlugEnum.Algebra,
      SkillSlugEnum.LinearAlgebra,
      SkillSlugEnum.Discrete,
      SkillSlugEnum.Geometry,
      SkillSlugEnum.Mechanics,
      SkillSlugEnum.Logics,
    ],
  },
  [SkillSlugEnum.VersionControlSystems]: {
    name: "Version Control",
    category: SkillCategoriesEnum.VersionControl,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Git,
      SkillSlugEnum.GitHub,
      SkillSlugEnum.GitLab,
      SkillSlugEnum.BitBucket,
    ],
  },
  [SkillSlugEnum.StateManagement]: {
    name: "State Management",
    category: SkillCategoriesEnum.FrontEndWebDevelopment,
    isMainSkill: false,
    skillType: SkillTypesEnum.General,
    relatedSkills: [
      SkillSlugEnum.Recoil,
      SkillSlugEnum.Zustand,
      SkillSlugEnum.Jotai,
      SkillSlugEnum.Redux,
    ],
  },

  //^ Soft Skills
  [SkillSlugEnum.Communication]: {
    name: "Communication",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillSlugEnum.ProjectManagement]: {
    name: "Project Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillSlugEnum.Teamwork]: {
    name: "Teamwork",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillSlugEnum.Leadership]: {
    name: "Leadership",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillSlugEnum.ProblemSolving]: {
    name: "Problem Solving",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillSlugEnum.CriticalThinking]: {
    name: "Critical Thinking",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillSlugEnum.Creativity]: {
    name: "Creativity",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillSlugEnum.Adaptability]: {
    name: "Adaptability",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillSlugEnum.TimeManagement]: {
    name: "Time Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillSlugEnum.RiskManagement]: {
    name: "Risk Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillSlugEnum.StakeholderManagement]: {
    name: "Stakeholder Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillSlugEnum.ScopeManagement]: {
    name: "Scope Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillSlugEnum.CostManagement]: {
    name: "Cost Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillSlugEnum.QualityManagement]: {
    name: "Quality Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillSlugEnum.ProcurementManagement]: {
    name: "Procurement Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillSlugEnum.IntegrationManagement]: {
    name: "Integration Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
  [SkillSlugEnum.HumanResourceManagement]: {
    name: "Human Resource Management",
    isMainSkill: false,
    skillType: SkillTypesEnum.Soft,
    category: SkillCategoriesEnum.SoftSkills,
  },
};

export default skillsHashmap;

export const skillSlugArrayNew: SkillSlugEnum[] = Object.keys(
  skillsHashmap
) as SkillSlugEnum[];
