import BlogDatabaseKeys from "../Blogs/BlogDatabaseKeys";
import CourseDatabaseKeys from "../Courses/CourseDatabaseKeys";
import ModuleDatabaseKeys from "../Modules/ModuleDatabaseKeys";
import ProjectDatabaseKeys from "../Projects/ProjectDatabaseKeys";
import SkillDatabaseKeys from "../Skills/SkillDatabaseKeys";
import CategoryDatabaseKeys from "./CategoryDatabaseKeys";
import CategoryInterface from "./CategoryInterface";

const categoryDatabaseMap: Database<CategoryInterface> = {
  [CategoryDatabaseKeys.WebDevelopment]: {
    name: "Web Development",
    relatedItems: [
      BlogDatabaseKeys.Backend,
      BlogDatabaseKeys.Frontend,
      BlogDatabaseKeys.RESTGraphQL,
      BlogDatabaseKeys.SessionsVsTokens,
      BlogDatabaseKeys.SyncAsync,
    ],
  },
  [CategoryDatabaseKeys.FrontEndWebDevelopment]: {
    name: "Front-End Web Development",
    relatedItems: [
      SkillDatabaseKeys.ReactJS,
      SkillDatabaseKeys.SvelteJS,
      SkillDatabaseKeys.VueJS,
      SkillDatabaseKeys.Recoil,
      SkillDatabaseKeys.Zustand,
      SkillDatabaseKeys.Jotai,
      SkillDatabaseKeys.Redux,
      SkillDatabaseKeys.TailwindCSS,
      SkillDatabaseKeys.HTML,
      SkillDatabaseKeys.CSS,
      SkillDatabaseKeys.ChakraUI,
      SkillDatabaseKeys.HeadlessUI,
      SkillDatabaseKeys.ShadcnUI,
      SkillDatabaseKeys.RadixUI,
      SkillDatabaseKeys.ReactQuery,
      SkillDatabaseKeys.NextUI,
      SkillDatabaseKeys.Bootstrap,
      SkillDatabaseKeys.MaterialUI,
      SkillDatabaseKeys.SemanticUI,
      SkillDatabaseKeys.AntDesign,
      SkillDatabaseKeys.StoryBooks,
      SkillDatabaseKeys.SimpleGUI,
      SkillDatabaseKeys.Axios,
      SkillDatabaseKeys.UserCentricDesign,
      SkillDatabaseKeys.StateManagement,
    ],
  },
  [CategoryDatabaseKeys.SoftwareEngineering]: {
    name: "Software Engineering",
    relatedItems: [
      BlogDatabaseKeys.JavaScriptVsTypeScript,
      BlogDatabaseKeys.SDKvsAPI,
      BlogDatabaseKeys.SoftwareTesting,
    ],
  },
  [CategoryDatabaseKeys.BackEndWebDevelopment]: {
    name: "Back-End Web Development",
    relatedItems: [
      ProjectDatabaseKeys.FlaskForumBackend,
      ProjectDatabaseKeys.FlaskJWTAuthentication,
      ProjectDatabaseKeys.DjangoAuthentication,
      ProjectDatabaseKeys.ClerkAuthentication,
      ProjectDatabaseKeys.Auth0Authentication,
      SkillDatabaseKeys.Firebase,
      SkillDatabaseKeys.Supabase,
      SkillDatabaseKeys.PocketBase,
      SkillDatabaseKeys.Auth0,
      SkillDatabaseKeys.ClerkAuth,
      SkillDatabaseKeys.NextAuth,
      SkillDatabaseKeys.Stripe,
      SkillDatabaseKeys.ExpressJS,
      SkillDatabaseKeys.Flask,
      SkillDatabaseKeys.Django,
      SkillDatabaseKeys.Spring,
      SkillDatabaseKeys.SpringBoot,
      SkillDatabaseKeys.Cloudinary,
      SkillDatabaseKeys.EdgeStore,
      SkillDatabaseKeys.Gunicorn,
      SkillDatabaseKeys.Jinja,
      SkillDatabaseKeys.WebSockets,
      SkillDatabaseKeys.UserAuthentication,
    ],
  },
  [CategoryDatabaseKeys.FullStackWebDevelopment]: {
    name: "Full-Stack Web Development",
    relatedItems: [
      ProjectDatabaseKeys.CircusDiscussions,
      ProjectDatabaseKeys.RingmasterMessaging,
      ProjectDatabaseKeys.MagicianAI,
      ProjectDatabaseKeys.DrumrollMusic,
      ProjectDatabaseKeys.JokerNotes,
      ProjectDatabaseKeys.Quizmify,
      ProjectDatabaseKeys.SideshowArticles,
      ProjectDatabaseKeys.Noodle,
      ProjectDatabaseKeys.ConvoGPT,
      SkillDatabaseKeys.NextJS,
      SkillDatabaseKeys.SvelteKit,
      SkillDatabaseKeys.AngularJS,
      SkillDatabaseKeys.NuxtJS,
    ],
  },
  [CategoryDatabaseKeys.Databases]: {
    name: "Databases",
    relatedItems: [BlogDatabaseKeys.ORM, BlogDatabaseKeys.SQLNOSQL],
  },
  [CategoryDatabaseKeys.DevOps]: {
    name: "DevOps",
    relatedItems: [
      BlogDatabaseKeys.CICD,
      BlogDatabaseKeys.DevOps,
      BlogDatabaseKeys.Docker,
      BlogDatabaseKeys.Kubernetes,
      SkillDatabaseKeys.Normalisation,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MySQL,
      SkillDatabaseKeys.SQLite,
      SkillDatabaseKeys.MongoDB,
      SkillDatabaseKeys.Redis,
      SkillDatabaseKeys.Convex,
      SkillDatabaseKeys.Databases,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.DatabaseManagementSystems,
      SkillDatabaseKeys.DatabaseIndexing,
      SkillDatabaseKeys.GitHubActions,
      SkillDatabaseKeys.GitLabCI,
      SkillDatabaseKeys.Jenkins,
      SkillDatabaseKeys.TeamCity,
      SkillDatabaseKeys.Docker,
      SkillDatabaseKeys.Podman,
      SkillDatabaseKeys.Kubernetes,
      SkillDatabaseKeys.Ansible,
      SkillDatabaseKeys.Vagrant,
      SkillDatabaseKeys.Terraform,
      SkillDatabaseKeys.ContinuousIntegration,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.DevOps,
      SkillDatabaseKeys.Containerisation,
      SkillDatabaseKeys.InfrastructureAsCode,
      SkillDatabaseKeys.Clusterisation,
      SkillDatabaseKeys.Automation,
    ],
  },
  [CategoryDatabaseKeys.ArtificialIntelligence]: {
    name: "Artificial Intelligence",
    relatedItems: [BlogDatabaseKeys.MachineLearningFoundations],
  },
  [CategoryDatabaseKeys.Mathematics]: {
    name: "Mathematics",
  },
  [CategoryDatabaseKeys.University]: {
    name: "University",
  },
  [CategoryDatabaseKeys.ProgrammingLanguages]: {
    name: "Programming Languages",
    relatedItems: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.GameMakerLanguage,
      SkillDatabaseKeys.ShellScript,
      SkillDatabaseKeys.C,
      SkillDatabaseKeys.Haskell,
      SkillDatabaseKeys.Scala,
      SkillDatabaseKeys.RLanguage,
      SkillDatabaseKeys.Groovy,
      SkillDatabaseKeys.ObjectOrientedProgramming,
      SkillDatabaseKeys.FunctionalProgramming,
    ],
  },
  [CategoryDatabaseKeys.AlgorithmsDataStructures]: {
    name: "Algorithms & Data Structures",
  },
  [CategoryDatabaseKeys.CloudComputing]: {
    name: "Cloud Computing",
  },
  [CategoryDatabaseKeys.Management]: {
    name: "Management",
  },
  [CategoryDatabaseKeys.Software]: {
    name: "Software",
  },
  [CategoryDatabaseKeys.MachineLearning]: {
    name: "Machine Learning",
    relatedItems: [
      ProjectDatabaseKeys.AdultIncomePrediction,
      ProjectDatabaseKeys.HousePricePrediction,
      ProjectDatabaseKeys.MachineLearningAssignment1,
      ProjectDatabaseKeys.MachineLearningAssignment2,
      ProjectDatabaseKeys.MachineLearningAssignment3,
      ProjectDatabaseKeys.MachineLearningLabQuestions,
      ProjectDatabaseKeys.ComputationalFinanceAssignment,
      ProjectDatabaseKeys.MachineLearningTheoryPractice,
    ],
  },
  [CategoryDatabaseKeys.JavaAssignments]: {
    name: "Java Assignments",
    relatedItems: [
      ProjectDatabaseKeys.JavaCalculatorAssignment,
      ProjectDatabaseKeys.BotanicGardenPlannerAssignment,
      ProjectDatabaseKeys.TrackAndTraceAssignment,
      ProjectDatabaseKeys.HollomonAssignment,
      ProjectDatabaseKeys.DatabasesMiniProject,
    ],
  },
  [CategoryDatabaseKeys.GameDevelopment]: {
    name: "Game Development",
    relatedItems: [
      ProjectDatabaseKeys.OsmosGame,
      ProjectDatabaseKeys.SurfaceFight,
      ProjectDatabaseKeys.Platformer,
      ProjectDatabaseKeys.PlatformerDeathWalk,
      ProjectDatabaseKeys.CodingBreakout,
      ProjectDatabaseKeys.CatchMaruf,
      ProjectDatabaseKeys.AgainstGravity,
      ProjectDatabaseKeys.ScrollingShooter,
      ProjectDatabaseKeys.Dungeon,
      ProjectDatabaseKeys.VegNinja,
      ProjectDatabaseKeys.AngryCatsSpace,
      ProjectDatabaseKeys.AngryCats,
    ],
  },
  [CategoryDatabaseKeys.ProgrammingParadigms]: {
    name: "Programming Paradigms",
  },
  [CategoryDatabaseKeys.ObjectRelationalMappers]: {
    name: "Object Relational Mappers",
    relatedItems: [
      SkillDatabaseKeys.Mongoose,
      SkillDatabaseKeys.Prisma,
      SkillDatabaseKeys.Drizzle,
      SkillDatabaseKeys.SQLAlchemy,
      SkillDatabaseKeys.TypeORM,
      SkillDatabaseKeys.Hibernate,
      SkillDatabaseKeys.ObjectRelationalMapping,
    ],
  },
  [CategoryDatabaseKeys.Testing]: {
    name: "Testing",
    relatedItems: [
      SkillDatabaseKeys.Jest,
      SkillDatabaseKeys.Vitest,
      SkillDatabaseKeys.PyTest,
      SkillDatabaseKeys.UnitTest,
      SkillDatabaseKeys.JUnit,
      SkillDatabaseKeys.Cypress,
      SkillDatabaseKeys.ReactTestingLibrary,
      SkillDatabaseKeys.Testing,
    ],
  },
  [CategoryDatabaseKeys.ProjectManagers]: {
    name: "Project Managers",
    relatedItems: [
      SkillDatabaseKeys.NPM,
      SkillDatabaseKeys.Yarn,
      SkillDatabaseKeys.PNPM,
      SkillDatabaseKeys.Poetry,
      SkillDatabaseKeys.Pip,
      SkillDatabaseKeys.PyBuilder,
      SkillDatabaseKeys.Maven,
      SkillDatabaseKeys.Gradle,
      SkillDatabaseKeys.Tox,
      SkillDatabaseKeys.NxJS,
    ],
  },
  [CategoryDatabaseKeys.DataScience]: {
    name: "Data Science",
  },
  [CategoryDatabaseKeys.APIs]: {
    name: "APIs",
    relatedItems: [
      SkillDatabaseKeys.REST,
      SkillDatabaseKeys.Apollo,
      SkillDatabaseKeys.GraphQL,
      SkillDatabaseKeys.TRPC,
      SkillDatabaseKeys.SocketIO,
      SkillDatabaseKeys.Pusher,
      SkillDatabaseKeys.OpenAI,
      SkillDatabaseKeys.ReplicateAI,
      SkillDatabaseKeys.APIs,
      SkillDatabaseKeys.SDKs,
    ],
  },
  [CategoryDatabaseKeys.SDKs]: {
    name: "SDKs",
  },
  [CategoryDatabaseKeys.WebSockets]: {
    name: "Web Sockets",
  },
  [CategoryDatabaseKeys.CodeQuality]: {
    name: "Code Quality",
    relatedItems: [
      SkillDatabaseKeys.Black,
      SkillDatabaseKeys.PyLint,
      SkillDatabaseKeys.Zod,
      SkillDatabaseKeys.Prettier,
      SkillDatabaseKeys.Checkstyle,
      SkillDatabaseKeys.ESLint,
      SkillDatabaseKeys.Linting,
      SkillDatabaseKeys.DesignPatterns,
    ],
  },
  [CategoryDatabaseKeys.VersionControl]: {
    name: "Version Control",
    relatedItems: [
      SkillDatabaseKeys.Git,
      SkillDatabaseKeys.GitHub,
      SkillDatabaseKeys.GitLab,
      SkillDatabaseKeys.BitBucket,
      SkillDatabaseKeys.VersionControlSystems,
    ],
  },
  [CategoryDatabaseKeys.PlatformDevelopment]: {
    name: "Platform Development",
  },
  [CategoryDatabaseKeys.CoreComputerScience]: {
    name: "Core Computer Science",
  },
  [CategoryDatabaseKeys.Automation]: {
    name: "Automation",
  },
  [CategoryDatabaseKeys.SoftSkills]: {
    name: "Soft Skills",
  },
  [CategoryDatabaseKeys.Security]: {
    name: "Security",
  },
  [CategoryDatabaseKeys.BachelorOfScience]: {
    name: "Bachelor of Science",
    relatedItems: [CourseDatabaseKeys.RHUL_ComputerScience],
  },
  [CategoryDatabaseKeys.Year1]: {
    name: "Year 1",
    relatedItems: [
      ModuleDatabaseKeys.RHUL_ObjectOrientedProgramming1,
      ModuleDatabaseKeys.RHUL_ObjectOrientedProgramming2,
      ModuleDatabaseKeys.RHUL_ProgrammingLaboratory,
      ModuleDatabaseKeys.RHUL_InternetServices,
      ModuleDatabaseKeys.RHUL_MathematicalStructures,
      ModuleDatabaseKeys.RHUL_MachineFundamentals,
      ModuleDatabaseKeys.RHUL_SoftwareDesign,
    ],
  },
  [CategoryDatabaseKeys.Year2]: {
    name: "Year 2",
    relatedItems: [
      ModuleDatabaseKeys.RHUL_SoftwareEngineering,
      ModuleDatabaseKeys.RHUL_TeamProject,
      ModuleDatabaseKeys.RHUL_OperatingSystems,
      ModuleDatabaseKeys.RHUL_Databases,
      ModuleDatabaseKeys.RHUL_AlgorithmsAndComplexity,
      ModuleDatabaseKeys.RHUL_MultidimensionalDataProcessing,
      ModuleDatabaseKeys.RHUL_ArtificialIntelligence,
      ModuleDatabaseKeys.RHUL_IntroductionToInformationSecurity,
    ],
  },
  [CategoryDatabaseKeys.Year3]: {
    name: "Year 3",
    relatedItems: [
      ModuleDatabaseKeys.RHUL_UserCentredDesign,
      ModuleDatabaseKeys.RHUL_ITProjectManagement,
      ModuleDatabaseKeys.RHUL_FunctionalProgramming,
      ModuleDatabaseKeys.RHUL_FinalYearProject,
      ModuleDatabaseKeys.RHUL_MachineLearning,
      ModuleDatabaseKeys.RHUL_ComputationalFinance,
      ModuleDatabaseKeys.RHUL_SecurityManagement,
    ],
  },
  [CategoryDatabaseKeys.Other]: {
    name: "Other",
    relatedItems: [
      ProjectDatabaseKeys.SearchingAndSortingAlgorithms,
      ProjectDatabaseKeys.AutomatedSetup,
      ProjectDatabaseKeys.Leetcode,
    ],
  },
};

SkillDatabaseKeys.ScikitLearn,
SkillDatabaseKeys.Pandas,
SkillDatabaseKeys.NumPy,
SkillDatabaseKeys.Matplotlib,
SkillDatabaseKeys.Seaborn,
SkillDatabaseKeys.Keras,
SkillDatabaseKeys.Jupyter,
SkillDatabaseKeys.MachineLearning,
SkillDatabaseKeys.DeepLearning,
SkillDatabaseKeys.ArtificialIntelligence,
SkillDatabaseKeys.DataScience,
SkillDatabaseKeys.Hyperparameters,
SkillDatabaseKeys.Boosting,
SkillDatabaseKeys.DataVisualisation,
SkillDatabaseKeys.NeuralNetworks