name: Mirror to GitLab

on:
  push:
    branches:
      - main  

jobs:
  mirror:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  

    - name: Verify 
      env:
        GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
        GITLAB_REPOSITORY: ${{ secrets.GITLAB_REPOSITORY }}
      run: |
        git config --global user.name 'Maruf Bepary'
        git config --global user.email 'bepary71@gmail.com'

        # Attempt to list the remote repository
        git ls-remote https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/${GITLAB_USERNAME}/${GITLAB_REPOSITORY}.git HEAD
        if [ $? -ne 0 ]; then
          echo "Failed to connect to GitLab repository. Check if repository exists and credentials/token are correct."
          exit 1
        fi

    - name: Mirror Repository 
      env:
        GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
        GITLAB_REPOSITORY: ${{ secrets.GITLAB_REPOSITORY }}
      run: |
        # Setup if the initial check is successful
        git remote add gitlab https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/${GITLAB_USERNAME}/${GITLAB_REPOSITORY}.git
        
        # Push code to GitLab
        git push gitlab main
